### ISSUE TITLE
Feature request predifined layers

### ISSUE THREAD

**Issue by MauriceVeraart** [CasparCG/server#1004]
Feature request

in #871 @Julusian  is mentioning predefined layers to play / initialize
while the server starts up
although specificly made for the timecode option
it would also be a nice option in general use.

like for instance load a colorbar after startup 

```
<channel>
  <timecode>free [free|clock|layer]</timecode>
  <timecode_offset>???</timecode_offset> 
  <timecode_layer>10</timecode_layer>
  <predefined_layers>
    <layer id="0">BG_LIGHT LOOP</layer> // video file
    <layer id="10">DECKLINK 5 FORMAT 1080i5000</layer>
    <layer id="20">[HTML] http://localhost:3000/overlay.html</layer>
  </predefined_layers>
</channel>
```

i bet @Julusian  already made this ;)

**Comment by Julusian** [comment]
The predefined layers I have done was added for timecode, but does not have to be used for timecode purposes and can have many layers defined as shown in that example.
It is something I have wanted for a while (and I know others have too), so I made sure to make it generic.
A 2.2/2.3 PR is planned, so this will be included in that.

**Comment by dotarmin** [comment]
> @Julusian It is something I have wanted for a while (and I know others have too), so I made sure to make it generic. A 2.2/2.3 PR is planned, so this will be included in that.

Closing this and referring to #871
