### ISSUE TITLE
Feature Request AMCP authentication

### ISSUE THREAD

**Issue by grahamspr86** [CasparCG/server#1005]
Could we have an option of authenticating on connection to ACMP before it accepts any commands, the token could be in the config.

This would secure the connection in a limited way as without SSL it can still be viewed what's passing between the client and the server.

**Comment by jesperstarkar** [comment]
2.1 AMCP has a request passphrase that works like this. Don't remember if it is removed in 2.2.

**Comment by baltedewit** [comment]
It's pretty easy to eaves drop on a TCP connection and just listen for the auth details so I don't think an implementation in amcp makes sense.

why wouldn't you just close the firewall for outside traffic to the amcp ports and you can establish a proper secure connection through either SSL or by tunneling all amcp traffic through something like webrtc data channels or websockets?

**Comment by Julusian** [comment]
> I don't think an implementation in amcp makes sense.

I agree with that. Anything that we implement will likely be riddled with security flaws or it would end up being a lot of effort to maintain and keep secure. Besides, I wouldn't be surprised if it was possible to crash caspar by sending some specially crafted packets or DOS it with a flood of data

> why wouldn't you just close the firewall for outside traffic to the amcp ports and you can establish a proper secure connection through either SSL or by tunneling all amcp traffic through something like webrtc data channels or websockets?

I'm not sure how easy it is to do on windows, but I would use ssh to create a secure tunnel between the machines. Its simple and secure. 

Alternatively, this could be a good thing to write as a standalone tool (perhaps in node.js) which would act as an amcp proxy.

**Comment by MauriceVeraart** [comment]
i think we must know a bit more of your context @grahamspr86 
i find the lock function very usefull in situations 

where person 1 or application 1 is controlling say ch1&2 (like a VT)
and person 2 or application 2 is controlling graphics like a CG on say CH3

this just to be sure someone does not touch somebody's else his channel ;)

exposing AMCP to a WAN is not where it's made for and needs a gateway of somekind

**Comment by grahamspr86** [comment]
I wasn't referring to putting ACMP on the WAN but securing it within a LAN.

You can use LOCK to secure a channel and stop multiple operators from stepping on each others channels in error but what stops a malicious user from sending the KILL command to the server?

**Comment by MauriceVeraart** [comment]
Ok if that is a concern in your environment, 
then I hink you need to make a security measure outside caspar.

SSH port forwarding to every client?? 

when you want to secure a protocol you need to do this or
very good or not at all in my opinion.

the beauty of AMCP is it to be plain and simple a extra security layer does not help it imo

**Comment by dotarmin** [comment]
> I don't think an implementation in amcp makes sense.

Agree.

Closing feature request because it's more of an infrastructure/environment question. If this becomes relevant again this issue can easily be opened.
