### ISSUE TITLE
Decklink Consumer Fill output periodic black frames

### ISSUE THREAD

**Issue by JamesWatton** [CasparCG/server#1009]
Hi,

I have a decklink 4k extreme being used for output from Caspar CG at 1080i50 (via an SDI to HDMI converter to check the output of the decklink card). I also have a screen consumer configured to view the output.

When I use a video + html layer (simple scrolling text) the output works as expected.
When I use a more complex HTML template, the key is output fine, but the fill only works for a second or two and then produces blank black frames in the decklink consumer - the screen consumer continues working as expected.

If I disable the video layer, it will output the HTML layer more consistently, but with black frames (1-2 seconds in duration) every 10 seconds or so.

With only the video layer and no HTML producer, the decklink consumer output is consistent and fine. 

Not sure if this is a bug with Caspar CG, or something to do with my setup (and would be better on the caspar forums instead), but the DIAG window doesn't show anything different to when its producing fill output, and a black frame.

If you want any further information regarding setup/hardware etc, I will gladly supply.

Here is a html template I've been using to test with: [https://pastebin.com/1x4gMeFz](https://pastebin.com/1x4gMeFz)

**Comment by hummelstrand** [comment]
Please post what version/builds/OS you are using.

**Comment by JamesWatton** [comment]
CasparCG Server is using latest commit from master branch, built from source.

Windows 7 Enterprise Service Pack 1 Build 7601
Graphics card is an NVIDIA Quadro K1100M with latest drivers (23.21.13.9158)

DeckLink 4K Extreme is using Driver v10.9.7

Cheers!

**Comment by dotarmin** [comment]
> @JamesWatton: built from source.

Can you try with a v2.2 (master) build from [http://builds.casparcg.com](https://builds.casparcg.com)?

**Comment by Julusian** [comment]
I have been thinking about this, and I think it is unlikely to be an issue with caspar.
If it was a few frames each time I could believe it being something in caspar, but not for a couple of seconds, especially with the screen consumer continuing normally.

It sounds to me like there is a signal dropout somewhere, causing the screen to rehandshake with the converter. That handshaking often takes a couple of seconds on consumer grade screens. Can you try a different hdmi cable? potentially screen too?

**Comment by JamesWatton** [comment]
Ok, I've tried this again this morning with the latest version from https://builds.casparcg.com/ and again with the latest from source and it is running fine with both on the exact same hardware but from cold as it hadn't been used in a few days. I suspect it was as @Julusian says, the signal dropping out, possibly from the sdi-hdmi converter over-heating as it was running quite hot when the issue occurred. I'll keep monitoring it but happy to close this issue. 

Thanks!
