### ISSUE TITLE
Random Checkerboard pattern in screen consumer

### ISSUE THREAD

**Issue by MauriceVeraart** [CasparCG/server#1011]
while using the screen consumer
Completely random a black checkerboard pattern appears on a video layer in the upper-left corner.
I have tried to catch it with a snapshot but it's only there for one frame  soo hard to catch.

has this something to do with triangles and quads mentioned in
#1002 ???

**Comment by Julusian** [comment]
Have you tried other consumers, and does it also show on them?
Does it happen with any video you try?

How much space does the checkerboard pattern occupy? 

I don't think it would be related to that

**Comment by MauriceVeraart** [comment]
I have not seen them yet on other consumers
they are really random in a low freq
say 1 or 2 frames in a 5 min period

i could not catch them yet 
but they look like squares of say 16x16 pixels in blocks off 8x8 square

sometimes you have only one block sometimes 4 adjacent to each other
always next to each other.

changing vsync to true seems  to make them occure less often (not sure)

**Comment by baltedewit** [comment]
I've made 15 minute screen recordings on both intel and nvidia gpu and was not able to reproduce this. (Checked with the npdecimate filter in ffmpeg)

What gpu / driver version are you on? I'm on intel 23.20.16.4973 (hd630) and nvidia 391.01 (1050ti 4gb mobile)

**Comment by MauriceVeraart** [comment]
Never seen again in later version. Fixed or hardware specific i guess.
