### ISSUE TITLE
Server 2.2 bug in showing the channel at device 2.

### ISSUE THREAD

**Issue by Hjesus** [CasparCG/server#1024]
### Current Behaviour
I have to devices. Both is set up with 1920x1080. Device 2 is ment to be set to 1280x720 on startup of CasparCG Server and show Channel 1.
But what happens is that Device 2 is set to 1536x864 and starts at x=1537 y=0 on device 1 and then shows the rest on device 2.
This is how it looks on server 2.2
![casparcg_2 2](https://user-images.githubusercontent.com/40465964/41725466-2814b412-7570-11e8-9418-27a15c4c251c.jpg)

This is how it looks at server 2.07
![casparcg_2 07](https://user-images.githubusercontent.com/40465964/41725467-284320c2-7570-11e8-947c-82e986a4eecf.jpg)

### Environment
* CasparCG Server version: 2.2
* Operating system: Windows 10
Graphics driver: Nvidia 22.21.13.8205

### Attachments

**Comment by dotarmin** [comment]
> Both is set up with 1920x1080 ... Device 2 is ment to be set to 1280x720

@Hjesus I assume you use `<width> and <height>` to set device 2 to be 1280x720, is that correct? Your video-mode is 1920x1080 according to your text and the size of screen-consumer window will be set to 1280x720...

Can you provide some more information such as your config-file.

**Comment by dotarmin** [comment]
ping @Hjesus

**Comment by Julusian** [comment]
@Hjesus Ive just had a quick test of this, and it looks to be working fine for me. It would be good to have your config to double check it is all correct there

**Comment by dotarmin** [comment]
I will close this issue for now and can open it again on request or if @Hjesus needs more help.
