### ISSUE TITLE
Playing a file outside of media folder

### ISSUE THREAD

**Issue by Phil403** [CasparCG/server#1026]
just wanted to bring up the question if it is possible to play a file outside of the media folder.
The file would not be checked in the database by media-scanner but technically the playback should work.

**Comment by dotarmin** [comment]
Yes it's possible. You use `<media-path/>`element in the `casparcg.config` to determine where to play your media files from.

**Comment by vimlesh1975** [comment]
Yes it is possible to play from anywhere. Command is like below
`Play 1-1 "D://my folder/my file.mp4"`
I have made a client for this.

![play_from_anywhere](https://user-images.githubusercontent.com/4338487/41959692-567b8c5a-7a0b-11e8-935d-469e628495f9.png)

Download from here.
[https://casparcgforum.org/t/simple-video-playout/61](url)

**Comment by Phil403** [comment]
Thanks vimlesh
I used the wrong slashes... It works now
