### ISSUE TITLE
FFMPEG Video Playback Stuttering

### ISSUE THREAD

**Issue by peterbbc** [CasparCG/server#1029]
Getting an issue where FFMPEG is stuttering on playback of a h.246 file.
The file is fairly large dimension wise (5568 x 576) but very short and is only 123MB.
Weirdly we've played back files with the same dimension and a longer duration with no visible issues and have no problems playing files that aren't quite as wide.

I've tried on the latest build and the original 2.2.0 Beta release and get the same fault, tweaking the buffers and pipelines seem to make no difference.

HWInfo and Task Manager confirm that there is plenty of CPU/GPU/Memory/SSD resource left so this isn't a hardware issue.

File plays back OK on a basic desktop PC in VLC so it's not a problem with the file.

Attempted to test on 2.0.7 but that kept crashing on me with an unhandled exception error before I even got as far as issuing the commands!

Log attached (including config) and a link to the offending graphic below.

### Expected Behaviour
Playback should be smooth as butter.

### Current Behaviour
Playback stutters with ffmpeg reporting a lot of dropped frames.

### Steps to Reproduce 
Route channel 7 to channels 1-6
Perform some mixer transforms (Issue occurs without these).
Play file

### Environment
* CasparCG Server version: 2.2.0 Beta 1 - f61e89755ff12e67e8da7b5efaf7ffb8d0d600ee (28/02/18) & 3c77a8378fde2384200a6494e2204a3acecd1b99 (25/06/18)
* Operating system: Windows 10 Pro x64
* Graphics driver: 391.74
* Decklink drivers: 10.11
* CPU: Intel Xeon W-2125
* RAM: 32GB
* GPU: nVidia P4000

### Attachments
[caspar_2018-06-28.log](https://github.com/CasparCG/server/files/2146535/caspar_2018-06-28.log)
[DRUGS_280618_GFX2.zip](https://www.dropbox.com/s/k7xjg51s1elb3ax/DRUGS_280618_GFX2.zip?dl=1)

**Comment by baltedewit** [comment]
![afbeelding](https://user-images.githubusercontent.com/9898648/42073508-84d09796-7b67-11e8-9c6e-0780dc836436.png)

Doesn't seem to be an issue to play in command line ffmpeg 3.4 @ronag 
I also ran a quick check with our 2.1 branch and that also plays back fine.

I've tried to reencode your file using a pix format of yuv422p (instead of yuv422p10le) and a fastdecode tune. This cuts my CPU use while playing back the file in half (from 50% to 25% on a 7700HQ) and makes the file play back smoothly, but only if I load it before playing back. (below is when using a direct play command)
![afbeelding](https://user-images.githubusercontent.com/9898648/42073848-38726864-7b69-11e8-9c5b-f1c1d87803eb.png)

**Comment by dotarmin** [comment]
Hi @peterbbc!

Thanks for reporting this and for all the information provided, it helps a lot!
Does the playback stutter when looking at the video when looking at it in a screen-consumer?

Best regards,
Armin

**Comment by peterbbc** [comment]
@dotarmin - Not sure, I'll have to check! I'm back in the office Wednesday so will do it first thing!

Probably also worth noting I've tried a few different Decklink and nVidia drivers with no improvement!

@baltedewit - I tried using yuv244p encoding as well with no joy and yuv420p. Didn't seem to make a difference sadly!
Out of interest what else did you change of the re-encode?
All the media for this system automatically gets converted to 'lossless' (crf 0) h.264 at 50fps progressive. I don't convert the colour space but if it helps improve performance I'd definitely look at changing the import process.

**Comment by baltedewit** [comment]
> Out of interest what else did you change of the re-encode?

Most notably, I changed the crf to something like 18, using a 50mbit bitrate with a fastdecode tune. My ffmpeg wasn't compiled for 10bit colour so it encoded in 8bit as well (although I didn't mean to do that)

**Comment by dotarmin** [comment]
> @dotarmin - Not sure, I'll have to check! I'm back in the office Wednesday so will do it first thing!
Probably also worth noting I've tried a few different Decklink and nVidia drivers with no improvement!

Another thing you could try when you're back is to play the file using Media Express from BMD (installed when installing Decklink Drivers) and see if it stutters.

**Comment by TKooijmans** [comment]
BMD media express does not support H264 only Mjpeg avi and uncompressed avi

**Comment by peterbbc** [comment]
@TKooijmans is correct, Media Express wouldn't let me import a H.264 file so I can't test that unfortunately.

@dotarmin I tried with a single screen consumer (and all other consumers removed) and got the same result (log below) so it's not specific to the Decklink consumer.

@baltedewit Interesting. I tried a couple of different options and found the following:

- CRF 0 - yuv422p10le - Stuttering
- CRF 17 - yuv422p10le - Better but still stutters a bit
- CRF 0 - yuv422p - Stuttering
- CRF 17 - yuv422p - FFMPEG still shows dropped frames (see logs below) but visually appears smooth

Interestingly you get the same number of dropped frame messages in the logs regardless of which encoding option is chosen above, however the options that visually stutter take more time to playback. I.E. they playback slower than realtime.

### Attachments
[screen_consumer.log](https://github.com/CasparCG/server/files/2162162/screen_consumer.log)
[crf_pixfmt_changed.log](https://github.com/CasparCG/server/files/2162163/crf_pixfmt_changed.log)

**Comment by dotarmin** [comment]
> @TKooijmans BMD media express does not support H264 only Mjpeg avi and uncompressed avi

You're right! I forgot it was a H.264 file.

> @peterbbc I tried with a single screen consumer (and all other consumers removed) and got the same result (log below) so it's not specific to the Decklink consumer.

This is kind of good because we can exclude potential Decklink only issues. Have you tried to play the file with ffmpeg directly?

**Comment by Julusian** [comment]
I suspect this could be a cpu performance issue. Even though the cpu is not being maxed out, the video decoding could be too single threaded, or it could be one of the ffmpeg filter steps (eg checking if needs deinterlacing, colour space conversion).

If you could try in ffplay from https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20180219-acdea9e-win64-static.zip that will help rule out whether the issue lies in ffmpegs decoding (and confirm it is something in caspar or the ffmpeg filter chain we use).

**Comment by peterbbc** [comment]
@Julusian @dotarmin Tested with ffplay on the Caspar machine and it appears to play smoothly. It's certainly much better than playing it back via Caspar. ffplay console output attached.

It also plays back fine in VLC on my Desktop (i5-4590 @ 3.3Ghz / 8GB RAM / Intel HD 4600 / Spinning Disk) and not quite perfectly but still better than Caspar in ffplay.

### Attachments
[ffplay_output.txt](https://github.com/CasparCG/server/files/2162785/ffplay_output.txt)

**Comment by ronag** [comment]
I will take a look next week.

**Comment by peterbbc** [comment]
Works for me!
It's just a bit of an odd one that very similar graphics have had no issues yet this particular one did.

We've been running then with CRF 17 & YUV422p which seems to make them visually smooth (even if ffmpeg still reports dropped frames).
I've not had any complaints since making the change 2 weeks ago but if I get any I'll go up to CRF 20 and YUV420p.

Be nice to see the performance increase for 2.3.0 but I appreciate it's not a focus for the current release!

**Comment by MauriceVeraart** [comment]
Probally a weird question but how hard / easy is 
it on the moment to stop the default deinterlace step
this as a question not for the main repository but for
a custom build which is used in a progressive only environment

**Comment by premultiply** [comment]
There should be no deinterlacing if the source is correctly flagged as progressive.
or better: deinterlacing is only done on frames or sources flagged as interlaced.
If the metadata or settings are wrong there may be wrong results too.

**Comment by baltedewit** [comment]
> There should be no deinterlacing if the source is correctly flagged as progressive.

That seems to contradict with the `deint=all` option in the av_producer here: https://github.com/CasparCG/server/blob/2de58a1f62545435ba52c644fbd82c08ab07190d/src/modules/ffmpeg/producer/av_producer.cpp#L152

Changing that to `interlaced` instead of `all` as per https://ffmpeg.org/ffmpeg-filters.html#bwdif would change the behaviour to what you specified I think.

**Comment by ronag** [comment]
It will run the de-int filter on all frames. The "interlaced" flag is known to be inaccurate in a lot of media.

**Comment by ronag** [comment]
This really should be an option...

**Comment by MauriceVeraart** [comment]
if this is the only place in the code were this is defined it is fairly easy to do some experiments.
thanks for the guidance !

in a more global view I agree with Robert to make it a option which defaults to the "save" resource heavy always deinterlace setup. with i guess 2 options (rely on metadata, progressive only)

thanks again

**Comment by ronag** [comment]
Is the input file interlaced? Try to deinterlacing it before playing it in Caspar.

**Comment by ronag** [comment]
forced deinterlacing is turned off, there is nothing more we can do here
