### ISSUE TITLE
How Can I get the Playing Video Clip's Remaining Frames to End?

### ISSUE THREAD

**Issue by akr4m** [CasparCG/server#1030]

**Comment by dotarmin** [comment]
Could you please provide more information? I'm not sure what you you're asking and it's really hard for the community to help you out when information is lacking.

Best regards,
Armin

**Comment by akr4m** [comment]
**_PLAY 1-1 AMB_**
this command means in 1 layer **amb.mp4** filename video is playing. 
What is remaining time to end this **amb.mp4** file video?
I mean I need to know the playing video file information (How many frames/seconds are successfully played? And remaining frames to end that video clip?)

**Comment by akr4m** [comment]
Can you provide me an example for 2.2 please?
I am building with Dot Net C Sharp Language.

**Comment by peterbbc** [comment]
It would probably be worth reading up on OSC first - http://opensoundcontrol.org/introduction-osc - Without the understanding of how an OSC packet is formed is tricky to explain why simply parsing them as a string doesn't give you the result you'd expect.

You also need to be aware that CasparCG requires you to either setup a fixed OSC server address or connect to CasparCG via AMCP at which point it sends OSC packets back to the originating host.

A very simple example using the Rug.Osc library (https://www.nuget.org/packages/Rug.Osc/) would be something like this:

`using System;
using System.Threading;
using System.Text.RegularExpressions;

using Rug.Osc;

namespace OSCDemo
{
    class Program
    {
        static OscReceiver receiver;
        static Thread thread;

        static void Main(string[] args)
        {
            // This is the port we are going to listen on 
            // Caspar requires you to either define a fixed OSC client in the config or to connect via AMCP before it sends OSC messages back
            int port = 6250;

            // Create the receiver
            receiver = new OscReceiver(port);

            // Create a thread to do the listening
            thread = new Thread(new ThreadStart(ListenLoop));

            // Connect the receiver
            receiver.Connect();

            // Start the listen thread
            thread.Start();

            // wait for a key press to exit
            Console.WriteLine("Press any key to exit");
            Console.ReadKey(true);

            // close the Receiver 
            receiver.Close();

            // Wait for the listen thread to exit
            thread.Join();
        }

        static void ListenLoop()
        {
            try
            {
                while (receiver.State != OscSocketState.Closed)
                {
                    // if we are in a state to receive
                    if (receiver.State == OscSocketState.Connected)
                    {
                        // get the next message 
                        // this will block until one arrives or the socket is closed
                        OscPacket packet = receiver.Receive();

                        // if it's a bundle then split it out
                        if (packet.ToString().StartsWith("#bundle"))
                        {
                            // bundles store their data inside curly brackets, find all instances
                            MatchCollection matches = Regex.Matches(packet.ToString(), "{(.*?)}");

                            // process each bundle message
                            foreach (Match match in matches)
                                MatchAddress(match.ToString().Trim(new char[] { '{', '}', ' ' }));

                        }
                        else
                        {
                            // process a single osc packet
                            MatchAddress(packet.ToString());
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                // if the socket was connected when this happens
                // then tell the user
                if (receiver.State == OscSocketState.Connected)
                {
                    Console.WriteLine("Exception in listen loop");
                    Console.WriteLine(ex.Message);
                }
            }
        }

        // find the address we're looking for in a single OSC string
        // realistically you'd want to filter for multiple address but the idea is there
        static void MatchAddress(string oscString)
        {
            string[] arguments = oscString.Split(',');
            // address format - /channel/[0-9]/stage/layer/[0-9]/file/time
            if (arguments[0] == "/channel/1/stage/layer/1/file/time")
            {
                // trim the f (float) indicator off the result and write to console
                Console.WriteLine("Channel 1 - Layer 1 - Elapsed Seconds: " + arguments[1].TrimEnd('f') + " - Total Seconds: " + arguments[2].TrimEnd('f'));
            }
        }
    }
}`

Please be aware this is a very quick and dirty example, it probably shouldn't be used in a production environment and definitely shouldn't be used without understanding OSC and the CasparCG OSC spec but hopefully it gives you some pointers.

If you wanted the Frame time you'd have to work that out by knowing the clips FPS, which you can get by looking at the Caspar OSC spec on the link @Julusian provided.

**Comment by akr4m** [comment]
@peterbbc Thank You So much..Dear

**Comment by dotarmin** [comment]
@akr4m Is this solved? :)
