### ISSUE TITLE
LOAD + LOADBG + PLAY makes the background layer play

### ISSUE THREAD

**Issue by baltedewit** [CasparCG/server#1033]
Assume the following command sequence:
```
LOAD 1-10 AMB
LOADBG 1-10 GO1080P25 AUTO
PLAY 1-10
```

### Expected Behaviour
AMB will play, once it finishes, GO1080P25 will play.

### Current Behaviour
GO1080P25 plays immediately after the play command.

### Environment
Tested on 2.1 and 2.2

**Comment by Julusian** [comment]
This is happening because after using load, the foreground producer is classed as paused, with no way of identifying it as never having started playback.

**Comment by baltedewit** [comment]
Huh, I guess that's technically intended behaviour then, although a little counter intuitive. Apparently already documented as such as well, my bad.

**Comment by Julusian** [comment]
I think this should be done (as a enhancement rather than bug) as it is confusing and not what I would expect to happen. It would be a simple thing to do too.

Is there documentation on it? I checked the code to determine that

**Comment by baltedewit** [comment]
Yeah, it's noted on the wiki: https://github.com/CasparCG/help/wiki/AMCP-Protocol#load

**Comment by jesperstarkar** [comment]
Does this mean that `RESUME` instead of `PLAY` works?

**Comment by Julusian** [comment]
@jesperstarkar yes, that is correct.

I still think this is something that wants to be looked at though, as the clip that via LOAD was technically never played, so if mixing LOAD and LOADBG it will get rather confusing on how to play the LOAD clip
