### ISSUE TITLE
Memory leak on linux with CasparCG 2.1.0

### ISSUE THREAD

**Issue by vinchi9** [CasparCG/server#1038]
### Expected Behaviour
CasparCG should destroy old FFMPEG producer threads after calling STOP command. This should work for the entire runtime and not only for a few hours after start.

### Current Behaviour
CasparCG has been running properly for 2 hours, but then it stopped destroying old FFMPEG producers resulting in 100MB increase in memory usage every time I play new HLS stream. In the end CasparCG fills the entire RAM and gets killed by system due to high memory usage. When CasparCG stops destroying old FFMPEG producers, it no longer prints the `ffmpeg [...] Destroyed.` messages in log. I periodically send commands PLAY and STOP via the AMCP and sometimes there is warning in CasparCG log: 
```
[2018-07-10 13:04:02.637] [18137] [info]    Received message from 127.0.0.1: stop 1-3 \r\n
[2018-07-10 13:04:02.638] [18174] [info]    Sent message to 127.0.0.1:202 STOP OK\r\n
[2018-07-10 13:04:02.649] [18163] [warning] Assertion Failed: destroyer->size() < 8 file:core/producer/frame_producer.cpp line:258 
```

### Steps to Reproduce
Keep running CasparCG for a while and periodically switch HLS streams with PLAY and STOP commands every 20 seconds. After some time RAM usage linearly increases every time the stream gets switched until it fills the entire memory. 

### Environment
* CasparCG Server version: CasparCG Video and Graphics Playout Server 2.1.0.478 b2a17fc Beta 2
* Operating system: Ubuntu 18.04 LTS x86_64, kernel: 4.15.0-24-generic
* Decklink drivers: 10.11

**Comment by ronag** [comment]
CCG 2.1 is no longer under development.
