### ISSUE TITLE
FFMPEG Producer does not apply video filters

### ISSUE THREAD

**Issue by vinchi9** [CasparCG/server#1058]
### Expected Behaviour
CasparCG should apply filters specified by -filter:v option to the video.

### Current Behaviour
When I try to play HLS video stream with -filter:v option, the video stream plays well, but the video filters are not applied and no errors are produced even with debug log level.

### Steps to Reproduce 
I tried playing HLS stream with FFMPEG filters via these commands:
```
PLAY 1-1 http://someserver.com/index.m3u8 -filter:v unsharp=luma_msize_x=3:luma_msize_y=3:luma_amount=3.0
PLAY 1-1 http://someserver.com/index.m3u8 -filter:v scale=1280:720
```
### Environment
* CasparCG Server version: CasparCG Video and Graphics Playout Server 2.2.0 e113f8c Beta 1
* Operating system: Ubuntu 18.04 LTS x86_64, kernel: 4.15.0-24-generic
* Decklink drivers: 10.11

**Comment by vinchi9** [comment]
I tried `filter` to add a filter chain, but in CasparCG 2.2 it resulted in badly connected audio and video filters. In [this issue](https://github.com/CasparCG/server/issues/1037) I was advised to use `-filter:v`, but it didn't have any effects. 

I tried using `vf` as you suggest and it works well. Thank you very much.

**Comment by ronag** [comment]
it's `-filter:v` and `-filter:a`.

**Comment by euphoricz** [comment]
I agree with lukasmican, -filter:v has no effect even though in this thread https://github.com/CasparCG/server/issues/1037 it was recommended.

I tried vf as well and verified it works, the output is clearly sharpened.

Using -filter:v is in my opinion the better syntax and falls more inline with the ccg 2.2 ffmpeg commonly used syntax.  It does not display any warnings or errors in the console but unfortunately does not sharpen the output.

This isn't a big deal to me as long as one command or another works, however it is probably a good idea to follow a common syntax or display a warning / error in the console if -filter:v does not work.

### Using vf ###
![image](https://user-images.githubusercontent.com/15693512/67575042-49669b80-f701-11e9-8667-d3083e5e5357.png)

### Using -filter:v ###
![image](https://user-images.githubusercontent.com/15693512/67575077-5e432f00-f701-11e9-91fe-d734e6f143ca.png)

**Comment by hreinnbeck** [comment]
For reference: https://github.com/CasparCG/server/blob/4784c0469744abfefc9d1365a273b3f1d2f97207/src/modules/ffmpeg/producer/ffmpeg_producer.cpp#L356

**Comment by euphoricz** [comment]
Thanks @hreinnbeck
