### ISSUE TITLE
HLS streams freeze channel output in 2.2

### ISSUE THREAD

**Issue by saltomodules** [CasparCG/server#1059]
### Expected Behaviour
CasparCG 2.2 plays HLS streams in a stable manner and gracefully deals with network dropouts or delays.

### Current Behaviour
When playing HLS streams with CasparCG 2.2 it seems that any sort of network dropout freezes up the entire channel output (including any cg/html overlays). 

Logging continues, INFO command still works, but new PLAY commands are no longer honoured. 

Only a restart of CasparCG returns things to normal.

The issue is reproducable by shutting off the network connection via firewall or pulling out the ethernet cable.

It happens pretty often, with and without extra cg layers. On Linux and Windows.

### Steps to Reproduce 
* Play an HLS stream. 
  We work with youtube live streams but other streams show the same issue, for instance:
  
  `PLAY 1-1 https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8`

  `PLAY 1-1 http://184.72.239.149/vod/smil:BigBuckBunny.smil/playlist.m3u8`

* After a while the complete channel output from casparcg freezes (including cg layers). Starting a new clip no longer works. For immediate result close off a firewall or pull out network cable.

### Environment

 Issue is observed on both an ubuntu and a windows 7 system:
   
   **System 1**

    CasparCG Server version:
    2.2.0 062c4e09a Beta 1
    video-mode 1080i5000    

    Operating system:
    Ubuntu 18.04

    Graphics driver:
    Nvidia 390.42  (for GTX1050)

    Decklink drivers:
    Blackmagic Design BlackmagicIO driver 10.10a3

  **System 2**

    CasparCG Server version:
    2.2.0 034a1a8f Beta 1
    video-mode 1080i5000    
    
    Operating system:
    Win 7 x64
    
    Graphics driver:
    Nvidia 391.01 (for GTX660)
    
    Decklink drivers:
    none

**Comment by ronag** [comment]
This seems to work in master. Also had to increase input buffering since currently caspar will read all versions of the HLS.
