### ISSUE TITLE
"Info paths"

### ISSUE THREAD

**Issue by vimlesh1975** [CasparCG/server#1060]
### Expected Behaviour
"Info paths" gives all path information of server in 2.07 and 2.1

### Current Behaviour
server 2.2 doesn't have this facility.

This information is used in custom clients to setup necessary things. Like
1. Getting clip list from file system.
2. Template list from file system.
3. Initial path of server is used for restarting server,  getting log files etc.

I can see these information are actually available in media scanner. But are not exposed.
I request this to be implemented as axisting clients are broken.

**Comment by TKooijmans** [comment]
please see
info/Info 1 not currently working correctly #923

**Comment by TKooijmans** [comment]
Almost all info commands do not work with beta  2.2.0 2696ec70 Beta 11
When is this fixed?
![afbeelding](https://user-images.githubusercontent.com/4194609/50228149-96723680-03a7-11e9-89df-6cb93e218b51.png)

**Comment by Julusian** [comment]
I thought there was another similar issue around to #1151. See my comment there, it would be good to know which INFO commands are desired. I shall look at adding some back depending on how messy/complicated they are

**Comment by TKooijmans** [comment]
I use info paths to get al the paths CasparCG is using.

You can change following to use CasparCG 2.2
You can read paths also from the config file.
I use INFO for current timecode of the playing clip, you have to change that too with your clients because
timecode is now returned in ms instead of frames

**Comment by Julusian** [comment]
This has been restored in 2.3/master
