### ISSUE TITLE
File recorder alway records in progressive 25p/50p

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#1067]
With build 8-8-2018 I tested the File recorder.
I had 1 channel set 1080i50 format with stereo audio layout

I used this command to record a file
ADD 1 FILE "Test.mxf" -b:v 35000000 -codec:a pcm_s24le -codec:v mpeg2video -pix_fmt yuv420p -alternate_scan:v 1  -g:v 12 -bf:v 2 -minrate:v 35000k -maxrate:v 35000k -color_primaries:v bt709 -color_trc:v 1  -colorspace:v 1

( -pix_fmt yuv420p is ignored)

### Expected Behaviour
Get a proper HDcam 1080i50 mxf file

### Current Behaviour
it always records progressive

### Environment
* CasparCG Server version: 8-8-2018
* Operating system: window7-64

### Attachments
media info
ID                                       : 2
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : 4:2:2@High
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Default
Format settings, GOP                     : M=3, N=12
Format settings, picture structure       : Frame
Format settings, wrapping mode           : Frame
Codec ID                                 : 0D01030102046001-0401020201040300
Duration                                 : 12s 20ms
Bit rate                                 : 35.0 Mbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 50.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:2
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Bottom Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.338
Time code of first frame                 : 00:00:00:00
Time code source                         : Group of pictures header
Stream size                              : 50.2 MiB (79%)
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 3
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, wrapping mode           : Frame (AES)
Codec ID                                 : 0D01030102060300
Duration                                 : 12s 20ms
Bit rate mode                            : Constant
Bit rate                                 : 9 216 Kbps
Channel(s)                               : 8 channels
Sampling rate                            : 48.0 KHz
Bit depth                                : 24 bits
Stream size                              : 13.2 MiB (21%)

**Comment by premultiply** [comment]
Just use a filterchain to convert p to i and maybe also do the correct color conversion.

**Comment by Julusian** [comment]
Caspar now runs all channels as progressive, so you will need to tell ffmpeg to interlace as it records. 
As premultiply says a filterchain can do this. something like `-vf tinterlace=5` might do it, if that is how filters are specified now
https://www.ffmpeg.org/ffmpeg-all.html#tinterlace

**Comment by TKooijmans** [comment]
With this most of the MXF is ok except audio channel mapping
ADD 1 FILE "Test.mxf" -b:v 35000000 -codec:a pcm_s24le -codec:v mpeg2video -filter:v format=yuv420p,tinterlace=4 -alternate_scan:v 1 -g:v 12 -bf:v 2 -minrate:v 35000k -maxrate:v 35000k -color_primaries:v bt709 -color_trc:v 1 -colorspace:v 1

next I'm gonna try Ronag filter, please join if you got audio mapping working ( -map)

**Comment by ronag** [comment]
what exactly is wrong with the audio mapping?

**Comment by TKooijmans** [comment]
Hi Ronag,
If I use -map it's ignored, can you add in this line audio mapping to 2 channels? (so output is 2 channel mxf)

ADD 1 FILE "Test.mxf" -b:v 35000000 -codec:a pcm_s24le -codec:v mpeg2video -filter:v format=yuv420p,tinterlace=4 -alternate_scan:v 1 -g:v 12 -bf:v 2 -minrate:v 35000k -maxrate:v 35000k -color_primaries:v bt709 -color_trc:v 1 -colorspace:v 1

**Comment by ronag** [comment]
I still don't understand what you are trying to do

**Comment by ronag** [comment]
maybe you want the "pan" filter?

**Comment by TKooijmans** [comment]
Hi Ronag,
When I try to capture from Decklink input, I want just 2 audio channels if I set channel mode to stereo.
With above line I capture a MXF file with 8 channels embedded in on audio stream...

Bit rate : 9 216 Kbps
Channel(s) : 8 channels
Sampling rate : 48.0 KHz
Bit depth : 24 bits

**Comment by ronag** [comment]
https://ffmpeg.org/ffmpeg-filters.html#pan-1

**Comment by TKooijmans** [comment]
Hi Ronag, we need -map to reduce the number of channels but that's not working...
We also need 2 mono audio channels..

**Comment by ronag** [comment]
-filter:a pan=1:c0=c0;pan=1:c0=c1

**Comment by ronag** [comment]
Hm, you can only have single output track, i.e. you can't have 2 mono, only 1 stereo:

-filter:a pan=2:c0=c0:c1=c1

**Comment by premultiply** [comment]
channelsplit=channel_layout=stereo ?

**Comment by premultiply** [comment]
Have you tried channelsplit filter?
But I think it does requiere -filter_complex

**Comment by ronag** [comment]
You can only have one audio stream at the moment.

**Comment by 5opr4ni** [comment]
> You can only have one audio stream at the moment.

Any status change regarding only one audio stream?

**Comment by ronag** [comment]
@5opr4ni not from me... I'd like to do another iteration over both the ffmpeg producer and consumer to simplify implementation and extend functionality... time is however a constant problem :)

**Comment by 5opr4ni** [comment]
Hahaha! Yes, you have to clone yourself.
