### ISSUE TITLE
frame-number never reaches nb-frame at INFO CMD

### ISSUE THREAD

**Issue by mcdikki** [CasparCG/server#107]
I encountered the following behavior in 2.0.3:

If a movie is played till its end and you send an INFO for its channel/layer,
the <frame-number> and <file-frame-number> is always behind the <nb-frames> and <file-number-frame> by a few frames.

**Comment by mcdikki** [comment]
As there is nothing moving here, may I suggest a solution:

There are several bugs which are on the same or a related topic ( #270 , #255 , #30 )
So it seems to be pretty clear, that ffmpeg and/or the way we're getting framing infos from it is buggy.

We could solve the problem of wrongly reported frames while playing (via OSC/INFO) by adding an own framecounter to the ffmpeg producer. Instead of getting the current frame from ffmepg, we just count it ourself. This way, at least the reported frame is correct.
Of course, this will not fix the problem with wrong framecounts given by cls/cinf/info(nb-frames/file-nb-frames), but at least clients depending correct framecount would work more reliable.

**Comment by mcdikki** [comment]
You can test this behavior i.e with the file amb.mp4 which is shipped with ccg.
This is a part of the osc messages received via OSC when playing amb.mp4 with 2.0.7 stable:
>03.03.2015 15:48:17: Frame Update msg received /channel/1/stage/layer/0/file/frame: 201/268
03.03.2015 15:48:17: Frame Update msg received /channel/1/stage/layer/0/file/frame: 202/268
03.03.2015 15:48:17: Frame Update msg received /channel/1/stage/layer/0/file/frame: 209/268
03.03.2015 15:48:18: Frame Update msg received /channel/1/stage/layer/0/file/frame: 215/268
03.03.2015 15:48:18: Frame Update msg received /channel/1/stage/layer/0/file/frame: 219/268
03.03.2015 15:48:18: Frame Update msg received /channel/1/stage/layer/0/file/frame: 226/268
03.03.2015 15:48:18: Frame Update msg received /channel/1/stage/layer/0/file/frame: 233/268
03.03.2015 15:48:18: Frame Update msg received /channel/1/stage/layer/0/file/frame: 238/268
03.03.2015 15:48:18: Frame Update msg received /channel/1/stage/layer/0/file/frame: 241/268
03.03.2015 15:48:18: Frame Update msg received /channel/1/stage/layer/0/file/frame: 243/268
03.03.2015 15:48:19: Frame Update msg received /channel/1/stage/layer/0/file/frame: 244/268
03.03.2015 15:48:19: Frame Update msg received /channel/1/stage/layer/0/file/frame: 249/268
03.03.2015 15:48:19: Frame Update msg received /channel/1/stage/layer/0/file/frame: 255/268
03.03.2015 15:48:19: Frame Update msg received /channel/1/stage/layer/0/file/frame: 259/268
03.03.2015 15:48:19: Frame Update msg received /channel/1/stage/layer/0/file/frame: 264/268
03.03.2015 15:48:19: Frame Update msg received /channel/1/stage/layer/0/file/frame: 266/268
03.03.2015 15:48:19: Frame Update msg received /channel/1/stage/layer/0/file/frame: 266/268
03.03.2015 15:48:19: Frame Update msg received /channel/1/stage/layer/0/file/frame: 266/268
03.03.2015 15:48:19: Frame Update msg received /channel/1/stage/layer/0/file/frame: 266/268
03.03.2015 15:48:20: Frame Update msg received /channel/1/stage/layer/0/file/frame: 266/268
03.03.2015 15:48:20: Frame Update msg received /channel/1/stage/layer/0/file/frame: 266/268
03.03.2015 15:48:20: Frame Update msg received /channel/1/stage/layer/0/file/frame: 266/268
03.03.2015 15:48:20: Frame Update msg received /channel/1/stage/layer/0/file/frame: 266/268
03.03.2015 15:48:20: Frame Update msg received /channel/1/stage/layer/0/file/frame: 266/268
03.03.2015 15:48:20: Frame Update msg received /channel/1/stage/layer/0/file/frame: 266/268

It's reproducible on different hardware.

**Comment by oneofsomany** [comment]
using MediaInfo dll and VLC, I have deduced that OSC and INFO are using the frame count from the video stream whilst CLS and CINF are using the frame count from the file header which seems to be the duration of the longest stream and not necessarily the video stream. In the case of the media assets supplied with CasparCG, their audio streams are longer than the video stream so this figure is what is used by CLS/CINF

**Comment by oneofsomany** [comment]
looking closely at the log files, I think the problem here is that the transition kicks in for the final 2 frames which does not appear to advance the frame information in OSC

**Comment by ronag** [comment]
2.2
