### ISSUE TITLE
Latest commit made HTML performance worse

### ISSUE THREAD

**Issue by pkeuter** [CasparCG/server#1075]
This commit: https://github.com/CasparCG/server/commit/8df72e76d950face7739b7e380111f7f95a2a3b4, made our tickertape go from almost fluent to stuttering, with exactly the same configuration. Other performance is the same. Animation is full CSS (`transform3d`). Is there any way this commit could be reverted? Or give an indication of what performance improvent it _does_ give?

**Comment by ronag** [comment]
Can you provide something we can reproduce your performance regression with?

**Comment by Julusian** [comment]
From a quick skim, is it really a good idea to be trying to do the memcpy this parallel?
https://github.com/CasparCG/server/blob/8df72e76d950face7739b7e380111f7f95a2a3b4/src/modules/html/producer/html_producer.cpp#L214-L216
splitting it into 1080 jobs seems excessive, and sounds like it could end up with more overhead than benefit. Would it not be sufficient to chunk it into 8 or 16? or just something closer to the core count of the cpu

**Comment by ronag** [comment]
@Julusian tbb will automatically select appropriate chunk size.

**Comment by ronag** [comment]
@Julusian you are right, should be a blocked_range parallel_for

**Comment by ronag** [comment]
Removed parallel for
