### ISSUE TITLE
OSC loopstate not changing after call

### ISSUE THREAD

**Issue by MauriceVeraart** [CasparCG/server#1077]
### Expected Behaviour
OSC message
`/channel/1/stage/layer/10/foreground/loop` 
should change state `true/false`
after call
`CALL 1-10 LOOP 1/0` 

### Current Behaviour
on initializing clip the OSC message follows as expected
when doing the call the clip is going in or out of loop
but the OSC message does not change

**Comment by ronag** [comment]
fixed in master
