### ISSUE TITLE
Audio gone after SEEK

### ISSUE THREAD

**Issue by MauriceVeraart** [CasparCG/server#1078]
### Current Behaviour
When doing
`PLAY 1-10 clipname SEEK 1234`
the clip is starting as expected but audio is gone.
it seems this only happens when the clip's FPS 
does not conform to the channel FPS

**Comment by ronag** [comment]
@MauriceVeraart can you provide a sample file?

**Comment by MauriceVeraart** [comment]
Hi ronald

off coarse i will do thaht when back in the office.

Although i guess you can try this with any clip with a other FPS then the channel

LS

**Comment by ronag** [comment]
@MauriceVeraart is this still a problem? If not please provide that sample file :)
