### ISSUE TITLE
9:16 aspect ratio video mode

### ISSUE THREAD

**Issue by manugo-dev** [CasparCG/server#1079]
HI!

Im working with Instagram and mobile streaming at 9:16 aspect ratio (1080x1920) its possible to add custom video mode for this resolution to CasparCG? I try to send signal on 1080p25 mode but it shows OpenGL error because my video resolution (1080x1920)

Thanks

**Comment by premultiply** [comment]
VVS? https://www.youtube.com/watch?v=Bt9zSfinwFA

**Comment by manuelgomezo** [comment]
Sorry, i need that, because my TV Shows its running on instagram and my clients like this format. I dont need to change the aspect ratio, i need that the caspercg allows me to send signal in this format

**Comment by baltedewit** [comment]
Hi, 

You have to run CasparCG in non-native resolution (e.g. 1920x1080) and scale in the consumer (to e.g. 1080x1920). If you have the ability to build your templates / transcode videos that would probably be easiest.

Another solution is to compile CasparCG with a new video mode. Then you have to change https://github.com/CasparCG/server/blob/master/src/core/video_format.cpp and https://github.com/CasparCG/server/blob/master/src/core/video_format.h

**Comment by Julusian** [comment]
custom resolutions are now supported in the config file https://github.com/CasparCG/server/pull/1433

It sounds like you were getting an opengl error, which I don't think we can really do much about
