### ISSUE TITLE
CasparCG Group Timedown

### ISSUE THREAD

**Issue by manuelgomezo** [CasparCG/server#1085]
Hi!

I have configured the casparcg for two ndi channels one for vertical video and other for horizontal, I need to play this two videos (identical time both) at the same time, I made a group with both videos and put in different channels, next to that I play the group BUT THE PROBLEM is that the group don’t have the countdown of the videos that means that I can’t know what time left to the video when is playing, there are an option to play two different videos (with same duration) in two different channels and see the time left ?

Thanks for help!!!

**Comment by Julusian** [comment]
Hi

The groups are handled only in the client, so I am moving this issue to the appropriate repo. https://github.com/CasparCG/client/issues/254
