### ISSUE TITLE
OSC gives a strange values

### ISSUE THREAD

**Issue by romanZay** [CasparCG/server#1090]
I’m receiving a values for “file/time” address. This is two 4-byte values. Converting them to decimal gives me a strange values. The most strange is that current time (when file starts to play) isn’t starts from zero. Why is it so? Obviously it’s not a seconds and not a frames and not a milliseconds. Who can tell me how to interpret these values?

**Comment by Julusian** [comment]
As I said on the forum, you need to look into how OSC encodes data. All I know is that we are conforming to the OSC spec on how the data is encoded, as shown by this monitor app decoding it correctly.
![image](https://user-images.githubusercontent.com/1327476/46300799-80b95600-c59c-11e8-880f-fee16348ee3f.png)

**Comment by romanZay** [comment]
I wonder where did you get that address “/channel/1/stage/layer/10/foreground?!?! There is no such packets...

**Comment by Julusian** [comment]
You didnt specify what version of caspar you are using, so I assumed 2.2 which has that structure.
In 2.0 and 2.1 I get the same numbers but with the slightly different path
