### ISSUE TITLE
Some AMCP commands fail/not recognized (Ubuntu 18.04, 2.2.0 beta 9)

### ISSUE THREAD

**Issue by tobinus** [CasparCG/server#1091]
### Expected behaviour
I expect the `HELP` command to work like described in [the wiki](https://github.com/CasparCG/help/wiki/AMCP-Protocol#help). Similarly for the `INFO CONFIG`, `LOG CATEGORY` and similar.

### Current behaviour
For `HELP`, `HELP <whatever>` and `LOG CATEGORY`, I simply receive `#400 Error`, followed by whatever I wrote on the next line.

The `INFO` command works, but `INFO CONFIG` and all others appear to be interpreted simply as the `INFO` command.

----

### Steps to reproduce
1. Start CasparCG
2. Write `HELP` and hit enter
3. Write `HELP CONSUMER` and hit enter
4. Write `LOG CATEGORY calltrace 1` and hit enter
5. Write `INFO` and hit enter
6. Write `INFO CONFIG` and hit enter

This looks like this:
```
HELP
[2018-10-02 22:22:49.216] [info]    Received message from Console: HELP\r\n
#400 ERROR
HELP
HELP CONSUMER
[2018-10-02 22:23:17.879] [info]    Received message from Console: HELP CONSUMER\r\n
#400 ERROR
HELP CONSUMER
LOG CATEGORY calltrace 1
[2018-10-02 22:24:29.617] [info]    Received message from Console: LOG CATEGORY calltrace 1\r\n
#400 ERROR
LOG CATEGORY calltrace 1
INFO
[2018-10-02 22:25:12.787] [info]    Received message from Console: INFO\r\n
[2018-10-02 22:25:12.787] [debug]   Executing command: INFO
#200 INFO OK
1 720p5000 PLAYING

[2018-10-02 22:25:12.787] [debug]   Executed command (0s): INFO
[2018-10-02 22:25:12.787] [trace]   Ready for a new command
INFO CONFIG
[2018-10-02 22:27:20.892] [info]    Received message from Console: INFO CONFIG\r\n
[2018-10-02 22:25:20.892] [debug]   Executing command: INFO
#200 INFO OK
1 720p5000 PLAYING

[2018-10-02 22:25:20.892] [debug]   Executed command (0s): INFO
[2018-10-02 22:25:20.892] [trace]   Ready for a new command
```
This was with the log level set to trace.

### Environment
* Commit: 727542f
* Server version: v2.2.0 beta 9
* Operating system: Ubuntu 18.04

I built CasparCG using Docker in an SSH session (thus no access to X11 session during build, though I don't think that should be related..?). This was simply with the default configuration file, and no producers set up.

I realize some of these errors may be independent of one another, but I'm reporting this as one bug since they might very well have a common cause. Feel free to split up at your discretion.

**Comment by Julusian** [comment]
Unfortunately, all of the commands you referenced have been removed in 2.2, and so are expected to not work.

Pretty much everything currently on the wiki is applicable to only 2.0 unless it specifies otherwise. https://github.com/CasparCG/help/issues/13

**Comment by tobinus** [comment]
Huh. According to the [changelog](https://github.com/CasparCG/server/blob/master/CHANGELOG.md#amcp-1), many of the commands were added in 2.1. The changelog does not mention removing any, except for [the `INFO` commands](https://github.com/CasparCG/server/blob/master/CHANGELOG.md#amcp). If more of them were removed, you should add that to the changelog.
