### ISSUE TITLE
INFO 1 10 returns empty xml 

### ISSUE THREAD

**Issue by olzzon** [CasparCG/server#1093]
CCG 2.2 beta 7 on Windows 10:
### Expected behaviour
INFO should return a xml with data and an ok like on 4.1NRK-RC2.
AMCP command:  INFO 1 10
Returns:
```
201 INFO OK
<?xml version="1.0" encoding="utf-8"?>
<channel>
   <video-mode>1080i5000</video-mode>
   <audio-channel-layout>[audio_channel_layout] num_channels=2 type=STEREO channel_order=FL FR</audio-channel-layout>
   <stage/>
   <mixer>
      <mix-time>0</mix-time>
   </mixer>
   <output>
      <consumers>
         <consumer>
            <type>decklink</type>
            <key-only>false</key-only>
            <device>1</device>
            <low-latency>false</low-latency>
            <embedded-audio>true</embedded-audio>
            <presentation-frame-age>280</presentation-frame-age>
            <index>301</index>
         </consumer>
      </consumers>
   </output>
   <index>0</index>
</channel>
```

### Current behaviour
On CCG 2.2beta7 It only return the 201 INFO ok and an empty data xml
AMCP Command:  INFO 1 10
```
201 INFO OK
<?xml version="1.0" encoding="utf-8"?>
<channel/>
```

----

### Environment
* Server version: 2.2beta7
* Operating system: Windows 10

---

Using the INFO command without any arguments, it returns the usual info:
```
200 INFO OK
1 1080i5000 PLAYING
2 1080i5000 PLAYING
3 1080i5000 PLAYING
4 1080i5000 PLAYING
```

Tested with:
https://github.com/o3jvind/CasparCG-Minimum
and with:
https://github.com/SuperFlyTV/casparcg-connection

**Comment by olzzon** [comment]
Thanks for the feedback, I´ll change my code to this behaviour.
Should we write "deprecated in 2.2" in:
https://github.com/CasparCG/help/wiki/AMCP-Protocol#info-1

To avoid further confusion?

**Comment by Julusian** [comment]
Not for now, there is a general task to update the wiki for 2.2 that is just waiting a decision on how best to structure the differences https://github.com/CasparCG/help/issues/13

**Comment by olzzon** [comment]
Thanks, i´ll close this one for now :)
