### ISSUE TITLE
Understading of OSC values for /time address

### ISSUE THREAD

**Issue by romanZay** [CasparCG/server#1094]
Guys! I have a problem. I'm parsing OSC bundles manually and only one problem is:
after address /channel/1/stage/layer/5/file/time I get some bytes: ,hh . According to description of OSC protocol "," is a signal for parser that next characters are data tags (describes the type of followed data). As long as packet size is multiply of 4, space after "ff" is necessary to reach correct packet size. After that goes TWO 4-byte values ("f" - is 4-byte and another "f" is 4-byte followed). I transcode it to decimal and get some strange values. 1) "current time" don't start from zero. And generally - what means these values? Who can explain how to interpret them?
P.S. Once again - I'm parsing OSC bundles manually)))
P.P.S. Value for current time is increasing irregularly - when it goes closer to the end of file - it is slowing down…
update: I've tried to look up OSC time tag (may be it should be used in calculations) but there are zeroes...

**Comment by Ultravibeman** [comment]
Issue is closed. It's all about float32 conversion. Wikipedia helps me with understanding of it!!!!
