### ISSUE TITLE
Unpredictive playout when using interlaced

### ISSUE THREAD

**Issue by dotarmin** [CasparCG/server#1097]
### Expected behaviour
Predictive output when playing progressive/interlaced media files in interlaced mode.

### Current behaviour
When setting a channel to `1080i50` and playing media files that are progressive or interlaced the output becomes unpredictive. For example, when playing a progressive file and then starting an interlaced file results sometimes in wrong upper and lower field order and sometimes the order is right.

Verified by using decklink output.

----

### Steps to reproduce
1. Set channel to 1080i50
2. Play a progressive file
3. Play an interlaced file
4. Toggle between those two files
5. Results in unpredictive output for interlaced media

### Environment
* Commit:  727542f
* Server version: v2.2

**Comment by dotarmin** [comment]
ping @ronag @Julusian

**Comment by ronag** [comment]
What does `unpredictive` mean?

**Comment by ronag** [comment]
Can you record and post?

**Comment by dotarmin** [comment]
ping @5opr4ni

**Comment by ronag** [comment]
Is seeking involved? e.g. `START`

**Comment by 5opr4ni** [comment]
Hi
No there is no seek involved. Made a phonerecording to clearer show the issue. I have one 50p 720 file, that plays flawlessly and then I have a 50i file that the first couple of times has the wrong field order but when I restart it several times, it jumps to the correct field order. I hope you can se it in the video here.
https://youtu.be/jDS4LmuPFc8

/olle

**Comment by ronag** [comment]
Can you provide me with the exact files used? The interlaced clip should be de-interlaced... so this issue should not be possible unless the meta in the interlaced file doesn't properly indicate it is interlaced.

**Comment by 5opr4ni** [comment]
Large one, uploading it to wetransfer, you will have a g*m*a*I*l soon.

**Comment by 5opr4ni** [comment]
MediaInfo shows 
ScanType: Interlaced
Scan order: Top Field First

**Comment by ronag** [comment]
Does this happen on the screen consumer as well? Or only decklink consumer?

**Comment by 5opr4ni** [comment]
You cant see the wrong fieldorder in the screenconsumer it shows both fields all the time.

**Comment by ronag** [comment]
@5opr4ni yes, screen consumer shows the de-interlaced output. If that is correct then this is an issue in the decklink consumer somewhere.

**Comment by ronag** [comment]
@5opr4ni that is totally wrong, it's something with the de-interlacer then. I will take a look.

**Comment by ronag** [comment]
The default config was to never deinterlace. Fixed in master.
