### ISSUE TITLE
Feature Request: Send LOG data via OSC

### ISSUE THREAD

**Issue by olzzon** [CasparCG/server#1099]
### Description:
In https://github.com/olzzon/casparcg-state-scanner/ I use OSC protocol to drive a Graphql server. So the only thing CCG needs to do is send OSC data, and you can query the state-scanner and always get the current state of playing media.
But as OSC does not send Load info (only a paused status, no name) and as INFO 1-10 in CCG2.2 does not tell about the loaded background media, I need some way to log what commands has been send and returned via ACMP. (E.G. the lines LOADBG --->   202 LOADBG OK)
This way state-scanner could now the status of the CCG server.

### Solution suggestion
My favourite would be to receive LOG data via OSC E.G. "/CASPARLOG/INFO" or "CASPARLOG/WARNING/" etc. There´s timestamp in the log implementation, so async could be handled in state-scanner. But I haven´t looked into the OSC implementation in CCG, so I don´t know if it´s possible.
If not, I´ll try and send the log via tcp, but this makes things a little more complicated, and it´s a bit of a workaround.

---

### What do you guys think?
I do think it´s important to be able to get the current status of the server, without putting extra load on the server. So I do prefer a separate "state-scanner" or something like that over the old "INFO" command.
Or is there something I´ve overseen, or something else thats planned for future?

**Comment by 5opr4ni** [comment]
Hi, This is removed for now and will be put back in at a later time in 2.3 or 3.0. You always have the console at the server where all commands are visible.  If you don't have the server nearby, set up a tight-vnc server and watch it from wherever you are.

**Comment by olzzon** [comment]
Hi Olle,
Yes the console are fine, but it´s for use in the CasparCG-state-scanner, so it knows what is loaded in the background and in paused clips. (and other things)
Thats why I propose to send INFO part of the LOG status in the OSC stream or as the TCP LOG protocol. 
This way the INFO 1-10 command can be deprecated. And a separate service (like the state-scanner) can handle loaded clips, playing status, count down etc.
I think it makes sense that the server only has to deliver realtime status, and another service delivers the "historical based" status.  :)

**Comment by olzzon** [comment]
After I discovered that the TCP LOG protocol also is gone in 2.2 I gave up, and will stay on 2.1 NRK release until a 2.3/3.0
INFO & OSC data sort of works in 2.2 but only on playing clips, so there´s no way to get status of backgroundclip and loaded non-playing foreground clip.
Anyway, I´ll try to stay updated, and as soon as it´s possible to get the status either from TCP-LOG or from OSC (LOG or Data) I will try to support CCG2.2 again.

**Comment by olzzon** [comment]
After CCG 2.2 got foreground - background also for paused clips, I think I´ll close this feature request.
