### ISSUE TITLE
MIPMAP ERROR

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#1100]
### Expected behaviour
Running the command **MIXER 1-0 MIPMAP 1** should execute the command successfully and reduce aliasing on the specified layer

### Current behaviour
Running the command **MIXER 1-0 MIPMAP 1** gives **#400 ERROR**

----

### Steps to reproduce
Type the command **MIXER 1-0 MIPMAP 1**

### Environment
* Commit: 727542f beta 9
* Server version: 2.2
* Operating system: Windows 10

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by ronag** [comment]
MIPMAP was removed in 2.2. Might make a comeback in 2.3

**Comment by PeterAkakpo** [comment]
Thanks for the info

**Comment by asmith3006** [comment]
Any news on this being brought back? Our resized videos look very poor right now. 

Thanks
