### ISSUE TITLE
After seek command info 1-1 or osc reports file/time 0 and total time 0

### ISSUE THREAD

**Issue by vimlesh1975** [CasparCG/server#1102]
### Expected behaviour
It should give actual file/time and total time.

### Current behaviour
When playing a video it gives file/time and total time ok by both way info and OSC.
But after a seek comaand like 
load 1-1 "go1080p25" seek 66 or
call 1-1 seek 66
It gives file/time and total time 0

### Environment
server 2.2 dated 21.09.18

**Comment by ronag** [comment]
@vimlesh1975 can you please confirm if this is still an issue?

**Comment by vimlesh1975** [comment]
call 1-1 seek 66  was actually working before as well. And Still it is working.
load 1-1 "go1080p25" seek 66 loads the file at seeked frame but time and total time reported is zero.

Means problem is still there as before.

**Comment by 5opr4ni** [comment]
Hi! Have a look at #1086

**Comment by 5opr4ni** [comment]
Hi! Test with the newest build and confirm that you get the desired result. If OK, close this issue.

**Comment by vimlesh1975** [comment]
Yes, working.
Thanks to the developers.
