### ISSUE TITLE
HTML template not playing smooth in 2.2

### ISSUE THREAD

**Issue by nickehallgren** [CasparCG/server#1103]
I tried casparcg-server-ec6d30dc7f5d8b73878a7345695dabd1df451ef2-windows.zip and it seems to work nicely but I have a problem with a HTML template that runs perfectly on 2.1 Beta 2 and not smooth in 2.2.

The template can be found here: https://www.digiactive.net/cgclient/template.zip
Comparing diagnostic (beta 2 vs latest 2.2) it seems like I have a performance problem.
https://www.digiactive.net/cgclient/beta2.png
https://www.digiactive.net/cgclient/latest.png

I'm running CasparCG on Win7 Pro, i7-3770 CPU with 16GB of RAM and a Nvidia Quadro 2000. Does anybody else have the same kind of problem? Or can you replicate it with my template?

**Comment by ronag** [comment]
ping @Julusian
