### ISSUE TITLE
length command reports total time equal to length

### ISSUE THREAD

**Issue by vimlesh1975** [CasparCG/server#1105]
### Expected behaviour
play 1-1 go1080p25 seek 10 length 100 should report total time 17 sec. Because file is of length 17 sec.

### Current behaviour
It reports total time equal to length i.e.  2 sec.

### Steps to reproduce
play 1-1 go1080p25 seek  10 length 100
### Environment

 Server version: . v2.2 date 03 November
 Operating system:  Windows 10

**Comment by 5opr4ni** [comment]
SEEK => go to frame 10 (of video)
LENGTH => play 100 Frames (in channel framerate)

**Comment by vimlesh1975** [comment]
Length is not total time.
And in Earlier versions 2.07 and 2.1 total time shows equal to actual file time.

**Comment by 5opr4ni** [comment]
Hi!

The total time is acquired from cinf on the file provided by the OSC. We have tried to make everything as clean as possible and not being too verbose in the OSC.
The OSC should reflect what is going on, and if you tell Caspar to play a certain length then that is the total length.

/o

**Comment by vimlesh1975** [comment]
In that case for the command play 1-1 go1080p25 seek 200 length 100
 current time may exceed total time.

**Comment by 5opr4ni** [comment]
Hi 

Can agree on that, it is a matter of responsibility. If Caspar should keep track, or if a client should.
I will discuss with some colleagues how this should be reflected with the least amount of data.

/o

**Comment by 5opr4ni** [comment]
Proposal:
`/channel/1/stage/layer/10/foreground/file/time 100.20f 190.02f`
(time would show current frame and the second number the TOTAL filelength)

/channel/1/stage/layer/10/foreground/file/stime 80.0f 15.02f
(stime=segment-time would show, statically, where the segment starts and how long it is)

The time-calculations will be done on the client side with the information from the channel frame-rate in the osc.

**Comment by vimlesh1975** [comment]
/channel/1/stage/layer/10/foreground/file/time 100.20f 190.02f
It seems to be ok as it will be backward compatible in the line of server 2.07 and server 2.1.


/channel/1/stage/layer/10/foreground/file/stime 80.0f 15.02f will provide extra information which may be used for better client programming.

**Comment by ronag** [comment]
Fixed in master. Please test.

**Comment by 5opr4ni** [comment]
> Can anyone recommend a good osc client or Mac or Window?

https://www.kasperkamperman.com/blog/processing-code/osc-datamonitor/

**Comment by 5opr4ni** [comment]
> Proposal:
> `/channel/1/stage/layer/10/foreground/file/time 100.20f 190.02f`
> (time would show current frame and the second number the TOTAL filelength)
> 
> `/channel/1/stage/layer/10/foreground/file/stime 80.0f 15.02f`
> (stime=segment-time would show, statically, where the segment starts and how long it is)

except for what @vimlesh1975 pointed out.
The /stime should show, statically, the seek value and the length.
without that, it is impossible for a 3rd "client" to show if there is a sub-clip playing.

Se the image below.
![casparcg-stime-osc-ex](https://user-images.githubusercontent.com/20354852/48700493-6559e700-ebec-11e8-8594-587ce5b5b5ba.png)

**Comment by vimlesh1975** [comment]
In my opinion stime information is unnecessary. It can be calculated and maintained in client code. time information should be corrected immediately.

**Comment by 5opr4ni** [comment]
Hi!
Can agree on that @vimlesh1975 if you only have a client. But how should a third party monitoring system know in and out in a subclip?

**Comment by PeterAkakpo** [comment]
I think "time" should report the current position and duration of the file currently playing irrespective of seek or not. Also "stime" should only report the seek time or frame. Casparcg should not worry about recalculating duration based on seek. If "stime" is zero, it means we played from start. Any other value greater than zero shows there was a seek. The client will then determine what to do with the "stime" value and the duration from "time"

**Comment by 5opr4ni** [comment]
> I think **"time"** should report the current position and duration of the file currently playing irrespective of seek or not. Also **"stime"** should only report the seek time or frame (should be constant value not position). Casparcg should not worry about recalculating duration based on seek. If **"stime"** is zero, it means we played from start. Any other value greater than zero shows there was a seek. The client will then determine what to do with the **"stime"** value and the duration from **"time"**

As in my post then ;)

**Comment by ronag** [comment]
> In my opinion stime information is unnecessary. It can be calculated and maintained in client code. time information should be corrected immediately.

In my opinion time information is unnecessary. It can also be calculated and maintained in the client code. And unlike stime I can't think of any actual use of it in any situation where it can't be calculated :).

**Comment by 5opr4ni** [comment]
Now it works like this
![osc_clip](https://user-images.githubusercontent.com/20354852/49329474-b4563380-f57f-11e8-8026-37806bbcf08e.png)

**Comment by 5opr4ni** [comment]
And hopefully, we got us a Golden Master :)

**Comment by vimlesh1975** [comment]
Works perfect. Thank you all involved.
