### ISSUE TITLE
Log lines on the console sometimes are interrupted by other logs lines

### ISSUE THREAD

**Issue by saltomodules** [CasparCG/server#1107]
### Expected behaviour
Log lines on the console are never mixed with other log lines

### Current behaviour
Log lines on the console are not always separated well from each other, especially when things go wrong.

For instance here on line 4 the `#202 CG OK` message breaks off the previous line in the timestamp

```
CG 1-100 UPDATE 0 "{\"testdata\":\"test  á test\"}"
[2018-11-08 16:09:21.602] [info]    Received message from Console: CG 1-100 UPDATE 0 "{\"testdata\":\"test  \r\n
[201#202 CG OK
8-11-08 16:09:21.602] [debug]   Executing command: CG UPDATE
[2018-11-08 16:09:21.603] [debug]   Executed command (0.001s): CG UPDATE
[2018-11-08 16:09:21.603] [info]    html[file:///opt/test.html] 1920 1080 50 Log: Uncaught SyntaxError: Unexpected end of JSON input
```

----

### Steps to reproduce

Issue reproduces well on Ubuntu with a `CG UPDATE` command directly from the console containing a problematic special character like `CG 1-100 UPDATE 0 "{\"testdata\":\"test  á test\"}"`

### Environment

Issue has been observed on an Ubuntu system:
   
   **System 1**

    CasparCG Server version:
    2.2.0 ec6d30dc7 Beta 10
    video-mode 1080i5000    

    Operating system:
    Ubuntu 18.04

    Graphics driver:
    Nvidia 390.42  (for GTX1050)

    Decklink drivers:
    Blackmagic Design BlackmagicIO driver 10.10a3

**Comment by k0d** [comment]
This happens due to mixing the console with logging.

I am interested, for what reason do we have the interactive console? Is it used by any clients? Can we not have logging on stdout/stderr and then have the interactive console over telnet (amcp port). 

Could be interesting to have amcp over websockets also!

**Comment by jesperstarkar** [comment]
I use the interactive console all the time, and I think that is a quite normal workflow for many users.

**Comment by jesperstarkar** [comment]
You can add as many new interfaces you'd like, but I don't see any good reason to remove something that has been here since day 1, that you don't need to use if you don't like it.

I use it daily during development. The most used commands in the console for me are `DIAG`, followed by `INFO`, `CLEAR`, and `PLAY 1 AMB`, `PLAY 2 RED` and even `RESTART`.

**Comment by Julusian** [comment]
I think we definitely need to keep the interactive console. Primarily as windows by default doesn't have a telnet client installed, and having to install a separate program to do something as simple as running `DIAG` would not be nice

**Comment by k0d** [comment]
I'm not saying that we remove something for no reason, however it's causing some (minor) issues to have logging and the interactive console in the same interface. So I'm trying to see how it's used before coming up with a suggestion for a fix.

Yes...I use those commands most myself, but they are part of development. So it could be that the interactive console is disabled in release builds (this is an example, not a suggestion!).

Please note: I would never suggest removing something that is used, I would however suggest removing something that is not used. If I don't know 100% how/if something is used, then I'll ask to check.

Most of the time, I actually use logging in the main console, and ```telnet 127.0.0.1 5250``` to get an interactive console. Having a split terminal makes that even nicer. I could think though, having a built-in simple web-panel for controlling CasparCG Server would be really nice. Especially if there are some quick-command buttons such as 'clear' and 'play 1 blue' (blue is so much nicer than red IMHO :) )

**Comment by jesperstarkar** [comment]
I work in a lot of different ways. Some days (both dev an production) i use logging port 3250 with GREP to fetch certain things on the fly. Some days I use an application on my mac to read the log files every now and then. Nearly each day i have a 5250 terminal on my mac open, but I still tend to do some commands directly on the interactive console. I nearly never read logs from the interactive terminale, as I 99% of the time in dev run log level trace and that's horrible to read on the fly. I'm 99.99% of the time typing blind and never seeing the response of things i type in the interactive console as the trace logging fly away. Some days I only work from CasparCG client to reproduce things over and over again, or map shortcuts to given commands. Some days I script a node script to run certain procedures. 

I don't mean to come out a bit harsh and shoot this thread down, please believe me. But seing 3250 and INFO being removed in the past, and reading discussion on how DIAG would be better done over OSC in a web interface etc, I'm afraid every time we start to touch upon removing things that I - and I'm certain hundreds others use every day.

That said: I'm all for adding websocket, http, a built in web client or even a simple GUI. All great ideas! Just don't remove the good old stuff that works one way or another.

Cheers.

**Comment by k0d** [comment]
Oh, and....web-usb/web-midi could really be interesting for interacting with control surfaces...I think I should make an issue for this....

I think it's clear we need to keep the interactive console, but in that case I don't see a good way we can fix this issue with log lines in the console getting mixed up.

There are possible things we could do, such as have a basic telnet client built alongside CCG Server.....telnet is probably 'code-able' in 3 lines of code (an exaggeration I know).

**Comment by k0d** [comment]
@jesperstarkar So it's better in your case to have logging not in the console, but to a file/pipe/socket etc. And the console is for interactivity only?

Of course, I think all of these things should be controlled by compile-time/run-time flags. So people can choose how they want things to work. Enabling only the features they want...

**Comment by jesperstarkar** [comment]
@k0d not at all. For _me_ i never read logs out of the interactive console, but I need the interactivity. For others they never type in it, and they use other log levels and read logs out of it.

Hence: we can't chose one way or the other. 
We can however play with new ideas as you have started, and a two-window solution would be a good start. One for logging only, and one for better interactions? Perhaps a third showing real time info of all channels/layers in a tree structure? Just thinking freely here - but at some point the answer gaining consensus would probably be - keep the server simple and add all high level functionality in supporting systems using the protocols and APIs available, which makes sense.

I think a good first start would be to start serving a static web page from a sibling process much like the scanner API.

Perhaps we should look at adding some clever tools to the Launcher we have created, that already serves scanner, how many other processes you want and static web content: https://github.com/nrkno/tv-automation-casparcg-launcher/releases

**Comment by Julusian** [comment]
> web-usb/web-midi could really be interesting for interacting with control surfaces
True, but that is definitely in the realm of a client program, and not part of this.

> Of course, I think all of these things should be controlled by compile-time/run-time flags.
I don't think compile-time flags is a good idea. @jesperstarkar is a user of caspar, so will want to be able to use the same official build everywhere.

A big question I have is how much of an problem this issue actually is. While it isn't pretty that the console output is mangled, our current solutions are to disable either the log output or the interactivity. So why don't we leave it as it is, and let the user decide if they want to use the interactive console, and accept that it may get mangled like this?

**Comment by k0d** [comment]
I will create a new issue for the web-admin system.

Does anyone object to this issue being closed? We can't fix it really....or should we ensure we can enable/disable the various console things before it's closed?

**Comment by k0d** [comment]
Compile-time flags...just an example...including HTML module is currently a compile-time flag...I don't mean all things should be compile-time or run-time flags...just didn't want to group all flags into one.... :)

**Comment by jesperstarkar** [comment]
If you guys don't see a way of solving the core issue that set the discussion off, I'm fine with it being closed. Of course all (non breaking) improvements to the console are welcome!

**Comment by k0d** [comment]
@saltomodules Do you feel that there are suitable workarounds for this issue? We're aware of the issue, but there doesn't seem to be a clear solution, can we close the issue?

**Comment by saltomodules** [comment]
I don't think this is a particular serious issue. Scarce resources are probably better spend elsewhere, especially if the solution is not clear. I'll close the issue.
