### ISSUE TITLE
Decklink Input Transparency

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#1111]
### Expected behaviour
Playing decklink input on a layer should not reveal what is playing on the lower layer

### Current behaviour
When playing a decklink input, say Play 1-2 decklink device 2, you could sometimes observe that the content playing on layer 1 (the layer beneath the decklink layer) flashes through. It does not occur continuously though. It happens in some time interval

----

### Steps to reproduce
1. Player any video on layer 1 (it can be any layer)
2. Play a decklink input on a layer higher than the layer in step 1 , PLAY 1-2 DECKLINK DEVICE 5 

### Environment
* Commit: beta 9
* Server version: 2.2
* Operating system: Windows 10

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by dotarmin** [comment]
Thanks for reporting this @PeterAkakpo. Does this also apply for `Beta 10`?

**Comment by PeterAkakpo** [comment]
Yes, @dotarmin, it also applies to version 2.2 f3f02c0d beta 10

**Comment by dotarmin** [comment]
I've tested this but I cannot really reproduce the described issue. What I did was the following steps:

1. `PLAY 1-10 RED` and `PLAY 1-10 <movie>`
2. `PLAY 1-20 DECKLINK DEVICE 3`

The red color playing on layer 10 was not flashing through layer 20. However, what I observed was when sending the decklink input command, it did flash randomly between one or two times, after that it didn't flash at all.

**Comment by PeterAkakpo** [comment]
Am running in PAL mode. It is  not something that occurs rapidly but it is there.

**Comment by dotarmin** [comment]
@PeterAkakpo Do you have an ATEM in-between or another switcher?

**Comment by Julusian** [comment]
This was fixed by https://github.com/CasparCG/server/commit/8f881a46566d11e96f8d39303ee3e15ca830edda in the v2.2.0 release
