### ISSUE TITLE
Non-free source in src/modules/bluefish/interop/BlueVelvetC.h?

### ISSUE THREAD

**Issue by petterreinholdtsen** [CasparCG/server#1118]
While reviewing the copyright status of the code to verify it can be accepted into Debian, I came across this header in src/modules/bluefish/interop/BlueVelvetC.h:

```
//
//  Copyright (c) 2017 Bluefish444. All rights reserved.
//
```

This statement indicate that the copyright law defaults apply to this code.  This mean it is non-free software, as there is no rights to distribute, modify, derive etc and thus distribution would be against the law.  Can you have a look at see if the header is present by mistake?

**Comment by Julusian** [comment]
@jamesdwise What is the license of the interop header files? Are they able to be distributed as part of a GPL project?

**Comment by ronag** [comment]
@jamesdwise ping

**Comment by petterreinholdtsen** [comment]
A similar situation is with BlueVelvetCUtils.h, with this header:

```
//
//  BlueVelvetCUtils.h
//  BlueVelvetC
//
//  Created by James on 21/05/2014.
//  Copyright (c) 2014 Bluefish444. All rights reserved.
//
// A file that contains useful Util functions that can ssist in general development.
// indente to be included as-is into BlueVelvetC projects and not part of a library.
```

The other two files in the directory lack copyright information header.

**Comment by petterreinholdtsen** [comment]
I see from the git history the files were introduced in commit af522e1709aa685bd2eff00c9e682b05216ba983 , added 2018-03-16.

**Comment by ronag** [comment]
@petterreinholdtsen they were added by James who works at Bluefish.

**Comment by dotarmin** [comment]
Hi @jamesdwise!

I appreciate if you check this when able.

Thanks!

**Comment by jamesdwise** [comment]
I have updated the license info for the files in question. 
I hope that this is ok.

**Comment by petterreinholdtsen** [comment]
It is very good to see the bluefish module can be included also in Debian.  I had a look at pull request #1122, and see the code now claim to be available using the Boost license, https://choosealicense.com/licenses/bsl-1.0/ .  This should solve the problem.

**Comment by dotarmin** [comment]
Thanks @jamesdwise
