### ISSUE TITLE
License and source of flash files in resources/windows/flash-template-host-files/?

### ISSUE THREAD

**Issue by petterreinholdtsen** [CasparCG/server#1119]
The directory  resources/windows/flash-template-host-files/ in the source is filled with flash Macromedia Flash data, typically the end result of a compilation process.  Where is the source of these files, and what is their license terms?  Are they used?  I could not find any references to "flash-template-host-files" in the source.

**Comment by Julusian** [comment]
These come from https://github.com/CasparCG/templatehost
Flash is not supported on linux, so those files are not used in any linux builds, and could be safely stripped from any linux source tar

**Comment by petterreinholdtsen** [comment]
Right.  Sound like a good idea.  But are they used on any build?  If so, where in the source can I see how they are used?

**Comment by ronag** [comment]
They are just used when bundling. Don’t need to be in this repo per se. Ping @dotarmin

**Comment by dotarmin** [comment]
That's correct @ronag, could be moved to another repo and the instructions on how to get up-and-running needs to be updated then. When building it would just mean to fetch from the repo, same as we do with scanner.

**Comment by Julusian** [comment]
@dotarmin what about uploading them as a zip against tags on the templatehost repo? That is a normal way to use distribute binaries. The builds can then pull either the latest version direct from there.

**Comment by dotarmin** [comment]
> What about uploading them as a zip against tags on the templatehost repo?

I don't have any issues with this, it just has to be communicated correctly and current version of templatehost files should still be bundled in the builds at [builds.casparcg.com](http://builds.casparcg.com)

I can fix this 😄

**Comment by Julusian** [comment]
These are now fetched by cmake (on windows only) from https://github.com/CasparCG/dependencies/releases/tag/flash-template-host during the build.
This is the same flow used for other dependencies
