### ISSUE TITLE
OSC messages getting delayed after a while

### ISSUE THREAD

**Issue by dotarmin** [CasparCG/server#1124]
### Current behaviour
After running v2.2.0, OSC messages are getting delayed and are sent from the server with an interval of multiple seconds. As most we encountered a delay up to about 3 seconds.

### Environment
* Commit: da9bc55
* Server version: v2.2
* Operating system: Windows 7 | Windows 10

**Comment by ronag** [comment]
Any difference when running 1 vs 2 channels?

**Comment by ronag** [comment]
Is it a problem on Linux as well?

**Comment by dotarmin** [comment]
> Any difference when running 1 vs 2 channels?

Cannot confirm this for the moment unfortunately.

> Is it a problem on Linux as well?

We have just used Windows for now. Any user running the server on Linux that could be kind and check this?

Thanks.

**Comment by ronag** [comment]
I've made some optimizations that might help. ARP resolution might also be a culprit, see https://stackoverflow.com/questions/33875210/long-delays-in-sending-udp-packets
