### ISSUE TITLE
Open casparcg server without X or the need of a user interface

### ISSUE THREAD

**Issue by luckcfm** [CasparCG/server#1125]
Is there anyway that I can run caspar server as a background application that doenst need for me to be logged in or to export a display?

I want to run it in an environment that I dont have a user interface, only a command line. 

------
Edit: I forgot to mention that I have a blackmamgic as a consumer.

**Comment by Julusian** [comment]
On linux or windows?

**Comment by dotarmin** [comment]
@Julusian, please correct me if I'm wrong but I'm sure we have been having this discussion in another issue.

**Comment by dotarmin** [comment]
Related to: #897

**Comment by Julusian** [comment]
https://github.com/CasparCG/server/issues/914 is also relevant

**Comment by luckcfm** [comment]
Thanks guys, I wanst aware that there were another discussions, Im running it on linux btw.
I'll close the issue for now.
