### ISSUE TITLE
OSC reports there is one frame left to play when all frames are played

### ISSUE THREAD

**Issue by dotarmin** [CasparCG/server#1127]
### Current behaviour
OSC reports there is one frame left to play but in the reality it has already played all frames.

### Environment
* Commit: da9bc559
* Server version: v2.2
* Operating system: Windows 7 | Windows 10

**Comment by ronag** [comment]
It's not sometimes, it's always, there is a logical explanation for the bug

**Comment by dotarmin** [comment]
Updated title and description, thanks @ronag
