### ISSUE TITLE
Incorrect return message for remove file command

### ISSUE THREAD

**Issue by dotarmin** [CasparCG/server#1129]
### Expected behaviour
In v2.2, command `REMOVE 1-1 FILE` should return `REMOVE FAILED` because no filename was passed with the command.

### Current behaviour
`REMOVE 1-1 FILE` always returns `REMOVE OK`, even when a recording is not in progress.

----

### Environment
* Commit:  533ab69
* Server version: v2.2
* Operating system: Windows 7 | Windows 10

**Comment by Julusian** [comment]
https://github.com/CasparCG/server/commit/48580ca36055741bd871b81a7e047b7ec0fd4cee
