### ISSUE TITLE
Pressing enter in the console shows 'Received message from Console: \r\n'

### ISSUE THREAD

**Issue by k0d** [CasparCG/server#1133]
### Description
When pressing enter in the console, we get an info message and a warning saying "Received message from Console: \r\n", this seems unnecessary.

### Solution suggestion
Unless there is a technical reason to keep them, can we not just ignore 'empty commands' in the console?

**Comment by ronag** [comment]
Sounds like a good idea to me.

**Comment by k0d** [comment]
Can you add to a milestone, so I know which branch to PR to.
