### ISSUE TITLE
Linux fails to run on first launch

### ISSUE THREAD

**Issue by k0d** [CasparCG/server#1138]
Note: issue report is work in progress....have to gather screenshots etc....

### Expected behaviour
It works first time.

### Current behaviour
A clear and concise description of what the current behaviour is.

----

### Steps to reproduce
1. TODO

### Environment
* Commit: [e.g. ab1234c]
* Server version: [e.g. v2.2]
* Operating system: [e.g. Windows 10]

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by Julusian** [comment]
I believe this is caused by the screen consumer.
I have had caspar fail to start sometimes, and disabling the screen consumer in the config appears to resolve that

**Comment by k0d** [comment]
I do believe it is the screen consumer also, I want to do more investigation on this issue myself before making a full report. I just wanted to make the issue so I don't forget to do it later.

**Comment by krzyc** [comment]
Is there any work on this issue? I have similar problem on current build from sources on Ubuntu 19.10. On first start I get:
```
[2019-11-16 13:37:22.293] [info]    Screen consumer [1|720p5000] Initialized.
Assertion 'close_nointr(fd) != -EBADF' failed at ../src/basic/fd-util.c:71, function safe_close(). Aborting.
Aborted (core dumped)
```
Then on following starts it work as expected.

**Comment by Julusian** [comment]
not seen this in a long time
