### ISSUE TITLE
Audio always 1 frame offsync with video playback

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#114]
I have tested with a Decklink Studio2 and CasperCG 2.03 and playback of HD mpeg 1080i25 and Pal Dv25 files
to see if every thing stays in sync.

Test setup is as follows,
Render the countdown in Premiere Pro to a HD MPEG2 file.
Playback this file with CasparCG + Studio Decklink2
capture SDI output of Studio2 to a second system
compare the original with the capture in a Premiere Pro timeline by mixing the video to a match,
look to the audiowaveform to see the offset.

I don't use the SEEK command, so when I start from the beginning of the file, I always get 1 frame audio offset.
Audio is 1 frame early.
The offset keeps constant during a longer playback period.
System audio is not used.

```
The same goes with Pal DV25 files.
What can I do about this?
```

This is the configfile (I tweaked special characters)

```
configuration
paths
media-path V: media-path
log-path log\ log-path
data-path data\ data-path
template-path templates\ template-path
paths
channels
channel
video-mode 1080i5000 video-mode
consumers
decklink
device 2 device
embedded-audio true embedded-audio
keyer internal keyer
latency normal latency
buffer-depth 3 buffer-depth
decklink
consumers
channel
channels
auto-deinterlace true auto-deinterlace
controllers
tcp
port 5250 port
protocol AMCP protocol
tcp
controllers
configuration

Hardware
Intel i7 3.2 GHZ +8 GB ram and Win7-64
Nvidia GTX470
Decklink Studio 2

regards,
```

**Comment by TKooijmans** [comment]
Hi folks,
Yesterday I had a bigscreen film event with playback from Casper server 2.07 (release) and HD MXF 422 HDCAM 50.
playback of audio was still one frame off, audio plays one frame early.
With big screens this unacceptable.
I had to switch to H264 to fix it but datarate has to be reduced then.
I have not tested it yet with blocking decklink, but that function becomes obsolete?

**Comment by TKooijmans** [comment]
I did some tests with playback of DV 25 files and I found out that audio is in sync with the playback of a single file.
When I use loadBG to run down a playlist always the second and following clips play 1 frame of sync
(audio -1 frame)

steps to repro
create with Premiere a dv25 countdown avi
put this twice or more in a playlist
playback with Casper and use LOADBG to play all and capture result
compare result with original

Tested with latest Deckilnk drivers and Casper 207

**Comment by ronag** [comment]
2.2
