### ISSUE TITLE
[HTML] [PAL] Text Scroll Jerky

### ISSUE THREAD

**Issue by sirfnomi** [CasparCG/server#1150]
**Expected Behaviour**
using HTML Template Text scroll or any animation should be as smooth as it is on server 2.0.7, 2.1 beta2 and browser

**Current Behaviour**
in Server 2.2 stable with PAL Mode Text scroll is jerky.
and with 720p5000 Mode Text scrolling smoothly without any jerk.

in recorded file text scroll jerk is double on both channel modes but on direct decklink output scrolling jerky only in PAL mode.

**Sample file and template**
attached tempalte files and sample test file. [ScrollTest.zip](https://github.com/CasparCG/server/files/2728022/ScrollTest.zip)
parameters for recording file: 
ADD 1 FILE "ScrollTest.mp4" -codec:v libx264 -format mpegts

**Environment**
Commit: []
Server version: [v2.2.0 Stable Build x64]
Operating system: [Windows 7]

**Comment by sirfnomi** [comment]
Hi @Julusian,
Scrolling is more jerky when added animated gif in scroll. this issue is also available in Server 2.0.7 and 2.1 but in early development builds of Server 2.2 (Like [28Feb Build](http://casparcg.com/builds/CasparCG%20Server/master/casparcg-server-7ba5e475f07ab7b6d1391097b04059b470457095-windows.zip)) scroll is smooth with animated gif

**Comment by sirfnomi** [comment]
> **Current Behaviour**
> in Server 2.2 stable with PAL Mode Text scroll is jerky.

**Comment by Julusian** [comment]
@sirfnomi does your diag window look something like this?

![image](https://user-images.githubusercontent.com/1327476/51433052-27079500-1c3a-11e9-92a0-6cbdce1937d7.png)

**Comment by sirfnomi** [comment]
![html2 2](https://user-images.githubusercontent.com/11202594/51476192-913d4880-1da6-11e9-95ff-a54de873ba6d.png)

diag window here

**Comment by Julusian** [comment]
ok, I am pretty sure this is cause by #1165 then
