### ISSUE TITLE
CEF leaving remotedebugging Screen white

### ISSUE THREAD

**Issue by MauriceVeraart** [CasparCG/server#1152]
### Expected behaviour
Nothing happens when leaving remotedebugging

### Current behaviour
When leaving remote debugging when the "elements"tab is open
some times leaves the template in a fullwhite background state

this also happens when the remotedebug window crashes

----

### Steps to reproduce
1. go into remote debugging
2. go to the elements tab
3. leave the browser window

**Comment by Julusian** [comment]
I quickly tried to reproduce this earlier and was unsuccessful.

But I'm not sure what we can do about this. It sounds like CEF is sending us a 'bad' frame, but I don't think there is a way to make CEF give us a new frame outside of the normal cycle.
Could it be that the CEF renderer is crashing? But again not anything to do with Caspar

**Comment by MauriceVeraart** [comment]
Hi Julian this happened to me quite some times this week.

of coarse this could also have something to do with the template it self.
but i can not post the template in public. i can send you in a PM

this is in fact a minor issue as you should not go into the debug window during production.

**Comment by Julusian** [comment]
> of coarse this could also have something to do with the template it self.

I am wondering that. If you could email it to git(at)julusian.co.uk or pm me on the forum then I can give it a try

> this is in fact a minor issue as you should not go into the debug window during production.

Definitely. I would still like to know more on why this is happening before closing as wont fix
