### ISSUE TITLE
PSD Producer: Cache as bitmap to be able to apply a mask to text

### ISSUE THREAD

**Issue by didikunz** [CasparCG/server#1159]
### Description
Add a cache as bitmap functionality to the Text Producer.

### Solution suggestion
As the Scene/PSD Producer is today, it is not possible to mask a (dynamic) text. For the PSD Producer to be able to use it in production this would be mandatory. We could render the Text Producer as a bitmap before displaying it and adding the functionality to update the bitmap, when the text is changed (Update command). Very similar as the cacheAsBitmap property in Flash works.

--

**Comment by didikunz** [comment]
I think I did not make myself clear. What I try is to use a mask in Photoshop. So this PSD file:
![grab1](https://user-images.githubusercontent.com/6048776/51526602-09e9e680-1e33-11e9-9b98-fdfa421ee275.png)
Shows in CasparCG 2.1.3 NRK like this:
![grab2](https://user-images.githubusercontent.com/6048776/51526642-1b32f300-1e33-11e9-9ef3-e037c57be41e.PNG)

**Comment by herzogmedia** [comment]
This is a very much appreciated feature, indeed ;)

**Comment by dotarmin** [comment]
CasparCG Server v2.1 is not supported anymore but the PSD producer is supposed to return in the future, see issue #707.

**Comment by didikunz** [comment]
> CasparCG Server v2.1 is not supported anymore but the PSD producer is supposed to return in the future, see issue #707.

I know, but I am referring to the NRK brach also and would need that before 2.3 comes out.

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
