### ISSUE TITLE
Error building on ubuntu 18.04

### ISSUE THREAD

**Issue by luckcfm** [CasparCG/server#1160]
### It should compile
I installed all the required libs and I am getting error when compiling

### When I run make -j8 it doesnt compile, it exits with error code

Below is a screenshot with the error that I get. Im feeling that something is missing... 

----

### Steps to reproduce
Just compile it after cmake.
### Environment
* Commit:  943f890  
* Server version: v2.2
* Operating system: Ubuntu 18.04

---

### Screenshots
![screenshot from 2019-01-15 14-28-26](https://user-images.githubusercontent.com/6090511/51194419-2a192300-18d2-11e9-9ff6-1515f6e6fcea.png)

**Comment by petterreinholdtsen** [comment]
Are you using clang to build?  The error look quite similar to the error I see when building with clang, see #1142 for proposed fixes.

**Comment by petterreinholdtsen** [comment]
Sorry, wrong number.  I mean #1141.

**Comment by luckcfm** [comment]
Thanks @petterreinholdtsen. 
But it seems that the problem was with the status variable. It should be a bool but we are passing a int. 
I changed the type of the var and compiled ok.

**Comment by petterreinholdtsen** [comment]
[Lucas Cesar F. de Medeiros]
> But it seems that the problem was with the status variable. It should
> be a bool but we are passing a int.  I changed the type of the var and
> compiled ok.

Sure, that is the problem with the code, as you could see from the issue
I pointed to.  And my gcc ignore the problem, while clang reject the
code.  Thus I was curious if you have a gcc version that reject the
code, or a clang version similar to mine.

A more acceptable change might be to use 'BOOL' instead of 'bool'.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by luckcfm** [comment]
I'm using the tools that is provided on the building list in a fresh install of Ubuntu, I believe I'm not using clang. 

Im kinda new on c++, so my knowledge in this area is very low.  But thanks again, I could build it and run successfully here. Hope this thread can help other with the same issue. 

Heres the diff from the file that I changed

https://pastebin.com/0KvEbP65 

Ill close the issue for now.
