### ISSUE TITLE
Get current frame as in version 2.1

### ISSUE THREAD

**Issue by luckcfm** [CasparCG/server#1162]
So in v2.1 I would do something like this to get the actual frame being played (via osc):

`/channel/1/stage/layer/1/file/frame`

But now in v2.2 I'm not being able to do so, was this removed? If so, how do I get those information?

**Comment by vimlesh1975** [comment]
In server 2.2 this information is not available now.
Now  available is /channel/1/stage/layer/1/foreground/file/time
And then we have to calculate frame number our self by multiplying above value by frame rate.

**Comment by luckcfm** [comment]
Thanks @vimlesh1975. Ill follow this aproach.
