### ISSUE TITLE
Why are terminate warnings hidden on Linux?

### ISSUE THREAD

**Issue by petterreinholdtsen** [CasparCG/server#1164]
I discovered this while trying to get the code to work with clang on Linux.  Clang do not understand the -Wno-terminate compiler flag.  Why is the flag used with gcc?  As far as I can tell, this will produce warnings when exceptions are used in destructors.  This should be avoided, and a warning from the compiler make sense to me.  Perhaps the flag should be removed from the linux build like this?

```
--- a/src/CMakeModules/Bootstrap_Linux.cmake
+++ b/src/CMakeModules/Bootstrap_Linux.cmake
@@ -75,7 +75,7 @@ ADD_DEFINITIONS (-DNDEBUG) # Needed for precompiled headers to work
 
 ADD_COMPILE_OPTIONS (-std=c++14) # Needed for precompiled headers to work
 ADD_COMPILE_OPTIONS (-O3) # Needed for precompiled headers to work
-ADD_COMPILE_OPTIONS (-Wno-deprecated-declarations -Wno-write-strings -Wno-terminate -Wno-multichar -Wno-cpp)
+ADD_COMPILE_OPTIONS (-Wno-deprecated-declarations -Wno-write-strings -Wno-multichar -Wno-cpp)
 ADD_COMPILE_OPTIONS (-msse3)
 ADD_COMPILE_OPTIONS (-mssse3)
 ADD_COMPILE_OPTIONS (-msse4.1)
```

**Comment by petterreinholdtsen** [comment]
I had a closer look, and the only issue hidden by -Wno-terminate is the throw in scope_exit::~scope_exit() from src/common/scope_exit.h:

```
    ~scope_exit()
    {
        try {
            if (valid_)
                func_();
        } catch (...) {
            if (!std::uncaught_exception())
#pragma warning(push)
#pragma warning(disable : 4297)
	        //throw;
#pragma warning(pop)
            else
                CASPAR_LOG_CURRENT_EXCEPTION();
        }
    }
```

I fail to undertstand why the throw is there.

**Comment by Julusian** [comment]
I don't know what to do about this.
To me the throw makes sense as this `scope_exit` is intended to allow deferring a chunk of code to the end of a function.
So in my mind, a throw is reasonable here, and should result in a throw from the function that deferred this block.

I'm happy to accept a change if someone has an idea for how to improve this, but I'm going to close this issue as it isn't something I will act upon
