### ISSUE TITLE
Inconsistent channel tick rate for interlaced decklink

### ISSUE THREAD

**Issue by Julusian** [CasparCG/server#1165]
### Expected behaviour
When the channel has no producers and a decklink consumer, the diag graph should have a consume-time line at roughly 50%

### Current behaviour
Fine when the channel is progressive, but when interlaced the consume-time line is at 0 with an occasional spike. (In debug builds, there are a lot more spikes)
If the decklink consumer is removed, then the line returns to normal.

Other consumer types are also showing massively varying tick-times, and their playback (especially noticable on screen consumer) is stuttery.
The decklink output looks fine, I assume because of the buffering done on the card.

Playback of files with ffmpeg looks to be fine, but the html producer is really unhappy with this if the template uses requestAnimationFrame. Templates doing dom changes using setTimeout run smoother (but not perfect).

I believe this is because when a frame is scheduled to the decklink, the consumer takes 2 frames from the buffer, and the channel then works as fast as possible to refill the buffer (as the buffer is what controls the rate of the channel). 

### Environment
* Commit: 713723609ccc0f2956170c2bd99cf11c053bde26
* Server version: 2.3-dev & 2.2.0
* Operating system: Windows 10

---

### Screenshots
Normal:
![image](https://user-images.githubusercontent.com/1327476/51433232-2a048480-1c3e-11e9-9e70-a16ad89744f3.png)
Debug: 
![image](https://user-images.githubusercontent.com/1327476/51432829-308efe00-1c36-11e9-86c7-46dc228979bf.png)
Release: 
![image](https://user-images.githubusercontent.com/1327476/51433204-8c10ba00-1c3d-11e9-9278-6cca60f0edcf.png)
Release timings: 
![image](https://user-images.githubusercontent.com/1327476/51433212-9e8af380-1c3d-11e9-9fcc-956dcfedd311.png)

**Comment by Julusian** [comment]
I think this is the cause of #1150 and maybe #1103.

@ronag I'm not sure how best to resolve this. Perhaps using prec_timer or similar in decklink_consumer::send() would be reliable enough?

**Comment by premultiply** [comment]
> I believe this is because when a frame is scheduled to the decklink, the consumer takes 2 frames from the buffer, and the channel then works as fast as possible to refill the buffer (as the buffer is what controls the rate of the channel).

Yes, sounds reasonable. Might be caused by the interlacer consuming two progressive frames at the same time from the internal pipeline to create an interlaced frames with two fields.

**Comment by brucedk** [comment]
Is #1145 has anything to do with it?

**Comment by sirfnomi** [comment]
Hi, @Julusian ,
Development builds are fixing issues but still I'm unable to use it because of this issue just wanna ask any fix for this issue soon ??
Thanks,

**Comment by grahamspr86** [comment]
Is this the fix? https://github.com/CasparCG/server/pull/1228

**Comment by Julusian** [comment]
Fixed by https://github.com/CasparCG/server/pull/1255
