### ISSUE TITLE
Auto-run Scanner.exe

### ISSUE THREAD

**Issue by didikunz** [CasparCG/server#1169]
### Description
Make scanner.exe autostart with the server.

### Solution suggestion
It should not be a big thing to add a few lines of code, that start the scanner.exe on startup of the server (if not already running). 

### Additional information
One of the most asked question in the forum these days is something along the lines of "Server 2.2 does not list the media files and templates in the client". Sometimes they complain about a error "that the media-scanner is not running" without realizing that this is one and the same issue.

**Comment by ronag** [comment]
The whole media scanner thing is outside of the main project. Maybe better packaging?

**Comment by didikunz** [comment]
I mean only add a shell run command somewhere in the startup code.

**Comment by ronag** [comment]
That’s what I mean. Packaging.

**Comment by Julusian** [comment]
The autostart bat script does start the scanner and it does say to run scanner in the readme, so I don't know how much more we can do without adding a proper launcher to start both components.
Perhaps the log message can be made clearer?
It would be nice for casparcg to be made to start and monitor the scanner, but I expect that will be too complex and defeat the point of separating the logic out

**Comment by didikunz** [comment]
Just a shell.start or similar command. You see, a lot of new Caspar users are very bad at reading and writing English and do not read the readme. The then use Google translate to ask a the same questions all over again. So it would be nice to add this simple thing.

**Comment by dotarmin** [comment]
> @didikunz You see, a lot of new Caspar users are very bad at reading and writing English and do not read the readme

I'm not sure what we can do about that?

However, what we could do is maybe clarify in the README to start CasparCG Server via the provided `casparcg_auto_restart.bat`?

**Comment by didikunz** [comment]
They will still not read it. Is there technical a reason why the main exe could not issue the shell comand to start the scanner?

**Comment by dotarmin** [comment]
> @didikunz They will still not read it :)

I'm still not sure what the project can do about that? 

> @didikunz Is there technical a reason why the main exe could not issue the shell comand to start the scanner?

I don't think so (@Julusian, @ronag) besides putting responsibility on the server it-self (which I'm against). Some users also do not use the scanner at all and putting it in the server wouldn't make sense because it's something optional today. 

My opinion is that this responsibility to start the scanner in some way should be put on the users because there is a workaround that is good enough. I mentioned Julian and Robert because they maybe have other thoughts on this.

:)

**Comment by dotarmin** [comment]
As @Julusian sugessted we can rename the`casparcg_auto_restart.bat` to `start_casparcg.bat` or something like that.

**Comment by didikunz** [comment]
That rename is a good idea. I now created a standard response residing on my desktop, that I will simply copy paste into all future questions regarding not be able to get the length of clips etc. That will do the job of keeping the issue not eating too much of my time spent in the forum.

**Comment by dotarmin** [comment]
I can shim in on the forum and assist you :)

**Comment by didikunz** [comment]
Thanks! But I think you have better stuff to do. :)
