### ISSUE TITLE
Youtube live stream does not work due outdated chrome browser

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#1172]
### Expected behaviour
Playback of Youtube live streams.

### Current behaviour
Playback of normal youtube videos works most of the time ok with CasparCG.
(older ones)
But I can’t get live videostream to work anymore,
I use
PLAY 1-1 [HTML] "https://www.youtube.com/embed/QhlSII3UKvc?autoplay=true&showinfo=0&autohide=1&vq=hd1080&nohtml5=1"

the nohtml5 tag worked in the past, but now I always get
![afbeelding](https://user-images.githubusercontent.com/4194609/51738242-f1760800-208e-11e9-8d6e-1f8b45b56af5.png)

----

### Steps to reproduce
PLAY 1-1 [HTML] "https://www.youtube.com/embed/QhlSII3UKvc?autoplay=true&showinfo=0&autohide=1&vq=hd1080&nohtml5=1"

### Environment

* Server version: all versions
* Operating system: Windows 7/10

---

### Screenshots
PLAY 1-1 [HTML] "https://www.youtube.com/embed/QhlSII3UKvc?autoplay=true&showinfo=0&autohide=1&vq=hd1080&nohtml5=1"

**Comment by Julusian** [comment]
CEF is already updated in 2.3, and is being kept as up to date as possible so there isnt really anything more we can do here.
If it still isnt working, then there is nothing more we can do until CEF fix some stuff upstream
