### ISSUE TITLE
Use a new instance of the host per template layer.

### ISSUE THREAD

**Issue by coral** [CasparCG/Server#119]
When loading to many templates at once the template hosts sometimes just refuses to load templates with error messages (that i ofc can't remember now) but it's something about the flash refuses to create instance.

Is it possible to create a entirely new instance of Flash in these cases to avoid having to restart the CasparCG server?

**Comment by jesperstarkar** [comment]
@coral This can be closed? Because it doesn't make sense, what you describe.

There's one TemplateHost for each Video Layer. Each TemplateHost is in fact a separate Flash Player, and the TemplateHost has an internal Stage with Flash Layers.
