### ISSUE TITLE
"Scalar deleting destructor" exception after HTML-producer usage

### ISSUE THREAD

**Issue by drakmor** [CasparCG/server#1193]
Got a exception on next start after HTML producer usage
[exception.txt](https://github.com/CasparCG/server/files/2979927/exception.txt)

### Steps to reproduce
1. Run in Debug mode
2. Send command "PLAY 1-1 [HTML] https://google.com"
3. Wait 10 sec
4. Quit server
5. Run server again

### Environment
* Commit: [c5b93c056 ]
* Server version: [v 2.3.0 dev]
* Operating system: [Windows 10]
---

**Comment by Julusian** [comment]
I used to see this, but havent in a while so it sounds like this was fixed by accident
