### ISSUE TITLE
Audio is pitched from internet radio stream

### ISSUE THREAD

**Issue by TondaKrist** [CasparCG/server#1194]
### Expected behaviour
Audio should not be pitched

### Current behaviour
Audio is pitched

----

### Steps to reproduce
1. PLAY 1-1 http://ice.abradio.cz/blanikfm128.mp3
2. listen to pitched audio on any consumer (declink or system audio)
3. compare to http://ice.abradio.cz/blanikfm128.mp3

### Environment
* Server version: 2.2 and 2.3
* Operating system: Windows 10

**Comment by premultiply** [comment]
#1170

**Comment by dotarmin** [comment]
@premultiply, can this issue be discussed in #1170?

**Comment by premultiply** [comment]
Yes, I think so.
There is no Samplerate conversion or it is not explained that CasparCG (currently) has only support for 48kHz only.

**Comment by ryci-us** [comment]
@premultiply , yesterday i found the same - CasparCG doesn't do sample rate conversion, so only 48kHz plays ok.

**Comment by dotarmin** [comment]
Refering to #1170 for further discussions
