### ISSUE TITLE
NDI producer debug info

### ISSUE THREAD

**Issue by ahallez** [CasparCG/server#1198]
I'm trying out the new NDI producer (https://github.com/ianshade/server/releases/tag/v2.3.0-ndi-v1.1)
I try to load an NDI source with a telnet command:
`LOAD 1-1 NDI "<PC-name> (<source name>)"`

The load fails, but I don't know why. Even after setting the log-level to debug or trace the log message still tells me to turn on log level debug in order to see the stack trace.

So I have no clue why the NDI source is not loaded.

The NDI source is sent by OBS on a different PC. Receiving the NDI stream with OBS works.

**Comment by sirfnomi** [comment]
I should play with play command

PLAY 1-1 [NDI] "PC-name (source name)"

**Comment by ahallez** [comment]
I see. Missed out on the brackets. It is working fine now
