### ISSUE TITLE
casparcg.com download page doesn't have latest version

### ISSUE THREAD

**Issue by cjdenio** [CasparCG/server#1200]
Hi, it looks like [this page](casparcg.com/downloads.html) lists v2.0.7 as being the latest, though the GitHub Releases page says otherwise. (it lists v2.2.0 as being stable) I was having some issues with the Client not quite working with the Server, and the reason was that I didn't have the latest version of the Server. Thank you!

**Comment by ducthiem90** [comment]
You can download from github:
https://github.com/CasparCG/server/releases

**Comment by dotarmin** [comment]
Hi,

casparcg.com will get a minor update after Foss-North upcoming Monday, the idea is to redirect users to appropriate GitHub repository for downloads/releases. We still have http://builds.casparcg.com for daily builds but releases will also be uploaded into a separate folder on that server in the future.

Bets regards,
Armin

**Comment by cjdenio** [comment]
Thank you!
