### ISSUE TITLE
HTML producer won't start rendering (CefRenderHandler > OnPaint)

### ISSUE THREAD

**Issue by kormikk** [CasparCG/server#1202]
### Current behaviour
When adding a HTML template to CasparCG, the HTML will be added, I get the #202 OK back in the console. However, the template won't start rendering. Upon checking the DIAG on CasparCG, I see that the "browser-tick-time" green line won't appear. After trying to add the template multiple times, it randomly works and in those cases it also shows the green line. _(see image attached)_
![slack_qmvG2lQytv](https://user-images.githubusercontent.com/34093183/55933599-2cb7ba00-5c2e-11e9-967e-90e71bf8b648.png)

**We've managed to track down the issue until a certain point:**
It comes from **html_producer.cpp**. The CefRenderHandler > OnPaint isn't called. This won't start rendering the template as the template info won't be sent from the memory to the caspar renderer.

```
void OnPaint(CefRefPtr<CefBrowser> browser,
                 PaintElementType      type,
                 const RectList&       dirtyRects,
                 const void*           buffer,
                 int                   width,
                 int                   height) override
```

---

The issue also happens with empty html, with no scripts, no info in them. Once we successfully add a template _(green browser-tick-time line appears)_ it won't crash or stop unless removed.

3 PCs out of 9 are producing this issue. Tried with **CPU AMD Ryzen 7 2700**, Motherboards, Memory _(DDR3, DDR4)_ and Windows _(10 & Server 2012)_

We've tried removing the Decklink cards _(2x SDI 4K)_ as previously it caused audio issues and slowdown but it didn't have any effect on our current issues.

Currently we're running on 1080p5994. On 1080i5994 & 720p5000 we have the same issues but it seems like the templates appear slightly more often _(6/10 over 1/10)_ when adding them compared to 1080p5994.

Tried putting the html files into a subfolder, but didn't solve the problem either.

The HTML are communicating with our custom admin software via a local server, and we get status feedback if we press a button, so the template is running but not rendering. _(Note: As mentioned before, we tried with plain empty clean html and didn't work either, so it's unrelated to the communication)_

Adding `<html><enable-gpu>true</enable-gpu></html>` to our config will make it so the template always gets rendered but the performance of the html producer will be really slow, and plays a regular template with about 5frames/sec.

---

### Steps to reproduce
1. cg 1-10 add 1 [template] 1

### Environment
* casparcg-server-196f76a5937cb499a854bdc7c11554a57aebb264-windows _(and upwards to the lastest release)_
* casparcg-server-2.2.0-stable-windows
* Windows 10 x64 Enterprise & Server 2012 Standard x64

---

### CasparCG Config
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<configuration>

	<paths>
		<media-path>media/</media-path>
		<log-path>log/</log-path>
		<data-path>data/</data-path>
		<template-path>template/</template-path>
	</paths>

	<lock-clear-phrase>secret</lock-clear-phrase>

	<channels>
		<channel>
			<video-mode>720p5000</video-mode>
			<consumers>
				<decklink>
					<device>1</device>
					<latency>default</latency>
					<keyer>external_separate_device</keyer>
					<key-device>device + 1</key-device>
				</decklink>
				<screen />
			</consumers>
		</channel>
	</channels>

	<controllers>
		<tcp>
			<port>5250</port>
			<protocol>AMCP</protocol>
		</tcp>
	</controllers>

	<amcp>
		<media-server>
			<host>localhost</host>
			<port>8000</port>
		</media-server>
	</amcp>

	<html>
		<enable-gpu>false</enable-gpu>
	</html>

	<osc>
		<predefined-clients>
			<predefined-client>
				<address>192.168.1.162</address>
				<port>6250</port>
			</predefined-client>
		</predefined-clients>
	</osc>

</configuration>
```

**Comment by kormikk** [comment]
**Update:** Seems like all PCs have AMD Ryzen 7 2700 3.2GHz in them. Maybe helpful for a potential fix?

**Comment by kormikk** [comment]
### **Update #2**
We've managed to build a custom client using the latest CasparCG source code available and added [Chromium 3.3578.1870](https://www.nuget.org/packages/cef.sdk/3.3578.1870) to our build. This solved our issue and now the HTML templates load every time on new generation AMD CPU

**Comment by dotarmin** [comment]
Hi @kormikk,

I'm glad it was solved for you, we will look into upgrading the Chromium.

Cheers!

/Armin

**Comment by Rajchl** [comment]
Hi, I now have the same problem and I am using Caspar server version 2.3.0 where cef 3.3578.1870 should already be.
Could we re-open the issue 1202

I have tryied to solve it on the forum, but so far without success:
[(https://casparcgforum.org/t/html-template-not-showing-on-outupt-sometimes/3535)]
