### ISSUE TITLE
build with mingw makefiles and qt for windows

### ISSUE THREAD

**Issue by a-lala** [CasparCG/server#1203]
I cant make with cmake and mingw makefiles environment in windows.

E:/server-master/build>cmake -G "MinGW Makefiles" -A x86_64 ../src
CMake Error at CMakeLists.txt:4 (PROJECT):
  Generator

    MinGW Makefiles

  does not support platform specification, but platform

    x86_64

  was specified.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "E:/server-master/build/CMakeFiles/CMakeOutput.log".

**Comment by Julusian** [comment]
We do not currently support compiling with mingw on windows, and I am not aware of any plans for that to change.
I would be willing to merge a PR which provides support for it.
