### ISSUE TITLE
If I select a video how can the output show 1st frame instead of showing black?  CasparCG_2.0.8

### ISSUE THREAD

**Issue by akabucwa** [CasparCG/server#1209]
### Current behaviour
A clear and concise description of what the current behaviour is.

----

### Steps to reproduce
1.
2.
3. ...

### Environment
* Commit: [e.g. ab1234c]
* Server version: [e.g. v2.2]
* Operating system: [e.g. Windows 10]

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by dotarmin** [comment]
I'm closing this issue due to the lack of information.
