### ISSUE TITLE
Support to LOAD/PLAY files with full filename

### ISSUE THREAD

**Issue by thezulk** [CasparCG/server#1210]
We have the need to specify the full filename some times as we have the same filename with different extentions.

This feature exist in 2.0.7

CasparCG 2.2.0

loadbg 2-3 GC-G-LANG-VJ
202 LOADBG OK
loadbg 2-3 GC-G-LANG-VJ.mov
404 LOADBG FAILED

CasparCG 2.0.7

loadbg 2-3 GC-G-LANG-VJ
202 LOADBG OK
loadbg 2-3 GC-G-LANG-VJ.mov
202 LOADBG OK

**Comment by ryci-us** [comment]
i.e. you can use fullpath:
loadbg 2-3 "C://CasparCG//media//GC-G-LANG-VJ.mov"

**Comment by thezulk** [comment]
Our need is not the full path, only the filename.
If there are two files with the same name, with different extentions, we need to be able to choose the correct one.

ex:
loadbg 2-3 GC-G-LANG-VJ.mov
loadbg 2-3 GC-G-LANG-VJ.dv
loadbg 2-3 GC-G-LANG-VJ.mxf
loadbg 2-3 GC-G-LANG-VJ

**Comment by dotarmin** [comment]
@thezulk, what's the need of having multiple files differentiated by the file extension?

**Comment by ryci-us** [comment]
@dotarmin why do you think that AMCP is involved? AMCP transfers everything to producer.

**Comment by dotarmin** [comment]
> @ryci-us, why do you think that AMCP is involved? AMCP transfers everything to producer.

Wrong label and wrong issue, thanks for noticing this 👍 

/Armin

**Comment by ducthiem90** [comment]
I don't have permisson to push request. You can:
1. Open file ffmpeg_producer.cpp
2. Edit in probe_stem function
`for (auto it = boost::filesystem::directory_iterator(dir); it != boost::filesystem::directory_iterator(); ++it) {
        if (boost::iequals(it->path().stem().wstring(), stem2.filename().wstring()) &&
            is_valid_file(it->path().wstring()))
            return it->path().wstring();
    }`

To
`for (auto it = boost::filesystem::directory_iterator(dir); it != boost::filesystem::directory_iterator(); ++it) {
        if ((boost::iequals(it->path().stem().wstring(), stem2.filename().wstring()) || boost::iequals(it->path().filename().wstring(), stem2.filename().wstring()))
            && is_valid_file(it->path().wstring()))
            return it->path().wstring();
    }`
3. Edit create_producer function
`if (!boost::contains(path, L"://")) {
        path = boost::filesystem::path(probe_stem(env::media_folder() + L"/" + path)).generic_wstring();
        name += boost::filesystem::path(path).extension().wstring();
    }`

To

if (!boost::contains(path, L"://")) {
        path = boost::filesystem::path(probe_stem(env::media_folder() + L"/" + path)).generic_wstring();
        auto ext = boost::filesystem::path(path).extension().wstring();
        if (!boost::iends_with(name, ext))
            name += ext;
    }

4. Rebuild

**Comment by ryci-us** [comment]
> I don't have permisson to push request. You can:

you can clone it, make a new local branch, edit code and send pull request, everything directly from website.

**Comment by ducthiem90** [comment]
> > I don't have permisson to push request. You can:
> 
> you can clone it, make a new local branch, edit code and send pull request, everything directly from website.

Thanks.

**Comment by thezulk** [comment]
> @thezulk, what's the need of having multiple files differentiated by the file extension?

@dotarmin we have different formats for video clips and moving graphics, and sometimes the graphics department saves some moving graphics to both formats for redundancy. But if you use the video clip files as if they where motion graphics the alpha channel is solid and the screen goes black except for the moving graphic.

**Comment by ducthiem90** [comment]
#1216

**Comment by dotarmin** [comment]
Thanks @ducthiem90 for submitting a PR fixing this 👍

**Comment by ryci-us** [comment]
@ducthiem90 Thanks for this PR.
I have almost same problem in image producer. I would like to ask you to make relative and absolute path support in image_producer.

**Comment by ducthiem90** [comment]
> @ducthiem90 Thanks for this PR.
> I have almost same problem in image producer. I would like to ask you to make relative and absolute path support in image_producer.

I updated
#1216

**Comment by Julusian** [comment]
This is in 2.2 now, and will be merged to 2.3 soon
