### ISSUE TITLE
Image Producer doesn't support absolute path

### ISSUE THREAD

**Issue by ryci-us** [CasparCG/server#1213]
Hello, i have upgraded from 2.0.7 to 2.2 and found a problem, that after image producer introduction it's not possible to specify absolute path for image files.

PLAY 1-2 "C://CasparCG//media//testchart.png"
#404 PLAY FAILED

PLAY 1-2 "testchart"
#202 PLAY OK

**Comment by dotarmin** [comment]
Hi, this is same issue as #1210, just a different producer. When #1210 is fixed it will be fixed for all producers and not just specific ones.

/Armin

**Comment by Sidonai-1** [comment]
Hi!
Has this been included in 2.3.x releases? Or only the full file name?
Thanks
