### ISSUE TITLE
HTML - Could not invert viewmatrix

### ISSUE THREAD

**Issue by JonFranklin301** [CasparCG/server#1220]
### Expected behaviour
HTML Template using [Lottie player](https://github.com/airbnb/lottie-web) plays animations smoothly.

### Current behaviour
HTML Template using Lottie player has jerky playback and logs the following message multiple times whilst performing animation: `[0620/155021.029:INFO:GrAAConvexPathRenderer.cpp(848)] Could not invert viewmatrix`

To be honest, I'm not too sure what this means - could it be my animation/Lottie using a feature that is not supported in the current CEF version?

----

### Steps to reproduce
1. Call `CG 1-101 ADD 1 "TeamSheetfirstEleven" 1` and `CG 1-101 STOP 1` - The message `[0620/155021.029:INFO:GrAAConvexPathRenderer.cpp(848)] Could not invert viewmatrix` is logged multiple times and the animation is not smooth.
This same template has been tested in 2.1.0 and plays out smooth + does not log this message.

### Environment
* Server version: Server 2.2.0 66a9e3e2 Stable
* Operating system: Windows 10

[_template.zip](https://github.com/CasparCG/server/files/3310987/_template.zip)

**Comment by hreinnbeck** [comment]
This seems related to the Skia library in CEF.  I think this might be related to using scale() with negative numbers or decimal zero "0.0".
