### ISSUE TITLE
JavaScript Engine Update

### ISSUE THREAD

**Issue by AskMP** [CasparCG/server#1221]
### Description
I have only recently come across CasparCG but I cannot see why I have missed this in the past. Attempting to migrate some of my existing tools over however, I'm finding many if not all of my JavaScript tooling won't work in the HTML Page rundown items. After doing some testing, I see that many of the current and last gen features are simply not available; fetch, promises, fat-arrows, classes, etc...

### Solution suggestion
Depending on what you're using as a JS/Browser engine on the different platforms, would it be possible to get an update to that? There are a lot of external web-tools that all run current (if not bleeding edge) methods. I'm hoping that it would be a simple plug-n-play engine update for you but alas I cannot speak on the complexity that it would involve.

**Comment by hreinnbeck** [comment]
What version are you running?  This should all be supported I think.

**Comment by AskMP** [comment]
> What version are you running? This should all be supported I think.

I just downloaded the latest version this past week: Client 2.0.8, Server 2.0.7.0

I just ran some code from 2017 and while most ran, it didn't like template strings `text-${variable}` which means it definitely an over JavaScript engine. Once I converted that to ("text-" + variable), it functioned.

**Comment by hreinnbeck** [comment]
2.0.7 is more than 2 years old.  Go for a nightly build of master: http://casparcg.com/builds/CasparCG%20Server/master/

**Comment by AskMP** [comment]
Interesting. These were the links pulled from casparcg.com downloads page... I will check that link you sent. Clearly nightly would be best! Also, there may need to be a new tutorial for NDI updated as the NewTek download link for the AirSend is a loop to their own primary download page. Luckily the YouTube video of the process has a URL for a few frames which can be manually entered... I may add a feature request for that update to the instructions.

**Thanks for the help**! I wouldn't have considered that. Instincts have taught me to download the latest from the primary site. That does indeed look like it's solve it. It looks like it's running Chromium 63. Still a few versions behind but clearly more up-to-date than 33 which is what it was before.

**Comment by hreinnbeck** [comment]
Nightlies have native NDI support

**Comment by Julusian** [comment]
The website is rather outdated, you will find a 2.2.0 release here on github.
There is now native NDI support in the 2.3 builds which hreinnbeck linked to.

And yes, the version of CEF in use is a bit dated, but hopefully that will be updated again soon in 2.3 by #1217

**Comment by AskMP** [comment]
Thanks to you both! Great to know. It was a bit of a cludge installing that with NDI last week but it was all on NewTek's side. I appreciate both of you dropping in to school me on where to get it.
