### ISSUE TITLE
How to fix an inverted screen?

### ISSUE THREAD

**Issue by vfmradio** [CasparCG/server#1223]
Good day! How to fix an inverted screen?

### Environment
* Server version: v2.2
* Operating system: Windows 10

---

### Screenshots
![image](https://user-images.githubusercontent.com/23094104/60810412-bfb4b180-a195-11e9-92f3-630f9d1de077.png)

**Comment by Julusian** [comment]
Is it just those files which are inverted, or everything you play on the channel?
Perhaps try playing a HTML page to verify.
