### ISSUE TITLE
NDI Output seems to be always progressive

### ISSUE THREAD

**Issue by navelencia** [CasparCG/server#1224]
### Expected behaviour
When setting "1080i5000" in "casparcg.config", I expect to get the same exact resolution/framerate/interlace in Newtek's NDI Studio Monitor.

### Current behaviour
When setting "1080i5000" in "casparcg.config", NDI Studio Monitor sees the signal as "1080p50".

----

### Steps to reproduce
1. Configure casparcg.config
2. Select source in software monitor

### Environment
* Commit: d442a8f8
* Server version: 2.3
* Operating system: Windows 10 Pro 1903

---

### Additional notes
This seems to happen since CasparCG 2.1, but didn't happen with 2.0.7 for instance, where it works as expected.

**Comment by premultiply** [comment]
This MAY be intended as this is the internal RGB+A progressive rendering format.

**Comment by hreinnbeck** [comment]
Are you referring to iVGA?  I'm guessing that will not be supported anymore.

If you are referring to native NDI in the latest builds, do you have the <allow-fields> set to true in the config?

```
<ndi>
                <name>[custom name]</name>
                <allow-fields>false [true|false]</allow-fields>
</ndi>
```

**Comment by navelencia** [comment]
I was referring to iVGA and the new NDI consumer. As I understand the NDI consumer is very new, and I didn't understand at first what was "allow-fields" about. Now, with it set to "true" it works ok ! Thanks for the advice, and the issue can be closed 👍

**Comment by vimlesh1975** [comment]
At run time this can be achieved with following command
`add 1 ndi name ch1 allow_fields`

**Comment by ianshade** [comment]
Maybe it should have been named differently to be more clear? What about _allow-interlaced_ or just _interlaced_? The idea is that it allows sending interlaced video only when the channel is interlaced, and has no effect when channel is progressive.
