### ISSUE TITLE
MPEG4 Quicktime videos detected as audio CLS

### ISSUE THREAD

**Issue by grahamspr86** [CasparCG/server#1231]
Seem to be having an issue where with server 2.2/2.3 is detecting MPEG-4 Quicktime videos as AUDIO and not MOVIE, issue wasn't present on server 2.0

![](https://casparcgforum.org/uploads/default/original/1X/eb69aea8e0701416f4f631f40a967c0d296b9316.png)

```
"BSSUMMERCHAMPS19/HYPE VIDEO 1"  MOVIE  70519049 20190813210224 2784 1/50
"BSSUMMERCHAMPS19/HYPE VIDEO 2"  MOVIE  68767218 20190813210224 2690 1/50
"BSSUMMERCHAMPS19/HYPE VIDEO 3"  MOVIE  78562275 20190813210224 1540 1/25
"BSSUMMERCHAMPS19/HYPE VIDEO 4"  AUDIO  112057924 20190813210321 4204800 1/48000
"BSSUMMERCHAMPS19/HYPE VIDEO 5"  AUDIO  95357801 20190813210225 2757120 1/48000
```

**Comment by dotarmin** [comment]
[media-scanner: pr#41](https://github.com/CasparCG/media-scanner/pull/41)

**Comment by grahamspr86** [comment]
Forgot the scanner was likely to be the issue here!

**Comment by Julusian** [comment]
Closing as this is an issue with the scanner as linked above
