### ISSUE TITLE
CALL 1-1 LEGNTH is returning different values in 2.1.0 and 2.2.0 

### ISSUE THREAD

**Issue by devteam-frslabs** [CasparCG/server#1238]
### Expected behaviour
I have a 5 min video.
When I played in 2.1.0 the CALL 1-1 LEGNTH command returns 5000

### Current behaviour
But in 2.2.0 and above versions the CALL 1-1 LEGNTH command returns as 14932

----

### Steps to reproduce
1. PLAY 1-1 MEDIA_FILE
2. CALL 1-1 LEGNTH

### Environment
* Commit: 
* Server version: v.2.2.0
* Operating system: Windows 10

---

**Comment by Julusian** [comment]
Lengths are now reported in the framerate of the channel, not of the source file. 14932 works out to 5 minutes at 50p, so looks correct of you are setup for 50p or 50i.
That number from 2.1 looks strange. At 5 minutes, that suggests 16.67 frames a second which is weirdly low.

**Comment by devteam-frslabs** [comment]
Oh, thanks. Sorry it is not 5000, it returned 7194 frames in 2.1.0 of the source file.
