### ISSUE TITLE
Audio out of sync for 44100Hz in v2.2.0 and above with SEEK command

### ISSUE THREAD

**Issue by abmkrishnan** [CasparCG/server#1239]
### Current behaviour
When playing a video file (44100Hz) in v2.2.0 the audio is going out of sync only when I used the SEEK command otherwise it is playing normally.  But if I convert that video file to 48000Hz then it is playing normally in v2.2.0 even with the SEEK command. But in v2.1.0 it is playing normally without converting to 48000Hz. Is there any workaround to play the file without converting to 48000Hz?

----

### Steps to reproduce
1. PLAY 1-1 VIDEO_FILE SEEK 1000 LENGTH 5000

### Environment
* Server version: v.2.2.0 and above
* Operating system: Windows 10

---

**Comment by premultiply** [comment]
Convert it to 48k if it differs to this standard sampling rate.
Its the same as with framerate missmatches.

**Comment by abmkrishnan** [comment]
What is the recommended framerate?

**Comment by premultiply** [comment]
Depends on your channel framerate.

**Comment by Julusian** [comment]
The fix was reverted (4176a9b1bcd03dd22061f30110b1664d8216c881), so this needs revisiting

**Comment by Julusian** [comment]
Fixed again in https://github.com/CasparCG/server/commit/99644d478673da7ebd716ad1d3aad8c8d1ec9bbc
