### ISSUE TITLE
H264 recorder settings are ignored with v 2.3

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#1242]
### Expected behaviour
When I try this with v2.3 settings are ignored and I get a 422 mp4 clip with 8 audio channels
channel setting is set hd1080i50

ADD 1 FILE "myfile 1.mp4" -codec:v libx264 -crf:v 23 -preset:v veryfast -filter:v format=pix_fmts=yuv420p -filter:v tinterlace=5 -codec:a aac -b:a 128k -ar:a 48k

If I do this
ADD 1 FILE "myfile 1.mp4" -codec:v libx264 -crf:v 23 -preset:v veryfast -filter:v format=pix_fmts=yuv420p -filter:v tinterlace=5 -codec:a aac -b:a 128k -ar:a 48k  -filter:a pan=stereo| FL < FL + 0*FC + 0*BL + 0*SL | FR < FR + 0*FC + 0*BR + 0*SR

I get a mp4 clip with stereo audio.

### Current behaviour
Video settings are ignored, but audio seems to work.
----

### Steps to reproduce
try to record a mp4 file with yuv 420 and upper field setting

### Environment
win10
server 2.3 sept 2019 build

---
![afbeelding](https://user-images.githubusercontent.com/4194609/68412866-5bc6e780-018d-11ea-8942-cb3bfc3570c6.png)

**Comment by hreinnbeck** [comment]
You can't use multiple filter arguments with ffmpeg.  Try it with "-filter:v format=pix_fmts=yuv420p,tinterlace=5"

**Comment by vimlesh1975** [comment]
I think scan type=mbaff is equivalent to interlaced scanning. 
`ADD 1 FILE "myfile10.mp4" -codec:v libx264 -crf:v 23 -preset:v veryfast "-filter:v format=pix_fmts=yuv420p" -flags:v +ildct+ilme -codec:a aac -b:a 128k -ar:a 48k`

**Comment by TKooijmans** [comment]
THANKS YUV420 works now and it seems I got a interlaced file, but media info still reports progressive..
I use
ADD 1 FILE "myfile 1.mp4" -codec:v libx264 -crf:v 23 -preset:v veryfast -filter:v format=pix_fmts=yuv420p,tinterlace=4 -codec:a aac -b:a 128k -ar:a 48k

![afbeelding](https://user-images.githubusercontent.com/4194609/68473268-cd04aa00-0222-11ea-93b6-34ad7d69b656.png)

**Comment by TKooijmans** [comment]
Thanks vimlesh! That works!
So to record a mp4 file with yuv 420 color and 2 channels audio we have to use this command
ADD 1 FILE "myfile 1.mp4" -codec:v libx264 -crf:v 23 -preset:v veryfast -filter:v format=pix_fmts=yuv420p,tinterlace=4 -flags:v +ildct+ilme -codec:a aac -b:a 128k -ar:a 48k -filter:a pan=stereo| FL < FL + 0*FC + 0*BL + 0*SL | FR < FR + 0*FC + 0*BR + 0*SR

the last part is to set only 2 audio channels for recording.

Much higher CPU load with CG2.3
CPU load with recording of a mp4 file seems to be a lot more higher with build 2.3 then with 2.1
Below a screen shot while recording a HD1080i50 channel with this command in CG2.1
ADD 1 FILE TestH264.mp4 -pix_fmt yuv420p -vcodec libx264 -preset ultrafast -tune film -crf 20 -x264opts tff=1

![afbeelding](https://user-images.githubusercontent.com/4194609/68593068-e2810a80-0494-11ea-9aa2-5f6e805db819.png)

This is with CG2.3 with recorder command
ADD 1 FILE "myfile 1.mp4" -codec:v libx264 -crf:v 23 -preset:v ultrafast -filter:v format=pix_fmts=yuv420p,tinterlace=4 -flags:v +ildct+ilme -codec:a aac -b:a 128k -ar:a 48k -filter:a pan=stereo| FL < FL + 0*FC + 0*BL + 0*SL | FR < FR + 0*FC + 0*BR + 0*SR

![afbeelding](https://user-images.githubusercontent.com/4194609/68593686-4ce67a80-0496-11ea-931b-703e0666c1e4.png)

**Comment by Julusian** [comment]
This sounds like it was resolved, and so just needs the documentation updated to help others in future?

**Comment by TKooijmans** [comment]
Not ok sofar, the mp4 file is not accepted by Adobe Premiere

**Comment by Julusian** [comment]
> Not ok sofar, the mp4 file is not accepted by Adobe Premiere

covered by #1331
