### ISSUE TITLE
RTMP Playback issue

### ISSUE THREAD

**Issue by Sevenlive** [CasparCG/server#1245]
### Expected behaviour

The Server should playout the Livestream which OBS sends to arut/nginx-rtmp-module.

The RTMP Stream should show up on the Output.

OBS -> nginx-rtmp -> CasparCG

Command:
PLAY 1-1 rtmp://127.0.0.1/1/test

### Current behaviour

The Output won't show up neither on the casparcg screen consumer or other output. 

CasparCG seems to read the Metadata and doesnt give any other errors.

VLC (and other ffmpeg-powered media-player) works flawless. 

Another Livestream (rtmp://fms.105.net/live/rmc1) works on CasparCG as well.

Assumption:

Using VLCs Codec information window i saw that obs sends the videostream as stream1 (audiostream is stream0) while the other Livestream is handing it as stream0 and the audiostream as stream1.

On the codec-side both streams use H264.

----

### Steps to reproduce
1. Install arut/nginx-rtmp-module
2. Send a Livestream to it using OBS
3. See the Metadata showing up in the console but no stream on the output

### Environment
* Commit: First seen -> d442a8f, Latest tested: 7829b13
* Server version: 2.3.0 N/A DEV
* Operating system: Ubuntu 18.04

**Comment by Julusian** [comment]
Can you retest this on latest master (https://github.com/CasparCG/server/commit/715449df5d3d670233624842049ca2b50cbb3441) as that was a rtmp fix so may have resolved this

**Comment by Julusian** [comment]
I have tested it, and this flow does appear to be fixed by the referenced commit.
