### ISSUE TITLE
CasparCG Goes Slow Mo

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#1249]
### Expected behaviour
caparcg should play smoothly provided there is more cpu and memory available
### Current behaviour
with 6 channels ( video playing on each channel) , casparcg play video is slow with total cpu comsumption at 8% and memory consumption of 500MB.  total system memory is 8GB

----

### Steps to reproduce
1. add 6 channel to config file
2. play videos on each of the 6 channel
3. add a screen consumer or NDI consumer to one of the channel to monitor

### Environment
* Commit: latest build
* Server version: 2.3
* Operating system: Windows 10

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by Julusian** [comment]
What is gpu usage like? I suspect that this could be either gpu maxing out, or bandwidth to/from the gpu maxed out on frame transfers (not 100% sure how to get numbers to check this).

**Comment by PeterAkakpo** [comment]
nvidia 1050 TI

**Comment by PeterAkakpo** [comment]
it also happens when you more then 5 videos on a single channel

**Comment by PeterAkakpo** [comment]
i have tried same on server 2.3.2 lts beta, same result (video going slow after playing the fourth file (2GB in size) ) with sound jerking/cracking (memory 650MB, cpu 15% , gpu 45% , resolution 1080i5000) **4 Files**


**OBS STUDIO**
 i also tried with obs studio and i was able to add 10 instances of the same file  into a scene with no issue, they all played smoothly . 

(memory 700MB , cpu  23%, GPU 40% , resolution 920x1080 60fps) **10 Files**



https://user-images.githubusercontent.com/7926382/106561577-dd3c2f80-6520-11eb-8e86-e4f73f990fc7.mp4

**Comment by PeterAkakpo** [comment]
i have tried 2.3.2 lts beta and i can say its a great improvement. i was able to play 9 instances a video files (2GB in size) with no issue, video was smooth and sound was ok too. upon playing the tenth file , sound is  jerking/cracking on decklink output and out of sink on system audio.  this is even with NVidia GT710 card. great work

**Comment by PeterAkakpo** [comment]
memory ,cpu and gpu have been stable for an hour now with only some -+5 up and down

**Comment by PeterAkakpo** [comment]
another observation, all the 9 videos play 90% smoothly only when i scale the layers as attached above. but when i play all the 9 video files without scaling (thus playing all layers full screen) then the videos start going slow

**Comment by Julusian** [comment]
this definitely sounds like a performance bottleneck of your machine.
there are other issues open about improving performance
