### ISSUE TITLE
Youtube video autoplay=true not working

### ISSUE THREAD

**Issue by vimlesh1975** [CasparCG/server#1256]
### Expected behaviour
Build dated 11 JUN 2019 playes a youtube video in autoplay=true
`play 1-1 [html] https://www.youtube.com/embed/plxV00PcX28?autoplay=true`
### Current behaviour
video loads but doesn't play on load. i.e. autoplay=true is not working
### Environment
Server dated 03 MARCH 2020
Windows 10

**Comment by Julusian** [comment]
Caused by the recentish cef upgrade (see https://github.com/obsproject/obs-browser/issues/105)

A fix is pushed
