### ISSUE TITLE
List Consumers over AMCP or OSC

### ISSUE THREAD

**Issue by Sevenlive** [CasparCG/server#1259]
### Description
Hi,

My idea is to make a Command either via AMCP or OSC that list all CasparCG Consumers. 

So you can see all Consumers. This would be useful for Adding/Removing or just to make sure, that a certain Consumer is still running.

### Solution suggestion
AMCP: LIST CONSUMERS

OSC: /channel/1/consumer

---

**Comment by sirfnomi** [comment]
it would be great for synchronize multiple clients with sever state with just 1 single amcp command

**Comment by Julusian** [comment]
This already exists in the code, but no consumer is providing any data to populate this with.
It should be in OSC under `/channel/1/output/port/__/____`, and the corresponding path in the `INFO 1` response.

**Comment by sirfnomi** [comment]
Is it quick work or it will take some time ?

**Comment by Julusian** [comment]
Some were being listed, some weren't. This is now enforced a bit better, and all consumers will have something there, even if its just
```
<port_500>
    <consumer>system-audio</consumer>
</port_500>
```
