### ISSUE TITLE
ffmpeg audio using AVFrame decode and swresampler

### ISSUE THREAD

**Issue by cambell-prince** [CasparCG/server#126]
Some notes for the forum following on from our irc chat the other day...

I've found the audio decode to be really slow in my debug build configuration, much less so in the release build. I wasn't able to dig enough to determine exactly why this would be, but seeing as I'm using a newer ffmpeg library I switched out the audio implementation to use the new AVFrame decode api, and also the swresampler audio resampler.

I found that the new decode api and the swresampler was much much faster (in debug build) when compared with the 2.0.3 in debug build.

Since our conversation the other day on IRC I've:
- Tested in debug swresampler vs 2.0.3. swresampler (with newer AVFrame audio decode also) is faster. This is dramatic on my machine. 2 year old i5, 8G RAM, strictly ordinary HDD.
- Tested in above in release. Again, faster but less noticable than the above. Still this made a difference. I can now use ffmpeg to bring in 4 - 5 SD h264 videos, + USB camera, Flash and record h264 to disk with no dropped frames. Previously I could not record to disk at all on this hardware (in debug build config).
- I tested the multi channel audio sample. I'm not using the multi-channel audio mod in 2.0.4 and I lack the hardware to try that anyway. But, the input was correctly resampled to use left, centre, right, and added the surround channels into the left and right appropriately.

I haven't done this mod particularly seriously, it would require the [newer ffmpeg](https://github.com/CasparCG/Server/pull/105) to include this. Let me know if this is something you're interested in and I'll fixup the patch.

**Comment by ronag** [comment]
2.2
