### ISSUE TITLE
Layers display out of order

### ISSUE THREAD

**Issue by euphoricz** [CasparCG/server#1263]
### Expected behaviour
Per CCG 2.0.7, loading a remote stream via url blocks subsequent AMCP commands until loading of the stream completes (enough data is buffered to begin displaying frames).

### Current behaviour
CCG 2.3 does not block, it seems a change was made that allows the AMCP queue to continue even though the remote stream has not entirely loaded.  This allows layersto display out of order (along with their transitions).

During testing it was also found that AMCP LOADBG OK response in 2.0.7 would not be returned until the remote stream loaded.  However in 2.3 the response is returned within 1 ms clearly not impacted by the load.

I understand this change was probably made to reduce the possibility for command queue overflows, or various other reasons.  I am curious though, is there another way to synchronize the display of layers?

### Steps to reproduce
1.  Add a png image named test.png to your CasparCG media folder, doesn't really matter what it is, just some image that is easy to see in the output.
2.  Start CasparCG
3.  Paste the following with extra carriage returns into the console so the commands execute immediately in order

```
PLAY 1-2 https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_1MB.mp4 MIX 30 easinsine
MIXER 1-2 FILL .5 .5 .5 .5
PLAY 1-1 test MIX 30 easinsine

```

4.  Compare results between CasparCG 2.0.7 and 2.3

### Environment
* Commit: 7829b13b
* Server version: 2.3
* Operating system: Windows 10 / Ubuntu 18.04

**Comment by Julusian** [comment]
If you do it with loadbg instead of a direct play it will be better
```
LOADBG 1-2 https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_1MB.mp4 MIX 30 easinsine
(wait a few seconds)
PLAY 1-2
MIXER 1-2 FILL .5 .5 .5 .5
LOADBG 1-1 test MIX 30 easinsine
(wait a few seconds)
PLAY 1-1
```

**Comment by premultiply** [comment]
@ronag changed this behaviour I think.
The AMCP response is now only a confirmation for receiving and understanding (correct syntax) the command properly. It does not wait for execution. So this is asynchronous now.

**Comment by euphoricz** [comment]
Thanks for such a prompt response, I really appreciate it.

@Julusian I understand that waiting a few seconds after LOADBG does work around the issue, and normally when our software uses a rundown you would never even know there was a problem because we require a minimum of 4 seconds for a particular screen (object containing content layers) to be on air before switching... however when a user just wants to take a screen to air immediately, or maybe manually clicking to play multiple screens quickly, this is when the problem is most seen, and an artificial delay can't always determine exactly how long it will take the stream to load (depending on network latency, bandwidth, etc).

We are working on using OSC to determine when the background producer finishes loading the stream to the point in which it can be properly displayed in the foreground, I can then use this information with a waithandle to play the layers of the screen all at once... still more work to be done though, currently reviewing live OSC output.

@premultiply thank you for the info, I had a feeling it was probably intended and it does make sense.  I guess I'll have to move forward with the OSC work around for now.

If either of you can think of another built in way to make this work I'd love to hear it, otherwise thanks a ton for the info!

**Comment by euphoricz** [comment]
OSC doesn't seem to be helpful as far as determining when the stream is loaded with LOADBG in the background.  In the foreground I can see when it begins to play in OSC.  I could possibly place the stream on a high layer with a mixer fill to move it out of the viewable area, monitor OSC foreground for when it begins to play, then swap the layer and play the rest of the content associated with the screen...
