### ISSUE TITLE
Extra forward slash in info paths

### ISSUE THREAD

**Issue by vimlesh1975** [CasparCG/server#1264]
### Expected behaviour
If following is the media path confuguration in config file-
` <media-path>c:/casparcg/_media\</media-path>`
upon command of info paths, it shoulds return
` <media-path>c:/casparcg/_media\</media-path>`

### Current behaviour
But it returns
` <media-path>c:/casparcg/_media\/</media-path>`
Notice both back slash and forward slash at last.

BUt when all slashes are forward in config file; the info paths returns ok.
### Environment
Casparcg Server 2.3 dated 16.03.2020
Windows 10 64 bit

### Screenshots

![not_ok](https://user-images.githubusercontent.com/4338487/77251119-844e0a80-6c72-11ea-8157-57d03e085648.png)

**Comment by hreinnbeck** [comment]
It's escaping the forward slash, use a backslash at the end of the path.

**Comment by vimlesh1975** [comment]
Using the back slash at the end gives this problem. This is what I am saying.
Using forward slash at the end works ok.

**Comment by hreinnbeck** [comment]
All your slashes should be backslashes.

**Comment by vimlesh1975** [comment]
If I put all back slashes there is same problem. Extra forward slash in info paths.
![not_ok2](https://user-images.githubusercontent.com/4338487/77252743-f6771d00-6c7b-11ea-81f9-8964b1a56f84.png)

**Comment by Julusian** [comment]
This does look like it could be a bug as that output looks inconsistent, and escaping a forward slash is a bit weird. 
I'll try and take 5 minutes tomorrow to at least understand why it is getting that result.

**Comment by Julusian** [comment]
This was a bug. Introduced in https://github.com/CasparCG/server/commit/0f98c1f95bc5fb8456d7c1b7d88fd9b2063d6a92
Fixed in https://github.com/CasparCG/server/commit/8bb2e21c378aeca940da0cbb4ff7a9c30402be9e
