### ISSUE TITLE
support 10bit for HDR

### ISSUE THREAD

**Issue by shenyanjie0807** [CasparCG/server#1266]
More TV stations join UHD&HDR broadcasting,Caspar needs to go further, supporting 10bit or higher color will be more widely used. 10bit is just the starting point for HDR.

**Comment by premultiply** [comment]
https://github.com/CasparCG/server/pull/1253#issuecomment-596365957

**Comment by Julusian** [comment]
Duplicate of https://github.com/CasparCG/server/issues/325
