### ISSUE TITLE
  Doesn't record in NTSC without specifying size

### ISSUE THREAD

**Issue by vimlesh1975** [CasparCG/server#127]
I observed casparcg doesn't record in video mode NTSC without specifying size.
For example following command doesn't work.
[code]ADD 1 FILE "test.mp4" -b 1000000[/code]

 Log says 
[code][05/19/13 14:24:31] [052E0DB0] [error]   [ffmpeg] [libx264 @ 02FB0AA0] height not divisible by 4 (720x486)[/code]
While following command works
[code]add 1 file test.mp4 -b 1000000 -s 888x444[/code]

http://casparcg.com/forum/viewtopic.php?f=3&t=1481

**Comment by ronag** [comment]
2.2
