### ISSUE TITLE
WRONG INFO STATUS

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#1270]
### Expected behaviour
INFO PATH should show the actual status of channel.

### Current behaviour
Showing PLAYING when there is nothing playing on the channel

----

### Steps to reproduce
1. Type INFO PATH
2.
3. ...

### Environment
* Commit: latest build
* Server version: 2.3
* Operating system: Windows 10

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by krinteron** [comment]
Same problem

![image](https://user-images.githubusercontent.com/24290554/197211471-7a059fb6-14ea-4765-a0f0-0a6d02251366.png)

**Comment by Julusian** [comment]
Some of the `INFO` commands have been reimplemented
