### ISSUE TITLE
FFmpeg seek/length broken in some ways

### ISSUE THREAD

**Issue by dotarmin** [CasparCG/server#1272]
There is some confusing behaviour around seek/in/out/length in the ffmpeg producer. Some cases of what I have found are below:

doing a 
PLAY 1-10 file1 SEEK 500
LOADBG 1-10 file2 AUTO
never starts file2. It gets stuck waiting for the last 500 frames to play.
but doing the same with an explicit duration is fine.

case 2,
PLAY 1-10 file1 SEEK 200 DURATION 8000
diag starts at 4.0/160.0 (aka 200/8000)
diag ends at 164.0/160.0
osc reports:
* file/time: <absolute position in file>, <file length>
* file/clip: 4, 160
amcp:
* CALL 1-10 length => 8000
* CALL 1-10 in => 200
* CALL 1-10 out => 8200

case 3,
PLAY 1-10 file1 SEEK 200
diag starts at 4.0/194.5 (aka 200/9725) (194.5 is length of clip)
amcp:
* CALL 1-10 length => 9723
* CALL 1-10 in => 200
* CALL 1-10 out => 9923 (beyond the end of the file)

dev note:
It looks like the av_producer is getting confused over the purpose of duration_ at times, so that sometimes it is duration_ (when explicitly set) and other times it is the file duration, not factoring in seek. And then some stuff is misusing start.

**Comment by Julusian** [comment]
This should all be resolved by https://github.com/CasparCG/server/commit/a1367bf137615576bd8e2d2a05ff3525bd87ed6a
