### ISSUE TITLE
INCREASED MEMORY USAGE

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#1279]
### Expected behaviour
Continuous playing of files should not have significant increase in memory (over 2GB) and cpu (over 50%)  used by previous PLAY must be released. 

### Current behaviour
There is a significant increase in memory with continuously issuing a play command.
----

### Steps to reproduce

CHANNEL 1

1. **PLAY 1-0 FILE1 mix 20 easeinsine**  (long running file about 1 hour)
2. **PLAY 1-1 POPUP**  (about 15 seconds file replayed in 5 minutes interval. STOP is issued after it ends)

CHANNEL 2

1. **PLAY 2-0 FILE2 mix 20 easeinsine**  (long running file about 1 hour)
2. **PLAY 2-1 POPUP**  (about 15 seconds file replayed in 5 minutes interval. STOP is issued after it ends )

CHANNEL 3

1. **PLAY 3-0 FILE3 mix 20 easeinsine**  (long running file about 1 hour)
2. **PLAY 3-1 POPUP**  (about 15 seconds file replayed in 5 minutes interval. STOP is issued after it ends)

repeat step 2 for each channel continuously with different files in about 3-5 minutes intervals and monitor the memory and CPU usage in about 30 minutes . Issue a STOP on layer 1 of each channel after every iteration

am using only the screen consumer for each channel

OBSERVATION

i think the STOP command on layer 1 is not releasing the memory used, because memory usage is normal about (500MB) when only the layer 0 of each channel is playing. as soon as layer 1 starts playing, memory starts increasing to over 2GB and never released after STOP.

Issuing **GL GC** has no significant effect

### Environment
* Commit: latest build
* Server version: 2.3
* Operating system: Windows 10

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by dotarmin** [comment]
Thanks for reporting.

Probably related to #1277. It seems like we have issues with producers not being cleaned after they have been removed, another example is #1265.

**Comment by Julusian** [comment]
I have pushed a fix for some of #1277, which might improve this. Could you retest to check?

**Comment by ronag** [comment]
This has been stale for a while so we assume it has been resolved.
