### ISSUE TITLE
Does not compile in docker on OSX

### ISSUE THREAD

**Issue by Behinder** [CasparCG/server#1280]
### Expected behaviour
Compile same way as in linux

### Current behaviour
During compilation got bunch of errors.

 45%] Building CXX object modules/html/CMakeFiles/html.dir/producer/html_cg_proxy.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
modules/ffmpeg/CMakeFiles/ffmpeg.dir/build.make:66: recipe for target 'modules/ffmpeg/ffmpeg_pch/StdAfx.h.gch/.c++' failed
make[2]: *** [modules/ffmpeg/ffmpeg_pch/StdAfx.h.gch/.c++] Error 4
make[2]: *** Deleting file 'modules/ffmpeg/ffmpeg_pch/StdAfx.h.gch/.c++'
CMakeFiles/Makefile2:344: recipe for target 'modules/ffmpeg/CMakeFiles/ffmpeg.dir/all' failed
make[1]: *** [modules/ffmpeg/CMakeFiles/ffmpeg.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 46%] Building CXX object modules/image/CMakeFiles/image.dir/util/image_algorithms.cpp.o
[ 46%] Building CXX object modules/image/CMakeFiles/image.dir/util/image_loader.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [modules/oal/CMakeFiles/oal.dir/consumer/oal_consumer.cpp.o] Error 4
modules/oal/CMakeFiles/oal.dir/build.make:62: recipe for target 'modules/oal/CMakeFiles/oal.dir/consumer/oal_consumer.cpp.o' failed
make[2]: *** Waiting for unfinished jobs....
[ 47%] Building CXX object modules/html/CMakeFiles/html.dir/producer/html_producer.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
modules/image/CMakeFiles/image.dir/build.make:86: recipe for target 'modules/image/CMakeFiles/image.dir/producer/image_producer.cpp.o' failed
make[2]: *** [modules/image/CMakeFiles/image.dir/producer/image_producer.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
[ 48%] Building CXX object modules/html/CMakeFiles/html.dir/html.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [modules/image/CMakeFiles/image.dir/consumer/image_consumer.cpp.o] Error 4
modules/image/CMakeFiles/image.dir/build.make:62: recipe for target 'modules/image/CMakeFiles/image.dir/consumer/image_consumer.cpp.o' failed
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [modules/oal/CMakeFiles/oal.dir/oal.cpp.o] Error 4
modules/oal/CMakeFiles/oal.dir/build.make:86: recipe for target 'modules/oal/CMakeFiles/oal.dir/oal.cpp.o' failed
CMakeFiles/Makefile2:400: recipe for target 'modules/oal/CMakeFiles/oal.dir/all' failed
make[1]: *** [modules/oal/CMakeFiles/oal.dir/all] Error 2
make[1]: *** [modules/image/CMakeFiles/image.dir/all] Error 2
CMakeFiles/Makefile2:685: recipe for target 'modules/image/CMakeFiles/image.dir/all' failed
Scanning dependencies of target accelerator
[ 48%] Building CXX object accelerator/CMakeFiles/accelerator.dir/ogl/image/image_kernel.cpp.o
[ 49%] Building CXX object accelerator/CMakeFiles/accelerator.dir/ogl/image/image_shader.cpp.o
[ 50%] Building CXX object accelerator/CMakeFiles/accelerator.dir/ogl/image/image_mixer.cpp.o
[ 51%] Building CXX object accelerator/CMakeFiles/accelerator.dir/ogl/util/device.cpp.o
[ 52%] Building CXX object accelerator/CMakeFiles/accelerator.dir/ogl/util/buffer.cpp.o
Scanning dependencies of target protocol
[ 53%] Building CXX object protocol/CMakeFiles/protocol.dir/amcp/AMCPCommandQueue.cpp.o
[ 54%] Building CXX object protocol/CMakeFiles/protocol.dir/amcp/AMCPCommandsImpl.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [modules/html/CMakeFiles/html.dir/producer/html_producer.cpp.o] Error 4
modules/html/CMakeFiles/html.dir/build.make:86: recipe for target 'modules/html/CMakeFiles/html.dir/producer/html_producer.cpp.o' failed
make[2]: *** Waiting for unfinished jobs....
[ 54%] Building CXX object accelerator/CMakeFiles/accelerator.dir/ogl/util/shader.cpp.o
[ 55%] Building CXX object accelerator/CMakeFiles/accelerator.dir/ogl/util/texture.cpp.o
CMakeFiles/Makefile2:629: recipe for target 'modules/html/CMakeFiles/html.dir/all' failed
make[1]: *** [modules/html/CMakeFiles/html.dir/all] Error 2
[ 56%] Building CXX object accelerator/CMakeFiles/accelerator.dir/accelerator.cpp.o
[ 57%] Building CXX object accelerator/CMakeFiles/accelerator.dir/StdAfx.cpp.o
[ 58%] Building CXX object protocol/CMakeFiles/protocol.dir/amcp/AMCPProtocolStrategy.cpp.o
[ 58%] Building CXX object protocol/CMakeFiles/protocol.dir/amcp/amcp_command_repository.cpp.o
[ 59%] Building CXX object protocol/CMakeFiles/protocol.dir/cii/CIICommandsImpl.cpp.o

----

### Steps to reproduce
according to instructions

### Environment
MacOS Mojave latest
---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by dimitry-ishenko** [comment]
> c++: internal compiler error: Killed (program cc1plus)

Shooting in the dark here, but you might be running out of memory...

**Comment by dotarmin** [comment]
Hi @Behinder,

I have to close this issue because we do not support macOS.
Hopefully the comment from @dimitry-ishenko is a hint or if you ask at the CasparCG Forum? 😄
