### ISSUE TITLE
Screen consumer command line Width and height not working

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#1284]
### Expected behaviour
Command line width and height should be taken into account
### Current behaviour
The width and height parameters are ignored

----

### Steps to reproduce
1. ADD 1 SCREEN 0 width 100 height 100

window opens with default width and height

### Environment
* Commit: latest build
* Server version: 2.3
* Operating system: Windows 10

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by Julusian** [comment]
https://github.com/CasparCG/server/blob/master/src/modules/screen/consumer/screen_consumer.cpp#L598
There is no attempt to try and parse the desired width and height from amcp.

It will be an easy 2 line fix if someone wants to attempt a PR

**Comment by Julusian** [comment]
this is implemented now
