### ISSUE TITLE
Huge memory leaks when trying to play unknown ndi source

### ISSUE THREAD

**Issue by STL1811** [CasparCG/server#1287]
Hello,
If I try to play NDI source that doesn't exist, CasparCG Memory is growing very fast.
I can see the same behavior if computer exists and source doesn't exist than if computer doesn't exist.

### to reporduce it :
` play 1-1 [ndi] "PC-10 (test)"`
where PC-10 doesn't exist, 
And after 15mn, CasparCG memory is about 5Go : 
![image](https://user-images.githubusercontent.com/7868276/80135465-8f14fb80-85a0-11ea-9102-ae81edbfd60e.png)
After `Stop 1-1` or `clear 1-1,` memory stops growing but doesn't go down.

### Environment
* Commit: 2.3.0 b728d299 Dev
* Server version: V2.3
* Operating system: Windows 10 Pro 1909
* GPU : NVIDIA GeForce GTX 1050
---

**Comment by walterav1984** [comment]
NDI lib version, casparcg.config default 720p50 template?

**Comment by Julusian** [comment]
From a quick skim of the code I would suspect that if this https://github.com/CasparCG/server/blob/master/src/modules/newtek/producer/newtek_ndi_producer.cpp#L160 is false, then we still need to free the video_frame.
The documentation doesnt make it clear if the frame needs freeing or not, but I suspect it would

**Comment by ducthiem90** [comment]
> From a quick skim of the code I would suspect that if this https://github.com/CasparCG/server/blob/master/src/modules/newtek/producer/newtek_ndi_producer.cpp#L160 is false, then we still need to free the video_frame.
> The documentation doesnt make it clear if the frame needs freeing or not, but I suspect it would

don't need free video frame, but need free audio frame. Code missed free audio frame

**Comment by STL1811** [comment]
> 
> 
> NDI lib version, casparcg.config default 720p50 template?

I have the same issue with NDI 3.8 and NDI 4.5 and in different configs (720p6000, 1080i5000)




In [https://github.com/CasparCG/server/blob/master/src/modules/newtek/producer/newtek_ndi_producer.cpp#L160 ](url), I've tried :
`if (video_frame.p_data != nullptr) {
...
}else {
                ndi_lib_->NDIlib_framesync_free_video(ndi_framesync_, &video_frame);
                ndi_lib_->NDIlib_framesync_free_audio(ndi_framesync_, &audio_frame);
            }`

before your comment (@ducthiem90). And it seems to works well.

Thank you all.

**Comment by ducthiem90** [comment]
> > NDI lib version, casparcg.config default 720p50 template?
> 
> I have the same issue with NDI 3.8 and NDI 4.5 and in different configs (720p6000, 1080i5000)
> 
> In [https://github.com/CasparCG/server/blob/master/src/modules/newtek/producer/newtek_ndi_producer.cpp#L160 ](url), I've tried :
> `if (video_frame.p_data != nullptr) { ... }else { ndi_lib_->NDIlib_framesync_free_video(ndi_framesync_, &video_frame); ndi_lib_->NDIlib_framesync_free_audio(ndi_framesync_, &audio_frame); }`
> 
> before your comment (@ducthiem90). And it seems to works well.
> 
> Thank you all.

better:

....
CASPAR_SCOPE_EXIT
            {
                if (video_frame.p_data != nullptr)
                    ndi_lib_->NDIlib_framesync_free_video(ndi_framesync_, &video_frame);
                if (audio_frame.p_data != nullptr)
                    ndi_lib_->NDIlib_framesync_free_audio(ndi_framesync_, &audio_frame);
            };

            if (video_frame.p_data != nullptr){
....

**Comment by Julusian** [comment]
This should be fixed now
