### ISSUE TITLE
Crop broken for HTML

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/server#1292]
### Expected behavior
Crop should behave as <=2.2 regarding loaded HTML

### Current behavior
When using crop on HTML assets a horizontal crop works, a vertical crop "stretches".
In `2.2.0 66a9e3e2 Stable` the behavior is as expected, it crops in both directions.

**IMPORTANT INFO!**
_On a regular asset image or video, it behaves as expected._
----

### Steps to reproduce

`PLAY 1-10 [HTML] "https://svt.se"`
`MIXER 1-10 CROP 0.238542 0.156481 0.58125 0.82037 0`

Additional info:
Another command to test is this.
`MIXER 1-10 PERSPECTIVE 0.0541667 0.378704 1 0 1 1 0 1 0`
Should I break this out to a separate issue, suspect they have the same origin.

For testing without jumping between Caspar versions just swap the asset/layer between a video and HTML asset to see the issue.

### Environment
2.3.0 e236466b Dev
Windows 10

---

### Screenshots
First image from `2.2.0 66a9e3e2 Stable`
![cropbug_01](https://user-images.githubusercontent.com/20354852/80679520-4d62e400-8abd-11ea-8970-763ad7cf394e.png)
Second image from `2.3.0 e236466b Dev`
![cropbug_02](https://user-images.githubusercontent.com/20354852/80679526-505dd480-8abd-11ea-9c67-a6e8554b99bc.png)

**Comment by 5opr4ni** [comment]
The issue seems to occur for more commands, testing Distort at the moment and the issue manifests itself in very much the same way.

**Comment by 5opr4ni** [comment]
Clip works as expected.

**Comment by 5opr4ni** [comment]
Finding more problems here. Crop and Distort should work together which they do on a normal asset like a video, but don't work together with an HTML asset.

**Comment by Julusian** [comment]
Does this happen only if `html.gpu-enabled` is set to true, or is it the same when false?

**Comment by Julusian** [comment]
This was because cef in gpu-enabled mode gives us the frame vertically flipped. and the method of flipping it back was not playing well with manually set mixer properties

14f52882fc8b325c103222f763d647ed12c198e4

**Comment by dotarmin** [comment]
Great work Julian, thanks for the fixing it so quick. 

@5opr4ni, have you time for testing this today in latest build?

**Comment by 5opr4ni** [comment]
works, nice job.
