### ISSUE TITLE
AMCP Command Queue Overflow

### ISSUE THREAD

**Issue by lukasmican** [CasparCG/server#1293]
### Current behaviour
I am sending 25 AMCP PLAY commands per second but after 20 seconds CasparCG server begins to output AMCP Command Queue Overflow error into log. 

### Expected behaviour
I need the CasparCG server to process the commands faster. In the best case I would like to send 100 AMCP commands per second including PLAY and LOADBG. Is this possible?

----

### Steps to reproduce
1. start CasparCG server
2. countinuously send 25 PLAY commands per second
3. wait for 20 seconds

### Environment
* Server version: CasparCG Video and Graphics Playout Server 2.3.0 N/A Dev
* Operating system: Ubuntu 18.04
* CPU: AMD Ryzen 7 3700X
* GPU: NVIDIA GTX 1060
* RAM: 32GB

---

**Comment by hreinnbeck** [comment]
To better understand this or point out a better solution, could you explain why you need to send so many PLAY or LOADBG commands?

**Comment by lukasmican** [comment]
I am trying to display many different images quickly after each other. Basically I am simulating a video stream with BMP images as a source. I need to have full control of the timing of each image, so I would load and play the image when needed and CasparCG would make a nice and stable output video. Currently I am loading the images in background on separate layers as a "buffer" and then play at the right time-

**Comment by hreinnbeck** [comment]
You would probably be better off modifying the FFmpeg producer or creating a new producer for this.

I'd also point you to other options like ffdynamic or ffmpeg using zeromq for control.

**Comment by Julusian** [comment]
I think casparcg simply cannot handle this well enough.
From the code, that error starts to happen once there are over 128 commands in the queue to be executed, which I would guess to be from loading each image to be taking too long, as they will be loaded sequentially.

I agree that doing something with the ffmpeg producer would be a better way to go on this, but if you really have to stick with this, try doing some of the loading in some other channels. Each channel has its own command queue and threads, so it may be a bit happier or perhaps not.

**Comment by demian-buijs** [comment]
You probably are better off doing an image sequence in HTML/CSS/JS and use the HTML producer for this.

**Comment by lukasmican** [comment]
How does the process of getting a command and then loading data work? Is it all in a single thread? Can I use media in different channel than where it was loaded without loading again?

**Comment by Julusian** [comment]
When loading images, that is done single threaded in the command handling thread for that channel. This includes any conversion that needs to be done to the image, so isn't optimal.

We have discussed this and don't feel that this is something worth optimising right now, as this is an unusual use case. 

I suggest you try using some additional channels to distribute the loading across more threads, and you can then use the swap command to move those into the target channel and layer when they want to be shown.
