### ISSUE TITLE
SET 1 MODE is out of order

### ISSUE THREAD

**Issue by malmgrenola** [CasparCG/server#1303]
### Expected behavior
It should be possible to change video mode by using `SET 1 MODE 1080i5000` in the console.

### Current behavior
While a channel is in 720p5000 and command `SET 1 MODE 1080i5000` is sent in the console DIAG won't reflect the change on the channel.

----

### Steps to reproduce
1. Start CasparCG Server :-)
2. Open `DIAG` & confirm channel is in 720p5000
3.  Send `SET 1 MODE 1080i5000` in the console

### Environment
* Server version: 2.3.0 14f52882f Beta1
* Operating system: Windows 10

**Comment by 5opr4ni** [comment]
Hi Ola

It seems as the DIAG window does not reflect/remove the device set in the mode switch, it just adds the new device at the bottom of the DIAG View. The Mode changes as It should. Confusing

**Comment by 5opr4ni** [comment]
This actually work the same in 2.2

**Comment by ronag** [comment]
Not a regression then. Cool.

**Comment by Julusian** [comment]
I've definitely seen similar quirks with the diag window in the past with some producers.
It probably just needs to call `graph_->set_text(...)` when changing the format

**Comment by Julusian** [comment]
Fixed in d49b5bc8f7e5490ba7dee8784c349d4136eb07e6
