### ISSUE TITLE
decklink audio

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#1312]
Not sure what the cause is but we have some machines where the audio from decklink is inaudible (crackles). Since the DIAG window is a bit broken I can't quite tell but it looks like the audio buffer is empty.

I'm not sure what could cause this but the only difference I have been able to determine between machines that have the problem and those that don't is that the ones that have the problem have "gpu-enable" set to true and play graphics.

Some kind of interference between the Decklink Drivers and DirectX?

**Comment by ronag** [comment]
The problem on the second machine might have been bad signal. I would not consider this a confirmed bug but I would recommend further testing with gpu-enabled false.

**Comment by dotarmin** [comment]
@ronag, as mentioned at the last TSC I have we have encountered same issues. However, our was fixed but upgrading the graphics card from Quadro K2200 to Quadro P4000. Have you done any further research? This one is a blocker for the release unless we don't move it to v2.3.1.

**Comment by ronag** [comment]
> Have you done any further research?

Haven't had time.

**Comment by ronag** [comment]
> our was fixed but upgrading the graphics card from Quadro K2200 to Quadro P4000

Can you downgrade? So we have a repro?

**Comment by dotarmin** [comment]
We have verified when going back to K2200 it starts crackle again and the GPU load is really high. A side note from my side, a lot of things happens on the server so it's not just play and stop. Routing, mixing and etc. is also done on this server where the issue is solved by bumping up the Quadro.

**Comment by ronag** [comment]
Sounds like a performance issue causes the decklink audio buffer to underflow and never recover.

**Comment by dotarmin** [comment]
> Sounds like a performance issue causes the decklink audio buffer to underflow and never recover.

I also asked the other team to try with `<gpu-enable>false</gpu-enable>` and `<gpu-enable>true</gpu-enable>` and they still get the same results. I can try to fix a recording of diag when this happens and share it.

**Comment by dotarmin** [comment]
I’m thinking of moving this to v2.3.1 milestone, what do you think @ronag?

**Comment by ronag** [comment]
Won't object. But I wouldn't consider it stable with this kind of issue.

**Comment by dotarmin** [comment]
> Won't object. But I wouldn't consider it stable with this kind of issue. 

Will you be able to spend some time looking at it next week? I agree that we need to find the reason why this is happening but I need help in that case.

**Comment by baltedewit** [comment]
> Sounds like a performance issue causes the decklink audio buffer to underflow and never recover.

Perhaps a coincidence but I recall having trouble with this is as far back as 2.0.7. If there's consistent performance strain the decklink audio will eventually give out. I've fixed at least 2 occurrences in 2.1 by upgrading GPU. +1 if it gets fixed.

**Comment by ronag** [comment]
As far as I can tell this happens in the following two scenarios:

1. Running internal keyer with a non-clean input source (i.e. sometimes unsynced)
2. Performance issue causing the card not to be fed sufficient frames.

1. Is solved by putting a frame store between the card and input. We should be able to handle/recover this. However, unsure if it's a hardware, firmware, driver or software issue.

2. Is solved by increasing hardware specs or reducing load.

I think this can be closed for now.
