### ISSUE TITLE
jenkins builds using incorrect ffmpeg.exe version

### ISSUE THREAD

**Issue by vimlesh1975** [CasparCG/server#1323]
FFMpeg version in changelog says it is updated to 4.2.2.
But actually it is show 3.4.2.

`Microsoft Windows [Version 10.0.19041.329]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\vimlesh>C:\Users\vimlesh\Downloads\casparcg-server-2.3.0-rc-windows\ffmpeg.exe
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'`

**Comment by Julusian** [comment]
That ffmpeg.exe is used solely by the scanner, not by casparcg itself, and they are downloaded separately and so have drifted.

@dotarmin can you update the jenkins builds to pull in the correct version of ffmpeg.exe?
I shall need to remember to use the correct one when building the release zip file

**Comment by dotarmin** [comment]
@Julusian, fixed or branches: `v2.3.x-lts` and `master`
