### ISSUE TITLE
 MP4 recording can't be imported in Adobe Premiere (recorded with v2.2 or v2.3)

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#1331]
When I setup a recording like this
ADD 1 FILE "myfile 1.mp4" -codec:v libx264 -crf:v 23 -preset:v veryfast -filter:v format=pix_fmts=yuv420p,tinterlace=4 -flags:v +ildct+ilme -codec:a aac -b:a 128k -ar:a 48k

I get a mp4 file with 8 channels audio.
This file does not import in Adobe Premiere, only audio is accepted not video.
Are the ffmpeg parameters changed again?
Are there good examples for stereo or 4 channel recordings?
This worked with v2.1

### Expected behaviour
mp4 should be fine for Premiere

### Current behaviour
Premiere cc2019-2020 only accept audio not the video
----

### Steps to reproduce
1.record a mp4 file with above settings
2.try to import in Adobe Premiere
3. ...

### Environment

* Server version: [2.2 and latest 2.3]
* Operating system:  Windows 10

---

**Comment by TKooijmans** [comment]
This is a working command for stereo recording, this is not accepted with video by Adobe Premiere however......(HD1080i50)
ADD 1 FILE "myfile 1.mp4" -codec:v libx264 -crf:v 23 -preset:v veryfast -filter:v format=pix_fmts=yuv420p,tinterlace=4 -flags:v +ildct+ilme -codec:a aac -b:a 128k -ar:a 48k -filter:a pan=stereo|c0=c0|c1=c2

**Comment by saltomodules** [comment]
What is the video-mode is the channel running in?

**Comment by TKooijmans** [comment]
it's 1080i50,  (1080i5000) if I set 720p2500 or 720p5000 I get the same problem.
The resulting mp4 file seems to play fine in VLC but does not import in Premiere with the video codec.

see attachment
[myfile plaback 2 clip.zip](https://github.com/CasparCG/server/files/5073027/myfile.plaback.2.clip.zip)

**Comment by TKooijmans** [comment]
fps=50 does not fix this problem.
in the attachment a Adobe h264 export

[Adobe h264 high profile export.zip](https://github.com/CasparCG/server/files/5074924/Adobe.h264.high.profile.export.zip)

**Comment by TKooijmans** [comment]
If I test this command direct on FFMPEG in the CasparCG directory the resulting file is compatible  with Adobe Premiere.
So CasparCG 2.2 and 2.3 created a problem with File consumer!

This is ok for Adobe (run in cmd prompt from Decklink input 1080i50)
ffmpeg -f dshow -video_size 1920x1080 -pixel_format uyvy422 -rtbufsize 200k -framerate 25.00 -i video="Decklink Video Capture" -f dshow -i audio="Decklink Audio Capture" -map 0:v -map 1:a -filter:v format=pix_fmts=yuv420p -flags:v +ildct+ilme -codec:v libx264 -crf:v 23 -preset:v veryfast -r 25 -codec:a aac -b:a 128k -ar:a 48k test.mp4

this is not ok with Adobe, video is ignored
ADD 1 FILE "myfile 1.mp4" -codec:v libx264 -crf:v 23 -preset:v veryfast -filter:v format=pix_fmts=yuv420p,tinterlace=4 -flags:v +ildct+ilme -codec:a aac -b:a 128k -ar:a 48k -filter:a pan=stereo|c0=c0|c1=c2

**Comment by Sidonai-1** [comment]
I encountered the same issue. I will try to find a workaround in the meantime, but we used this feature a lot with 2.0.7.

**Comment by TKooijmans** [comment]
I don't know what this problem is, both files shown with mediainfo don't give me a clue.....
Untill this is fixed we use CasparCG 2.1 to record files

**Comment by jhl6** [comment]
Heb je dit probleem nog ooit opgelost gekregen. Wil opnemen in mp4, en verwerken in adobe premiere.
VLC speelt wel af, maar adobe premiere niet.

Jan Hein

**Comment by TKooijmans** [comment]
Nee, tot nog toe is het nog niet opgelost, ik gebruik CasparCG 2.1 voor opnames in mp4

**Comment by jhl6** [comment]
> Nee, tot nog toe is het nog niet opgelost, ik gebruik CasparCG 2.1 voor opnames in mp4

Ben ook al zo ver dat ik nu 2.1 gebruik.
Mag ik weten welke ADD 1 FILE ....... commando je gebruikt voor het opnemen van een MP4 file?
heb er al verschillende geprobeerd, maar gebruik telkens de verkeerde toevoegingen.
Jan Hein

**Comment by TKooijmans** [comment]
Ha Jan, hier zijn de presets voor CasparCG2.1
SD 4-3 interlaced PAL capture adaptive quality
ADD 1 FILE myfile.mp4 -pix_fmt yuv422p -vcodec libx264 -preset veryfast -tune grain -crf 21 -x264opts tff=1 -vf setdar=4:3
HD/SD adaptive quality interlaced
ADD 1 FILE myfile.mp4 -pix_fmt yuv420p -vcodec libx264 -preset veryfast -tune film -crf 21 -x264opts tff=1

**Comment by Julusian** [comment]
perhaps this has changed with https://github.com/CasparCG/server/commit/670bec33e704d7951192dfe8a63787bf38c6a49c?
Its a long shot, but that change doesnt look specific to rtmp streams

**Comment by Julusian** [comment]
I can confirm that with latest 2.4 premiere 2018 is able to import these files, but is unable to import one produced with the same command from 2.3.2
