### ISSUE TITLE
Image scroll

### ISSUE THREAD

**Issue by luca336** [CasparCG/server#1350]
### Expected behaviour
1920px x 5000 px scrolling on screen. 

### Current behaviour
1920px x 5000 px image is being scaled to 1920 x 1080

----

### Steps to reproduce
1. Create a png image. 
2. Load it in server
3. Add it to the client 
4. Hit play 

### Environment
* Commit:  a4a7c05
* Server version:  v2.3.0-lts-stable
* Operating system: windows 10

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by dotarmin** [comment]
Closing this because it's fixed in [v2.3.3 LTS Stable](https://github.com/CasparCG/server/releases/tag/v2.3.3-lts-stable)
