### ISSUE TITLE
Error at installing Server on Ubuntu 18.04

### ISSUE THREAD

**Issue by peterfuehrer** [CasparCG/server#1351]
When i try to install CasparCG Server from source on Ubuntu Desktop 18.04 i get following errors by using the command ./tools/linux/build-in-docker and no folder casparcg/server gets created.

ogl/image/image_kernel.cpp"-Winvalid-pch" "-include" "/build/accelerator/acceler                                                                                                                     ator_pch/StdAfx.h"
ogl/image/image_mixer.cpp"-Winvalid-pch" "-include" "/build/accelerator/accelera                                                                                                                     tor_pch/StdAfx.h"
ogl/image/image_shader.cpp"-Winvalid-pch" "-include" "/build/accelerator/acceler                                                                                                                     ator_pch/StdAfx.h"
ogl/util/buffer.cpp"-Winvalid-pch" "-include" "/build/accelerator/accelerator_pc                                                                                                                     h/StdAfx.h"
ogl/util/device.cpp"-Winvalid-pch" "-include" "/build/accelerator/accelerator_pc                                                                                                                     h/StdAfx.h"
ogl/util/shader.cpp"-Winvalid-pch" "-include" "/build/accelerator/accelerator_pc                                                                                                                     h/StdAfx.h"
ogl/util/texture.cpp"-Winvalid-pch" "-include" "/build/accelerator/accelerator_p                                                                                                                     ch/StdAfx.h"
accelerator.cpp"-Winvalid-pch" "-include" "/build/accelerator/accelerator_pch/St                                                                                                                     dAfx.h"
StdAfx.cpp"-Winvalid-pch" "-include" "/build/accelerator/accelerator_pch/StdAfx.                                                                                                                     h"
diagnostics/graph.cpp"-Winvalid-pch" "-include" "/build/common/common_pch/stdafx                                                                                                                     .h"
gl/gl_check.cpp"-Winvalid-pch" "-include" "/build/common/common_pch/stdafx.h"
base64.cpp"-Winvalid-pch" "-include" "/build/common/common_pch/stdafx.h"
env.cpp"-Winvalid-pch" "-include" "/build/common/common_pch/stdafx.h"
filesystem.cpp"-Winvalid-pch" "-include" "/build/common/common_pch/stdafx.h"
log.cpp"-Winvalid-pch" "-include" "/build/common/common_pch/stdafx.h"
stdafx.cpp"-Winvalid-pch" "-include" "/build/common/common_pch/stdafx.h"
tweener.cpp"-Winvalid-pch" "-include" "/build/common/common_pch/stdafx.h"
utf.cpp"-Winvalid-pch" "-include" "/build/common/common_pch/stdafx.h"
os/linux/filesystem.cpp"-Winvalid-pch" "-include" "/build/common/common_pch/stda                                                                                                                     fx.h"
os/linux/prec_timer.cpp"-Winvalid-pch" "-include" "/build/common/common_pch/stda                                                                                                                     fx.h"
os/linux/thread.cpp"-Winvalid-pch" "-include" "/build/common/common_pch/stdafx.h                                                                                                                     "
consumer/frame_consumer.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdA                                                                                                                     fx.h"
consumer/output.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx.h"
diagnostics/call_context.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/Std                                                                                                                     Afx.h"
diagnostics/osd_graph.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx                                                                                                                     .h"
frame/draw_frame.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx.h"
frame/frame.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx.h"
frame/frame_transform.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx                                                                                                                     .h"
frame/geometry.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx.h"
mixer/audio/audio_mixer.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdA                                                                                                                     fx.h"
mixer/image/blend_modes.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdA                                                                                                                     fx.h"
mixer/mixer.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx.h"
producer/color/color_producer.cpp"-Winvalid-pch" "-include" "/build/core/core_pc                                                                                                                     h/StdAfx.h"
producer/separated/separated_producer.cpp"-Winvalid-pch" "-include" "/build/core                                                                                                                     /core_pch/StdAfx.h"
producer/transition/transition_producer.cpp"-Winvalid-pch" "-include" "/build/co                                                                                                                     re/core_pch/StdAfx.h"
producer/transition/sting_producer.cpp"-Winvalid-pch" "-include" "/build/core/co                                                                                                                     re_pch/StdAfx.h"
producer/route/route_producer.cpp"-Winvalid-pch" "-include" "/build/core/core_pc                                                                                                                     h/StdAfx.h"
producer/cg_proxy.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx.h"
producer/frame_producer.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdA                                                                                                                     fx.h"
producer/layer.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx.h"
producer/stage.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx.h"
StdAfx.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx.h"
video_channel.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx.h"
video_format.cpp"-Winvalid-pch" "-include" "/build/core/core_pch/StdAfx.h"
producer/av_producer.cpp"-Winvalid-pch" "-include" "/build/modules/ffmpeg/ffmpeg                                                                                                                     _pch/StdAfx.h"
producer/av_input.cpp"-Winvalid-pch" "-include" "/build/modules/ffmpeg/ffmpeg_pc                                                                                                                     h/StdAfx.h"
util/av_util.cpp"-Winvalid-pch" "-include" "/build/modules/ffmpeg/ffmpeg_pch/Std                                                                                                                     Afx.h"
producer/ffmpeg_producer.cpp"-Winvalid-pch" "-include" "/build/modules/ffmpeg/ff                                                                                                                     mpeg_pch/StdAfx.h"
consumer/ffmpeg_consumer.cpp"-Winvalid-pch" "-include" "/build/modules/ffmpeg/ff                                                                                                                     mpeg_pch/StdAfx.h"
ffmpeg.cpp"-Winvalid-pch" "-include" "/build/modules/ffmpeg/ffmpeg_pch/StdAfx.h"
StdAfx.cpp"-Winvalid-pch" "-include" "/build/modules/ffmpeg/ffmpeg_pch/StdAfx.h"
consumer/decklink_consumer.cpp"-Winvalid-pch" "-include" "/build/modules/decklin                                                                                                                     k/decklink_pch/StdAfx.h"
producer/decklink_producer.cpp"-Winvalid-pch" "-include" "/build/modules/decklin                                                                                                                     k/decklink_pch/StdAfx.h"
decklink.cpp"-Winvalid-pch" "-include" "/build/modules/decklink/decklink_pch/Std                                                                                                                     Afx.h"
StdAfx.cpp"-Winvalid-pch" "-include" "/build/modules/decklink/decklink_pch/StdAf                                                                                                                     x.h"
linux_interop/DeckLinkAPIDispatch.cpp"-Winvalid-pch" "-include" "/build/modules/                                                                                                                     decklink/decklink_pch/StdAfx.h"
consumer/newtek_ndi_consumer.cpp"-Winvalid-pch" "-include" "/build/modules/newte                                                                                                                     k/newtek_pch/StdAfx.h"
producer/newtek_ndi_producer.cpp"-Winvalid-pch" "-include" "/build/modules/newte                                                                                                                     k/newtek_pch/StdAfx.h"
util/ndi.cpp"-Winvalid-pch" "-include" "/build/modules/newtek/newtek_pch/StdAfx.                                                                                                                     h"
newtek.cpp"-Winvalid-pch" "-include" "/build/modules/newtek/newtek_pch/StdAfx.h"
StdAfx.cpp"-Winvalid-pch" "-include" "/build/modules/newtek/newtek_pch/StdAfx.h"
amcp/AMCPCommandQueue.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_pc                                                                                                                     h/StdAfx.h"
amcp/AMCPCommandsImpl.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_pc                                                                                                                     h/StdAfx.h"
amcp/AMCPProtocolStrategy.cpp"-Winvalid-pch" "-include" "/build/protocol/protoco                                                                                                                     l_pch/StdAfx.h"
amcp/amcp_command_repository.cpp"-Winvalid-pch" "-include" "/build/protocol/prot                                                                                                                     ocol_pch/StdAfx.h"
cii/CIICommandsImpl.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_pch/                                                                                                                     StdAfx.h"
cii/CIIProtocolStrategy.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_                                                                                                                     pch/StdAfx.h"
clk/CLKProtocolStrategy.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_                                                                                                                     pch/StdAfx.h"
clk/clk_commands.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_pch/Std                                                                                                                     Afx.h"
clk/clk_command_processor.cpp"-Winvalid-pch" "-include" "/build/protocol/protoco                                                                                                                     l_pch/StdAfx.h"
osc/oscpack/OscOutboundPacketStream.cpp"-Winvalid-pch" "-include" "/build/protoc                                                                                                                     ol/protocol_pch/StdAfx.h"
osc/oscpack/OscPrintReceivedElements.cpp"-Winvalid-pch" "-include" "/build/proto                                                                                                                     col/protocol_pch/StdAfx.h"
osc/oscpack/OscReceivedElements.cpp"-Winvalid-pch" "-include" "/build/protocol/p                                                                                                                     rotocol_pch/StdAfx.h"
osc/oscpack/OscTypes.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_pch                                                                                                                     /StdAfx.h"
osc/client.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_pch/StdAfx.h"
util/AsyncEventServer.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_pc                                                                                                                     h/StdAfx.h"
util/lock_container.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_pch/                                                                                                                     StdAfx.h"
util/strategy_adapters.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_p                                                                                                                     ch/StdAfx.h"
util/http_request.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_pch/St                                                                                                                     dAfx.h"
StdAfx.cpp"-Winvalid-pch" "-include" "/build/protocol/protocol_pch/StdAfx.h"

+ apt-get update
Err:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu bionic InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temp                                                                                                                     orary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelea                                                                                                                     se  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRel                                                                                                                     ease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRel                                                                                                                     ease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used                                                                                                                      instead.
+ apt-get install -y --no-install-recommends libc++1 libnss3 fontconfig
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libc++1
E: Couldn't find any package by regex 'libc++1'
E: Unable to locate package libnss3
E: Unable to locate package fontconfig
The command '/bin/sh -c set -ex;                apt-get update;                a                                                                                                                     pt-get install -y --no-install-recommends                       libc++1        l                                                                                                                     ibnss3                  fontconfig              ;               rm -rf /var/lib/                                                                                                                     apt/lists/*' returned a non-zero code: 100

Please help me installing!

**Comment by Julusian** [comment]
`Temporary failure resolving 'security.ubuntu.com'`
Looks like you are having network/dns issues
