### ISSUE TITLE
Low performance with Decklink producer

### ISSUE THREAD

**Issue by lukasmican** [CasparCG/server#1354]
### Expected behaviour
The Decklink producer performance should be similar to FFMPEG producer.

### Current behaviour
When using Decklink producers the performance hit is pretty significant. With hardware described below I was able to play into 2160p30 channel smoothly only from two Decklink producers in 1080p30 format with 95% GPU utilization. Adding more than two Decklink producers resulted in 100% GPU usage and choppy output video. However when I used 4 separate ffmpeg processes which grabbed video from Decklink, encoded into mpeg2 and streamed it over UDP to CasparCG I managed to play all four Decklink sources smoothly with only 75% GPU utilization.

----

### Steps to reproduce
1. Start CasparCG in 2160p3000 mode with Decklink consumer output
2. Start multiple Decklink producers in 1080p3000 mode

### Environment
* Commit: 7ac31ee
* Server version: v2.3
* Operating system: Ubuntu 18.04 with kernel 5.4
* NVIDIA Driver: 455.38
* DeckLink driver: 11.7
* CPU: AMD Ryzen 3600XT
* GPU: Nvidia GeForce RTX 2060 6GB
* Capture card: DeckLink Quad HDMI Recorder
* Video output card: DeckLink Mini Monitor 4K

**Comment by Julusian** [comment]
There have been various changes to the decklink producer which improve performance since this was opened. Hopefully this is better now
