### ISSUE TITLE
Low performance with high resolution channels

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#1357]
[casparcg.TXT](https://github.com/CasparCG/server/files/5728534/casparcg.TXT)

### Expected behaviour
You should be able to play more than one file without any distortion in audio and video

### Current behaviour
Playing more than one file distorts the video and audio. there is jerking and cracking in audio and video is not smooth

----

### Steps to reproduce
1. setup up channel in config file with video mode set to either 1080i5000 or 1080p5000 or above
2. Play 1-1 File1
3. Play 1-2 File2
4. Play 1-3 File3

### Environment
* Commit: latest commit
* Server version: 2.3
* Operating system: Windows 10
* Graphics Card: nvidia P4000, Blackmagic Duo 2
---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by hreinnbeck** [comment]
Does this happen with any file?  If you play 3x AMB or CG1080i50 do they work? If they work and not your other files, what's the format and encoding? Are they very large and this might be disk performance issues?

No errors in logs? Please test again by setting `<log-level>trace</log-level>` in config.

I notice that the config file you provided has elements that are not part of CCG, are you using a custom build?

**Comment by PeterAkakpo** [comment]
those extra details in the config file are for a custom client. they are just there to inform the client which channel is the primary id=1 and secondary id=2. casparcg will ignore those extra details. the files are not all of the same format and they are loaded from SSD drive. the size of the files are about 2GB

**Comment by PeterAkakpo** [comment]
i have tried 2.3.2 LTS beta and i can say its a great improvement. i was able to play 9 instances a video files (2GB in size) with no issue, video was smooth and sound was ok too. upon playing the tenth file ,video is still smooth with a noticeable slowness, but sound is jerking/cracking on decklink output and out of sink on system audio.

RESOURCE USAGE FOR 10 VIDEO FILES (2gb IN SIZE)
MEMORY 1.3GB
CPU 26%
GPU: 60%

SYSTEM
Windows: 10 Pro
graphic card: NVidia GT710
Decklink card: Intensity Pro 4K

CASPARCG SETTINGS
video mode: 1080i5000

I think it will rock with better hardwares

great work

**Comment by PeterAkakpo** [comment]
> AMB or CG1080i50

**Comment by PeterAkakpo** [comment]
practically, i don't think  AMB or CG1080i50  are good examples to use.

**Comment by PeterAkakpo** [comment]
casparcg should be able to play any number of files simultaneously  provided the hardware supports it. Could  that be a codec issue? if its is , what is the recommended video and audio formats for casparcg.
