### ISSUE TITLE
INFO TEMPLATE is broken in 2.0.7.1 Hotfix

### ISSUE THREAD

**Issue by didikunz** [CasparCG/server#1359]
### Expected behaviour
The Flash EOL hotfix for server version 2.0.7 should work exactly the same as the unpatched version.

### Current behaviour
The INFO TEMPLATE command returns "403 INFO ERROR" instead of the templates metadata.

### Steps to reproduce
Send a INFO TEMPLATE command to the server and see the response

### Environment
* Server version: 2.0.7.1
* Operating system: Windows 10

**Comment by didikunz** [comment]
People get upset about this issue. See [here](https://casparcgforum.org/t/casparcg-server-hotfix-releases-for-flash-player-end-of-life/3757/16).

**Comment by Julusian** [comment]
I made an unofficial build that fixed this https://builds.julusian.dev/casparcg/CasparCG.Server-2.0.7.2-flash-eol-hotfix.zip
As this is very old now, I am going to close this
