### ISSUE TITLE
LOADBG AUTO not working with PLAY SEEK in current playing file

### ISSUE THREAD

**Issue by laurensvane** [CasparCG/server#1375]
### Expected behaviour
When issuing a "LOADBG 1-1 $itemid AUTO" directly after a "PLAY 1-1 $itemid SEEK $seektime" the item in loadbg will be played after the foreground item stops playing.

### Current behaviour
The loadbg item directly becomes active on the foreground.
When

----

### Steps to reproduce
1. run PLAY 1-1 $itemid SEEK $seektime
2. run LOADBG 1-1 $itemid AUTO

in my case the play item was a 12 second videoclip, the seek was 13 or 14.
the loadbg item was "EMPTY" which results in a color[EMPTY]

These are scripted commands so they get sent directly after each other.
i could not reproduce this by issuing the commands by hand.
Sending the loadbg command after receiving a 202 from casparcg doesn't help either.

When i issue PLAY 1-1 $itemid without the SEEK parameter the same way all works as expected.

### Environment
* Commit: e767c1dda
* Server version: v2.3.1
* Operating system: windows 10 1909

**Comment by Julusian** [comment]
I am unable to reproduce this. If you still can in 2.4, perhaps you could provide a script which reproduces it, or some logs?
