### ISSUE TITLE
Routed layer not cleared when source layer is cleared

### ISSUE THREAD

**Issue by grahamspr86** [CasparCG/server#1377]
Routed layer not cleared when source layer is cleared.

If you issue the following command to play a video on 2-10 and route it to 1-20 when you use the clear command on 2-10 the last frame is left on the 1-20

I don't believe this use to be an issue, I'm using build fd75dd58

```
LOADBG 2-10 "TEST" CUT 0 Linear RIGHT
PLAY 2-10
PLAY 1-20 route://2-10
```

`CLEAR 2-10`

**Comment by Julusian** [comment]
fixed by https://github.com/CasparCG/server/commit/97461c6c17fab0fa350bcf4f2289aa418670a70e?
