### ISSUE TITLE
GPU Error

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#1378]
### Expected behaviour
there shouldn't be any error on start up
### Current behaviour
Log display Lost UI shared context

----

### Steps to reproduce
1. start casparcg
2.
3. ...

### Environment
* Commit: 4de6d18f
* Server version: 2.3.2
* Operating system: Windows 10
* NVidia Card: P2000
* Blackmagic card: Duo 2
![ccg](https://user-images.githubusercontent.com/7926382/113475319-71b10880-9464-11eb-89fb-b2817effac3d.png)

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by PeterAkakpo** [comment]
Does this error has any effect on performance?. i asked this because am unable to play more than two 1920x1080 video files smoothly. Video goes slow and the sound breaks

**Comment by Julusian** [comment]
That error is thrown by CEF, so if it has any impact I think should only affect html performance.
