### ISSUE TITLE
CLS returning old list of media after changing media folder

### ISSUE THREAD

**Issue by JonFranklin301** [CasparCG/server#1379]
### Expected behaviour
The CLS command should return a list of media that exactly matches the content in the media folder.

### Current behaviour
After stopping the server and media scanner, changing the media path in the config file and restarting the server, running CLS returns the list of media from the previous media folder and does not list any content from the new media path.

----

### Steps to reproduce
1. Have two different media folders setup with different content in each (image and video). ("D:\FolderA" and "D:\FolderB" for example)
2. Have CasparCG 2.3.1 and Media Scanner running, with the media path "D:\FolderA". 
3. Run CLS and check the list of media matches FolderA
4. Stop CasparCG and media scanner. 
5. Change the media path in config file to be "D:\FolderB".
6. Start CasparCG and Media Scanner
7. Run CLS and check the list of media matches FolderB

### Environment
* Commit: e767c1dda
* Server version: v2.3.1 LTS
* Operating system: Windows 10 Pro
* Media is stored on a separate internal SSD, "D:\FolderA"

We have 10 CasparCG playout machines all with the same same setup. So far I am aware of this issue happening on 3 machines.

---

### Other Info
We have found the only way to resolve this issue and get the correct CLS list is to stop the server, delete the folders "_media", "blob_storage", "data" and "pouch__all_dbs__" then restart the PC. Caspar can then be started again and will return the correct list of media.
 (all of these folders may not need deleting, we have not tested deleting different combinations of these)

**Comment by JonFranklin301** [comment]
Tested on v2.3.3 and has the same issue.
After changing the media folder and restarting the server, the CLS command returns a combined list of the old media folder and the new media folder content.

**Comment by Julusian** [comment]
This sounds like a bug in media-scanner that I think was fixed
