### ISSUE TITLE
Website download page woefully out of date.

### ISSUE THREAD

**Issue by Jamie-** [CasparCG/server#1381]
If you Google for "download casparcg", the first hit is http://casparcg.com/download.html

This page is woefully out of date, advertising the latest build to be one from December 2014!

Additionally, the link to install the Microsoft Visual C++ 2010 redist is dead now as Microsoft have moved it.

Not sure where else to report this so thought I'd try here.

**Comment by ducthiem90** [comment]
You can download it here:
https://github.com/CasparCG/server/releases

**Comment by dimitry-ishenko** [comment]
@ducthiem90 yes you can, but I think you are missing his point that the "official" downloads page is outdated.

**Comment by ronag** [comment]
The problem here is there is no active maintainer nor funding to hire one. IMO. Unfortunately, It’s unlikely any further updates will happen on the website anytime soon.

**Comment by hreinnbeck** [comment]
Simply redirecting casparcg.com to this repo would be better than it being outdated/unmaintained.

**Comment by huslage** [comment]
Is SVT no longer using/maintaining CasparCG?!

**Comment by dotarmin** [comment]
> Is SVT no longer using/maintaining CasparCG?!

Hi @huslage

Short answer, yes we are still contributing to the project and to the upstream (through framework agreements last 2-3 years). However, this is a friendly reminder that this is an open source project and has plenty of room for more contributors and maintainers :)

**Comment by Julusian** [comment]
The website has been updated
