### ISSUE TITLE
 HD video to SD playback using either center cut or letterbox 

### ISSUE THREAD

**Issue by ark1974** [CasparCG/server#1382]
I need to come up with a general formula for HD video to SD playback using either center cut or letterbox. 

Lets  say i am using a playing a video 1080x720 resolution, i want change the screen consumer as well as the decklink consumer to a letter box or center cut using CasparCG console commands. How do I do it ? It should also work for other HD resolutions.

Please tag this not an issue but as a query. Unable  to find answer from CasparCG forum.

**Comment by vimlesh1975** [comment]
We use following for HD 1920x1080 to PAL 720x576

For CenterCut mixer 1-1 -0.17 0.0 1.34 1.0
For LetterBox mixer 1-1 0.0 0.12 1.0 0.76
