### ISSUE TITLE
Spectacular memory leak in build from 865502c on Ubuntu 18.04

### ISSUE THREAD

**Issue by saltomodules** [CasparCG/server#1385]
Made a build in docker from current master (at 865502c). 

As soon as you start a (h264) clip in that build memory starts running op very fast. 16gb is exhausted in 30 secs or so.

Logs don't say much that seems relevant, but there are lots of latency warnings when memory starts getting full 

Probably has something to do with recent commits related to threading

**Comment by dimitry-ishenko** [comment]
May have something to do with TBB

**Comment by saltomodules** [comment]
It looks like it's more recent than that. Did a few intermediate builds and it looks like it is b657428 (refactor(ffmeg_producer): decoder threads)

The build from the preceding 5dcd50c commit doesn't seem to have the leak.

**Comment by stemcc** [comment]
> 
> 
> It looks like it's more recent than that. Did a few intermediate builds and it looks like it is [b657428](https://github.com/CasparCG/server/commit/b657428db652a2ef43601fc3923934498506a916) (refactor(ffmeg_producer): decoder threads)
> 
> The build from the preceding [5dcd50c](https://github.com/CasparCG/server/commit/5dcd50c53c4df4ecc1fe1ca3a53c5eee3e2f3afe) commit doesn't seem to have the leak.

I can confirm this same memory leak in Windows 10, and that using a build from the prior commit as you mentioned here does not cause this memory leak.

**Comment by fabiankaestner** [comment]
Is there any progress on this? I believe I am experiencing this issue as well, and it is indeed quite spectacular to witness :)
Using Windows 10, and building from the most recent commit.

**Comment by gizahNL** [comment]
Doing some debugging and looking at the code it looks like the decoder thread in  src/modules/ffmpeg/producer/av_producer.cpp line 143 decodes the entire file into memory.

This also explains why bigger files result in a bigger memleak.

**Comment by gizahNL** [comment]
Uncomenting waiting on the condvar on line 201 in the same file fixes the issue for me.

**Comment by toresbe** [comment]
Experiencing similar issues on 865502c092f26d8205937a1bd7d60850f071f656 running this in Docker on Linux.
