### ISSUE TITLE
Not able to run YUV files on 2.3.3

### ISSUE THREAD

**Issue by shorbagy14** [CasparCG/server#1386]
`ffplay "akiyo_cif.yuv" -f rawvideo -video_size 352x288`
I can run the file using the above command on ffmpeg but when I use CCG, I get the following error

`[2021-07-19 12:23:59.492] [error]   [ffmpeg] [IMGUTILS @ 0000006E9A0FF190] Picture size 0x0 is invalid`

I used this to try to play it
`PLAY 1-1 "akiyo_cif.yuv" -c:v rawvideo -s:v 352x288 -preset slow -s 352x288`

**Comment by Julusian** [comment]
I think the syntax for playing files changed in 2.2?
