### ISSUE TITLE
Screen producer (not windowed) broken

### ISSUE THREAD

**Issue by MauriceVeraart** [CasparCG/server#1389]
### Current behaviour
when using `<windowed>false</windowed>` the screen producer stays black.
when using `<windowed>true</windowed>`all works as expected

tested it on 2 completly different machine's

----

**Comment by jpc0** [comment]
I'm aware it has been two years but I am unable to reproduce this on the current branch or the latest stable.

@Julusian @MauriceVeraart  I'm guessing this is resolved?

**Comment by MauriceVeraart** [comment]
I checked today and it's working. thanks for the reminder.
