### ISSUE TITLE
Problem executing large files (Sudden increase in RAM)

### ISSUE THREAD

**Issue by masoori** [CasparCG/server#1401]
In the final version, when we play a large video file, the RAM increases rapidly so that the system hangs.

OS - Windows10
CCG - Last Commited

https://user-images.githubusercontent.com/7155745/141696928-e4233d5c-ce9f-47ae-a47b-c03b19a9ccad.mp4

**Comment by gizahNL** [comment]
Yes it seems there is a memleak in casparcg on the latest commit on master

**Comment by gizahNL** [comment]
Seems to be a duplicate of 1385

**Comment by gizahNL** [comment]
@Julusian this one can be closed duplicate of #1385
