### ISSUE TITLE
Building on Debian 11

### ISSUE THREAD

**Issue by ogmkp** [CasparCG/server#1411]
### Expected behaviour
Follow the building guide and build without problems.

### Current behaviour
Follow the building guide and get many errors and failure with libboost.
----

### Steps to reproduce
1. Following development section of the building guide (installing dependencies, docker, git clone casparcg lts 2.3.3, extract boost, ffmpeg and cef from docker images to /opt with the extracting script, doing cmake and make).
2. Launch building
3. Have a lot of mistakes at the step CXX linking and get stop from make with error: 
```
[100%] Linking CXX executable casparcg
/usr/bin/ld: /opt/boost/lib/libboost_locale.a(date_time.o): attention: réadressage sur « _ZTIN6icu_608CalendarE » dans la section en lecture seule « .text._ZNK5boost6locale8impl_icu13calendar_impl10get_optionENS0_17abstract_calendar20calendar_option_typeE[_ZNK5boost6locale8impl_icu13calendar_impl10get_optionENS0_17abstract_calendar20calendar_option_typeE] »
/usr/bin/ld : /opt/boost/lib/libboost_locale.a(boundary.o) : dans la fonction « boost::locale::boundary::impl_icu::get_iterator(boost::locale::boundary::boundary_type, icu_60::Locale const&) » :
boundary.cpp:(.text+0x4c) : référence indéfinie vers « icu_60::BreakIterator::createLineInstance(icu_60::Locale const&, UErrorCode&) »
/usr/bin/ld : boundary.cpp:(.text+0xa9) : référence indéfinie vers « icu_60::BreakIterator::createSentenceInstance(icu_60::Locale const&, UErrorCode&) »
/usr/bin/ld : boundary.cpp:(.text+0xb9) : référence indéfinie vers « icu_60::BreakIterator::createCharacterInstance(icu_60::Locale const&, UErrorCode&) »
/usr/bin/ld : boundary.cpp:(.text+0xc9) : référence indéfinie vers « icu_60::BreakIterator::createWordInstance(icu_60::Locale const&, UErrorCode&) »
/usr/bin/ld : /opt/boost/lib/libboost_locale.a(boundary.o) : dans la fonction « boost::locale::impl_icu::create_boundary(std::locale const&, boost::locale::impl_icu::cdata const&, unsigned int) » :
boundary.cpp:(.text+0x729) : référence indéfinie vers « icu_60::Locale::Locale(icu_60::Locale const&) »
/usr/bin/ld : boundary.cpp:(.text+0x7c9) : référence indéfinie vers « icu_60::Locale::Locale(icu_60::Locale const&) »
/usr/bin/ld : boundary.cpp:(.text+0x92b) : référence indéfinie vers « icu_60::Locale::~Locale() »
/usr/bin/ld : boundary.cpp:(.text+0x938) : référence indéfinie vers « icu_60::Locale::~Locale() »
/usr/bin/ld : /opt/boost/lib/libboost_locale.a(boundary.o) : dans la fonction « boost::locale::boundary::impl_icu::boundary_indexing_impl<char>::~boundary_indexing_impl() » :
boundary.cpp:(.text._ZN5boost6locale8boundary8impl_icu22boundary_indexing_implIcED2Ev[_ZN5boost6locale8boundary8impl_icu22boundary_indexing_implIcED5Ev]+0x2b) : référence indéfinie vers « icu_60::Locale::~Locale() »
/usr/bin/ld : /opt/boost/lib/libboost_locale.a(boundary.o) : dans la fonction « boost::locale::boundary::impl_icu::boundary_indexing_impl<wchar_t>::~boundary_indexing_impl() » :
boundary.cpp:(.text._ZN5boost6locale8boundary8impl_icu22boundary_indexing_implIwED2Ev[_ZN5boost6locale8boundary8impl_icu22boundary_indexing_implIwED5Ev]+0x2b) : référence indéfinie vers « icu_60::Locale::~Locale() »
/usr/bin/ld : /opt/boost/lib/libboost_locale.a(boundary.o) : dans la fonction « boost::locale::boundary::impl_icu::boundary_indexing_impl<wchar_t>::~boundary_indexing_impl() » :
boundary.cpp:(.text._ZN5boost6locale8boundary8impl_icu22boundary_indexing_implIwED0Ev[_ZN5boost6locale8boundary8impl_icu22boundary_indexing_implIwED5Ev]+0x2b) : référence indéfinie vers « icu_60::Locale::~Locale() »
/usr/bin/ld : /opt/boost/lib/libboost_locale.a(boundary.o):boundary.cpp:(.text._ZN5boost6locale8boundary8impl_icu22boundary_indexing_implIcED0Ev[_ZN5boost6locale8boundary8impl_icu22boundary_indexing_implIcED5Ev]+0x2b) : encore plus de références indéfinies suivent vers « icu_60::Locale::~Locale() »
[..]
/usr/bin/ld : codecvt.cpp:(.text._ZNK5boost6locale8impl_icu15uconv_converter5cloneEv[_ZNK5boost6locale8impl_icu15uconv_converter5cloneEv]+0xe8) : référence indéfinie vers « ucnv_close_60 »
/usr/bin/ld : codecvt.cpp:(.text._ZNK5boost6locale8impl_icu15uconv_converter5cloneEv[_ZNK5boost6locale8impl_icu15uconv_converter5cloneEv]+0x2c1) : référence indéfinie vers « ucnv_getMaxCharSize_60 »
/usr/bin/ld : /opt/boost/lib/libboost_locale.a(time_zone.o) : dans la fonction « boost::locale::impl_icu::get_time_zone(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) » :
time_zone.cpp:(.text+0x29) : référence indéfinie vers « icu_60::UnicodeString::UnicodeString(char const*) »
/usr/bin/ld : time_zone.cpp:(.text+0x31) : référence indéfinie vers « icu_60::TimeZone::createTimeZone(icu_60::UnicodeString const&) »
/usr/bin/ld : time_zone.cpp:(.text+0x3e) : référence indéfinie vers « icu_60::UnicodeString::~UnicodeString() »
/usr/bin/ld : time_zone.cpp:(.text+0x61) : référence indéfinie vers « icu_60::TimeZone::createDefault() »
/usr/bin/ld : time_zone.cpp:(.text+0x73) : référence indéfinie vers « icu_60::UnicodeString::~UnicodeString() »
/usr/bin/ld: attention: création de DT_TEXTREL dans un PIE
collect2: error: ld returned 1 exit status
make[2]: *** [shell/CMakeFiles/casparcg.dir/build.make:170 : shell/casparcg] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:761 : shell/CMakeFiles/casparcg.dir/all] Erreur 2
make: *** [Makefile:103 : all] Erreur 2
```

### Environment
* Commit: [Revision: 4de6d18f8]
* Server version: [v2.3.3]
* Operating system: [Debian 11 Bullseye stable]

---

Thank you.

**Comment by gizahNL** [comment]
If you only modified the docker file to use debian instead of ubuntu then it will fail since it will pull the cached cef/boost/ffmpeg layers that were build with ubuntu. 

You can also build with system ffmpeg & boost btw.

**Comment by gizahNL** [comment]
For building cef you might need a patch:
```
diff --git a/cmake/cef_variables.cmake.in b/cmake/cef_variables.cmake.in
index 10698843e..e42b7ed85 100644
--- a/cmake/cef_variables.cmake
+++ b/cmake/cef_variables.cmake
@@ -169,6 +169,12 @@ if(OS_LINUX)
       )
   endif()
 
+  if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
+    list(APPEND CEF_CXX_COMPILER_FLAGS
+      -Wno-attributes             # The cfi-icall attribute is not supported by the GNU C++ compiler
+      )
+  endif()
+
   if(PROJECT_ARCH STREQUAL "x86_64")
     # 64-bit architecture.
     list(APPEND CEF_COMPILER_FLAGS
```

**Comment by ogmkp** [comment]
Is there a way to make casparcg work on Debian 11, a guide, a docker image?

**Comment by gizahNL** [comment]
```
FROM debian:bullseye as builder

RUN sed -i 's/main/main contrib non-free/' /etc/apt/sources.list
RUN apt-get update && apt-get install -yq --no-install-recommends \
               build-essential \
               git \
               ninja-build \
               cmake \
               debhelper    \
               libass-dev    \
               libavcodec-dev    \
               libavdevice-dev    \
               libavfilter-dev    \
               libavformat-dev    \
               libavutil-dev    \
               libboost-chrono-dev    \
               libboost-coroutine-dev    \
               libboost-date-time-dev    \
               libboost-dev     \
               libboost-filesystem-dev    \
               libboost-locale-dev    \
               libboost-log-dev    \
               libboost-regex-dev    \
               libboost-thread-dev    \
               libbz2-dev    \
               libcrypto++-dev    \
               libfdk-aac-dev    \
               libfreeimage-dev    \
               libfreetype6-dev    \
               libgconf2-dev    \
               libglew-dev    \
               libglfw3-dev    \
               libgmp-dev    \
               libjpeg-dev    \
               liblzma-dev    \
               libmp3lame-dev    \
               libopenal-dev    \
               libopus-dev    \
               libpostproc-dev    \
               librtmp-dev    \
               libsfml-dev    \
               libsndfile1-dev    \
               libssl-dev    \
               libswresample-dev    \
               libswscale-dev    \
               libtbb-dev    \
               libtheora-dev    \
               libvpx-dev    \
               libwebp-dev    \
               libx264-dev    \
               libx265-dev    \
               libxcb-shm0-dev    \
               libxcursor-dev    \
               libxi-dev    \
               libxinerama-dev    \
               libxrandr-dev    \
               pkg-config    \
               ca-certificates \
               libnss3 \
               libxcomposite1 \
               libatk1.0-0 \
               libatk-bridge2.0-0 \
               libatspi2.0-0 \
               txt2man

RUN update-ca-certificates

FROM builder as cef
ARG PROC_COUNT=8
ADD https://cef-builds.spotifycdn.com/cef_binary_3.3578.1870.gc974488_linux64_minimal.tar.bz2 /opt/cef.tar.bz2
WORKDIR /opt
COPY cef-patch /opt/cef-patch
RUN tar -jxf cef.tar.bz2 && mv /opt/cef_binary_* /opt/cef
RUN ls /opt/cef
RUN cd /opt/cef; \
    patch -p 1 < /opt/cef-patch;
RUN mkdir /opt/build
WORKDIR /opt/build
RUN cmake /opt/cef && make -j $PROC_COUNT
RUN cp /opt/build/libcef_dll_wrapper/libcef_dll_wrapper.a /opt/cef/Release/
RUN strip /opt/cef/Release/libcef.so


FROM builder as casparcg
ARG PROC_COUNT=8
COPY --from=cef /opt/cef /opt/cef
ADD https://api.github.com/repos/CasparCG/server/compare/master...HEAD /dev/null
RUN git clone https://github.com/CasparCG/server.git /server
WORKDIR /server
RUN   git config --global user.email "bla@bla.com"; \
  git config --global user.name "Bla Bla"
ADD https://github.com/CasparCG/server/pull/1308.diff /1308.patch
RUN patch -p 1 < /1308.patch
ADD https://github.com/CasparCG/server/pull/1397.diff /1397.patch
RUN patch -p 1 < /1397.patch
ADD https://github.com/CasparCG/server/pull/1403.diff /1403.patch
RUN patch -p 1 < /1403.patch
ADD https://github.com/CasparCG/server/pull/1404.diff /1404.patch
RUN patch -p 1 < /1404.patch
ADD https://github.com/CasparCG/server/pull/1406.diff /1406.patch
RUN patch -p 1 < /1406.patch
ADD https://github.com/CasparCG/server/pull/1410.diff /1410.patch
RUN patch -p 1 < /1410.patch
RUN mkdir /build
WORKDIR /build
RUN cmake -DCMAKE_BUILD_TYPE=Release /server/src
RUN make -j ${PROC_COUNT}

FROM builder
COPY --from=casparcg /build/staging /staging
```
Try with that, it's based on my development train

**Comment by ogmkp** [comment]
Thank you for sharing your script !

I encounter a issue on step 9:

```
Step 7/42 : ADD https://cef-builds.spotifycdn.com/cef_binary_3.3578.1870.gc974488_linux64_minimal.tar.bz2 /opt/cef.tar.bz2
Downloading [==================================================>]  213.2MB/213.2MB
 ---> fcef8ad39ddc
Step 8/42 : WORKDIR /opt
 ---> Running in 9de43de2be56
Removing intermediate container 9de43de2be56
 ---> 3d68068e45e3
Step 9/42 : COPY cef-patch /opt/cef-patch
COPY failed: file not found in build context or excluded by .dockerignore: stat cef-patch: file does not exist
```

How to add the cef-patch ?

**Comment by gizahNL** [comment]
Copy paste the contents of the patch I pasted above into 'cef-patch'  and place it next to the Dockerfile

**Comment by ogmkp** [comment]
Thank you, thats make sense.
I have another error on the building process with boost:

```
Step 36/41 : RUN mkdir /build
 ---> Running in 7cef5bd5d09c
Removing intermediate container 7cef5bd5d09c
 ---> 672c7d1b2d84
Step 37/41 : WORKDIR /build
 ---> Running in d87aa9ebc0e4
Removing intermediate container d87aa9ebc0e4
 ---> dd979773b7e8
Step 38/41 : RUN cmake -DCMAKE_BUILD_TYPE=Release /server/src
 ---> Running in 72a8d33befd9
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.30.2") 
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/boost_system-1.74.0/boost_system-config.cmake

  but it set boost_system_FOUND to FALSE so package "boost_system" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_system.so.1.74.0 (shared, Boost_USE_STATIC_LIBS=ON)

  * libboost_system.a (release, Boost_USE_RELEASE_LIBS=OFF)

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:258 (boost_find_component)
  CMakeModules/FindBoost.cmake:245 (find_package)
  CMakeModules/Bootstrap_Linux.cmake:29 (FIND_PACKAGE)
  CMakeLists.txt:18 (INCLUDE)


-- Configuring incomplete, errors occurred!
See also "/build/CMakeFiles/CMakeOutput.log".
The command '/bin/sh -c cmake -DCMAKE_BUILD_TYPE=Release /server/src' returned a non-zero code: 1

```

I keep all your patchs added, is it related to boost patch or boost provided by debian ?

**Comment by gizahNL** [comment]
The latter, if you add a patch that changes Boost_USE_RELEASE_LIBS=OFF to Boost_USE_RELEASE_LIBS=ON it should work

**Comment by ogmkp** [comment]
Sorry but how to do a patch for change this variable ?

**Comment by gizahNL** [comment]
git diff filechanged > output patchfile

```
diff --git a/src/CMakeModules/Bootstrap_Linux.cmake b/src/CMakeModules/Bootstrap_Linux.cmake
index 5742f58c3..d10097738 100644
--- a/src/CMakeModules/Bootstrap_Linux.cmake
+++ b/src/CMakeModules/Bootstrap_Linux.cmake
@@ -24,7 +24,7 @@ ENDIF ()
 SET (BOOST_ROOT_PATH "/opt/boost" CACHE STRING "Path to Boost")
 SET (ENV{BOOST_ROOT} "${BOOST_ROOT_PATH}")
 SET (Boost_USE_DEBUG_LIBS ON)
-SET (Boost_USE_RELEASE_LIBS OFF)
+SET (Boost_USE_RELEASE_LIBS ON)
 SET (Boost_USE_STATIC_LIBS ON)
 FIND_PACKAGE (Boost 1.66.0 COMPONENTS system thread chrono filesystem log locale regex date_time coroutine REQUIRED)
```

**Comment by ogmkp** [comment]
Thank you for your help, the server is running.
I had to add lsb-release and libxtst-dev for a complete build.

Thats great.
I close this ticket.

**Comment by dequedrapha** [comment]
Hey there,
i also wanna install caspargc on my debian 11 vps and i am failing at this one error in step 28... maybe someone could help me aswell :)

> Sending build context to Docker daemon  69.63kB
Step 1/42 : FROM debian:bullseye as builder
 ---> d8cacd17cfdc
Step 2/42 : RUN sed -i 's/main/main contrib non-free/' /etc/apt/sources.list
 ---> Using cache
 ---> a0083629b9ec
Step 3/42 : RUN apt-get update && apt-get install -yq --no-install-recommends                build-essential                git                ninja-build                cmake                debhelper                   libass-dev                   libavcodec-dev                   libavdevice-dev                   libavfilter-dev                   libavformat-dev                   libavutil-dev                   libboost-chrono-dev                   libboost-coroutine-dev                   libboost-date-time-dev                   libboost-dev                    libboost-filesystem-dev                   libboost-locale-dev                   libboost-log-dev                   libboost-regex-dev                   libboost-thread-dev                   libbz2-dev                   libcrypto++-dev                   libfdk-aac-dev                   libfreeimage-dev                   libfreetype6-dev                   libgconf2-dev                   libglew-dev                   libglfw3-dev                   libgmp-dev                   libjpeg-dev                   liblzma-dev                   libmp3lame-dev                   libopenal-dev                   libopus-dev                   libpostproc-dev                   librtmp-dev                   libsfml-dev                   libsndfile1-dev                   libssl-dev                   libswresample-dev                   libswscale-dev                   libtbb-dev                   libtheora-dev                   libvpx-dev                   libwebp-dev                   libx264-dev                   libx265-dev                   libxcb-shm0-dev                   libxcursor-dev                   libxi-dev                   libxinerama-dev                   libxrandr-dev                   pkg-config                   ca-certificates                libnss3                libxcomposite1                libatk1.0-0                libatk-bridge2.0-0                libatspi2.0-0                txt2man
 ---> Using cache
 ---> d74ef304a88c
Step 4/42 : RUN update-ca-certificates
 ---> Using cache
 ---> ba4422419ea3
Step 5/42 : FROM builder as cef
 ---> ba4422419ea3
Step 6/42 : ARG PROC_COUNT=8
 ---> Using cache
 ---> 32f963b94eae
Step 7/42 : ADD https://cef-builds.spotifycdn.com/cef_binary_3.3578.1870.gc974488_linux64_minimal.tar.bz2 /opt/cef.tar.bz2
Downloading [==================================================>]  213.2MB/213.2MB
 ---> Using cache
 ---> 1d28ee641af9
Step 8/42 : WORKDIR /opt
 ---> Using cache
 ---> 7fa28e3f8246
Step 9/42 : COPY cef-patch /opt/cef-patch
 ---> Using cache
 ---> 4081a1737bdf
Step 10/42 : RUN tar -jxf cef.tar.bz2 && mv /opt/cef_binary_* /opt/cef
 ---> Using cache
 ---> 78f3b74cb890
Step 11/42 : RUN ls /opt/cef
 ---> Using cache
 ---> 153ee0a29fce
Step 12/42 : RUN cd /opt/cef;     patch -p 1 < /opt/cef-patch;
 ---> Using cache
 ---> c8b1dcb63cc7
Step 13/42 : RUN mkdir /opt/build
 ---> Using cache
 ---> 03da144b1581
Step 14/42 : WORKDIR /opt/build
 ---> Using cache
 ---> 2163fdae3a2c
Step 15/42 : RUN cmake /opt/cef && make -j $PROC_COUNT
 ---> Using cache
 ---> b1b7e865daaf
Step 16/42 : RUN cp /opt/build/libcef_dll_wrapper/libcef_dll_wrapper.a /opt/cef/Release/
 ---> Using cache
 ---> 9adb461000e0
Step 17/42 : RUN strip /opt/cef/Release/libcef.so
 ---> Using cache
 ---> c3258f8be0b0
Step 18/42 : FROM builder as casparcg
 ---> ba4422419ea3
Step 19/42 : ARG PROC_COUNT=8
 ---> Using cache
 ---> 32f963b94eae
Step 20/42 : COPY --from=cef /opt/cef /opt/cef
 ---> Using cache
 ---> 5c0d6c2ecffb
Step 21/42 : ADD https://api.github.com/repos/CasparCG/server/compare/master...HEAD /dev/null
Downloading  6.833kB
 ---> Using cache
 ---> c3b70911c961
Step 22/42 : RUN git clone https://github.com/CasparCG/server.git /server
 ---> Using cache
 ---> 5ac0af804883
Step 23/42 : WORKDIR /server
 ---> Using cache
 ---> d87cf5c3903c
Step 24/42 : RUN   git config --global user.email "bla@bla.com";   git config --global user.name "Bla Bla"
 ---> Using cache
 ---> 4d82c55aad9d
Step 25/42 : ADD https://github.com/CasparCG/server/pull/1308.diff /1308.patch
Downloading     924B
 ---> Using cache
 ---> e846a22787ab
Step 26/42 : RUN patch -p 1 < /1308.patch
 ---> Using cache
 ---> d9b96aa047c8
Step 27/42 : ADD https://github.com/CasparCG/server/pull/1397.diff /1397.patch
Downloading  1.291kB
 ---> Using cache
 ---> 3f2173037042
Step 28/42 : RUN patch -p 1 < /1397.patch
 ---> Running in 80853ca625ec
patching file src/common/except.h
Hunk #1 FAILED at 145.
1 out of 1 hunk FAILED -- saving rejects to file src/common/except.h.rej
patching file src/common/log.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/common/log.cpp.rej
The command '/bin/sh -c patch -p 1 < /1397.patch' returned a non-zero code: 1
