### ISSUE TITLE
Version 2.3 library update

### ISSUE THREAD

**Issue by ijuvia** [CasparCG/server#1422]
I changed the path in the config file for the media multiple times but it never reflects in the client no matter how many times I restart both server and client.

I even cleared the server connection from settings in client and reconnected again but it doesn't read the new path media still .. each time I would restart both server and client and refresh library but to no avail

this only happened with version 2.3

**Comment by dimitry-ishenko** [comment]
Are you running the [media-scanner](https://github.com/CasparCG/media-scanner)? It is needed for CasparCG Server 2.2 and up

**Comment by ijuvia** [comment]
> 

oh, thank you so much, it works now, but what is the logic behind the scanner, should i open it every time i open the server ?

**Comment by Julusian** [comment]
I think it was done as doing the scanning in c++ is complex and in the past has crashed casparcg on occasion.
By making it a separate process it becomes a lot simpler to implement and avoids the risk of crashing casparcg.

So yes, whenever you have the server running you should also run the scanner if you want the media listing to be up to date.
I personally recommend using https://github.com/nrkno/sofie-casparcg-launcher as it will launch both for you and minimise the number of console windows opened
