### ISSUE TITLE
HTML producer High GPU usage

### ISSUE THREAD

**Issue by sirfnomi** [CasparCG/server#1424]
### Current behavior

Is it normal for a static Hello World text HTML template to use approximately 20% GPU (NVIDIA Quadro K4000 3 GB) in 1080i5000 channel ?
----

### Steps to reproduce

```
<!DOCTYPE html>
<html>
<head>
    <style type="text/css">
        body{
            background: transparent;
            overflow: hidden;
        }
        #main {
            position: absolute;
            top: 50%;
            left: 40%;
            color: #fff;
            font-size: 4em;
        }
    </style>
    <script>function play(str){}function stop(){}function update(str){}</script>
</head>
<body>
    <div id="main">
        HELLO WORLD
    </div>
</body>
</html>
```

### Environment
* Commit: [master 2021-12-01 build]
* Server version: v2.3.3
* Operating system: Windows 10

---

**Comment by Julusian** [comment]
That gpu is rather old, so maybe?
Even though it is static, caspar is rendering at 50fps, and downloading the texture to be output to a decklink or wherever.
