### ISSUE TITLE
Exception thrown on server stop, when HTML producer is loaded (CCG 2.3.3)

### ISSUE THREAD

**Issue by leftearsons** [CasparCG/server#1425]
### Expected behaviour
When sending `q` or `bye` command to the server, we expect the server to uninitialize and stop smoothly, regardless of any loaded producers.

### Current behaviour
Currently, when an HTML producer is loaded at the time the exit command (`q` or `bye`) is received, CCG server is forcefully stopped and an error is thrown on exit (no "_Successfully shutdown CasparCG server_" & "_press any key to continue..._" messages are shown).
At the same time, a `backtrace.dump` file is created in casparcg root folder.
Once the server is restarted, the below error information is being shown on top of console logs:
```
 0# 0x00007FF67395B906 in casparcg
 1# 0x00007FF67396F080 in casparcg
 2# raise in ucrtbase
 3# abort in ucrtbase
 4# terminate in ucrtbase
```

----

### Steps to reproduce
1. Start CCG 2.3.3
2. Load an HTML producer (CG 1-1 ADD 1 "index" 1)
3. Send `q` or `bye` command 

### Environment
* Commit: https://github.com/CasparCG/server/commit/4de6d18f89d47fc03278dfb555c9338b6cf3ae57
* Server version: v2.3.3 LTS Stable (Mar 16, 2021)
* Operating system: Windows 10

---

**Comment by krzyc** [comment]
I get segfault on quit with active HTML template on 2.3.3 stable. Checked stable releases down to 2.3.0 - same effect.
Without producers server shuts ok. With color producer - ok. With ffmpeg playing - segfault.
I get segfault also when quitting with no producers and active NDI consumer (at least on 2.3.3).
I use custom build on Ubuntu 20.10.

**Comment by Julusian** [comment]
It sounds like this is the same issue as #1511, which is now fixed
