### ISSUE TITLE
Route producer throws exception when clearing source layer. All producers currently routed are killed

### ISSUE THREAD

**Issue by leftearsons** [CasparCG/server#1426]
### Expected behaviour
When using Route producer, the expected behaviour would be to stop routing frames from the source layer to the destination layer, once the source layer get cleared.
It is expected for the destination layer to keep showing the last frame that arrived from the source layer, until more frames start to arrive from the source layer.

### Current behaviour
Currently once the source layer gets cleared, an exception is thrown (as shown below), causing all Route producers to forcefully exit!
At the same time, all producers (`flash`, `html`, `ffmpeg` & `color`, have been tested) that were routed, also exit forcefully!
An important note is that all loaded producers exit, regardless of the source layer cleared.

```
[error]   Exception: No diagnostic information available.

[error]    0# 0x00007FF687B1A37E in casparcg
[error]    1# 0x00007FF687B19CAF in casparcg
[error]    2# 0x00007FF688055E1C in casparcg
[error]    3# 0x00007FFADDCE1030 in VCRUNTIME140
[error]    4# is_exception_typeof in VCRUNTIME140
[error]    5# RtlCaptureContext2 in ntdll
[error]    6# 0x00007FF687C55F54 in casparcg
[error]    7# 0x00007FF687C5C707 in casparcg
[error]    8# 0x00007FF687C5970A in casparcg
[error]    9# 0x00007FF687C02E52 in casparcg
[error]   10# 0x00007FF687BFF7E0 in casparcg
[error]   11# 0x00007FF687B150B9 in casparcg
[error]   12# configthreadlocale in ucrtbase
[error]   13# BaseThreadInitThunk in KERNEL32
[error]   14# RtlUserThreadStart in ntdll
```

----

### Steps to reproduce

The example below contains three different producers in order to make the problem more clear.

1. Initialize source layers for all producers, by both muting them and making them invisible
```
mixer 1-1 fill 0 0 0 0
mixer 1-2 fill 0 0 0 0
mixer 1-3 fill 0 0 0 0

mixer 1-1 volume 0
mixer 1-2 volume 0
mixer 1-3 volume 0
```

2. Initialize destination layers, just for the example in order to make them all visible
```
mixer 1-10 fill 0 0 0.5 0.5
mixer 1-11 fill 0.5 0 0.5 0.5
mixer 1-12 fill 0 0.5 0.5 0.5
```

3. Load source layers
load flash producer: ```cg 1-1 add 1 "flash_template" 1```
load html producer: ```cg 1-2 add 1 "html_template" 1```
load ffmpeg producer: ```play 1-3 "video_file" loop 1```

4. Load Route producers, by routing source layers to the destination ones
route flash producer layer: ```play 1-10 route://1-1```
route html producer layer: ```play 1-11 route://1-2```
route ffmpeg producer layer: ```play 1-12 route://1-3```

6. Clear one of the source layers by issueing one of the below commands:
```clear 1-1``` or ```clear 1-2``` or ```clear 1-3```
And notice both the exception thrown and how all producers in layers `1-1`, `1-2` and `1-3`, are all killed forcefully.

### Environment
* Commit: https://github.com/CasparCG/server/commit/4de6d18f89d47fc03278dfb555c9338b6cf3ae57
* Server version: v2.3.3 LTS Stable (Mar 16, 2021)
* Operating system: Windows 10

---

**Comment by Julusian** [comment]
Fixed in 97461c6c17fab0fa350bcf4f2289aa418670a70e
