### ISSUE TITLE
Ability to transmit OSC from Flash templates and OSC

### ISSUE THREAD

**Issue by phillipseamore** [CasparCG/server#143]
Feature request.

I've taken a quick look at the TemplateHost and saw that it communicates with CasparCG through ExternalInterface.  I would be interested in the option of sending messages out to OSC from Flash templates using ExternalInterface.  See potential for simple things like a recurring ping to make sure the template is running or to give status of a multifunctional template with different states.

This might also be expanded to an option of sending OSC messages through the AMCP (and open it up more as a messaging system for all the different producers).

I also miss OSC TCP from 2.1 as Flash can only connect over TCP (unless you use another program as a UDP->TCP bridge).

**Comment by TomKaltz** [comment]
#633

**Comment by jesperstarkar** [comment]
Gotta love the *3 years later* aspect here. Good work Thomas.

**Comment by TomKaltz** [comment]
I never knew about TraceToLog in the template host. I stumbled upon it and then realized the server change (hack) would be pretty easy.  Thankfully it worked!  I haven't tested parsing out the xml response in node yet but seems like it will be straightforward enough.
