### ISSUE TITLE
Temporary build download links

### ISSUE THREAD

**Issue by Julusian** [CasparCG/server#1439]
Until the build scripts are fixed, the automated builds are broken.
As I merge changes I shall try and remember to produce new builds which shall be added here

6bb06aa7cb2c409dff4ba4978c979c29a09c8034 https://builds.julusian.dev/casparcg/casparcg-server-v2.3.x-6bb06aa7-20220907.zip
abc35821b797bbcc9cfedabf396fd2e2ef5c9b8c https://builds.julusian.dev/casparcg/casparcg-server-v2.3.x-abc35821-20220913.zip

**Comment by hreinnbeck** [comment]
@wouterDevelop  It's not the build, you are missing the latest MS Visual C++ redistributable. Try https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Julusian** [comment]
Yes, the builds now require vs2019 runtime to run.

Builds are now being produced by github actions, so this issue is no longer necessary
