### ISSUE TITLE
MXF Multichannel Audio Routing

### ISSUE THREAD

**Issue by premultiply** [CasparCG/server#144]
I tried the new multichannel feature with some broadcast MXF files (XDCAM HD and AVC Intra 100).
Most of these files have a channel layout of 8 x 1 (mono) channel. This should be mapped to the output channels 1 to 8 (in this case).
The last build of 2.0.4 does only output 1 mono channel in that case. Normal MPEG2 clips with single stereo audio track are fine.
The output channel configuration in my config file is set to "passthru".

When the mode in config file is set to "stereo" the first mono channel will output (copied) on channel 1 and 2.

Is this a internal problem or how can this be fixed by configuration options?

I can provide demo files for this but they are large...

**Comment by keenanhuda** [comment]
did anyone has solve this problems, we have the same problems with separating 2 mono channel mxf op1a build by mediacomposer using avid interplay transfer

**Comment by jesperstarkar** [comment]
This bug is alive and real. 
1) A single stream/track with multiple channels gets mapped correctly and the channel_layout routing works as expected.
2) The problem is, like mentioned above, if you have multiple streams with just one mono channel in each, typical MXF wrappers of XDCam or similar broadcast standards.

**Comment by premultiply** [comment]
Maybe have a look at the code of the melted Playoutserver (part of MLT Framework).
https://github.com/mltframework
This audio mapping problem is solved there as expected: All input channels are mapped as output channels regardless of the input track one by one.

**Comment by ronag** [comment]
2.2

**Comment by maxmuzy** [comment]
Hello everyone! Sorry to revive such an old topic, but I couldn't find a way to perform this audio mapping. Can someone help me? I want to record an MXF clip with 8 mono audio streams and not 1 stream with 8 audio channels. What should the configuration file look like or what command should be used?
