### ISSUE TITLE
HTML Page

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/server#1443]
### Expected behaviour
`PLAY 1-10 [HTML] "https://svt.se" ` should show the webpage from https://svt.se

### Current behaviour
`PLAY OK`   Nothing shows up!

----

### Steps to reproduce
1. `PLAY 1-10 [HTML] "https://svt.se" CUT 0 Linear RIGHT`

### Environment
* Commit: From https://builds.julusian.dev/casparcg/ 
* Server version: https://builds.julusian.dev/casparcg/casparcg-server-v2.3.x-custom-resolutions.zip
* Operating system: Windows 11 Home

---

**Comment by 5opr4ni** [comment]
Sorry for this, but it showed up some time later, but leaves it here if there is an issue anyway!

/Olle

**Comment by 5opr4ni** [comment]
Strange!!! Now there seems to be no problem. My fault then!!! SORRY!!!!!
You can close then ;)

**Comment by baltedewit** [comment]
Is this reproducible by loading that page as the first HTML producer when you start the server? I've seen behaviour before where the first cef instance could take ~10 seconds to start up.
