### ISSUE TITLE
Where to find CG Server Release 2.3.3 LTS 

### ISSUE THREAD

**Issue by zalaudekr** [CasparCG/server#1447]
Hi,

where do I find the casparcg-server-v2.3.3-lts-stable Windows build? On Release Page the download of V2.3.3 LTS says it's "Server 2.3.2 4de6d18f Dev" when starting and not the 2.3.3 LTS

Thanks for Info

Regards
Raimund

**Comment by Bohoaush** [comment]
Hi, 
I think you have the 2.3.3LTS, because there is no commit between https://github.com/CasparCG/server/commit/4de6d18f89d47fc03278dfb555c9338b6cf3ae57 and the release of 2.3.3.

**Comment by Julusian** [comment]
As I said in #1430 

> Yeah this is annoying but as long as the git hash matches it is fine.
> Im not going to change the build zip now, as it will probably break some autodeploy tools in use which will be verifying the checksum of that zip
