### ISSUE TITLE
NO TRANSPARENCY PLAYING IMAGE WITH A FULL PATH 

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#1455]
### Expected behaviour
images with transparent background should show the transparent background when played with the full path
### Current behaviour
Images with transparent background when played with the full path, shows an opaque (white) background. Playing from the media folder with the short syntax shows the image correctly.
----

### Steps to reproduce
1.  Play any image file that has a transparent background with the full path eg:  PLAY 1-0 "c://images/scene.png"
2.
3. ...

### Environment
* Commit: latest
* Server version: 2.3.3
* Operating system: Windows 11

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by vimlesh1975** [comment]
I tested this issue on server build 07.12.22.
I fiound this problem is not there. And working fine as it should.

**Comment by PeterAkakpo** [comment]
![onscreen](https://user-images.githubusercontent.com/7926382/209971610-368ceaff-32c7-4444-8a8c-37b061a63af3.png)
Please try with this image

**Comment by Julusian** [comment]
fixed!
the ffmpeg and image producers now use the same fuzzy file matching logic.

I found it was also possible to reproduce this by trying to play a file in the media folder called `test.png` with `PLAY 1-10 TEST`
