### ISSUE TITLE
SCREEN IS DESTROYED AFTER PRINT

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#1456]
### Expected behaviour
When a screen is added via the command line  (with the ADD command) and PRINT is issued, the screen should not be destroyed

### Current behaviour
Issuing PRINT after a screen is created from the command line with the ADD command, the screen is destroyed. But if the screen is created in the config file, everything works fine.

----

### Steps to reproduce
1. ADD 1-100 SCREEN 0
2. PRINT 1
3. ...

### Environment
* Commit: latest
* Server version: 2.3.3
* Operating system: Windows 11 Home

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by Julusian** [comment]
This is happening because you added your screen consumer with an 'index'/id of 100, which is the same as what `PRINT` uses.

I don't fully know what the consumer index is used for, so I don't know if this can be improved easily. But the easy solution for you is to not give the screen an id of 100

**Comment by PeterAkakpo** [comment]
confirmed, thanks
