### ISSUE TITLE
memory leak when using mixer fill command on a decklink consumer.

### ISSUE THREAD

**Issue by ben1979** [CasparCG/server#147]
when we use mixer fill command with a decklink producer the ram used memory is not completely restored. In fact, we see a average of 13MB leak.

First, start the server: the process = 225MB
play 1-3 decklink device 4 = 363MB
202 PLAY OK
stop 1-3 =230MB
202 STOP OK
play 1-3 decklink device 4 = 363MB
202 PLAY OK
stop 1-3 =230MB (We consider that's negligeable)
202 STOP OK
play 1-3 decklink device 4 =363MB
202 PLAY OK
mixer 1-3 fill 0 0 0.5 0.5 =390MB
202 MIXER OK
mixer 1-3 clear =377MB (and not 363 anymore)
202 MIXER OK 
mixer 1-3 fill 0 0 0.5 0.5 =402MB
202 MIXER OK
mixer 1-3 fill 0 0 1 1 =390MB (and not 363 anymore)
202 MIXER OK
mixer 1-3 clear =390MB
202 MIXER OK
mixer 1-3 fill 0 0 0.2 0.2 =413MB
202 MIXER OK
mixer 1-3 fill 0 0 1 1 =402MB
202 MIXER OK
mixer 1-3 fill 0 0 0.2 0.2 =427MB
202 MIXER OK
mixer 1-3 fill 0 0 1 1 =414MB
202 MIXER OK
mixer 1-3 fill 0 0 0.2 0.2 =439MB
202 MIXER OK
mixer 1-3 fill 0 0 1 1 =427MB
202 MIXER OK
mixer 1-3 fill 0 0 0.2 0.2 =451MB
202 MIXER OK
mixer 1-3 fill 0 0 1 1 =439MB
202 MIXER OK

So with 6 "mixer fill" operations the memory used increases by more or less 70MB.
When we do the same operations on a clip, in place of a input SDI, the memory is stable.

What do you think about it?

The same behavior with 2.0.3.f845d1f STABLE

**Comment by ronag** [comment]
2.2
