### ISSUE TITLE
Poor HTML Webm performance (2.4 build)

### ISSUE THREAD

**Issue by Sidonai-1** [CasparCG/server#1475]
When using 2.4 build with CEF 90 (2023-04-19 13:48) in Windows, HTML templates that have Webm videos don't play smoothly most of the time.
Also, when we concatenate one Webm with the next one (video IN and then calling video OUT for example), there is 1-2 empty frames in the middle about 70% of the times, but not every time, which is weird.

The same templates in the same machine work just fine on 2.3.3 release version, with CEF 71.

I do not have animated templates without Webm videos, so I cannot say if this is a problem specific to Webm or it happens with all types of HTML template animations.

The videos are encoded in VP9 4:2:0 with alpha, Quality 80-100

It should not be PC-performance related, I have tested it in very different hardware configurations with the same result.

I've tested both with "GPU enable" true and false in the config, no difference.
Also tried 1080i50 and 1080p50 with similar results.

Thanks!

**Comment by Julusian** [comment]
Does this behave any better with CEF117?

**Comment by Sidonai-1** [comment]
Yes, I have tested the pre-release 2.4.0 Beta 1 and it is working as it should.

Thank you.
