### ISSUE TITLE
Template name reference is lost from INFO, DIAG and OSC

### ISSUE THREAD

**Issue by hreinnbeck** [CasparCG/Server#149]
Somewhere from AMCP parsing to Flash execution, reference to the template name gets lost.

INFO, DIAG and also OSC messages alway return the templatehost name (i.e. cg20.fth.1080i5000) instead of the template name.

I've looked over the code but can't seem to find where the reference is lost.

**Comment by visualUniverse** [comment]
Having the same issue with server version "2.0.7.e9fc25a Stable".
Always get the templatehost returned by osc:
/channel/1/stage/layer/1/host/path --- C:\CasparCG\CasparCG Server207\Server\templates\\cg20.fth.1080i5000

**Comment by ronag** [comment]
Not a bug. The "host/path" should be the template host.

**Comment by visualUniverse** [comment]
OK, thanks for the information. In the Wiki it says should be returning the .ft filename.
