### ISSUE TITLE
Segfault when loading html5test.com

### ISSUE THREAD

**Issue by aDifferentJT** [CasparCG/server#1492]
### Expected behaviour
The page to load

### Current behaviour
Segfault

----

### Steps to reproduce
1. PLAY 1-10 [HTML] "html5test.com"

### Environment
* Commit: b76d4e0
* Server version: master
* Operating system: Linux, running within docker

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by Julusian** [comment]
What command did you use to launch the docker container?
Does it work when not running in docker?

**Comment by Julusian** [comment]
As there aren't more reports of this, it sounds like something specific to your environemnt
