### ISSUE TITLE
casparcg server not starting (no logs, don't ask for it)

### ISSUE THREAD

**Issue by TemaisgameNoobas** [CasparCG/server#1494]
### Expected behaviour
expected it to launch

### Current behaviour
A clear and concise description of what the current behaviour is.
does not launch without logs
----

### Steps to reproduce
1. just run casparcg

### Environment
* Commit: i don't know
* Server version: latest build from builds.casparcg.com
* Operating system: ubuntu 22.04

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by Bohoaush** [comment]
Hi, this also happened to me on some devices. Try running the casparcg in bin directory directly, not through the run.sh. It will probably write that libnettle7 library is missing. The solution to that would be to build CasparCG manually, or use https://github.com/Bohoaush/docker_build_caspar_Ub23 dockerfile I've made.

**Comment by TemaisgameNoobas** [comment]
@Bohoaush nope, libnettle7 is not missing.

**Comment by TemaisgameNoobas** [comment]
@Bohoaush thank you, it works!!
