### ISSUE TITLE
COMMIT COMMAND DOESN'T CLEAR DEFER ON CHANNEL 2

### ISSUE THREAD

**Issue by fillandkey** [CasparCG/server#1505]
After I execute a COMMIT command for execute more animations, i have the same animations again if i resend COMMIT command.

The command doesn't clear the DEFER in the animations executed.

**_This was corrected for channel 1 but not for channel 2 or  above_**

**Comment by Julusian** [comment]
This was another dumb error in the implementation, I am surprised that channel 1 didn't fall into the same bug..

Fixed in the next build (d84a8b4)
