### ISSUE TITLE
Again - Macos version

### ISSUE THREAD

**Issue by Behinder** [CasparCG/server#1507]
As previously someone mentioned there was more download client for Macos than Linux. Also someone previously started effort to port into Metal but then resigned after realising that Apple dropped support also for Vulcan that is compatibility layer transforming OpenGL to Metal.

However, I read that OpenGL is still supported but marked "deprecated"  and if Vulcan is not supported on MacOS then what this really is https://vulkan.lunarg.com/doc/sdk/1.3.268.1/mac/getting_started.html ????

Anyway I have now new machine (unfortunately M chip not Intel) so I could help if someone gives me some guidance.

**Comment by Julusian** [comment]
There is a macos github issue still open, discussion should continue there #428

**Comment by Behinder** [comment]
You must be kidding - open source software done for community and you dare
to say "not planned"? If you are lazy maybe don't make decision for the
others?

wt., 21 lis 2023 o 01:52 Julian Waller ***@***.***>
napisał(a):

**Comment by mint-dewit** [comment]
@Behinder apologies for the miscommunication. It's fine if anyone is willing to pick this up and it can be done in a manner such that the current maintainers can keep maintaining it _or_ if that contributor is willing to maintain it. If that is the case, they can use the previously linked issue for discussion. We prefer not to have duplicate issues, that's definitely one reason for this issue to be closed.

I know Julian is not lazy so I think he either misclicked and wanted to close as a duplicate or wanted to communicate that this is not planned to be done by any of the current maintainers.

I hope this clarifies the situation :)
