### ISSUE TITLE
Debugging connection closes.

### ISSUE THREAD

**Issue by vimlesh1975** [CasparCG/server#1512]
### Expected behaviour
Debugging connection should not close..

### Current behaviour
Debugging connection closes.

----

### Steps to reproduce
play a html template.
open a ormal broswer http://localhost:1024/

### Environment
 Server version: 2.4 dated 27 november
 Operating system:  Windows 11

---

### Screenshots
![image](https://github.com/CasparCG/server/assets/4338487/6430cb1d-ce53-499e-a9eb-725044a2f145)

**Comment by Julusian** [comment]
This is fixed in the next build.
As a workaround in older builds, it might work to run caspar with the argument `--remote-allow-origins=*`
