### ISSUE TITLE
NDI OUTPUT

### ISSUE THREAD

**Issue by quasir114** [CasparCG/server#1516]
I just installed Caspar Server 2.3.3 with cliend 2.0.8. It is working fine. 

I need to take its output on NDI. Need your help in this regard. 

Secondly, I want to integrate RSS Feeds. Please guide for this as well.

**Comment by 5opr4ni** [comment]
Install NDI tools on casparcg from ndi.video
In casparconfig add ndi to consumersection for the channel.
            <ndi>
                <name>channel_one</name>
                <allow-fields>false</allow-fields>
            </ndi>

You can see in the config-file in the comment section, things you can do.

Regarding RSS i think this is the wrong place to ask that. 
Go to https://casparcgforum.org
and ask for help.
