### ISSUE TITLE
OSC don't reach the Client anymore

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/server#1521]
### Observed Behavior

OSC seems to have some issues in this release. for example, the Client don't get the OSC's for current clip time it seems like. 

### Expected behaviour

Worked in the December builds.

### Steps to reproduce

Start CasparCG, connect with Client

### Environment

* Commit: casparcg-server-35ffe5268748877b30ec420320c0715efa22de8e-windows
* Server version: v2.4
* Operating system: Windows 11

**Comment by 5opr4ni** [comment]
?

**Comment by Julusian** [comment]
I believe this is a bug in the client and is fixed by https://github.com/CasparCG/client/commit/6d74aa37a2c01eee3f909fbf1db79ad9a3ce5199
