### ISSUE TITLE
Bug: [Unable to play files with extra dots in filenames]

### ISSUE THREAD

**Issue by nrgcreative** [CasparCG/server#1524]
### Observed Behavior

I'm using ACMP command like LOAD BG"Abc Feat. Cdf".
I tried all charachters and its worked. Except dot. if there is more that one dot in the filename its given 404 error, file not found.

### Expected behaviour

work like earlier versions.

### Steps to reproduce

1.
2.
3. ...

### Environment

* Commit: [FF149ACF4D0FA3CB]
* Server version: [e.g. v2.4.0rc1]
* Operating system: [Windows 10]

**Comment by Julusian** [comment]
fixed by 97c409ff9c6c539703e02b9ff5516c20e31be703

**Comment by nrgcreative** [comment]
I tried it and its not working.

**Comment by Julusian** [comment]
Oh, the fix has been made since 2.4.0rc1, you will need to use a beta build or wait for 2.4.0 stable

**Comment by nrgcreative** [comment]
I tried 2.4.0rc1, but that one is not working,  this is what I'm saying..
