### ISSUE TITLE
Bug: Mono wav file plays out of channel 3

### ISSUE THREAD

**Issue by Julusian** [CasparCG/server#1527]
### Observed Behavior

Since 2.4.0 RC1, a mono wav file will play out on sdi channel 3. This looks to be the center channel in a 5.1/7.1 setup

This is not the case in 2.4.0 Beta1.

### Expected behaviour

A mono wav file should play out of channel 1 (or both 1 and 2?). Check previous versions to determine exact expected behaviour

### Steps to reproduce

1.
2.
3. ...

### Environment

* Commit: 2.4.0-RC1
* Server version:  2.4.0-RC1
* Operating system: Ubuntu 22.04

**Comment by 4l4R1** [comment]
Maybe related.
Strange things happened when using the FFmpeg PAN filter

2.4.0.RC1
Playing stereo file with sound in 1 channel 
filter: AF "pan=8c|c0=c0|c1=c1|c2=c0|c3=c1|c4=c0|c5=c1|c6=c0|c7=c1"
audio from channel 1 plays to channels 1, 3, 4, 7
audio from channel 2 plays to channels 2, 5, 8

**Comment by Julusian** [comment]
I believe this is fixed now. By telling ffmpeg we accept any number of audio channels up to 16, it appears to have stopped attempting to remap/downmix/upmix the audio for us
