### ISSUE TITLE
Bug: Server is not playing Mp4 video in HTML video tag

### ISSUE THREAD

**Issue by sirfnomi** [CasparCG/server#1551]
### Observed Behavior

casparcg server is not playing mp4 video in HTML video tag, tested it in chrome it is playing fine.

```
<!DOCTYPE html>
<html>
<head>
  <title>testmp4</title>
</head>
<body style="overflow: hidden;">
  <div style="font-size: 36px; color: red;">MP4 TEST</div>
  <video src="https://www.w3schools.com/tags/movie.mp4" style="position: relative; top: 0; left: 0; width: 400px; height: 300px; " controls autoplay loop muted></video>
</body>
</html> 

```

### Expected behaviour

It should play as it is on chrome

### Steps to reproduce

Steps ...

### Environment

* Commit: [Dev build 03-06-2024]
* Server version: [v2.4.x]
* Operating system: [Windows 10]

**Comment by Julusian** [comment]
See #350 for more discussion on this
