### ISSUE TITLE
Bug: Input Signal is stretched (2ffc202)

### ISSUE THREAD

**Issue by Sidonai-1** [CasparCG/server#1563]
### Observed Behavior

2.5 2ffc202 introduced a bug regarding input signals. Input signal shows the correct height but double the width.

Channel format is 1080i50
Input signal is 1080i50

![_18_9_2024_14_6_3](https://github.com/user-attachments/assets/e79819c0-33ce-4e99-ac3d-b23c7a88ee65)

![_18_9_2024_14_6_32](https://github.com/user-attachments/assets/20b1bf97-5498-40c8-bd24-a90363aa6ca8)

`PLAY 1-20 DECKLINK 1 `  works normally in the previous build (d3af0b0) as well as the 2.4.x builds.

I guess it has to do with the higher pixel precision feature.

### Environment

* Commit: 2ffc202
* Server version: 2.5
* Operating system: Windows 10
* Driver Version: 14.0.1

**Comment by Julusian** [comment]
Sounds like the same issue as #1542?

**Comment by Sidonai-1** [comment]
> I'll have a look at it this week

Just in case it's related to your latest commit: latest 2.5 build d37b9d0 from the 27th is not able to play a decklink, it throws an error.
