### ISSUE TITLE
Added mixer transitions will override the time of active tra

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#16]
Converted from [SourceForge issue 3560198](http://sourceforge.net/support/tracker.php?aid=3560198), submitted by zebiolo

Transitions need to be stacked.

**Comment by ronag** [comment]
Could someone please try to reproduce on 2.2?

**Comment by jesperstarkar** [comment]
#668?

**Comment by ronag** [comment]
duplicate
