### ISSUE TITLE
video is recorded incorrectly

### ISSUE THREAD

**Issue by gk1** [CasparCG/server#180]
Windows 7 ultimate 64
intel i7 2.93ghz cpu
16g ram
flash 10.3.181.14
casparcg 2.0.4.f27a404 beta 1

I am trying to record video via decklink quad. I have two consumers chan 1 and 2.
inputs are ports 3 and 4 on decklink being feed with NTSC D1 720x486 29.97 video feeds that are also being uplinked to satellite.
I issue the following commands:
PLAY 1-10 DECKLINK 3
ADD 1 FILE ntv.mov -vcodec qtrle -b 5000000
later:
REMOVE 1 FILE ntv.mov

Attempt to play back:
PLAY 1-10 ntv.mov

video is seemingly playing back at between 1 and 2x normal speed.
I can also open the files via vlc and observe the same behaviour. 

I also have a forum post concerning this: http://casparcg.com/forum/viewtopic.php?f=9&t=1721

The recorded file is huge approx 20gb so i can not upload it anywhere, but i can make it available on the machine via teamviewer if required.

**Comment by ronag** [comment]
2.2
