### ISSUE TITLE
Seeking issue in 2.0.3/2.0.4/2.1.0

### ISSUE THREAD

**Issue by DevChameleon** [CasparCG/server#193]
Discussion: http://casparcg.com/forum/viewtopic.php?f=3&t=1751&p=11613#p11613

Seeking does not work for various formats(tested on MP4, MXF and MOV). Actual seeked frame number is not correct due to integer(int32_t in code) overflowed in calculation.

Suggest changing data type to int64_t or changing the order of calculation to avoid overflow before division.

This is my fix:
int64_t fixed_target = target \* (stream->time_base.den \* codec->time_base.num \* codec->ticks_per_frame / (stream->time_base.num \* codec->time_base.den));
...
THROW_ON_ERROR2(avformat_seek_file(format_context_.get(), default_stream_index_, std::numeric_limits<int64_t>::min(), fixed_target, std::numeric_limits<int64_t>::max(), flags), print());

I used AVSEEK_FLAG_FRAME as seeking flag because it provides better seeking results in my situation.

**Comment by Julusian** [comment]
@dotarmin I suspect this is resolved by the ffmpeg rewrite

**Comment by dotarmin** [comment]
I will close this issue for now, if you experience same issues we can reopen the issue.
