### ISSUE TITLE
"JavaScript error(s) occurred " Bug on Template Generation

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/Server#20]
Converted from [SourceForge issue 3560692](http://sourceforge.net/support/tracker.php?aid=3560692), submitted by None

On attempting to generate a template the error "The following JavaScript error(s) occurred" appears in the Flash Console.

After this occurs no more templates can be generated until Flash is closed and reopened.

It didn't happen to begin with, but now happens on every first generation.

Mac OS X 10.8
Flash CS6
Caspar Template Generator 2.0.0

[code]||Generating CasparCG Flash template, version 2.0.0||

 +-----------------------------------------------------

 +Verbose tracing is activated (+), this can be turned off in the Settings tab.

 +Scanning the main timeline for keyframes with labels...

 +Scanning elements...

 +Scanning elements...

 +Scanning elements...

 +Scanning elements...

 +Scanning elements...

 +Scanning elements...

 +Scanning the library for movie clips and bitmaps...

 + >Found a movie clip, scan it's timeline...

 +Scanning a timeline for caspar components...

 +Scanning elements...

 + >Found a movie clip, scan it's timeline...

 +Scanning a timeline for caspar components...

 +Scanning elements...

 + >Found a movie clip, scan it's timeline...

 +Scanning a timeline for caspar components...

 +Scanning elements...

 + >Found a movie clip, scan it's timeline...

 +Scanning a timeline for caspar components...

 +Scanning elements...

 + >Found a movie clip, scan it's timeline...

 +Scanning a timeline for caspar components...

 +Scanning elements...

 + >Found a movie clip, scan it's timeline...

 +Scanning a timeline for caspar components...
The following JavaScript error(s) occurred:

The following JavaScript error(s) occurred:[/code]

Flash Console Log file also attached

**Comment by jesperstarkar** [comment]
This is old. Should be closed.
