### ISSUE TITLE
Devise strategy to move/rename the 2.1 branch as master

### ISSUE THREAD

**Issue by TomKaltz** [CasparCG/server#206]
Wanted to start a discussion regarding moving the 2.1 branch to master.  Wondering how it should be handled.  The 2.1.0 branch is vastly different than master.  Should we create a "2.0" branch at "master" HEAD then merge the master branch into "2.1.0" branch HEAD?

Also, I think we should keep minor version numbers out of branch names and use git tags for minor releases numbers.

What does everyone think?

**Comment by TomKaltz** [comment]
@HellGore should we change the default branch for github to "2.1.0" to signify that's where new work is and should be done?

**Comment by cambell-prince** [comment]
Something [like this](http://stackoverflow.com/questions/173919/is-there-a-theirs-version-of-git-merge-s-ours) should do the trick.  IMHO In and open source project with active contributions I think it better to have the main line of development continually being merged into master.  Otherwise the 'develop' branch (like 2.1.x in this case) can get stale very easily.

	# in case master is not our current branch
	git checkout master

	# make merge commit but without conflicts!!
	# the contents of 'ours' will be discarded later
	git merge -s ours 2.1.0    

	# make temporary branch to merged commit
	git branch branchTEMP         

	# get contents of working tree and index to the one of 2.1.0
	git reset --hard 2.1.0

	# reset to our merged commit but 
	# keep contents of working tree and index
	git reset --soft branchTEMP

	# change the contents of the merged commit
	# with the contents of 2.1.0
	git commit --amend

	# get rid off our temporary branch
	git branch -D branchTEMP

	# verify that the merge commit contains only contents of 2.1.0
	git diff HEAD 2.1.0

**Comment by krzyc** [comment]
I agree that we should move 2.1 branch to master, as development of 2.0 is as far as I know ended and probably there will only be bug fixes. I agree with cambell-prince that keeping 2.0 as master can have bad impact on development, as it suggests that 2.0 is actively developed.

**Comment by cambell-prince** [comment]
You can make a 2.0.x branch if there are any bug fixes required on a 2.0.x
stabilization branch should such fixes be created.

**Comment by TomKaltz** [comment]
It's pretty destructive to cross-merge.  Why not just make a not for
developers in the README about which branch is relevant and also notify on
proper channels (forum, mailing-list, facebook)?

**Comment by HellGore** [comment]
I am not sure that now is the right time to make the switch. I agree that it should be done soon. At this point I'm doing a lot of refactoring in 2.1.0, and I feel that it would be better for contributors if the codebase they are targeting is stable with regards to the API.
