### ISSUE TITLE
Audio/Video Sync Issue When Using MIXER With DeckLink Input

### ISSUE THREAD

**Issue by intellibloke** [CasparCG/server#212]
We have a recommended spec system with 2 Decklink 4k Extreme cards. Format is PAL and audio is SDI embedded.  The system is downstream of the mixer and is using Mixer functions for squeezeback of the live video as well as overlaying graphics.

By the end of a 2 1/2 hour show we have had to add approximately 26 frames of audio delay to maintain lip sync.

We have optimised all templates to the point where diagnostics shows no strange peaks. 
![2013-11-20 19 45 33](https://f.cloud.github.com/assets/4385315/1587532/ee3d07e2-523a-11e3-94ca-55cea83cfc07.jpg)

As I see it there are 2 issues:
1. Despite embedded audio sync is being lost with the video
2. ~1/2 a second of drift per hour of show is quite significant

Whilst I haven't been able to pinpoint the cause I have observed that merely playing the live video/audio through CasparCG does not (seem to) cause any delays or sync issues to occur.

Nick

**Comment by ronag** [comment]
2.2
