### ISSUE TITLE
TLF Text causes CasparCG template not to load

### ISSUE THREAD

**Issue by jmwebslave** [CasparCG/Server#218]
I have performed some testing last night and found that the inclusion of any TLF Text Fields in a CasparCG template (whether prefixed with 'x' or not) cause CasparCG to be unable to play the resulting template.

I have observed this issue on Windows 7 x64 running CasparCG 2.0.4 with TemplateGenerator 2.0.1b (latest I believe).

The template appears to compile perfectly fine.  Interestingly enough, exporting the movie as an swf and then attempting to play it back as media in CasparCG also doesn't work if there's a TLF Text Field in the file.

You can test this issue by creating a new .fla and placing a single TLF Text Field on the stage with text on it and then generating a template.  You should find that the resulting template will never display through CasparCG.

It would be lovely if TLF Text Fields 'worked' (insofar as the template will still display if one is there - even if the TLF Text Field isn't considered a text field by the template generator), as they allow you to do quite a few things that the standard text fields don't.

**Comment by jesperstarkar** [comment]
This should be close.

It's not a bug in CasparCG.
