### ISSUE TITLE
WebSocket support or Javascript bridge from HTML producer

### ISSUE THREAD

**Issue by hreinnbeck** [CasparCG/server#225]
With the possibility of adding Robert Nagy/VRT's Chromium/Berkelium HTML producer to CCG it would be of great benefit to implement either:
- A reverse Javascript bridge from the HTML producer back to CCG
- Adding a WebSocket server to the protocol stack of CCG (for instance http://libwebsockets.org/)
  This would also enable building WebSocket based clients for controling CCG where many have been using gateway solutions to move to and from AMCP over telnet.

**Comment by jesperstarkar** [comment]
I REALLY would like to se a websocket connection for AMCP in 2.1 in addition to regular TCP socket.

**Comment by ronag** [comment]
https://github.com/zaphoyd/websocketpp

**Comment by ronag** [comment]
https://github.com/CasparCG/server/issues/688
