### ISSUE TITLE
Filename with extension

### ISSUE THREAD

**Issue by vimlesh1975** [CasparCG/server#226]
Latest build of casparcg server (2.0.6) dated 27th November 2013 can play media file when giving command with file extension.
[code]play 1-1 amb.mp4[/code]
But CLS command is not giving files with extension. Is it there or can it be done?

**Comment by mcdikki** [comment]
There are still problems here.
We need to harden the way ccg works with files and extensions.
The situation now (2.0.7 Stable) is that the media folder can contain files of the same name but different extension.
This leads to the situation, that you can't work with this files on clients which only uses CLS to retrieve a list of media as it doesn't give any extensions.
You can test it with the Testpattern media shipped with 2.0.7 stable where you find i.e. PAL_test as tga and mov. file.

My suggestion is to either consistently use extensions (which really should be the easiest way) or change the way load/loadbg/play etc. are using media.
We could add a something like a protocol marker:
```play 1-1 [STIL] PAL_test``` 
```play 1-1 [MOVIE] PAL_test``` 
```play 1-1 [HTML] PAL_test```
```play 1-1 [AUDIO] PAL_test```  

But I would prefer using extension all over in ccg.
