### ISSUE TITLE
Feature requst Audio timer/counter

### ISSUE THREAD

**Issue by markusnygard** [CasparCG/server#230]
Hi.
Would love a feature where I can see how much time is remaing for audio-files the same way as I see for video-files. 
Best Markus

**Comment by premultiply** [comment]
Is that fixed in 2.2 with new FFMPEG producer?

**Comment by ronag** [comment]
@premultiply I believe so.

**Comment by markusnygard** [comment]
Thank you with great respect for everyone who is putting their time into developing this great software.
br markus
