### ISSUE TITLE
Chroma Key Bright White/Yellow Being Keyed

### ISSUE THREAD

**Issue by SonicAcademy** [CasparCG/server#232]
When using CHROMA we are getting bright white/Yellow spots being keyed out.

Bright spots on teeth, metal zips, eyes etc some bright clothing.

![full key](https://f.cloud.github.com/assets/6419259/1930162/ed47266e-7ea5-11e3-9eaa-6ea5188c3ba9.png)
![keying teeth 1](https://f.cloud.github.com/assets/6419259/1930163/ed49ee62-7ea5-11e3-9970-8d49925e4d8d.png)
![keying teeth 3](https://f.cloud.github.com/assets/6419259/1930164/ed4c4540-7ea5-11e3-8475-ca7f6dff5c32.png)
![keying teeth 2](https://f.cloud.github.com/assets/6419259/1930165/ed4d59b2-7ea5-11e3-9277-0bdec4a1aa7b.png)
![Uploading Keying Teeth 4.png . . .]()

**Comment by Julusian** [comment]
This is missing details needed to be able to reproduce/fix this
