### ISSUE TITLE
HTML Producer - show browser window

### ISSUE THREAD

**Issue by hreinnbeck** [CasparCG/server#233]
I'd like to see if it's possible to add a command option to actually open the Berkelium browser window.

Two benefits:
- Enable interaction with the webpage (scroll, click etc.) so a website could be shown on-air
- Enable using the console for debugging (like I'm trying to debug why websockets don't work when run in Berkelium through CCG, but work when Berkelium is run standalone).

**Comment by Julusian** [comment]
Screen consumer will pass mouse interaction through to the html producer and remote dev tools is possible, so this can now be done.
@dotarmin
