### ISSUE TITLE
Inconsistent channel numbers in AMCP INFO command

### ISSUE THREAD

**Issue by jaccovanschaik** [CasparCG/server#235]
The AMCP command "INFO 1" gives me information about the first channel, with channel index 0 in the reply. The command "INFO SERVER" gives me information on all channels, but in this case the index of the first channel is 1.

I would expect the same channel numbers in the command and in the returned data. At the very least, I would expect the channel numbers between the "INFO 1" and "INFO SERVER" commands to be consistent.

CasparCG server version 2.0.6.fb579b2 Stable

**Comment by ronag** [comment]
info is deprecated
