### ISSUE TITLE
Problem with ProRes recording (Server 2.0.6)

### ISSUE THREAD

**Issue by EmileCervia** [CasparCG/server#238]
I want to use CasparCG to record video from a MiniRecorder Blackmagic card. In DNxHD I have no problem. ProRes recorded video using CasparCG are played too fast, I tried to play videos with VLC and Premiere Pro. The same recording time is almost four times lower in ProRes in weight and length compared to a DNxHD file.

I use CasparCG Server 2.0.6

My recording writiing speed is 184MB/s (test with blackmagic disk speed test).
I looked at the CPU usage, the processor is used at 26%.

I have post in the forum : 
http://casparcg.com/forum/viewtopic.php?f=9&t=1936

I have a log file and sreenshots : 
http://emylio.free.fr/CasparCG/

My PC : i7 à 3.06GhZ, 16GB RAM DDR3; Nvidia Quadro 2000; Blackmagic Decklink mini recorder and intensity shuttle usb3

Request me if you want more details.
Thanks !

**Comment by ronag** [comment]
2.2
