### ISSUE TITLE
Investigate: Decklink Desktop video 10.x driver

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#249]
A new set of drivers, and afaik a new firmware, opens a ton of possibilitis with the Decklink 4K card. New features are listed here: http://casparcg.com/forum/viewtopic.php?f=3&t=1701&p=13811#p13811

It should be checked out and implemented, if we can nativly build loop playback and use more channels from a single 4K card.

**Comment by yapus** [comment]
@Julusian What do you mean by "simultaneous in and out"?

I've tested 10.4 driver with Caspar 2.0.7 and with Decklink 4k Extreme I can do 1 fill+key output OR 1 fill+key input. With Decklink Quad - also only 4 ports (in any combination: 0 in/4 out, 1 in/3 out, 2 in/2 out, 3 in/1 out, 4 in/0 out) works simultaneously.

**Comment by jesperstarkar** [comment]
I can confirm that 4K Extreme supports full Duplex, 1 HD in AND HD key + fill out simultaneous.

**Comment by jesperstarkar** [comment]
@TomKaltz I honestly don't know. This thread should be closed.

**Comment by yapus** [comment]
@jesperstarkar Could you please explain – do you just add 1 decklink consumer and then you can issue AMCP like this:
```
PLAY 1 DEVICE DECKLINK 1
```
?

**Comment by jesperstarkar** [comment]
Yes. Nothing fancy.

**Comment by yapus** [comment]
Great to know! Thanks.

**Comment by FedorSymkin** [comment]
I've read Decklink 4K Extreme can't be simultaneous input and output with CasparCG:
https://docs.google.com/spreadsheets/d/1ekN7v7W0BPCaSD8KGGVjdptoY-rLcr129jupwH_DobY/edit?pli=1#gid=443551150 (column "Simultaneous connections per card"). Is it depend on blackmagiс driver version?

**Comment by jesperstarkar** [comment]
>10.2

**Comment by jesperstarkar** [comment]
Old, should be closed.
