### ISSUE TITLE
OSC message total frames bug (Server 2.0.6)

### ISSUE THREAD

**Issue by Kwils** [CasparCG/server#255]
Forum topic - http://casparcg.com/forum/viewtopic.php?f=3&t=2026
Summary: 
I have unexpected behavior with OSC messages with some files (which have the same codec info as the others and nothing seems to be wrong with them as I understand). Instead of receiving by  "file/frame" type of messages current and total number of frames, I receive just current in both Data elements (4/4, 5/5/ etc.). If I use cls command Cospar send me correct info about frame counts for this file.

DxDiag - https://dl.dropboxusercontent.com/u/61168478/DxDiag.txt
CaspasrCG log - https://dl.dropboxusercontent.com/u/61168478/caspar_2014-02-25.log
Example video file (sorry, this one is quite big) https://dl.dropboxusercontent.com/u/61168478/BIG%20BROVAZ_Favorite%20things.mpg

**Comment by ronag** [comment]
2.2
