### ISSUE TITLE
Problem playing files when file extension is used in 2.0.7beta

### ISSUE THREAD

**Issue by gfto** [CasparCG/server#261]
In 2.0.7beta the following bug is observed:

PLAY 1-10 file_not_found

> Correctly reports that file is not found

PLAY 1-10 file_not_found.png
PLAY 1-10 file_not_found.mp4

> Incorrectly reports that PLAY succeeded but nothing is being played (there is no file named file_not_found.png and file_not_found.mp4)

PLAY 1-10 split.bmp

> Reports PLAY OK, but fails to play split.bmp file (which exists).

PLAY 1-10 split

> Plays split.bmp as expected.

In 2.0.4 the above commands work as expected.

Full log is accessible at : http://casparcg.com/forum/viewtopic.php?f=3&t=2070

**Comment by hummelstrand** [comment]
Closing as part of issue house-keeping. 2.0.7beta no longer relevant.
