### ISSUE TITLE
Differences between CINF, CLS, INFO and OSC stats

### ISSUE THREAD

**Issue by oneofsomany** [CasparCG/server#270]
Linked with forum post http://casparcg.com/forum/viewtopic.php?f=3&t=2101

Running CasparCG 2.0.6 in default PAL SD configuration. Information returned in CLS/CINF differs from OSC and INFO.

Example below illustrates different frame counts with media already supplied with CasparCG..

AMCP:
cinf cg1080i50
200 CINF OK
"CasparCG\CG1080i50"  MOVIE  6159792 20140224130237 264 1/25

info 1-10 f
201 INFO OK
<?xml version="1.0" encoding="utf-8"?>
<producer>
  <type>separated-producer</type>
  <fill>
    <producer>
      <type>ffmpeg-producer</type>
      <filename>C:\Users\Dan\Videos\CASPARCG\CG1080i50.mp4</filename>
      <width>1920</width>
      <height>1088</height>
      <progressive>true</progressive>
      <fps>25</fps>
      <loop>false</loop>
      <frame-number>70</frame-number>
      <nb-frames>260</nb-frames>
      <file-frame-number>70</file-frame-number>
      <file-nb-frames>260</file-nb-frames>
    </producer>
  </fill>
  <key>
    <producer>
      <type>ffmpeg-producer</type>
      <filename>C:\Users\Dan\Videos\CASPARCG\CG1080i50_A.mp4</filename>
      <width>1920</width>
      <height>1088</height>
      <progressive>true</progressive>
      <fps>25</fps>
      <loop>false</loop>
      <frame-number>70</frame-number>
      <nb-frames>260</nb-frames>
      <file-frame-number>70</file-frame-number>
      <file-nb-frames>260</file-nb-frames>
    </producer>
  </key>
</producer>

OSC:
/channel/1/stage/layer/10/file/frame
70,260

**Comment by oneofsomany** [comment]
using MediaInfo dll and VLC, I have deduced that OSC and INFO are using the frame count from the video stream whilst CLS and CINF are using the frame count from the video header which seems to be the duration of the longest stream. In the case of the aforementioned videos, the audio duration is longer than the video duration but the file is only played for the duration of the video.

**Comment by ronag** [comment]
moved to media-scanner, info is deprecated
