### ISSUE TITLE
With Server V2.06 after SEEK Audio not in sync with video (MPG and MXF)

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#272]
I tested this in 2 modes with Server V2.06, both modes have the same problem
- Decklink
- Blocking Decklink

When using the SEEK command with PLAY or CALL the audio goes badly offsync.
I tested PLAY 1-1 MyMovie SEEK framenumber and
during playback CALL 1-1 SEEK framenumber
When these files are started without SEEK AV sync is fine untill a SEEK command is sent.

When start a new movie with a SEEK number set, audio goes also badly offsync.
It seems that only h264 (mp4) works very well.
These files keep very good in sync while using SEEK.

**Comment by ronag** [comment]
2.2
