### ISSUE TITLE
SEEK - can't seek to second or last frame

### ISSUE THREAD

**Issue by jaskie** [CasparCG/server#280]
I noticed that Caspar is capable seeking with frame accuracy only with I-frame only movie files. That's generally is a con, but acceptable (am I wrong?).
Recently I noticed, that such files seeking is not exact as I thought:
- SEEK 1 seeks to _third_ frame, so it's impossible to seek second frame (while SEEK 0 seeks the first).
- Subsequent frames are displayed with 1-frame advance each.
  Then I expected to see last frame at seek to length-2. But the frame displays as black, so it's impossible to seek to last frame as well.

The file with TC is here: http://didi.szczecin.tvp.pl/Caspar/timecode.mov
Tested on 2.06 (release) and 2.04 (community) builds.

**Comment by jesperstarkar** [comment]
Related: #393

**Comment by ronag** [comment]
2.2
