### ISSUE TITLE
Recording with libx264/h264 glitches

### ISSUE THREAD

**Issue by jmwebslave** [CasparCG/server#282]
Hi guys,

I am getting a bug when recording using libx264 with CasparCG using the command:
ADD 1 FILE "14-04-08 MUS@ICE P1-wm.mp4" -vcodec libx264 -preset ultrafast -tune fastdecode SEPARATE_KEY

The file has a scorebar in the top-left of the screen with a timeclock.  When recording this normally I get gliches every second or so a few seconds into the video.  It almost looks like the wrong keyframe is being used over and over.
http://atcproductions.tv/storage/14-04-08 MUS@ICE P1-BUG.MP4

If I add something of a reasonable size anywhere on screen that moves then the bug goes away.  For example, if I add a spinning logo then the file is perfect.
http://atcproductions.tv/storage/14-04-08 MUS@ICE P1-NOBUG.MP4

If I make the logo much smaller (or replace it with a still image) the bug returns.

Any ideas?

CasparCG Server 2.0.6 on Win7 x64.

Kind regards,
James.

**Comment by ronag** [comment]
2.2
