### ISSUE TITLE
Complete channel hangs all of a sudden

### ISSUE THREAD

**Issue by pkeuter** [CasparCG/Server#285]
Sometimes a channel all of a sudden just crashes. When I have a screen-consumer open, that window crashes. When I only have a Decklink-consumer, it gets black.

Looks like it is hanging in the transition-producer and keeps adding all new play-commands to some sort of "backstack" which returns a really long nested XML.

It keeps adding up all the time. So sometimes I'll get an info-command return of 10MB starting with a whole load of transition-producers like this:

 (foreground)
    (producer)
      (type)transition-producer(/type)
       (source)
        (producer)
          (type)transition-producer(/type)
          (source)
            (producer)

changed the brackets to () because GitHub doesn't understand brackets.

logfiles are on the forumthread I made: http://forum.casparcg.com/viewtopic.php?f=3&t=2206

This problem happens to me with 2.0.6 as well as 2.0.7b1. I have 2 decklink cards with 6 channels (the last 2 channels having a key/fill). The problem mostly occurs with the last 2 channels (with the key/fill). Maybe this makes it easier tracing the problem.

[edit]I've tried turning the key Decklink-consumers off, and since I've done that, the problem hasn't occured. Maybe this helps narrowing down the cause of the problem[/edit]

**Comment by HellGore** [comment]
No longer relevant in 2.1
