### ISSUE TITLE
Apply a filter to already playing media

### ISSUE THREAD

**Issue by oneofsomany** [CasparCG/server#290]
I would like to be able to apply a filter to media that is already playing. 

For example, I might notice that my field orders are incorrect on my media and want to flip them whilst it is on air.

Perhaps this could be achieved with the CALL function by putting something like CALL filter <fiter details>

original forum post at http://www.casparcg.com/forum/viewtopic.php?f=3&t=2336

**Comment by ronag** [comment]
duplicate https://github.com/CasparCG/server/issues/776
