### ISSUE TITLE
INFO returns incorrect duration

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#30]
Converted from [SourceForge issue 3585161](http://sourceforge.net/support/tracker.php?aid=3585161), submitted by hummelstrand

http://casparcg.com/forum/viewtopic.php?f=5&t=1011&p=5871

The files linked to in the forum post do play without a problem in VLC, but apparently CasparCG Server 2.0 stable reports incorrect duration and fps data.

**Comment by oneofsomany** [comment]
using MediaInfo dll and VLC, I have deduced that OSC and INFO are using the frame count from the video stream whilst CLS and CINF are using the frame count from the file header which seems to be the duration of the longest stream and not necessarily the video stream.

**Comment by hummelstrand** [comment]
Cleaning out old and irrelevant issues.
