### ISSUE TITLE
Code masking fails occasionally

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/Server#31]
Converted from [SourceForge issue 3587098](http://sourceforge.net/support/tracker.php?aid=3587098), submitted by snakemastr508

Two objects: a mask and an animated object 

Code:
    maskThis.cacheAsBitmap = true;
    msk.cacheAsBitmap = true;
    maskThis.mask = msk;

When I build several instances of this template, some of them don\\\'t apply the masking and show the mask onscreen. 
Regenerating the template fixes the problem eventually but makes it unreliable.

Everything else works as it should, no errors and the problem exists in the template once its created. 

Template Generator: 2.0.0;
Flash CS4; 
The attached file was resaved in CS6 due to software upgrades. This was after the masking problem.

Files are attached. Code in the files is partially Dutch (my apologies for the incovenience)
The masked image has been removed due to filesize

**Comment by jesperstarkar** [comment]
This should be close.

Not relevant to CasparCG.
