### ISSUE TITLE
HTML local getJSON call failed

### ISSUE THREAD

**Issue by Dannybevers** [CasparCG/server#311]
Hello,

On the stable version we use the following code to call a locally .json file.

$.getJSON('localfile.json').done(function(data){
      $('body').append(data.content);
});

Works perfectly  on the stable version. But we updated to the new unstable version with the new HTML5 implementation in our testcase. We reproduce the following error with the same code.

Info:console "XMLHttpRequest cannot load file:///C:/caspar/media/localfile.json?_=1412204519960. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is thereforce not allowed access.", source: file:///C:/caspar/media/template.html

Is it possible to force locally file calling with javascript? 
It's a requirement for our system to use locally file load.

Hope there's a fix for it or something else.

**Comment by HellGore** [comment]
Didn't cb1f366a695f1f102ff56747aa8880e5e38f072d fix the issue in 2.1?

**Comment by tomswinkels** [comment]
@HellGore With download of 2.1? Now we use 2.0.7 beta 2, there are no problems.

**Comment by HellGore** [comment]
Ok, then you are using Berkelium instead of CEF3. But in 2.1.0 this might also work as expected although CEF3 is used there.

**Comment by tomswinkels** [comment]
That's right. In which download of 2.1.0 is this problem be solved? I will test it.

**Comment by HellGore** [comment]
Many versions back, but take the latest for a go. It is the most stable version.

**Comment by tomswinkels** [comment]
When i run the casparcg.exe of the latest build start, i get an system error that VCOMP140.DLL is missing?

**Comment by HellGore** [comment]
From `README`, line 61:

> Install "Microsoft Visual C++ Redistributable for Visual Studio 2015" from
   https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by tomswinkels** [comment]
Thanks, that helps.

Now i get another error.

PLAY 1-10 [HTML] C:/caspar/media/template.html?widget=6566990
[2016-03-01 11:08:26.047] [1056] [info]    Received message from Console: PL
-10 [HTML] C:/caspar/media/template.html?widget=6566990\r\n
[2016-03-01 11:08:26.065] [564]  [info]    transition[empty=>html[C:/caspar/
a/template.html?widget=6566990]] Initialized
#202 PLAY OK
[2016-03-01 11:08:26.079] [2248] [info]    html[C:/caspar/media/template.htm
dget=6566990] Destroyed.
[0301/110826:ERROR:renderer_main.cc(226)] Running without renderer sandbox

**Comment by HellGore** [comment]
Does the error affect the rendering of your web page or does it display fine?

**Comment by tomswinkels** [comment]
This issue is fixed. Locally .json file works.

**Comment by tomswinkels** [comment]
The locally .json file works. But i think CALL not work.

This is the command;

PLAY 1-10 [HTML] C:/caspar/media/template.html?widget=6566990
CALL 1-10 invoke "playWidget('ticker-10266865')"

**Comment by HellGore** [comment]
ok it is impossible for me to know what the problem is without the file

**Comment by tomswinkels** [comment]
I have found the problem.

We use in us html template "window.onEnterFrame" and in the new version of caspar the function doesn't work. Is there an alternative?
