### ISSUE TITLE
Feature request:Can the out streaming has audio and video when playing a html that includes video or flash

### ISSUE THREAD

**Issue by hfmanly** [CasparCG/Server#316]
casparcg play a url (or a html file palced in d:\ CasparCG Server 2.0.7 Beta 2\Server\media) and the url include flash( the flash includes video and audio) or mp4( the mp4 includes audio and video ) file ,for example :
PLAY 1-0 [html] http://v.youku.com/v_show/id_XNzkwNTI4ODc2_ev_1.html\r\n 

how can hear the audio when watching video from the output of udp://192.168.109.186:2000 by using 
vlc playing the url "udp://@192.168.109.186:2000 "

thanks

**Comment by baltedewit** [comment]
@dotarmin can we close this in favour of #669 since that describes the feature more clearly?

**Comment by dotarmin** [comment]
@baltedewit Yes we can, good point! When 2.2.0 is released we have to go over all the issues and close the already completed that's open, old issues that are not applicable and clean among duplicates. Everyone is more than welcome to help out with this as well.

Thanks @baltedewit!
