### ISSUE TITLE
Levels whilst playing out v210 .mov

### ISSUE THREAD

**Issue by st599** [CasparCG/server#324]
We've been playing with a v210 file generated from a YUV4416be frame using the following commands:

``` bash
for i in `seq 0 99`; do cat stairCase7Steps.16p4 >> sc_loop.16p4; done
cat sc_loop.16p4 | ffmbc.exe -y -f rawvideo -pix_fmt yuv444p16be -s 1920x1080 -r 24 -f rawvideo -i - -vcodec v210 sc.mov
```

We have noticed that when playing out from CasparCG via Decklink into a professional reference monitor, that the Luma and Chroma levels differ from the values seen when played out via Blackmagic Media Express.

The correct values (we made the file and know the values) for Luma are:
64, 210, 356, 502, 648, 794 and 940
with CR and Cb set to 512.

CasparCG is playing the file out with varying levels, none of which are correct:
64, 204/208/212, 348/352, 496/500/504, 640/644, 788, 932/936
With Cr and Cb ranging from 506 - 512

There is also evidence of filter rings near distinct edges which is not present in the Media Express output.

Is it possible that this is being caused by CasparCG doing 10-bit File -> 8-bit Processing -> 10-bit HD-SDI? If that is the case, can we force 10-bit operation?

**Comment by ronag** [comment]
Fixed in 2.2
