### ISSUE TITLE
Audio Sync problem is back with 2.07

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#329]
With playback of HD MXF and Mpeg the audio is always of with 1 frame.
This was fixed with sync decklink in earlier versions but this is now not there anymore.

Steps to repro,
Render an Adobe countdown to a HD mpeg file
playback on system with 2.07 server and capture on another system
compare capture with original file in Premiere Pro
Tested with 10.1.4 Decklink drivers.
(note this works fine with 2.04 and using sync decklink)

**Comment by premultiply** [comment]
I can confirm this problem.
But for me it looks like that even live input from Decklink to CasparCG is delayed the same way.
So maybe this a bug in Decklink consumer.
Is there any chance to get this fixed?
Sync Decklink is not availible anymore...

**Comment by premultiply** [comment]
Tested it again today with current CasparCG 2.1 and Decklink 10.6.6: Audio is exactly and always 1 frame off (40 ms at 1080i50) with all sources (clip playback and live input). Checked it with Vistek Valid Generator and Reader. Maybe a problem in MIXER or DECKLINK CONSUMER?

Setting different buffer sizes and low delay mode in CasparCG config does not change anything.

**Comment by premultiply** [comment]
#114

**Comment by premultiply** [comment]
They are not in sync like all other sources too.


@TKooijmans Did you test it with Vistek Valid or similar equipment?
Please note that creating MP4 files with codecs like AAC and MP3 with overlapping between audio frames that are in sync on different playback systems is nearly impossible.

**Comment by TKooijmans** [comment]
I test the following way,
Create a counter with tone in Premiere Pro
Render this to a HD movie (H264,MXF, MPEG, AVI)
Playback this movie with Casper while capture with a second system.
Compare captured clip with original in Premiere timeline (zoomed-in to 1 frame)

With H264/mp4 playback is always in sync with audio, with other formats audio is always 1 frame early.
(Only tested with V207)

**Comment by jesperstarkar** [comment]
Good job @premultiply. Valuable information.

**Comment by premultiply** [comment]
I will do more checks on p50 (and maybe p25 if Valid generator does support this format) to check if that makes a difference. And if Vistek Valid does not do it maybe Tektronix TG700 and WFM8200 will do it.

@TKooijmans That is exactly why I said do not do such tests with MP4 file format.

Hopefully someone can check the code to find and fix this bug...

**Comment by ronag** [comment]
2.2. Please reopen if still an issue.
