### ISSUE TITLE
WIPE direction does not work

### ISSUE THREAD

**Issue by jimmn** [CasparCG/server#332]
LOADBG 1-10 "\STILLS\picturefile" WIPE 40 LEFT\r\n

always wipes to the right when the play command is sent. PUSH and SLIDE work fine in either direction but not WIPE.

**Comment by ronag** [comment]
2.2

**Comment by dotarmin** [comment]
This appears to be an issue in v2.2.x and it applies for WIPE in all directions. PUSH and SLIDE works in either direction.

**Comment by hreinnbeck** [comment]
https://github.com/CasparCG/server/blob/6ee169018e7bfd935bb8330683733b430a08bd7f/src/core/producer/transition/transition_producer.cpp#L170

FROM:
dst_frame.transform().image_transform.clip_scale[0] = delta;

TO:
dst_frame.transform().image_transform.clip_scale[0] = (-1.0 + delta) * dir;

**Comment by dotarmin** [comment]
@hreinnbeck, wow that was fast! THANKS!

**Comment by jimmn** [comment]
Wow, bug fixes sure have improved since 2014

**Comment by Sidonai-1** [comment]
It seems this is still present on 2.3.x lts:

Wipe only works from left to right

Push and slide only work sideways but not up-down or viceversa.

If the fix is as easy as it seems it would be great to include it in the next build!

Thank you.

**Comment by Sidonai-1** [comment]
> https://github.com/CasparCG/server/blob/6ee169018e7bfd935bb8330683733b430a08bd7f/src/core/producer/transition/transition_producer.cpp#L170
> 
> FROM: dst_frame.transform().image_transform.clip_scale[0] = delta;
> 
> TO: dst_frame.transform().image_transform.clip_scale[0] = (-1.0 + delta) * dir;

I see there's some activity recently around the commits. It may be a good time, do you think you could push this change to the main branch?
Thank you!

**Comment by Julusian** [comment]
Your suggestion there didn't work, but I ported the change from https://github.com/nrkno/sofie-casparcg-server/pull/31/files which does appear to

**Comment by Sidonai-1** [comment]
> Your suggestion there didn't work, but I ported the change from https://github.com/nrkno/sofie-casparcg-server/pull/31/files which does appear to

 Is there a build available with WIPE/PUSH/SLIDE working in all 4 directions? I cannot seem to find one with all the transitions fixed.
Thanks.

**Comment by Sidonai-1** [comment]
Just to comment on this: the left/right transitions are fixed but there aren't any up/down transitions implemented. I guess it's not even planned.
