### ISSUE TITLE
Request Infomation Regarding Distribution of CASPAR

### ISSUE THREAD

**Issue by WASP3D** [CasparCG/server#334]
Hi,
We would like to have information regarding distribution of Caspar CG server app build EXE with our software. We have already created a producer and uploaded the source code. Its not merged with the main branch but i think we can distribute the binary as as the source code is open. Can we go ahead and provide as a setup or we need some permissions from the caspar community ? Any links would be helpful.

Thanks and Regards
Manish

**Comment by Julusian** [comment]
@dotarmin This looks to be answered
