### ISSUE TITLE
PRINT no Alpha

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/Server#34]
Converted from [SourceForge issue 3596921](http://sourceforge.net/support/tracker.php?aid=3596921), submitted by didikunz

The PRINT command creates a PNG-graphic in the Data server path. Under Server 2.0 Stable the PNG has a alpha channel, that is the alpha of the template, or whatever is on that channel at that moment. Under 2.1.0 there is no alpha channel. Is this by design or by error? 

I would want to use it to render lower-thirds and the like for using in non-linear-editing. (Need to use 2.1.0 because there is no OpenGL capable GPU).

Didi

**Comment by HellGore** [comment]
This works
