### ISSUE TITLE
Add information about compiling 2.1.0 source

### ISSUE THREAD

**Issue by krzyc** [CasparCG/Server#351]
I think we should add some info about compiling 2.1.0 server.
I have succesfully compiled it with VS 2013 Community but as my primary environment is linux it took me a while to figure all things out.
So why not put suggested workflow in readme.txt or at http://casparcg.com/wiki/Building_from_Source.
To generate VS 2013 project I have issued:
cmake -G "Visual Studio 12 Win64" .

**Comment by HellGore** [comment]
Now there is a file called BUILDING describing this
