### ISSUE TITLE
Testing 2.1.0 branch

### ISSUE THREAD

**Issue by ChristianAnders** [CasparCG/server#353]
After the new build script for windows was committed last night I could finally get 2.1.0 to build for me.  I did a few tests and just wanted to let you know what I experienced.  Please excuse me if this is the wrong venue for it.

I'm running Win7 64bit Ultimate, with the original Decklink SDI (not latest generation) running at 1080i5000 and also tested 720p5000.  Nvidia GeForce GTX 9780 graphics card.

**1)** Playing video files (like GO1080P25 and CG1080I50) I get the the original audio plus static noise, tested with decklink+embedded and screen+system audio, same results.

**2)** Really wanted to test the PSD feature.  Created a file with a named text layer and it wouldn't change the text.  Saw the YouTube video and figured the text layers had to be colored green.  Testing that threw errors in Caspar, in psd_scene_producer.cpp there are references to like "RunArray..StyleSheet", this seems like a replace error, rebuild with replacing all the .. to just . now doesn't throw an error but the text still doesn't change when running the PSD (Play 1-1 PSDTEST5 Rad1 "TEXT 1" Rad2 "Text 2").

**3)** Checked some HTML templates out (BTW the new screen consumer interaction with HTML is COOOOL).  Problem I found was that issuing commands often made Caspar unresponsive, after 15-25 seconds all the commands would run at once, or I had to kill the casparcg.exe process).  This only seems to happen with HTML, not video. (Didn't test Flash).

Log shows:

``` javascript
Inital command: [2015-05-22 01:34:12.357] [8600]  [info]    Received message from [127.0.0.1:5250]: CG 1-116 ADD 1 HTMLTEMPLATE 1 "<templateData><name><![CDATA[NAME TEST]]></name><title><![CDATA[TITLE TEST]]></title></templateData>"\r\n

A few dozen: [2015-05-22 01:34:12.530] [9140]  [debug]   [ogl-device] Performance warning. Buffer allocation blocked: 0.115

A few dozen: [2015-05-22 01:34:19.496] [3960]  [debug]   executor[OpenGL Rendering Context] Overflow. Blocking caller.

And a few hundred: [2015-05-22 01:34:20.530] [7144]  [info]    Received message from Console: \r\n
(Don't believe the client actually issued all those "\r\n")

Also noticed errors like these in logs: [2015-05-22 01:49:05.033] [4180]  [warning] Assertion Failed: counter < 8 file:D:\_CCG_2.1\Server\core\consumer\frame_consumer.cpp line:69
```

**4)** Playing a video with LENGTH parameter doesn't work like in 2.0 branch.  Usually doing a "PLAY 1-1 GO1080P25 LENGTH 100" would play until frame 100 and then freeze, the video now just plays till the end and doesn't stop at LENGTH frame position.

**Comment by baltedewit** [comment]
About the audio. It looks like only the left channel has audio. the right channel is just static.

also, the html producer does not suffer from this issue, which leads me to think that the audio from that still isn't routed through the audio producer. that's definitely something that should be improved in 2.1

it would also be great if the html producer would support mp3 and mp4 playback..

**Comment by HellGore** [comment]
The audio problem is fixed in the last commit.

**Comment by vimlesh1975** [comment]
I am testing server 2.1 from build dated 17-09-15. I want to point out following things.
1. Thumbnails are being generated of image files only and not for video files.
2. Server is not able to play file while giving command with filename with extension. I mean-
working play 1-1 amb
not working play 1-1 amb.mp4

**Comment by Vojsooo** [comment]
I have the same problem like vimlesh in point 1.

**Comment by vimlesh1975** [comment]
1. Thumbnails are now being generated ok.
2. Plays h.265 encoded file ok while 2.07 not.
3. OSC Gives total duration of velocity 9.1 exported d10 mpg files. But server 2.07 not.

**Comment by vimlesh1975** [comment]
In Server 2.07
With info 1-1, I get <status>paused</status>

201 INFO OK
<?xml version="1.0" encoding="utf-8"?>
<layer>
   <status>paused</status>
   <auto_delta>-1</auto_delta>
   <frame-number>30</frame-number>
   

<nb_frames>438</nb_frames>
   <frames-left>409</frames-left>
   <frame-age>41</frame-age>
   <foreground>
      <producer>
         <type>ffmpeg-

producer</type>
         <filename>c:/casparcg/_media\\go1080p25.mp4</filename>
         <width>1920</width>
         <height>1080</height>
         

<progressive>true</progressive>
         <fps>25</fps>
         <loop>false</loop>
         <frame-number>29</frame-number>
         <nb-

frames>438</nb-frames>
         <file-frame-number>30</file-frame-number>
         <file-nb-frames>439</file-nb-frames>
      </producer>
   

</foreground>
   <background>
      <producer>
         <type>empty-producer</type>
      </producer>
   </background>
   <index>1</index>
</layer>



In Server 2.1
With info 1-1, I do not get status rsponse.
201 INFO OK
<?xml version="1.0" encoding="utf-8"?>
<layer>
   <auto_delta>null</auto_delta>
   <frame-number>42</frame-number>
   <nb_frames>444</nb_frames>
   

<frames-left>402</frames-left>
   <frame-age>1</frame-age>
   <producer>
      <type>ffmpeg</type>
      <filename>media\go1080p25.mp4</filename>
     

 <width>1920</width>
      <height>1080</height>
      <progressive>1</progressive>
      <fps>25</fps>
      <loop>false</loop>
      <frame-

number>42</frame-number>
      <nb-frames>444</nb-frames>
      <file-frame-number>141</file-frame-number>
      <file-nb-frames>445</file-nb-

frames>
   </producer>
   <background>
      <producer>
         <type>empty-producer</type>
      </producer>
   </background>
   <index>1</index>
</layer>



I want to use this response for desining a single button for play/resume.

**Comment by vimlesh1975** [comment]
In Server 2.07
With info 1-1, I get <status>paused</status>

201 INFO OK
<?xml version="1.0" encoding="utf-8"?>
<layer>
   <status>paused</status>
   <auto_delta>-1</auto_delta>
   <frame-number>30</frame-number>
   

<nb_frames>438</nb_frames>
   <frames-left>409</frames-left>
   <frame-age>41</frame-age>
   <foreground>
      <producer>
         <type>ffmpeg-

producer</type>
         <filename>c:/casparcg/_media\\go1080p25.mp4</filename>
         <width>1920</width>
         <height>1080</height>
         

<progressive>true</progressive>
         <fps>25</fps>
         <loop>false</loop>
         <frame-number>29</frame-number>
         <nb-

frames>438</nb-frames>
         <file-frame-number>30</file-frame-number>
         <file-nb-frames>439</file-nb-frames>
      </producer>
   

</foreground>
   <background>
      <producer>
         <type>empty-producer</type>
      </producer>
   </background>
   <index>1</index>
</layer>



In Server 2.1
With info 1-1, I do not get status rsponse.
201 INFO OK
<?xml version="1.0" encoding="utf-8"?>
<layer>
   <auto_delta>null</auto_delta>
   <frame-number>42</frame-number>
   <nb_frames>444</nb_frames>
   

<frames-left>402</frames-left>
   <frame-age>1</frame-age>
   <producer>
      <type>ffmpeg</type>
      <filename>media\go1080p25.mp4</filename>
     

 <width>1920</width>
      <height>1080</height>
      <progressive>1</progressive>
      <fps>25</fps>
      <loop>false</loop>
      <frame-

number>42</frame-number>
      <nb-frames>444</nb-frames>
      <file-frame-number>141</file-frame-number>
      <file-nb-frames>445</file-nb-

frames>
   </producer>
   <background>
      <producer>
         <type>empty-producer</type>
      </producer>
   </background>
   <index>1</index>
</layer>



I want to use this response for desining a single button for play/resume.

**Comment by ronag** [comment]
2.2
