### ISSUE TITLE
[Feature Request] Send AMCP-commands via Javascript console log

### ISSUE THREAD

**Issue by loveolsson** [CasparCG/server#356]
The ability to send AMCP-commands from HTML5-templates. I suggest decoding commands from the console.log output, maybe with a prefix like "[AMCP]".

**Comment by respectTheCode** [comment]
What about making the server accept WebSocket connections? Then it would be easy control CasparCG from JS in either a template or a web page.

**Comment by jesperstarkar** [comment]
Yeah, Websockets is the way to go. For sure.

**Comment by niklasR** [comment]
Websockets +1. Not sure CasparCG needs websocket support though, as it has AMCP (and I'm guessing if done correctly it'd be quite a big feature). We built a quick and dirty node application with which we communicate over websockets, which then talks to Caspar over AMCP (and listens to OSC). Can't find any of the AMCP code in any open source repo though, might have a look tonight

**Comment by jesperstarkar** [comment]
What we want/"need" is the AMCP protocol implemented over WebSocket.

**Comment by ronag** [comment]
https://github.com/CasparCG/server/issues/688
