### ISSUE TITLE
Server crash after INT_MAX milliseconds if flash template is running

### ISSUE THREAD

**Issue by jaskie** [CasparCG/Server#357]
I've made Caspar-based CG inserter for channel branding. Logo, crawl, parentals... But  every 24,8 days server crashes. The errors are as follows:

*First*
```
Nazwa aplikacji powodującej błąd: casparcg.exe, wersja: 2.0.6.0, sygnatura czasowa: 0x5538a3c7
Nazwa modułu powodującego błąd: ieframe.dll_unloaded, wersja: 0.0.0.0, sygnatura czasowa: 0x52944cf2
Kod wyjątku: 0xc0000005
Przesunięcie błędu: 0x6e7aa978
Identyfikator procesu powodującego błąd: 0xad8
Godzina uruchomienia aplikacji powodującej błąd: 0x01d098506e8bb785
Ścieżka aplikacji powodującej błąd: C:\Playout\Server\casparcg.exe
Ścieżka modułu powodującego błąd: ieframe.dll
Identyfikator raportu: 4a716b57-1728-11e5-8b4a-001e679d5ec0
```
*After close windows error message*
```
Nazwa aplikacji powodującej błąd: casparcg.exe, wersja: 2.0.6.0, sygnatura czasowa: 0x5538a3c7
Nazwa modułu powodującego błąd: Flash32_15_0_0_223.ocx_unloaded, wersja: 0.0.0.0, sygnatura czasowa: 0x544ecba4
Kod wyjątku: 0xc0000005
Przesunięcie błędu: 0x6e20f5ea
Identyfikator procesu powodującego błąd: 0xad8
Godzina uruchomienia aplikacji powodującej błąd: 0x01d098506e8bb785
Ścieżka aplikacji powodującej błąd: C:\Playout\Server\casparcg.exe
Ścieżka modułu powodującego błąd: Flash32_15_0_0_223.ocx
Identyfikator raportu: 0bc176a4-172f-11e5-8b4a-001e679d5ec0
```

Of course there is nothing about the crash in caspar log.

What I already know:
* the error is independent of windows GetTickCount() counter, it occurs precisely counting from start of CasparCG,
* the error didn't occur if flash template was not loaded,
* reloading flash template (say daily) didn't help.

I had one case when template was unloaded when INT_MAX passed, and crash happened after 49 days (UINT_MAX - template was loaded again).

Any idea?

**Comment by jesperstarkar** [comment]
"reloading flash template (say daily) didn't help." 
Did you "CG STOP" then "CG PLAY" or "CLEAR" then "CG PLAY"? 

The first unloads a single template from within the TemplateHost, but keeps the producer, the last example restarts the producer fully.

**Comment by jaskie** [comment]
The actual unload command was CG 1-11 CLEAR. I noticed that ieframe.dll and flash.ocx were unloaded with this command.

**Comment by jaskie** [comment]
It seems that this error depends on Flash Player version. Adding CoFreeUnusedLibrariesEx() to DestroyAxControl() in FlashAxContainer.cpp and rolling Flash Player version back to 11.8 solved problem, although importance of CoFreeUnusedLibrariesEx() wasn't confirmed.
