### ISSUE TITLE
LNK4254 warning while building CasparCG using VS Express

### ISSUE THREAD

**Issue by FedorSymkin** [CasparCG/server#359]
I build CasparCG server using Visual Studio Express 2012 (VS2010 tools + external ATL from WinDDK 7600.16385.1) and I get warnings LNK4254: 

```
warning LNK4254: section ATL merged into .rdata with different attributes.
```

I've found definition and merging ATL section in atlbase.h with read and shared attributes (both for x86 and x64 builds):

``` C++
#if defined(_M_IA64) || defined(_M_IX86) || defined (_M_AMD64)

#pragma section("ATL$__a", read, shared)
#pragma section("ATL$__z", read, shared)
#pragma section("ATL$__m", read, shared)
extern "C"
{
__declspec(selectany) __declspec(allocate("ATL$__a")) _ATL_OBJMAP_ENTRY* __pobjMapEntryFirst = NULL;
__declspec(selectany) __declspec(allocate("ATL$__z")) _ATL_OBJMAP_ENTRY* __pobjMapEntryLast = NULL;
}

#if !defined(_M_IA64)
#pragma comment(linker, "/merge:ATL=.rdata")
#endif
```

There was forum topic about same problem in MSDN: https://social.msdn.microsoft.com/Forums/en-US/4763bc2d-0e86-45e9-bfe4-ddaa735e5ad5/lnk4254-section-atls-merged-into-rdata-with-different-attributes?forum=vcmfcatl, but question there is still unanswered.

I thought about workaround - removing shared attribute in atlbase.h:
http://stackoverflow.com/questions/9559547/atl-library-warning-lnk4254-and-lnk4078
But changing external headers is not so clean way.

Has anybody faced with it? Should I worry about this warning or I can just disable it in linker options?

**Comment by seccpur** [comment]
Seeing the \dependencies64\boost\stage\lib files, it seems Casparcg server 2.1  is build with V120 & MT built settings.Keeping uniform project settings is the key to successful built.  But linking with the CEF lib files has always been the biggest nightmare.

**Comment by Julusian** [comment]
Only Visual Studio 2017 is now supported for building on windows. 
@dotarmin
