### ISSUE TITLE
Playlist Producer

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/server#361]
We currently have "front" and "back" players. We should have AMCP commands and an internal queue for swapping and re-loading the background layer. So that we could have PLAY -> LOADBG AUTO -> LOADBG AUTO... done by just adding a list of movies in the first place.

**Comment by PeterAkakpo** [comment]
Server side playlist with id for each media item

**Comment by HellGore** [comment]
Earlier we had a work in progress `playlist_producer` in the code that was later removed. Something similar could be created again.

**Comment by PeterAkakpo** [comment]
any word on the progress of the playlist_producer ?

**Comment by HellGore** [comment]
No, there is no progress on that.

**Comment by jesperstarkar** [comment]
#872
