### ISSUE TITLE
Compile error with GCC 5

### ISSUE THREAD

**Issue by sesse** [CasparCG/server#366]
Hi,

CasparCG doesn't compile with GCC 5.1.1, but the fix is simple: modules/ffmpeg/producer/util/util.cpp tries to “return nullptr;” where it should “return false;” (nullptr is not implicitly convertible to bool).

Now, after that there's still an issue with that you're shipping lots of libraries precompiled (I assume this is because Windows has no working package system) and the C++11 std::string ABI changed, but that's for a separate issue.

**Comment by Julusian** [comment]
Ubuntu 16.04 is now a supported platform which uses GCC 5.4, so this should now be resolved
@dotarmin
