### ISSUE TITLE
Files get replaced and group names changed on multiple rundowns

### ISSUE THREAD

**Issue by NH9087** [CasparCG/Server#367]
Hello,

Relatively new but understand how to use caspar in the function of running our live events.

Problems I have are renaming a group (small issue) on one group in a certain rundown. Lets call this commercial rundown, when changing the name of a group on said rundown, another group/image/video file on a totally different rundown will be changed with the same name. Aside from being confusing and annoying this issue doesn't greatly alter my use of the program.

The bigger issue I have is when files are being replaced in separate rundowns. Similar to the above, I will update a .png image in commercial rundown and the new image will replace a totally video or image file on a totally different rundown.

I am unsure why this happens but it typically causes me to scatter and sometimes even send the wrong graphic or video live to our stream.

Please let me know if there is any additional information I can provide, we are running version 2.0.7.

Thank you,

**Comment by Zebiolo** [comment]
This is a client issue and should therefore be posted in the clients issue tracker. Anyhow the issue has been fixed in the 2.0.8 bransch. Download the latest build from builds.casparcg.com
