### ISSUE TITLE
DIAG command on linux leads to core dump

### ISSUE THREAD

**Issue by krzyc** [CasparCG/Server#371]
I have compiled CasparCG Server from GitHub (2.1.0.72e6417 UNSTABLE) on Kubuntu 15.04 and everything seems to be fine until I execute DIAG command. Then, after about 5 seconds of seeing valid diagnostic window, I get:

    [2015-09-01 17:05:35.946] [140042205452032] [info]    Received message from Console: diag\r\n
    #202 DIAG OK
    [2015-09-01 17:05:35.946] [140042222237440] [debug]   Executed command: DIAG 0
    casparcg: ../../src/xcb_conn.c:186: write_vec: Assertion `!c->out.queue_len' failed.
    Przerwane (zrzut pamięci)

**Comment by krzyc** [comment]
Probably it is a result of a bug in libxcb 1.10 fixed in 1.11 version.

http://lists.freedesktop.org/archives/xcb/2013-December/009027.html
https://bugs.launchpad.net/ubuntu/+source/libxcb/+bug/1402966

**Comment by krzyc** [comment]
I can confirm that after upgrading libxcb to 1.11 problem is fixed.

**Comment by hummelstrand** [comment]
Thanks for reporting back, can we close this issue?

**Comment by HellGore** [comment]
yes
