### ISSUE TITLE
Remove .pdb files from builds

### ISSUE THREAD

**Issue by hummelstrand** [CasparCG/Server#373]
The 207 MB .pdb file that is included in every Windows build adds 24 MB to the zip file. Can this be excluded without any negative consequences?

**Comment by ronag** [comment]
The .map file an be excluded as well.

**Comment by HellGore** [comment]
We could provide a separate download with the pdb and map files if it is still wanted by someone. Remote debugging for example

**Comment by ronag** [comment]
Sure, doesn't hurt. Though I've never heard of it ever being relevant in the past 6 years...

**Comment by hummelstrand** [comment]
The only issue with keeping them is that the hosting of builds fills up quickly, and has to be manually maintained.

**Comment by ronag** [comment]
I vote for removing them entirely. In the 8 years I've been involved in this project the .map and .pdb files have never been used. If you need them you will mostly build the source code yourself. Removing them is a huge save on both hosting and download times.

**Comment by HellGore** [comment]
I see now that without the `.pdb` the `StackWalker` code can't even print proper function names, so bug reports with stack traces would be useless. Currently I have made the `*_debug_symbols.zip` a separate download but it might be best to move it back into the main download for the sake of stack traces.
