### ISSUE TITLE
video name

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#38]
Converted from [SourceForge issue 3600381](http://sourceforge.net/support/tracker.php?aid=3600381), submitted by ncsmedia

Hi I am new here in casparCG and I think I found a little "bug".
When you forget to instance a name in a video imported in Flash and try to compile an error message is generate. 

**_Error**_
 If you want to optimize embedded video instances they need to have instance names.

But when you go back and fix it the error message is still generate. You have to shutdown Flash to compile succesfully.

**Comment by dotarmin** [comment]
@jeansson Is this related to TemplateGenerator? Then it should be closed because it haven't to do with the server.
