### ISSUE TITLE
HTML Template JSON Array Parameter Encoding

### ISSUE THREAD

**Issue by mfrro** [CasparCG/Server#382]
A Json Array passed to a Html-Template via the HTML-UPDATE function cannot be decoded using  JSON.parse(). In my case, the data-flow is as follows: NodeJS-Server->AMCP (update function)->CasparCG->Html-Template.

**Comment by HellGore** [comment]
Can you be more specific? Is it in 2.0.7 or 2.1.0? Also you should provide the AMCP conversation you are sending and the html template you are using.

**Comment by mfrro** [comment]
Sorry, it's in 2.0.7. 
The Array that gets passed to the caspar-cg Module is parsed to a Json string before being added to the AMCP Command:
var songInfoArray = ["Song Title","Artist Name","image.jpg"];
songInfoArray = JSON.parse(songInfoArray);

The AMCP command sent from the node-server looks like this:
CALL 1-10 UPDATE ["Song Title","Artist Name","image.jpg"]

Here's the content of the CasparCG Log-File when UPDATE gets called:
[2015-10-02 11:50:50.855] [10904] [info]    Received message from 127.0.0.1: CALL 1-10 UPDATE ["Song Title","Artist Name","image.jpg"]\r\n
[2015-10-02 11:50:50.856] [8444]  [debug]   Executed command: CallCommand
[2015-10-02 11:50:50.856] [8444]  [info]    Sent message to 127.0.0.1: 202 CALL OK\r\n

The update function in the template looks like this:
function update(songInfoArray) {
	songInfoArray = JSON.parse(songInfoArray);
	document.getElementById("song").innerHTML=songInfoArray[0];
	document.getElementById("artist").innerHTML=songInfoArray[1];
	document.getElementById("logo").src=songInfoArray[2];
}

The divs that should be set are empty.

**Comment by ronag** [comment]
You could start by logging out "songInfoArray" so we can see what actually arrives into the template... I think it's simply a case of either replacing `"` with `'`  or putting your entire data string in quotes.

**Comment by mfrro** [comment]
You were right ronag.
This didn't work: 
CALL 1-10 UPDATE "["Song Title","Artist Name","image.jpg"]"
I didn't want to use single quotes either, since double quotes are JSON standard. Double Escaping the double quotes within the string solved my problem. The working call looks like this:
CALL 1-10 UPDATE "[\\"Song Title\\",\\"Artist Name","image.jpg"]"

Would you consider this a bug or not? It would be great if JSON data was supported "out of the box". My problem is solved, so I'm happy anyway :)
Thank you both.

**Comment by HellGore** [comment]
It is not a bug, it is supposed to be like that

**Comment by ronag** [comment]
Actually, I believe it is a bug. Everything inside the first quotations mark should be fine, i.e.

`CALL 1-10 UPDATE "["Song Title","Artist Name","image.jpg"]"`

Should work.

**Comment by HellGore** [comment]
Actually when looking at the working line one more time:

```"[\\"Song Title\\",\\"Artist Name\\",\\"image.jpg\\"]"```

I am confused why the line is not:

```"[\"Song Title\",\"Artist Name\",\"image.jpg\"]"```

Double backslash should not be used if I am thinking correctly. However:

```"["Song Title","Artist Name","image.jpg"]"```

I am guessing could confuse the AMCP tokenizer state machine. It would be tokenized into something like (one AMCP parameter per line):

```
[
Song
Title
,
Artist
Name
,
image.jpg
]
```

**Comment by jesperstarkar** [comment]
@ronag how could your suggestion be correct? No other system would parse the quotes correctly. Do you mean Caspar should handle it this way, or that it is correct syntax in general?

@HellGore The double backslashes are a nightmare hunting CasparCG.

**Comment by ronag** [comment]
@jesperstarkar: What do you "mean no other system would parse the quotes correctly"?

@HellGore: The correct behaviour of the state machine should be, once first quote is detected treat everything until the last quote as a raw string. Once it has gotten the first quote it should keep consuming characters until next whitespace or line break.

The parser should probably be rewritten to use regex.

**Comment by jesperstarkar** [comment]
No other parser/compiler I have ever touched accepts nested quotes. But it would sure be nice for this purpose.

**Comment by ronag** [comment]
@jesperstarkar: Then you have missed quite a few parsers/compilers. Also, what other parsers/compilers do is not really relevant.

**Comment by HellGore** [comment]
@ronag but how should we then support more than one quoted AMCP parameter if we always treat the "rest" after a doublequote-character as a single parameter (the last)? This would also mean that:

```PLAY 1-10 "folder/clip with space" LOOP```

would be sent to the producers with a params-vector with one element containing

```folder/clip with space" LOOP```

instead of the LOOP parameter being a separate element in the params-vector.

**Comment by jesperstarkar** [comment]
Hmmmm, are we sure we want to limit the protocol to just support one param with quotation marks? It will be a mess to revert in the future if we at some point need multiple params of such kind. One example is if you use a template name in double quotes, and then send template data with double quotes in the same command.

**Comment by ronag** [comment]
@HellGore: No it would look for the last quote, not the end of line... but yes, you are both right that doing it like that will limit things to a single parameter with quotes which is probably a bad idea.

**Comment by HellGore** [comment]
My example was wrong, it should have been with quotes around LOOP as well, so yes, we agree I think.
