### ISSUE TITLE
HTML producer: requestAnimationFrame and cancelAnimationFrame

### ISSUE THREAD

**Issue by domasx2** [CasparCG/Server#388]
Hi,

Per spec (https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) requestAnimationFrame has a return value (id), which can be used with cancelAnimationFrame to cancel the request. However CasparCG version of requestAnimationFrame does not implement the return value. Some animation libs (like GSAP) depend on this feature, and exhibit funky behaviour on CasparCG

**Comment by HellGore** [comment]
O, I will look into this

**Comment by domasx2** [comment]
In the meanwhile using this to wrap requestAnimationFrame and implement return value / cancelAnimationFrame:

https://gist.github.com/domasx2/e97dce67349fb46f01de

**Comment by HellGore** [comment]
Can you provide a test html template requiring this feature so I can verify my implementation?

**Comment by domasx2** [comment]
Hi, sorry for late reply,

There you go, banged something out:
https://rawgit.com/domasx2/5a3b812e12f3a600dddb/raw/817d0fe2544b4691f6ca01506fd1ac32b0c0e488/testgsapfps.html

[GSAP](http://greensock.com/gsap) animation framework uses cancelAnimationFrame internally. If this does not work and canceled raf requests get called, gsap updates tweens too often. This tests actual GSAP tween fps and FPS by simply looping raf. If all is correct, both tests should return identical fps.

source:
https://gist.github.com/domasx2/5a3b812e12f3a600dddb

**Comment by domasx2** [comment]
Update:
 the correct url is https://rawgit.com/domasx2/5a3b812e12f3a600dddb/raw/1dd022c34a06464d14db186f730e3dc8e2b34154/testgsapfps.html, linked to an older gist first..
