### ISSUE TITLE
Can't SEEK to frame 29, 59, 113...

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/server#392]
OP1a Wrappers with IMX 30 and AVC-Intra Class 100 codecs testet. Both har n=1 GOP.

LOAD with SEEK to frame 29 gives frame 28. Seeking 27, 28, 29, 30 gives 27, 28, 28, 30. Same goes for 56/57 ans 112/113. Haven't testet further.

DIAG/INFO (file_frame_number) reports frames 29/57/113, but a burn in timecode overlay reveals that 28/56/112 are played twice. Please note that there's an offset between reported file_frame_number and actual frame played, I will post a separate issue on that (#393). But my findings concludes that SEEK x = frame z played (in these codecs having n=1 GOP). At the same time x+2 is the reported file_frame_number.

**Comment by hummelstrand** [comment]
![seek-problems_illustration_v01](https://cloud.githubusercontent.com/assets/2979793/10996572/ac27ba52-8486-11e5-9677-7b55cd5a502c.jpg)

**Comment by jesperstarkar** [comment]
I did tests with burnt in timecode overlay. I then added a Decklink input with the DIAG window as a reference to file_frame_number. I did an automated test issuing LOAD with SEEK across 6 files and from frame 1-130. I added enough pause to each step in the macro to compensate for latency in the pipeline, so that it was certain that the DIAG window showed the same frame as being displayed.

**Comment by ronag** [comment]
2.2
