### ISSUE TITLE
file_frame_number offset on SEEK

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/server#393]
LOAD with SEEK in OP1a wrappers with IMX 30 and ACV-Intra Class 100 codecs, both having n=1 GOP. Haven't tested other codecs.

There's a consistent offset of +2 frames between frame played and frame reported in diag/info under file_frame_number. SEEKING to frame x actually plays frame x (tested with burnt in timecode overlay), but file_frame_number reports x+2.

**Comment by jesperstarkar** [comment]
Related: #280

**Comment by hummelstrand** [comment]
Related #266

**Comment by hummelstrand** [comment]
Related: #184

**Comment by ronag** [comment]
This is not really a bug. It shows the frame number of what the producer has sent. Then there is the delay of the mixer and the consumer that is not included. Including those would be tricky and require quite significant changes.

**Comment by jesperstarkar** [comment]
How come it then reports frame+2 and not frame-2? The correct frame is displayed, but the reported frame number is ahead of the frame displayed. SEEK 2 = 2 displayed and 4 reported. SEEK 300 = 300 displayed and 302 reported. 

I don't get "2" and "302" comes from, when we only ask for "0" and "300".

**Comment by ronag** [comment]
2.2
