### ISSUE TITLE
2.1: Make 16ch default audio channel layout on both channels and Decklink consumer

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/server#395]

**Comment by jesperstarkar** [comment]
It would be super brilliant to get rid of STEREO as default values for all audio layouts, setting everything to 16ch/passthrough.

2.2 or even 2.1? I can't see any reason why not.

@ronag

**Comment by ronag** [comment]
@jesperstarkar 8 channels passthrough, yes

**Comment by elanvrt** [comment]
Oh yes it does!

CCG 2.1.0.3440 beta2 and my own custom client test panel. 
Footage is a single-track 16-channel MXF file
Output on a Decklink 4Kpro

![16channels](https://user-images.githubusercontent.com/4322556/35055421-78cd8a2c-fbaf-11e7-8874-9424843799fd.jpg)

It seems not to work with a 16-track mono-channels file, so all 16 channels need to be in one single track.
However it does work with an 8-track mono-channels file, it play all 8 tracks.

**Comment by MauriceVeraart** [comment]
i prefer having as much channels as possible as a default 
if 16 is hard to make then 8 would be nice

**Comment by jesperstarkar** [comment]
> It will be 8 channels.

Does that mean that all 16-channel capabilities will be removed/disabled/or not working? If 16ch is an option, and it is as shown above, why go for 8 and not 16/passthrough?

**Comment by dimitry-ishenko** [comment]
+1 for 16 channels. We often put foreign tracks on channels 3 and up and in few cases needed more than 8 channels.

**Comment by ronag** [comment]
We're going with 8 channels for this release. We can increase to 16 channels in a future release.

There is a significant difference in terms of development between the two.

**Comment by dimitry-ishenko** [comment]
@ronag that's understandable. Thank you for your good work! :smiley:

**Comment by dirkdamerau** [comment]
+1 for 16 channel audio

**Comment by dimitry-ishenko** [comment]
Here we are almost 2 years later. @ronag @dotarmin any update on this? We do foreign tracks and need to be able to use 16 channels. It's a deal breaker for me. (Having to fall back to EVS for now.)

**Comment by BlakeB415** [comment]
+1 16 channel audio would be great!

**Comment by vasalmona** [comment]
+1 16 channel audio would be amazing! Would like to be able to run latest master instead of older NRK.

**Comment by dimitry-ishenko** [comment]
> **ronag** commented [on Jan 22, 2018](https://github.com/CasparCG/server/issues/395#issuecomment-359375645)
> We're going with 8 channels for this release. We can increase to 16 channels in a future release.

Has the future arrived yet? I am staying on NRK version 2.1 as I need 16 channels.

**Comment by Julusian** [comment]
This is now working.
I have verified it works for ffmpeg producer, decklink consumer, ndi producer and consumer. The other producers and consumers look like they will be fine, so do say if you have any issues with anything
