### ISSUE TITLE
Ubuntu 14.04.3: Binary CasparCG server died + Compilation fails 

### ISSUE THREAD

**Issue by zenny** [CasparCG/Server#396]
Hi,

I tried to run the binary build 2.1.0 master (03d43afba5604ba8b1bf2502c0f7489b81d0b421) , but it dies:

> $ ./run.sh 
> Type "q" to close application.
> Illegal instruction (core dumped)

However CasparCG client works fine.

Therefore, I tried to compile by cloning the git repo, but it failed with:

> /usr/bin/ld: cannot find -lsndfile
> collect2: error: ld returned 1 exit status

Tail of the log is as follows:

Scanning dependencies of target casparcg
[ 98%] Building CXX object shell/CMakeFiles/generate_docs.dir/generate_docs.cpp.o
[ 98%] [ 99%] Building CXX object shell/CMakeFiles/casparcg.dir/main.cpp.o
[100%] [100%] Building CXX object shell/CMakeFiles/casparcg.dir/server.cpp.o
Building CXX object shell/CMakeFiles/casparcg.dir/stdafx.cpp.o
Building CXX object shell/CMakeFiles/casparcg.dir/linux_specific.cpp.o
/usr/bin/ld: cannot find -lsndfile
collect2: error: ld returned 1 exit status
make[2]: **\* [unit-test/unit-test] Error 1
make[1]: **\* [unit-test/CMakeFiles/unit-test.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
Linking CXX executable generate_docs
/usr/bin/ld: cannot find -lsndfile
collect2: error: ld returned 1 exit status
make[2]: **\* [shell/generate_docs] Error 1
make[1]: **\* [shell/CMakeFiles/generate_docs.dir/all] Error 2
Linking CXX executable casparcg
/usr/bin/ld: cannot find -lsndfile
collect2: error: ld returned 1 exit status
make[2]: **\* [shell/casparcg] Error 1
make[1]: **\* [shell/CMakeFiles/casparcg.dir/all] Error 2
make: **\* [all] Error 2
Command exited with non-zero status 2
Build time 6:06.75
make failed

Thanks.

**Comment by Zebiolo** [comment]
On 2015-11-12 11:46, zenny wrote:
> [...]
> Therefore, I tried to compile by cloning the git repo, but it failed with:
> 
> > /usr/bin/ld: cannot find -lsndfile
> > collect2: error: ld returned 1 exit status

Have you read https://raw.githubusercontent.com/CasparCG/Server/2.1.0/BUILDING

1. Install GCC, make and cmake etc:

   sudo apt-get install build-essential cmake

2. Install development packages for libraries which are not bundled:

   sudo apt-get install libxrandr-dev libjpeg-dev libsndfile1-dev libudev-dev libglu1-mesa-dev


	Peter

**Comment by zenny** [comment]
@Zebiolo Thanks for the pointer. libsndfile1-dev was missing.

However, the built also failed to run similar to what had happened with the server binary from the builds.casparcg.com.

> $ ./run.sh 
> Type "q" to close application.
> Illegal instruction (core dumped)

Even running as sudoer outputs the same message. Nothing in the log directory!

How to debug?

**Comment by HellGore** [comment]
What CPU do you have?

**Comment by zenny** [comment]
> What CPU do you have?

AMD Phenom(tm) II X4 965 Processor

**Comment by HellGore** [comment]
I think your CPU does not support SSSE3

**Comment by zenny** [comment]
Yep, that is the cause. Is SSSE3 required by sfl lib?

**Comment by HellGore** [comment]
You could laborate with the lines in CMakeLists.txt containing:

```
        add_compile_options( -msse3 )
        add_compile_options( -mssse3 )
        add_compile_options( -msse4.1 )
```

Some of the compiler intrinsics that CasparCG uses will be disabled if you remove some of those lines. Furthermore I am guessing that if you get "Illegal instruction (core dumped)" without using key-only (uses an SSSE3 instruction) on a consumer, it means that the compiler has found an optimization using one of the instructions that your processor does not support.

**Comment by zenny** [comment]
@HellGore Tried by disabling all the options as you suggested, but the build failed. Since the CPU supports sse4, I tried to compile by disabling the -msse3 and -mssse3 lines, yet the situation is like the OT.

**Comment by HellGore** [comment]
Well, I am not sure of how I could help you any further then I guess. Your CPU is simply too old for the CasparCG Server.

**Comment by zenny** [comment]
yep, that sounds like it. I am trying now on a different machine which supports ssse3. Thanks anyway for your inputs.
