### ISSUE TITLE
4 line vertical timing delay with decklink 4k pro

### ISSUE THREAD

**Issue by domasx2** [CasparCG/Server#398]
Hey,

We've been using CasparCG to output tv game show cg using html producer. Mostly everything works great, but tech guys report that there is a vertical timing delay of 4 lines. We're using blackmagic's decklink 4k pro card. 
Any ideas?

Thanks!

**Comment by TomKaltz** [comment]
This issue is related to your hardware and not to CasparCG server.  Please consult the manual for your output card to adjust genlock timing.
