### ISSUE TITLE
[Feature Request for 2.1] Play Mediafile or Stream at original frame rate

### ISSUE THREAD

**Issue by NicholasRush** [CasparCG/Server#399]
Put frame sync off for a specific Producer on a channel layer.

Like so:
1-10 play [STREAM OR MEDIAFILE] sync=off

To play a media file or stream at original frame rate in that layer without interrupt the frame synchronisation in other layers.

http://www.casparcg.com/forum/viewtopic.php?f=3&t=3511

**Comment by HellGore** [comment]
Should work out of the box since the frame rate converting `framerate_producer` was added.
