### ISSUE TITLE
LOAD still image 2.0 vs 2.1

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#40]
Converted from [SourceForge issue 3601803](http://sourceforge.net/support/tracker.php?aid=3601803), submitted by kaosconman

Previously, on 2.0, when a still image, PNG, was loaded, it would display automatically.  Now, on the alpha release of 2.1, the PLAY command must be sent before it displays.

Server: 2.1.0.3385 UNSTABLE x64

**Comment by ronag** [comment]
2.2
