### ISSUE TITLE
DATA REMOVE returns 201, not 202

### ISSUE THREAD

**Issue by calmcl1** [CasparCG/Server#400]
When calling the `DATA REMOVE` remotely on a Caspar Server (currently using v 2.0.7, Win 10 x64), the returned code is `201`. Only the response string (`201 DATA REMOVE OK\r\n`) is returned, nothing else.

According to the wiki, code 201 means:
> 201 [command] OK - The command has been executed and data (terminated by \r\n) is being returned.

However, since the command does not return any further information, should it not return a code 202?
> 202 [command] OK - The command has been executed.

Indeed, the rest of the commands that only return the response string all return `202` codes.

...or, am I missing something?

**Comment by HellGore** [comment]
I just fixed this in 2.1 last week

**Comment by hummelstrand** [comment]
Thanks for reporting this bug, @calmcl1. Since this will be fixed in Server 2.1, I'm closing the issue. I'm afraid you'll have to work around this slight irregularity until Server 2.1 is production-ready.

**Comment by calmcl1** [comment]
Wonderful! :D
Good to know it's been taken care of, anyway :)
