### ISSUE TITLE
[2.1] FFmpeg option pix_fmt not supported

### ISSUE THREAD

**Issue by mjbartholomew** [CasparCG/Server#402]
I am setting up a stream and the service I am streaming to requires the pixel format Y'UV420p, yet CasparCG outputs Y'UV444. When attempting to use **-pix_fmt yuv420p** from within CasparCG's stream arguments, I receive the following error message in the log:

`[2015-12-02 11:20:29.227] [3888] [warning] Invalid option: -pix_fmt yuv420p`

The stream still launches, but the output remains in Y'UV444 pixel format.

From the CLI on my Mac, I am able to use the FFmpeg option **-pix_fmt yuv420p** and the output is in the correct format, so it appears to be an issue with CasparCG's support of FFmpeg.

*Note: While the stream will not be a multicast in production, I have tested as such so that it is reproducible for others besides myself.*

I have attached the log showing my config settings and the warning message received.

[caspar_2015-12-02.txt](https://github.com/CasparCG/Server/files/49932/caspar_2015-12-02.txt)

**Comment by florisporro** [comment]
+1, as far as I can see this prevents streaming to YouTube, which raises errors when receiving 444 content.

**Comment by rahulan** [comment]
@florisporro 

Thank You. finally I got the video with audio. 

if I want stream in aac codec what do I have to change here?

```
<args>-vcodec libx264 -x264opts keyint=45 -ar 44100 -tune zerolatency -preset ultrafast -b:v 4000k -minrate 2500k -maxrate 2500k -bufsize 1146k -vf format=pix_fmts=yuv420p -format flv</args>
```

**Comment by mjbartholomew** [comment]
Replace ``-ar 44100`` with ``-strict -2 -acodec aac -b:a 192k -af aresample=44100``

Here is a revised version:

    <args>-vcodec libx264 -x264opts keyint=45 -strict -2 -acodec aac -b:a 192k -af aresample=44100 -tune zerolatency -preset ultrafast -b:v 4000k -minrate 2500k -maxrate 2500k -bufsize 1146k -vf format=pix_fmts=yuv420p -format flv</args>

This will still result with an output aspect ratio that will confuse Quicktime when HTTP Live Streaming (HLS) is being used. Adding the video filter ``scale=720x480`` will solve that issue.

    <args>-vcodec libx264 -x264opts keyint=45 -strict -2 -acodec aac -b:a 192k -af aresample=44100 -tune zerolatency -preset ultrafast -b:v 4000k -minrate 2500k -maxrate 2500k -bufsize 1146k -vf scale=720x480,format=pix_fmts=yuv420p -format flv</args>

*Note: you can use resolutions other than 720x480. I am streaming SD content, so this is what I use in my configuration.*
