### ISSUE TITLE
CasparCG 2.1: Support for Video Stream Producer

### ISSUE THREAD

**Issue by baltedewit** [CasparCG/Server#409]
Hi,

2.1 is awesome with cef updates and ffmpeg updates. Something that will refrain me from using it as a 24/7 playout is the fact that it misses any kind of networked input.

Right now all ffmpeg input urls have to be files placed in the media folder. It would be very nice if we could have absolute urls, like we can have in 2.0.7.

If need be, the AMPC protocol could be updated to support absolute urls in the way it already does for the html producer. if PLAY 1-10 [HTML] EXAMPLE.COM\r\n gives the correct output. Makes me wonder why PLAY 1-10 [FFMPEG] UDP://127.0.0.1:1234/\r\n can't...

I understand that NDI will give some solution to network input, but it'll take a while before things like ffmpeg will support it, and it will mean workarounds will be needed for IPTV input..

**Comment by Julusian** [comment]
#480

**Comment by HellGore** [comment]
Works now in 2.1
