### ISSUE TITLE
Documentation structure || HELP vs Wiki

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/server#412]
I guess the Wiki should be updated based on changes in the description-methods related to HELP in 2.1. However, the structure is a bit challenging.
- Decklink producer's description and the sub-set of params it takes, should be described as a feature under Loadbg.
- FFMPEG Produces describes CHANNEL_LAYOUT, this is not mentioned under Loadbg.
- All Producers' callable params should be listed under Call.
- etc...

**Comment by HellGore** [comment]
I was thinking of doing something like this:

* Under the help for `PLAY` iterate through all examples starting with `PLAY` from each producer help describers.
* The same for `CALL` and all the producer examples starting with `CALL`.
* Do the same under `ADD` but instead iterate over the registered *consumer* examples starting with `ADD`.

This would mean that the main help for `PLAY`, `CALL` and `ADD` would still be very formal and consumer/producer agnostic, but the examples will be more informal and mention all examples from all consumers/producers.

Then we need to figure out a way of getting the contents of `amcp_commands.wiki` to be uploaded to http://casparcg.com/wiki/Template:CasparCG_2.1_AMCP_AutoGenerated if it has been changed after running `generate_docs` in the build_scripts.

**Comment by jesperstarkar** [comment]
Yeah. But in some cases you have just subsets of parameters available depending on the consumer/producer. It is in fact like overloading methods, so it should maybe be presented like different versions of the main LOAD, LOADBG, PLAY function on the top level? LOADBG with FFMPEG, LOADBG with STREAM etc. I'm thinking about the Wiki as the main source of documentation. It needs to be as complete as possible. For me it makes more sense to have a few overlapping descriptions in full format, rather than just having a lot of examples with a lot of quirks listed.

**Comment by HellGore** [comment]
What do you mean by "subsets of parameters available"

**Comment by ronag** [comment]
wiki
