### ISSUE TITLE
Scene producer inconsistent syntax for updating variables

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#413]
Currently done through CALL, but should support UPDATE. Even though the key/value syntax doesn't match either Flash or HTML templates, that's no problem. But I can't see why SCENEs should differ from Flash and HTML by being updated over CALL.

**Comment by HellGore** [comment]
Do you mean `CG UPDATE`? Because it supports that. The `scene_cg_proxy` class provides the functionality I think that you mean (if I didn't miss understand you). It parses the `<templateData />` structure and translates it to simple key values that the scene producer supports.

**Comment by jesperstarkar** [comment]
Good. I overlooked that.

**Comment by HellGore** [comment]
Only flat `<templateData />` structures are supported though, just like the client itslef.

**Comment by jesperstarkar** [comment]
@id=key and @value=value?

**Comment by HellGore** [comment]
Lets see:
```
<templateData>
  <componentData id="variable_name">
    <data value="value" />
  </componentData>
  <componentData id="variable2_name">
    <data value="value2" />
  </componentData>
</templateData>
```

...is parsed and translated by the `scene_cg_proxy` to a call to the delegated `scene_producer` with the parameters:
`"variable_name" "value" "variable2_name" "value2"`

Any other attributes or elements (like for example the usual `id="text"` on the `<data />` element are ignored).

**Comment by jesperstarkar** [comment]
Good.
