### ISSUE TITLE
Chopped up embedded audio on Bluefish card

### ISSUE THREAD

**Issue by elanvrt** [CasparCG/server#416]
I tried CCG 2.1.0 with my trusty Bluefish Epoch Core card, and I noticed a big problem with the SDI-embedded audio.
The sound is chopped up. Analysis showed that of every 40ms (25Hz frame rate), just over 5ms of sound is reproduced, as in this capture image with a 1000Hz sine wave:
![ccg210_bluefish](https://cloud.githubusercontent.com/assets/4322556/13467893/8ac1274c-e0a0-11e5-8a3d-fdb6b60cd8bc.jpg)

It happens with any kind of clip, SD, HD or audio-only. (and with all 2.1.0 builds I tried so far)
No errors appeared in the log. Embedded audio init looks normal: 
`Blue` Epoch Core [1-1|1080i5000] Enabled embedded-audio.`
If this cannot be fixed, CCG 2.1.0 will be as good as useless to me, as I am still very much dependent on these Bluefish cards.

Chris

**Comment by elanvrt** [comment]
No response until now. :-( 
Is Bluefish card support being given up in the 2.1 branch?

**Comment by baltedewit** [comment]
I can't imagine SVT still uses bluefish cards for their CasparCG machines
so I don't think you should expect any added support other than what is in
CasparCG right now.

Met vriendelijke groet,
Yours sincerely,
Balte de Wit

2016-09-12 11:38 GMT+02:00 Christiaan Van den Bossche <
notifications@github.com>:

**Comment by Julusian** [comment]
I am hoping this is better as bluefish have improved support in the years since this was opened
