### ISSUE TITLE
Errors after static code analyzer

### ISSUE THREAD

**Issue by drakmor** [CasparCG/server#418]
It's correct code ?

The '?:' operator, regardless of its conditional expression, always returns one and the same value: 1. filter.h 95
https://github.com/CasparCG/Server/blob/2.1.0/modules/ffmpeg/producer/filter/filter.h#L95

V547 Expression 'params.size() < 0' is always false. Unsigned type value is never < 0. color_producer.cpp 207
https://github.com/CasparCG/Server/blob/2.1.0/core/producer/color/color_producer.cpp#L207

V614 Potentially null smart pointer 'channel_remapper' used. audio_mixer.cpp 209
https://github.com/CasparCG/Server/blob/2.1.0/core/mixer/audio/audio_mixer.cpp#L209

**Comment by niklasR** [comment]
:grinning:
