### ISSUE TITLE
CEF proxy setting for GNU/Linux

### ISSUE THREAD

**Issue by deedos** [CasparCG/server#420]
I'm having some difficulties using Ubuntu/Unity global proxy server settings and the HTML producer.
Should I edit another env variable for proxy being effective on CEF? The requisitions juts do not go throu8gh the proxy.
My application only go to the internet to retrieve my data if my sysadmin turns the proxy off, so 100% is a proxy matter.
Using Linux build http://casparcg.com/builds/CasparCG Server/2.1.0/CasparCG Server 220f122a814beae306eaf4533a54e67df41209b1_linux.tar.gz , Ubuntu 14.04/4 and Server working perfectly for other tasks

Thanks in Advance

**Comment by dimitry-ishenko** [comment]
Have you tried exporting http_proxy and/or https_proxy?

**Comment by drakmor** [comment]
Hello.

You can use command line arguments like this:
casparcg.exe   casparcg.config  --proxy-server="socks://127.0.0.1:3000"

Details here: https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-proxy-resolution

**Comment by drakmor** [comment]
Deedos, works?

**Comment by deedos** [comment]
I could not test yet, hope to do asap and I 'll report back. thanks

2016-03-11 15:52 GMT-03:00 Roman <notifications@github.com>:

> Deedos, works?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CasparCG/Server/issues/420#issuecomment-195496177>.
>



-- 
Daniel Roviriego
(21) 972361654

**Comment by deedos** [comment]
Hi. Tested here with the options, but once I 'm in Linux, my run.sh was like:
LD_LIBRARY_PATH=lib bin/casparcg casparcg.config --proxy-pac-url=http:yyy.pac "$@" (and many others proxy settings as in here https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-proxy-resolution 
So, what to do ?
