### ISSUE TITLE
 Freezing thumbnail creation.

### ISSUE THREAD

**Issue by drakmor** [CasparCG/server#421]
After commit https://github.com/CasparCG/Server/commit/7246d2b6051dce6f9c17a848cf79d526861ba5c0 freezes on creating thumbnails for MP4 files with audio: CG1080i50.mp4, go1080p25.mp4.

**Comment by HellGore** [comment]
I will look into it

**Comment by Julusian** [comment]
No longer relevent now that thumbnail generation has moved to seperate project
@dotarmin
