### ISSUE TITLE
Is this a good observation?

### ISSUE THREAD

**Issue by mauricev78** [CasparCG/server#423]
Hi all

trying to do syncstart's on more then one channels divided over 2 machine's
all systems are gen-locked and running on Linux. with decklink quads on 1080i5000

When i try to sync start 8 channels with the normal client there is a too large possibility one channel will start 1 frame late.

After that i builded a little app that runs locally and starts the local channels referenced to the system clock. syncstart on the local machine's are doing a much better job. but between machines it's worse.

BUT

after syncing the clocks with NTP / Chrony things are looking REALLY GOOD
almost all startsalvo's result in 8channels in sync !!!!
started with the client and with the NTP app

My question is, 
Is there a direct relationship between system clock and command handling or internal buffering.

**Comment by ronag** [comment]
There should be no relationship.
