### ISSUE TITLE
Unhandled Exception Error

### ISSUE THREAD

**Issue by peterbbc** [CasparCG/Server#429]
Had a random crash after leaving CasparCG Server 2.0.7 running overnight.
I'd been playing about with the mixer effects (and mostly getting the syntax wrong) before the server crashed about 20 minutes after I'd sent my last command. (Log attached).

Final error was:
[2016-04-21 10:05:13.553] [2344] [fatal]   #######################
 UNHANDLED EXCEPTION: 
Adress:72697571
Code:3221225477
Flag:0
Info:13AEFAB8
Continuing execution. 
#######################

[caspar_2016-04-21.txt](https://github.com/CasparCG/Server/files/229589/caspar_2016-04-21.txt)

**Comment by peterbbc** [comment]
As a heads up I've had a similar error recently.
[2016-04-22 21:10:44.486] [3684] [fatal]   #######################
 UNHANDLED EXCEPTION: 
Adress:72697571
Code:3221225477
Flag:0
Info:14DEFAB8
Continuing execution. 
#######################

[caspar_2016-04-22.txt](https://github.com/CasparCG/Server/files/234174/caspar_2016-04-22.txt)

**Comment by peterbbc** [comment]
And again:
Always the same address and code. Sadly I'm unable to test on 2.1.0 as that has issues with the commands I'm using.

[2016-04-28 08:30:48.105] [5892] [fatal]   #######################
 UNHANDLED EXCEPTION: 
Adress:72697571
Code:3221225477
Flag:0
Info:255EFAB8
Continuing execution. 
#######################

[caspar_2016-04-28.txt](https://github.com/CasparCG/Server/files/240222/caspar_2016-04-28.txt)

**Comment by dimitry-ishenko** [comment]
Shooting in the dark here, but have you tried rebooting the server?

**Comment by peterbbc** [comment]
I have indeed, both the CasparCG server software, the hardware itself and gone for a full pull the power out and start from a complete cold boot.
I've now managed to get 2.1.0 to work after figuring out I was being an idiot on the reference signal side. So I'm going to leave that running and see if it crashes too!

**Comment by dimitry-ishenko** [comment]
OK good. Unfortunately, the error message doesn't say very much. And I believe the devs are now focusing on the 2.1 branch anyway.

**Comment by jimmn** [comment]
There were a lot of
[fence] Performance warning. GPU was not ready during requested host read-back. Delayed by atleast: 4 ms.

messages, including the one immediately before it crashed.

What hardware are you using and does it conform to the recommended specs?

**Comment by peterbbc** [comment]
Hardware is a HP Z440 Workstation.
CPU: Intel Xeon E5-1650 v3 (6 core at 3.5Ghz)
RAM: 16GB
GPU: nVidia Quadro M4000 (8GB)
HDD: All SSD

So yes, it meets/exceeds the recommended specs.

**Comment by jimmn** [comment]
Looks ok.  What about the driver for the Quadro, have you tried rolling back?

**Comment by peterbbc** [comment]
Yep, tried both older and newer Quadro drivers with no success and older versions of Blackmagic Desktop Video.
After a few days testing of the 2.1.0 builds it appears the issue no longer occurs, going to leave it running over the weekend to confirm.

**Comment by peterbbc** [comment]
Sorry for taking forever to respond, other work got in the way.
Oddly the issue no longer occurs in 2.0.7 nor do I seem to have any issues in the 2.1.0 builds, I've updated the drivers a few times since then so wouldn't surprise me if it was related to that.
Closing the issue.
