### ISSUE TITLE
Quad 2, no yellow with caspar only, when card is set to fill&key

### ISSUE THREAD

**Issue by peteraellig** [CasparCG/Server#431]
found an error
if I set the card in the Blackmagic Desktop Video Utility to channel 1/Fill AND Key / SDI 1 &SDI 2, i have no Yellow.
if I set the card in the Blackmagic Desktop Video Utility to channel 1/Fill only/SDI 1, i have Yellow!
This happens only in Caspar.
All other Programs like Photoshop export Image / Shotcut / Insta Playout are working correct.
[http://casparcg.com/forum/viewtopic.php?f=3&t=3738#p25855](url)

**Comment by HellGore** [comment]
Really strange, I have to investigate further and maybe contact Blackmagic about this.

Maybe the other programs you are using does not use the same pixel format when they submit frames to the decklink api? We use bmdFormat8BitBGRA. This is probably some kind of overflow bug in Blackmagic's colorspace conversion when external key is used.

**Comment by HellGore** [comment]
I have made a test image to reproduce the problem and to see what kind of colors are affected by the bug and in addition to yellow, cyan is also affected. When RGB values are between (251, 251, 0) and (255 255 0) as well as between (0, 251, 251) and (0, 255, 255).

![quad2_color_bug_detection](https://cloud.githubusercontent.com/assets/2980939/14880643/45c789e4-0d30-11e6-8047-658222c8b54a.png)

The two last gradients are yellow between 250 and 255 and cyan between 250 and 255. Only 250 is displayed as expected.

I have alerted Blackmagic about this issue.

**Comment by peteraellig** [comment]
thanks! so the error is in the Hardware or could it be solved in the driver?

**Comment by HellGore** [comment]
Either one. Only Blackmagic will know if it is in the driver or in the card firmware. I am positive they will be able to solve this without having to provide us with replacement hardware.

I am also guessing that the Decklink Duo 2 also has this issue.

**Comment by peteraellig** [comment]
new Desktop Video 10.6.5 Driver solves the problem.
thanks!
