### ISSUE TITLE
HTML producer DIAG, don't show empty frames as late frames

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#433]
I get the mechanism of RAF and why empty (non-rendered) frames are displayed as late frames, as there's just no time to calculate frame time from.

But could you actually tell which fames are empty, and avoid drawing these as late-frames to the DIAG window? I guess this is essential once DIAG data gets streamed over OSC, and you don't clearly see the picture of whats's happening as you visually do in DIAG window. 

![screen shot 2016-05-12 at 11 55 22](https://cloud.githubusercontent.com/assets/6236874/15210869/87a4c80a-1838-11e6-94e8-ed47d930a944.png)

**Comment by HellGore** [comment]
I could see whether they are empty or not, but it would not be enough anyway since there may be graphics on screen just not animating right now, and that would also be a false positive. I will remove the late-frame tag completely instead.

**Comment by jesperstarkar** [comment]
As discussed, late-frame shouldn't be entirely removed, just toggled off when there's no current callback registered for AF. Late-frame DIAG working good during animations
