### ISSUE TITLE
Key/Fill Displayed Incorrectly when ouput set to 1080p59.94 on Decklink Extreme 4k

### ISSUE THREAD

**Issue by TracyPeterson** [CasparCG/Server#434]
when using the decklink consumer setting of 1080p59.94, a "resolution not supported" error is thrown and the key and fill channels are shown as fill on both outputs.  Using same config, only changing resolution to 1080i, outputs display correctly: one fill, one key.

**Comment by HellGore** [comment]
Duplicate of https://github.com/CasparCG/Server/issues/305
