### ISSUE TITLE
Distribution without sample media (minimal distribution)

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/server#435]
I totally support that the main download bundle should keep supporting sample media. This is great for new users.

However. I install CasparCG 20+ times a year. I want to be able to download just the minimal required file-set.

Ideally we start offering the standard + a new mini distro through SourceForge. And then we will have some stats to navigate out from in further discussions on this topic.

@HellGore It is easy for you to do a secondary build that excludes sample media, I guess? Do you support the idea of distributing two sets?

**Comment by ronag** [comment]
Make a PR 😀
