### ISSUE TITLE
VERSION command is missing parameter for html

### ISSUE THREAD

**Issue by hummelstrand** [CasparCG/Server#437]
http://casparcg.com/wiki/CasparCG_2.0_AMCP_Protocol#VERSION

**Comment by jesperstarkar** [comment]
The AMCP command supports "CEF" parameter.

`VERSION CEF` returns "#201" with proper version data.


However, the version_describer doesn't list CEF as a valid component.

**Comment by jesperstarkar** [comment]
This can be closed. Fixed with #450
