### ISSUE TITLE
Decklink input does not support some interlaced/progressive mixed modes

### ISSUE THREAD

**Issue by premultiply** [CasparCG/server#439]
While trying to do some measurements regarding the av-delay issues I found that mixing some input modes with specific channel (output) modes does gives just black screen when using Decklink producer. If input signal is same as channel configuration everything is fine. But when mixing interlaced input with full rate progressive output (or vice versa) the result is just black screen. Tested on current 2.1 branch.

For example these input (Decklink Producer) to output (Channel config/Decklink Consumer) configurations fail:
1080i5000 -> 720p5000
1080p2500 -> 1080p5000
720p5000 -> PAL
720p5000 -> 1080i5000
PAL -> 720p5000
PAL -> 1080p5000
720p50 -> 1080p2500

But 1080i5000 -> 1080p2500 and 1080p2500 -> 1080i5000 does work.

**Comment by ronag** [comment]
Duplicate https://github.com/CasparCG/server/issues/714
