### ISSUE TITLE
Cb offset on Decklink output

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#44]
Converted from [SourceForge issue 3603756](http://sourceforge.net/support/tracker.php?aid=3603756), submitted by avanier

YCbCr values are offset by -4Cb for all non-black pixels that should be white on SDI output of Decklink SDI.

Bug found on system running
Windows 7 x64
Core i3-540
GeForce GTX 460 (Drv. V. 8.17.13.142)
Blackmagic Design Decklink SDI (Drv. V. 9.7.0.0) (It was confirmed other applications such as Adobe Premiere output correct levels for same source files)
Tested on CasparCG 2.0.3.3590 / 2.0.3.3760 / 2.1.0.3385 with identical results

Bug exhibited on material originating from original material provided in TGA, flash templates, and pictured alpha masks part of the CasparCG demo file library.

**Comment by ronag** [comment]
Fixed in 2.2
