### ISSUE TITLE
Internal Audio/Video sync needs bugfixing

### ISSUE THREAD

**Issue by premultiply** [CasparCG/Server#440]
Today a validated that CasparCG has an internal AudioVideo-Sync problem.

Measurement Setup:
[Vistek Valid Generator] -> [Decklink 4K Extreme (2), Decklink Producer->CasparCG->Decklink Consumer, Decklink 4K Extreme (1)] -> [Vistek Valid Reader]

Vistek Generator and Decklink Ouput are genlocked.

CasparCG: 2.1 0b5b222 on Windows 7 x64
Decklink Driver: 10.6.6

```
  Input      Ouput
    PAL ->     PAL:     -40ms (=1 Frame advanced)
    PAL -> 1080i50:     -40ms (=1 Frame advanced)
    PAL -> 1080p25:     -40ms (=1 Frame advanced)
 720p50 ->  720p50:     -20ms (=1 Frame advanced)
1080p25 -> 1080p25:     -40ms (=1 Frame advanced)
1080p25 ->     PAL:     -50ms (>1 Frame advanced)
1080p25 -> 1080i50:     -50ms (>1 Frame advanced)
1080i50 -> 1080i50:     -40ms (=1 Frame advanced)
1080i50 ->     PAL:     -40ms (=1 Frame advanced)
1080i50 -> 1080p25:     -40ms (=1 Frame advanced)
```

File playback is comparable but ffmpeg producer has slightly different av-sync behaviour (some ms more or less) on different containers or from different filewriters.

Related: #114 #329

**Comment by premultiply** [comment]
Please let me know if I could assist you with testing related to this issue.

**Comment by DouglasHeriot** [comment]
Would love to see this fixed! I’d love to start using Caspar CG for playout but this is definitely a blocker.

**Comment by ronag** [comment]
Closing in favor of #636. Please create a new issue if it still remains after that one is resolved.

**Comment by ronag** [comment]
It's a problem with CasparCG not handling ffmpeg stream start times
