### ISSUE TITLE
RemoteDebug works but how ?

### ISSUE THREAD

**Issue by mauricev78** [CasparCG/Server#442]
when i open the port in a browser i get a empty HTML

`<html> <head></head> <body></body> </html>`
when i do this i see in caspar
`ERROR:content_client.cc(101) No data resource avalable for id 27500`
i tried to do a javascript call `GetDevToolsUrl(true)`

but it gives
`ReferenceError: GetDevToolsUrl is not defined in the browser console`

**Comment by mauricev78** [comment]
tested on windows by the way with the latest nightly build 
f2fe60165ee8498a771403a8c38a967f63af5589

**Comment by hreinnbeck** [comment]
Please open in Chrome

**Comment by pkeuter** [comment]
@mauricev78 Place cef.pak and devtools_resources.pak in the path where your casparcg.exe lives. It'll work better then. It might be a good idea to pack these files into the zip at build time, but for now you have to compile yourself, or download the files from here: https://github.com/CasparCG/Server/tree/2.1.0/dependencies64/cef/bin/win32.

**Comment by mauricev78** [comment]
Thanks that does work already had benefit from this !

**Comment by jesperstarkar** [comment]
They are now included in the build. This could be closed @HellGore .
