### ISSUE TITLE
Very high GPU-load even when Idle

### ISSUE THREAD

**Issue by nytamin** [CasparCG/server#445]
I have a somewhat strange issue, CasparCG causes my GPU-load to be extremely high, even when idle. Due to the high idle-GPU-load that leaves not much left for actual work, like compositing and video-decoding, causing output to stutter like crazy.

I believe this to be hardware-related, as I see this problem on both Windows 7 & 10, Caspar 2.07 and 2.1 (latest build). On my other rig with another GPU I have no issues.

Hardware setup:
MoBo: Gigabyte Z97MX
CPU: Intel i7-4790K
GPU: GTX 960

Since this is not something causing a crash I don't have a log file to provide, but if there is something more I could provide to facilitate the bug tracking, just let me know.

I'm using GPU-Z to monitor the GPU-load.

**Situations I've experienced:**
(note: "idle" = no producers running.)
(CasparCG 210= build from 17-Jun-2016 17:08 )
Caspar not started: 0-1% GPU-load.

CasparCG 207, 1 channel configured, idle: 50% GPU-load.
CasparCG 207, 1 channel configured, 1-10 PLAY AMB: 60% GPU-load.
CasparCG 207, 2 channels configured, idle: 99% GPU-load.
If playing anything now, all playback stutters.

CasparCG 207, 1 channel configured, 1-10 CG 1 ADD someFlash.ft: 60% GPU-load.

CasparCG 210, 1 channel configured, idle: 12% GPU-load.
CasparCG 210, 1 channel configured, 1-10 PLAY AMB: 60% GPU-load.
When the video file is done playing, the GPU-load stays at 60% until a CLEAR 1-10, then it returns to 12%, a 1-10 STOP does not make the GPU-load go down.
# 

I have the latest drivers installed of course, and the behavior is the same both on windows 7&10. I experience no issues in other software, only CasparCG.

**Comment by baltedewit** [comment]
Hi,

Please make sure you have no other PCIe devices installed and that your card is installed in the 16x slot of your motherboard.

If you are still running into performance issues after this is probably card or even system specific. Please understand that only the Nvidia Quadro Cards are supported and only the quadro 2000 card is recommended.

ps: your motherboard has two physical 16x slots but only number one actually features a 16x connector. And your processor only supports a single 16x PCIe card.
