### ISSUE TITLE
Upgrade forum

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#447]
I see the need for three major features added to the forum:
- Mentions by username to ping users and ask questions
- Vote up/down for quality improvement
- Direct upload of images to easier enhance explanations with illustrations

**Comment by hummelstrand** [comment]
I would also like it to be easier to judge the reputation of the poster,
plus a way to subscribe to the threaded forum posts via email.

I've suggested SVT look at https://vanillaforums.org/

**Comment by jesperstarkar** [comment]
I think you have email subscriptions in place in the current forum. 

<img width="188" alt="screen shot 2016-07-01 at 13 49 48" src="https://cloud.githubusercontent.com/assets/6236874/16520768/b364746e-3f92-11e6-91d2-099d18601d83.png">

**Comment by hummelstrand** [comment]
What I've always lacked is a way to read/reply to the forum via email. Who
has time to browse a web forum and scroll to new posts (even though I
always have them sorted with the newest posts first...)

**Comment by dotarmin** [comment]
After the vacation periods I'll try to manage some time to checkout how upgrade the forum and to how to migrate the posts from the current one to the new one. But first, a appropriate forum needs to be found and vanillaforum as @hummelstrand  suggests seems to have what is requested.
