### ISSUE TITLE
Feature Request: Add subpath-parameter to CLS, TLS, FLS

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#449]
I want to have the ability to add a relative path to filter on which folders should be listed pr. CLS/TLS/FLS-call, as an optional parameter.

Example:

`CLS "subfolder"`

returns content both for 

```
[media_root]/subfolder        
[media_root]/subfolder/nested_subfolder
```

and

`CLS "subfolder/nested_subfolder"`

returns content just for

`[media_root]/subfolder/nested_subfolder`

The idea behind this request is to limit the amount of data being processed and transferred when querying large media folder structures.

This makes sense, and is a good (backward compatible) change in the AMCP protocol, right? Any reason this shouldn't be added?

**Comment by HellGore** [comment]
I committed a change on #524 just now that actually was more about this issue: https://github.com/CasparCG/Server/commit/c1ef012e379f805f75d2dee71d8129b8bf9f1630

**Comment by HellGore** [comment]
Fixed
