### ISSUE TITLE
Bug: channel_grid not honouring configuration

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#455]
`<channel-grid>false</channel-grid>` is the default configuration.

Channel_grid still works in this default configuration.

Also: setting the value to false explicitly still allows channel_grid to be created.

**Comment by jesperstarkar** [comment]
I now see that there's no code in the 2.1 repo containing "configuration.channel-grid", so this feature is probably not implemented at all?

Same goes for force-deinterlace

**Comment by HellGore** [comment]
```server.cpp:299``` has code for creating the ```channel_grid``` channel conditionally

**Comment by jesperstarkar** [comment]
Ok, but does it work? I can't see any effect from toggling this config value.

**Comment by HellGore** [comment]
The only thing that happens if you disable channel-grid in the config is that the low-res channel is not appended to the list of channels. The ```channel_grid``` command always uses the **last** channel available.

**Comment by jesperstarkar** [comment]
Thank you for the explanation.
