### ISSUE TITLE
Bug/unexpected behaviour: configurable AMCP commands, wrong response. 

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/server#456]
Mixer blend-modes are disabled by default. This bug/unexpected behaviour is valid in both default configuration and by explicitly disabling Mixer blend-modes.

If blend-modes are disabled globally, the mixer will still "set" a blend mode and respond with a positive 200-status.

If you query the layer for its blend mode it will report the blend-mode previously set.

I expect AMCP to respond negatively to setting blend-modes if these are disabled through config, and I expect AMCP not to respons a false-positive blend-mode in this case.

**Comment by jesperstarkar** [comment]
Same goes for `straight_alpha_output` and `channel_grid` (channel_grid config actually not being implemented at all #455).

**Comment by Julusian** [comment]
What response code would you expect for the 'failed' set? 
`600 [command] FAILED	[command] not implemented` looks to be the closest match. 
Perhaps adding `601 [command] FAILED	[command] disabled` would be better.

Would you also want them to be hidden from the help listings? Leaving them there could help users discover them, but it also may be a bit confusing as they won't work.

**Comment by jesperstarkar** [comment]
601 disabled is a perfect fit, imo.

**Comment by Julusian** [comment]
Ill raise a PR once 2.2.0 branch has stabilised. For now, you can see the changes at:
https://github.com/Julusian/CasparCG-Server/tree/456-amcp-disabled-commands

I ended up going with 600 as the error code as that was already being used for this purpose with thumbnail generation.
channel_grid hasnt been done as it operates on the last channel (as mentioned by hellgore in #455). Both straight_alpha_output and blend_modes now return this error though.

**Comment by jesperstarkar** [comment]
Thank you Julian! Nice and important little fix! Will test it later.
