### ISSUE TITLE
CMake Error: The source directory "/home/technik/Server/build/x64" does not exist.

### ISSUE THREAD

**Issue by macpit** [CasparCG/Server#458]
Error:

`~/Server/build$ cmake -G "Unix Makefiles" -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo
CMake Error: The source directory "/home/technik/Server/build/x64" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
`

**Comment by dimitry-ishenko** [comment]
Cool

**Comment by dimitry-ishenko** [comment]
What platform are you running on?

**Comment by dimitry-ishenko** [comment]
At the end of the command replace the `CMake` part with `..`
You will also probably need to remove -A x64. I get an error that Unix Makefiles generator does not support platform specification. Using CMake 3.3.1.
