### ISSUE TITLE
Bug: 2.1 NDI - not discovered on the network

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#460]
2.0.7 channels appear as Bonjour sources in the LAN, and I can connect to them.

With 2.1, same machine, same firewall settings (disabled), same config: No sources appear, and I can't connect.

Aynone else share this experience?

**Comment by MasterDalK** [comment]
I can't seem to get NDI to work with 2.1 either, works fine on 2.0.7 as you said.

In the console on 2.0.7 I get this
>[2016-12-02 21:11:22.279] [4056] [info]    newtek-ivga[not connected] Successfully Initialized.
>[2016-12-02 21:11:22.281] [6428] [info]    output[1] newtek-ivga[not connected] Added.

However the only the first line appears in 2.1.0.

**Comment by 5opr4ni** [comment]
Hi

NDI works grate, but there is an issue with the Newtek upgrade software.  It fails to copy one of its files during airsend upgrade installation, so you have to do that manually.  I'll be back with witch file. 

Olle

**Comment by MasterDalK** [comment]
Confusing that it works in 2.0.7 but not 2.1.0 without that file. Thanks for the heads up.

**Comment by 5opr4ni** [comment]
2.07  32      2.1  64

/  Olle

**Comment by HellGore** [comment]
Copy `C:\Program Files\NewTek\NewTek NDI AirSend Updater\Processing.AirSend.x64.dll` to `C:\Windows\System32\`

**Comment by jesperstarkar** [comment]
This works well. Thank you both @5opr4ni and @HellGore.
