### ISSUE TITLE
CPU usage goes up when file has finished playing in 2.1.0.7e7ef09

### ISSUE THREAD

**Issue by pkeuter** [CasparCG/Server#461]
It appears that in the latest dev build the entire CPU usage goes down with the same config (65% on idle with 2.0.7 vs 45% on 2.1.0.7e7ef09). Even when playing a file the usage stays low, 50% vs 75% which are pretty nice numbers. But there is a problem when the file finishes playing and I do not clear the channel afterwards (with LOADBG 1-1 EMPTY AUTO), the CPU of the dev build starts going up to 75% or sometimes a bit higher, until I clear the channel.

I would say this is unusual behaviour since a clip that has been paused should not be eating CPU, should it? This only happens on video files by the way so it appears the ffmpeg producers has something to do with it. I've tried with multiple files, like AMB and WIPE, but also with my own mov and mp4 files. It happens every time.

I don't know if this plays any part but I do want to point out that in the logs of both versions there is a different order of messages:

### 2.1.0.7e7ef09
```
play 1-1 amb
[2016-08-05 09:24:46.963] [15408] [info]    Received message from Console: play 1-1 amb\r\n
[2016-08-05 09:24:47.073] [2080]  [info]    ffmpeg[AMB.mp4|1920x1080p25.00|19/268] Initialized
[2016-08-05 09:24:47.096] [2080]  [info]    transition[empty=>ffmpeg[AMB.mp4|1920x1080p25.00|19/268]] Initialized
#202 PLAY OK
[2016-08-05 09:24:47.145] [12732] [warning] [ogl-device] Performance warning. Buffer allocation blocked: 0.052
```
### 2.0.7.e9fc25a

```
play 1-1 amb
[2016-08-05 09:19:43.876] [17344] [info]    Received message from Console: play 1-1 amb\r\n
[2016-08-05 09:19:43.909] [12040] [info]    ffmpeg[AMB.mp4|1920x1080i50.00|0/268] [video-decoder] H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
#202 PLAY OK
[2016-08-05 09:19:43.917] [12040] [info]    transition[empty=>ffmpeg[AMB.mp4|1920x1080i50.00|0/268]] Initialized.
[2016-08-05 09:19:43.934] [12040] [debug]   Executed command: PlayCommand
[2016-08-05 09:19:43.937] [244]   [info]    transition[empty=>ffmpeg[AMB.mp4|1920x1080i50.00|0/268]] End Of File.
[2016-08-05 09:19:44.004] [244]   [info]
+---------------+
| filter_buffer |default--[1920x1080 1:1 yuv420p]--filter_buffersink:default
|   (buffer)    |
+---------------+

                                                       +-------------------+
filter_buffer:default--[1920x1080 1:1 yuv420p]--default| filter_buffersink |
                                                       |   (buffersink)    |
                                                       +-------------------+


[2016-08-05 09:19:44.049] [244]   [info]    [frame_muxer] simple 1920x1080p25.00
[2016-08-05 09:19:44.067] [244]   [info]    transition[empty=>ffmpeg[AMB.mp4|1920x1080p25.00|1/268]] Uninitialized.
```

I noticed that there isn't a `transition[empty=>ffmpeg[AMB.mp4|1920x1080i50.00|0/268]] End Of File.` in 2.1.0. Could this be the problem? That the end is never noticed?

I am using the screen consumer by the way. When I close the screen consumer the CPU-usage obviously lowers. But it goes down even more when I call the clear command. So I think the problem is in the ffmpeg producer never "seeing" the end.

**Comment by pkeuter** [comment]
Ok. So I did some profiling here. The selected part is the part where the video has finished playing. As you can see the usage is going up here pretty bad.
 
![image](https://cloud.githubusercontent.com/assets/433441/17456369/9ef0b0e2-5bd5-11e6-8ec9-395323026943.png)

This is the "hot code"-stack:
![image](https://cloud.githubusercontent.com/assets/433441/17456377/fdb867d2-5bd5-11e6-96e5-2174becb5075.png)

Now, before the CPU goes up (the video is playing), the tick-function runs as well. But it takes about 0.5% CPU. When the file is at its end. This goes up to 42%. The stack goes down to OSC, but I think the problem lies before that. The tick-function might be getting into a very fast loop here (maybe because there aren't any more frames to be generated, do we need to throttle the function then?).

I'm finding it hard to identify the exact problem, but I am still trying, and will get back to it when I find something. It would be nice though if someone like @ronag or @HellGore could help me narrow this down, as I would be glad to submit a pull request.

**Comment by ronag** [comment]
Change
```cpp
while(full() && !seek_target_ && is_running_)
						cond_.wait(lock);
```

to

```cpp
while((eof_ || full()) && !seek_target_ && is_running_)
						cond_.wait(lock);
```

**Comment by pkeuter** [comment]
Thanks @ronag! I've submitted the PR #462 (first one referenced here is a wrong one (wrong markup).

I thought @HellGore just did a whole bunch of refactoring in 687eaaf. What is wrong with that?

**Comment by ronag** [comment]
@pkeuter: I haven't looked into that. All I can see is that there is still a lot of half decent code I wrote in a hurry 5 years ago still lying around.

The main issue with the ffmpeg producer is that it is frame based instead of using presentation timestamp provided by ffmpeg. Because of this the implementation is quite fragile, especially when it comes to syncing audio & video, looping and seeking in general.

**Comment by dimitry-ishenko** [comment]
@ronag, wouldn't they be required to open source it under the terms of GPL? Or do they have a separate license from SVT?

**Comment by ronag** [comment]
@dimitry-ishenko: As long as they only use it internally and don't sell it as a product they can do whatever they want. As a consultant it is none of my business.

**Comment by pkeuter** [comment]
So how does that work then? Is it now impossible for you to ever commit a fix to the ffmpeg-parts in Caspar because things you would change would always intersect with the work you've done for the three clients?

**Comment by ronag** [comment]
@pkeuter When working as a consultant all code you write is the property of the client. I am not allowed to use any code written. Essentially I have to erase it from my drive when the contract ends. There is nothing stopping me from re-doing it from scratch.

**Comment by pkeuter** [comment]
True, interesting though, but definitely off topic :-) Problem has been solved (thanks for the help) so I'll close this and hope you (or someone else) merges the PR soon!
