### ISSUE TITLE
Spelling error: "recieved"

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#47]
Converted from [SourceForge issue 3607245](http://sourceforge.net/support/tracker.php?aid=3607245), submitted by hummelstrand

Just debugged a log from 2.0.3.3590 STABLE and found that "recieved" is misspelt.

Here's a sample: 
[03/07/13 07:50:26] [062BC578] [debug]   flash-player[cg20.fth.pal|1024x576] [command]      <invoke name="OnCommand" returntype="xml"><arguments><string>Command recieved @GetInfo@?@</string></arguments></invoke>

The devil is in the details...  :)

**Comment by dotarmin** [comment]
> I actually adopted this spelling error, and still struggles with it. Can someone be sued?

@jesperstarkar Can this issue be closed?

**Comment by jesperstarkar** [comment]
It belongs to TemplateHost. Can be closed.

**Comment by dotarmin** [comment]
> @jesperstarkar It belongs to TemplateHost. Can be closed.

I can copy it over to appropriate the CasparCG/templatehost repo.
Thanks!

**Comment by Julusian** [comment]
Actually, it is relevant to this repository, not the templatehost
https://github.com/CasparCG/Server/blob/2.2.0/modules/flash/producer/FlashAxContainer.cpp#L623

**Comment by dotarmin** [comment]
@Julusian Then it has to be fixed in both projects. Thanks! :)

**Comment by ronag** [comment]
2.2
