### ISSUE TITLE
Decklink playout stops with 4K files.

### ISSUE THREAD

**Issue by Canigou77** [CasparCG/Server#473]
I've a 4K PRO dekclink and I plays 4K files with a channel configured in dci2160p2400. I've build a 2.1.0 version on windows sources of June.
When a 4K file is playing after a while, image freezes. The delay could be some minutes. The test is to play a 4K file with FFMPEG and decode on DeckLink. The issue occurs with multiple files.
I see that I don't have ressource problems (CPU/GPU/memory).
The decklling driver is 10.6.8.

I jump in the code and I updated the run() function in /ffmpeg/producer/input/input.cpp with the eof_ check
I did some tests in that file with traces. My last conclusion is that the try_pop_video() function doesn't call the cond_.notify_one() . Then, the image is frozen.

I'm not sure that my analysis is correct but I'm not able to go further now. I focused on 4K playout and I don't know if the issue occurs for HD files.

Do somebody meet a behaviour like that ? How can I help you on this issue ?

**Comment by HellGore** [comment]
Please try with newest build and report back.

**Comment by Canigou77** [comment]
It's OK now with the new code.
I close this one.
