### ISSUE TITLE
custom format info to client

### ISSUE THREAD

**Issue by mauricev78** [CasparCG/Server#478]
hi all

i added in /core/video_format.cpp
the following line on line 67
`{ video_format::xMYRES, 1280, 1024, 1280, 1024, field_mode::progressive, 30000, 1000, L"MYRES", { 1602, 1601, 1602, 1601, 1602                          } },`

and added in /core/videoformat.h
the following line on line 70
`xMYRESS,`

this gives me a screen consumer that does what i want i did not know it was that simple ;)

but in the standard client the transform widget (mixer fill command) only show zero's as if it 
can not retrieve the channel resolution. is there a other place where i have to add the channel resolution too make this work ??

grt
Maurice

**Comment by HellGore** [comment]
The CasparCG Client has no idea what "MYRES" means. It will at least need a new `INSERT INTO Format` line in `src/Core/Sql/Schema.sql` and you need to remove the sqlite-database in your `$HOME/.CasparCG`.

Btw this is a question, not an issue.

**Comment by dotarmin** [comment]
Questions such as this one should be asked in the official CasparCG forum.

**Comment by mauricev78** [comment]
Oh sorry about that will move it to the forum

thanks HellGore will have a look into it
