### ISSUE TITLE
Release version of 2.1

### ISSUE THREAD

**Issue by elanvrt** [CasparCG/Server#479]
Dear developers, 

It's been since december 2014 that a "stable and production-ready" version of CasparCG has been released.

Is there any hope we can get such a release version of 2.1 anytime soon?

**Comment by HellGore** [comment]
I have created a forum thread http://casparcg.com/forum/viewtopic.php?f=3&t=4060

The issue tracker is not for asking questions. The forum is more appropriate for that.

**Comment by dotarmin** [comment]
> The issue tracker is not for asking questions. The forum is more appropriate for that.

I couldn't agree more!
