### ISSUE TITLE
Flexible field order handling

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#48]
Converted from [SourceForge issue 3014286](http://sourceforge.net/support/tracker.php?aid=3014286), submitted by hummelstrand

Enable per-clip command for setting for field dominance of pre-rendered videos played by the FFmpeg Producer, making it possible to switch the field dominance of interlaced videos. This would trigger the field dominance switcher function. 

Expose the list of interpretation rules used for such things as the field dominance switcher function, in a user-editable text file.
[
Enable a per-session setting of the field dominance render setting in the Flash Producer so that lower/even field rendering is supported.

**Comment by hummelstrand** [comment]
Cleaning out old and irrelevant issues.

**Comment by jesperstarkar** [comment]
2.2.0 FFmpeg filters actually solve this, I believe.
