### ISSUE TITLE
SEEK audio sync loss

### ISSUE THREAD

**Issue by TondaKrist** [CasparCG/Server#481]
After SEEK command, audio is out of sync. Even rounding SEEK to nearest GOP does not solve this. When using CasparCG fork with MAV/EVS, it is working with rounding, but there are performace issues.

**Comment by HellGore** [comment]
The ffmpeg producer has now been replaced by the one in 2.0.7. This might resolve this issue.

**Comment by TondaKrist** [comment]
Sorry, are you talkning about replacement in 207 or about 210, where you replaced producer from 207? Thanks.

**Comment by jesperstarkar** [comment]
210 now has the same ffmpeg producer as 207,  so you ahould test the latest build (builds.casparcg.com) of 210.

**Comment by TondaKrist** [comment]
Yeah, but this seeking issue is there from 207 stable. In 207 there is almost impossible to seek without sync loss in MPEG2 using GOP12 and MP2 audio. I will try and let you know. Thanks for feedback

**Comment by jesperstarkar** [comment]
Please try 210 anyway. 207 is not being developed, and will not be developed further. And a lot of things have happened between 207 and the current 210, so the problem might just be gone by now. 

Please test ang give valuable feedback to help the dev team.

**Comment by TondaKrist** [comment]
Trying each day latest builds, but still audio sync is lost after SEEK. There is a file for tests to reproduce: http://download.satplus.cz/PUBLIC/TENIS.mpg

Try to jump to 20 minutes for example (CALL 1-1 SEEK 30000)

**Comment by ronag** [comment]
Closing in favor of #636. Please create a new issue if it still remains after that one is resolved.

**Comment by TondaKrist** [comment]
Will be that build available for download for Windows?  
http://builds.casparcg.com/CasparCG%20Server/2.1.0




Dne Mon, 18 Dec 2017 16:59:46 +0100 Robert Nagy <notifications@github.com>  
napsal(a):

**Comment by ronag** [comment]
@TondaKrist: when finished yet, I hope to finish it up before the end of the year
