### ISSUE TITLE
Screenconsumer framestutter 29.97/30 fps modes

### ISSUE THREAD

**Issue by mauricev78** [CasparCG/server#482]
It seems that the screenconsumer 
is stuttering / dropping frames in these modes.

setup is with clips in the same native format as the channel
Vsync on in the consumer settings 
display output on the  same refreshrate as the channel or double

tracing / searching the log gives me as far as i can trace it 
no frame dropping by the FFMPEG producer.
diag screen is also not showing any droppings
tested multiple clips / codecs 
log is saying me that framerate conversion / blending is not initiated.

is there a  way  to change the buffer size for the screenconsumer
like in the decklinkproducer  to see if there is too small buffer perhaps ?

**Comment by HellGore** [comment]
It probably is not a performance problem, but if it is you could try `<auto-deinterlace>false</auto-deinterlace>` in the screen consumer config.

> on the same refreshrate as the channel or double

Are you 100% sure of this? The high precision timer we use in caspar to keep the pace could have a different idea of how long 1001/60000 or 1/60 seconds is than your graphics card thinks. If you try with vsync off you will probably see that no frames are dropped/late, but with tearing instead.

If you are using an Nvidia graphics card you could try creating a custom resolution in the NVIDIA Control Panel where timings can be adjusted.

**Comment by seccpur** [comment]
My guess is ffmpeg producer does not parse a media file to detect fps and only uses the pre-defined standards, so any variation will lead undefined behavior like lip sync or false media duration value. If Caspar can fix this nonstandard video could be played better.

**Comment by mauricev78** [comment]
Hi @HellGore where can i find these timers
and how are/were these calculated.
i have a detailed EDID of the displays in use where i maybe 
can calculatethe timer from in this specific situation


LS
Maurice

**Comment by HellGore** [comment]
Do you mean the timer in caspar? It is only based on the videomode of the channel, and is not configurable beyond changing the videomode. But the videomode in caspar should of course match the clips you want to play, so you are left with trying to change the refresh-rate of the monitor.

I have never created a 59.94Hz mode in the Nvidia Control Panel but I have successfully created a 50Hz mode.

NVIDIA Control Panel -> Display -> Change resolution -> Customize
allows for creating custom resolutions.

**Comment by mauricev78** [comment]
hmm while i view the diag window

With vsync on i see a "cadance" off the screen producer dropping/repeating frames in a fixed rhythm even when black. 

With vsync off this is less / dissapears but frame tearing appears. 

am i right if i say the videocard is out of sync with the consumer (or the other way around ;) )
where is this vsync coming from i thought this was a sort off feedback from the videocard to the software in what pace it is running.

LS
Maurice

**Comment by HellGore** [comment]
The screen consumer does not return true on ``has_synchronization_clock()``. But if the screen consumer was designed to be able to provide sync then it could "drive" the channel based on vsync. If you on the other hand add a decklink consumer on the same channel it will "drive" the channel. That could make you not see dropped/repeating frames.

It is only when no consumer "drives" a channel that the internal ``high_prec_timer`` is used instead.
