### ISSUE TITLE
[2.1.0 @ 009816d] Video-stream overflow

### ISSUE THREAD

**Issue by dimitry-ishenko** [CasparCG/Server#485]
I am running version 2.1.0 at commit 009816de6e071c6a35c74b0954d04cf61005b971 with 2 channels. This is my shadow server. The main server runs 2.0.6.

When playing 2 videos -- one on each channel -- channel 2 stops playing after a few seconds with error: `video-stream overflow. This can be caused by incorrect frame-rate. Check clip meta-data.` The video on channel 1 keeps playing.

These same files continue playing totally fine on the main server (2.0.6). Attached is the log.

[caspar.txt](https://github.com/CasparCG/Server/files/527619/caspar.txt)

**Comment by dimitry-ishenko** [comment]
UPDATE: it seems to not be related to the fact that I have 2 channels.

I tried playing just the 2nd video on channel 2 all by itself and it also stops.

**Comment by HellGore** [comment]
Framerate I think is the problem. I might have to implement a rounding of the framerate to the closest matching broadcast rate. This might be the problem. As the file is reported by ffmpeg as 2997/100 (inexact) fps instead of 30000/1001 (exact).

**Comment by HellGore** [comment]
I am pretty sure that is the problem, since for the audio cadence I already do this rounding so it needs to be done for video framerate as well. Could you give me the file?

**Comment by dimitry-ishenko** [comment]
@HellGore I will try to make a small clip of it that can reproduce the problem. The current file is 8GB and I think the content has some stuff, which I can't release

**Comment by dimitry-ishenko** [comment]
@HellGore I feel stupid. I think the file just didn't rsync properly to the shadow server. I made a snippet and re-ran rsync to copy it over and now I can't reproduce the problem. Everything plays fine on both servers.

**Comment by HellGore** [comment]
I still think it is a problem though. Because:

"Frame blending frame rate conversion required to conform to channel frame rate."

This would not have happened if the `ffmpeg_producer` reported 30000/1001 to the `framerate_producer` instead of 2997/100

**Comment by HellGore** [comment]
Do you experience that the audio drifts out of sync when approaching the end of the file?

**Comment by dimitry-ishenko** [comment]
I haven't noticed sync problem so far. I am now playing 3-hr long clip and will keep an eye on it. Will let you know afterwards.

**Comment by HellGore** [comment]
It could be that after an hour or two you will notice 2 frames being blended together so it will look blurry. You may not notice the audio sync drift during only 3 hours.

**Comment by HellGore** [comment]
What software has generated this incorrect frame rate?

**Comment by dimitry-ishenko** [comment]
ffmpeg with -r 29.97 option.

I did play the file and there was no noticeable drift.

**Comment by HellGore** [comment]
I believe this calculates how many frames until the blending is exactly between two frames:

![100/2997 * x - 1001/30000 * x = 50/2997]
(http://latex.codecogs.com/gif.latex?%5Cfrac%7B100%7D%7B2997%7D%20x%20-%20%5Cfrac%7B1001%7D%7B30000%7D%20x%20%3D%20%5Cfrac%7B50%7D%7B2997%7D)

x solves to 500000 (~4.63 hours) so that would mean that after 1000000 frames exactly 1 frame drift, the next in between frames should be at 1500000.

Note that the image degradation because of the frame blending will be gradual up to 500000 so it is a problem much earlier than that.

**Comment by dimitry-ishenko** [comment]
@HellGore thanks for the math. Since it was a UBD, should I close this issue?
