### ISSUE TITLE
2.1 bug: Channel outputs opaque black when Alpha is set to 0 on top layer

### ISSUE THREAD

**Issue by nytamin** [CasparCG/server#486]
Bug description:
When playing a media clip that has an alpha channel and setting the OPACITY of that layer to 0 the whole channel outputs black color (not transparent).

From my tests the bug appears only if:
- The media clip has an alpha channel
- The media clip is played on a top layer (i.e. nothing is played on a layer above it)
- The opacity of that layer is set to 0

How to reproduce:
CLEAR 1
PLAY 1-20 CG1080i50
MIXER 1-20 OPACITY 0

What happens:
The whole channel outputs opaque black color
What is expected to happen:
The layer should become transparent

Caspar version: 2.1.0 13-Oct-2016 15:29

**Comment by HellGore** [comment]
Really tricky to figure out but a one liner fix

**Comment by jesperstarkar** [comment]
Good job! We'll test and get back to you.

**Comment by HellGore** [comment]
It also solves the problem when `MIXER KEYER` is used without a layer above to key.

**Comment by jesperstarkar** [comment]
@ronag is this still valid? I have no system to test on this week. Also, if valid - is it really 3.0 and not 2.x?

**Comment by ronag** [comment]
Can't reproduce in 2.2.
