### ISSUE TITLE
Reference signal not detected

### ISSUE THREAD

**Issue by Canigou77** [CasparCG/Server#489]
Hi, working on the last 2.1.0 code under Windows with BMD Desktop Video 10.8.2 and a BMD 4K pro card.
A PAL reference is connected. BM Desktop Video Setup software confirms the presence of a PAL reference.
But CasparCG says always "Reference signal: not detected". Even if I unplug/plug the cable.
I think it's a bug but I don't know where.
Your opinion ?

Second point : what is the impact of presence/miss of reference signal in CasparCG ?

**Comment by HellGore** [comment]
The video mode in Caspar must be incompatible with the PAL reference. Only 25 fps and 50 fps modes will get "Reference signal: locked". You can change your reference signal generator to NTSC and it should work (or 24 fps if that's what you are outputting).

The impact differs depending on what you have hooked to the SDI output of Caspar, if it is a machine like a monitor then it does not matter (it will show what it gets), but if it is a machine with video contribution from different sources like a video mixer it could matter.

If the video mixer has frame buffers (frame stores) on the SDI inputs it matters less whether you are genlocked or not. It will still matter though if the 4K pro internal clock drifts in relation to the video mixer's clock.

**Comment by Canigou77** [comment]
OK thanks a lot. I can close it.

**Comment by HellGore** [comment]
So what video mode where you running?

**Comment by Canigou77** [comment]
I was in 24fps. If I switch to  25fps, I see the "correct" behaviour.
