### ISSUE TITLE
PSD producer crashes Caspar2.1 using interlaced output with excessive resources.

### ISSUE THREAD

**Issue by DavidORiley** [CasparCG/server#491]
The fault can be replicated by setting caspar to output an interlaced format, i.e.
NTSC or PAL or 1080i50 or 1080i60.

Now play a psd template, i.e.
CG 1-180 ADD 1 “CLOCK 1” …	(Clock1 is  a small clock 201x52px)

see below diag screen showing an increase in “produce-time”
![psdproducer](https://cloud.githubusercontent.com/assets/23194423/19897763/3f22d17a-a051-11e6-8179-c4f8c7930489.png)
If we now play another four templates of any size, on four different video layers we have used more than the available resources and many frames will be dropped. Caspar usually crashes soon after this.

In contrast if the same psd files are played having started caspar using a non-interlaced output, i.e. 720pxx or 1080pxx or 2160p30 then more than thirty templates have been tested with no dropped frames and very little resource being used.

The above has been replicated using;

Ubuntu 16.04
Caspar Server b59ec2b89fbc8a2fbccaaa42d623db97a241a54b_linux (also five previous versions)
Decklink 4K Extreme – Driver 10.8.1
Intel HD4600
Also tested with;
Nvidia FX5600 – Driver 340.98

Windows 7
Caspar Server b59ec2b89fbc8a2fbccaaa42d623db97a241a54b_windows
Bluefish 444 - 
Nvidia FX5600 – Driver R340 U14 (342.00)

**Comment by HellGore** [comment]
I think it is a combination of the sleep in https://github.com/CasparCG/Server/blob/2.1.0/core/producer/scene/scene_producer.cpp#L322 and TBB not having enough threads to spare in the `parallel_for_each` call in https://github.com/CasparCG/Server/blob/2.1.0/core/producer/stage.cpp#L96

The reason for the sleep is that the `scene_producer` cannot know whether the producers on each layer is system clock sensitive or not (whether the rendered frame depends on the system clock or not).

Try removing the line at https://github.com/CasparCG/Server/blob/2.1.0/core/producer/scene/scene_producer.cpp#L322 and recompile and report back.

**Comment by HellGore** [comment]
Btw, what do you mean with "crashes"? It should not happen regardless.

**Comment by DavidORiley** [comment]
Hi HellGore,

Many thanks for your response. I have tried compiling on ubuntu 15.04.5 and
following the building instructions I am getting the following error;

c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [core/CMakeFiles/core.dir/consumer/output.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [core/CMakeFiles/core.dir/diagnostics/call_context.cpp.o]
Error 4
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [core/CMakeFiles/core.dir/diagnostics/osd_graph.cpp.o] Error 4
make[1]: *** [core/CMakeFiles/core.dir/all] Error 2
make: *** [all] Error 2
Command exited with non-zero status 2
Build time 1:35.03
make failed
dave@E5500:~/git/caspar/Server/build-scripts$ cmake --version
cmake version 2.8.12.2
dave@E5500:~/git/caspar/Server/build-scripts$ lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:    14.04
Codename:    trusty

Your help would be much appreciated!

Thanks,
Dave.

**Comment by HellGore** [comment]
I don't know why your compiler crashes. I can say that I use 14.04 LTS when compiling CasparCG, not 15.04.

**Comment by DavidORiley** [comment]
OK, I have done an install of 14.04.3 and have compiled with the line
removed. This has stopped the large increase in product-time as you
suggested. Meaning I can play many psd files, which is great!

It has introduced some issues which are some FILL commands are either being
ignored or miss timed.

I have just found this, please advise what information would help you?

Thanks again.

**Comment by HellGore** [comment]
> It has introduced some issues which are some FILL commands are either being
ignored or miss timed.

Could you be more specific?

**Comment by DavidORiley** [comment]
Please see attached videos. Both were taken sending the same commands which can be seen in the attached log files. 1080p30 shows how the graphics should transform. 1080i50 transforms position five from the wrong place which would happen if the command on Line 177 was not sent or is not being processed?

For my own tests I have sent hundreds of positions. If I check which positions are wrongly transformed it is different each time I play the test client script.

[reporting.tar.gz](https://github.com/CasparCG/Server/files/569327/reporting.tar.gz)

**Comment by dimitry-ishenko** [comment]
@DavidORiley are you running Diagnostics under Linux? Through WINE or can it be natively compiled? I thought Diagnostics was removed since 2.0.7

**Comment by DavidORiley** [comment]
I run everything natively under Linux, I do not use wine.

**Comment by dimitry-ishenko** [comment]
@DavidORiley so does the Diagnostics app come bundled with 2.1 or did you compile yourself? And is it working with 2.1?

**Comment by DavidORiley** [comment]
I am guessing you are asking about the diag screen on the screen shot above? If so, it is part of 2.1. Just type diag in the console window.

**Comment by dimitry-ishenko** [comment]
Yes that's exactly right. Just downloaded latest Server 2.1 build and I don't see it in there... Are you sure about that?

**Comment by DavidORiley** [comment]
I compiled Caspar from source. Last downloaded build I used was Server 9e4b.....
You should get "202 DIAG OK" returned?

**Comment by dimitry-ishenko** [comment]
Oh, I see what you mean now. I do get a window, when I send DIAG command. Now I have to figure out why it only shows garbage. Thank you and sorry for hijacking the thread

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
