### ISSUE TITLE
[2.1.0 Beta 1] Audio-stream overflow when seeking

### ISSUE THREAD

**Issue by dimitry-ishenko** [CasparCG/Server#492]
I have two very similar files. One about 3.5min long and the 2nd -- about 1hr 15min long. I tried the following test with both files:

1. Restart server.
2. Play file.
3. Issue SEEK 0 command

The 1st file (short) seeks to the beginning and continues to play as expected. The 2nd file (long) barfs with "audio-stream overflow" exception. (Seeking to any other point causes same behaviour.)

Attached are logs for both files.

**Comment by dimitry-ishenko** [comment]
[caspar1.txt](https://github.com/CasparCG/Server/files/565452/caspar1.txt)
[caspar2.txt](https://github.com/CasparCG/Server/files/565453/caspar2.txt)

**Comment by dimitry-ishenko** [comment]
@HellGore on a slightly separate note, it seems that the SEEK command does not check if the seek value is out of bounds. If you seek to a negative value or past the file end, the playback just freezes. (Version 2.0.6 ignores negative value and stops playing the file in the latter case.)

**Comment by jesperstarkar** [comment]
@dimitry-ishenko I did notice the SEEKing past the boundaries of the file as well, but never got to report it. I think it will be correct to clamp the SEEKing values to the first- and last frames of the file. I can't see any other way of doing it.

**Comment by dimitry-ishenko** [comment]
@jesperstarkar I've submitted PR #493

**Comment by jesperstarkar** [comment]
Nice one!

**Comment by dimitry-ishenko** [comment]
This is really bizarre. I ran the file through this command:

    ffmpeg -i in.mov -codec copy out.mov

which essentially just "re-containers" the file without any encoding. And seeking in the resulting file works on both servers. Tried the original file again, and it only works on 2.0.6, but still throws exception on 2.1.

The file was made in our studio on the west coast and I believe they used Avid to export it. Still it seems strange that (a) 2.0.6 handles seeking just fine; and (b) if I just play the file all the way through without seeking it works fine on both servers.

@HellGore any insight on this?

**Comment by HellGore** [comment]
Is it possible for you to give me access to the files?

**Comment by dimitry-ishenko** [comment]
@HellGore I thought you would ask that. Unfortunately, the file contains some content, which I cannot give out... :( And I realize this makes things almost impossible to debug. But maybe if you can guide me a bit, I can do some tests here locally?

**Comment by HellGore** [comment]
I would probably start with looking into audio/video packet interleaving and see if that is what makes the files differ after the remux.

However I think that the only difference between 2.0.7 and 2.1 is how framerates are handled.

I would like you to keep the original file that makes it fail and see if I implement the "snap to closest matching framerate" as I suggested in your other issue, if that solves it.

**Comment by dimitry-ishenko** [comment]
No problem, I'll tell the guys to hold on to the file for now and will test once you implement it

**Comment by dimitry-ishenko** [comment]
UPDATE: This error is still happening with 2.1.0 Beta 1 on both Windows and Linux versions.

**Comment by dimitry-ishenko** [comment]
OK, I figured out what the problem is. I've sprinkled some `CASPAR_LOG()` commands:

- one here: [`caspar::ffmpeg::input::implementation::tick()`](https://github.com/CasparCG/Server/blob/2.1.0/modules/ffmpeg/producer/input/input.cpp#L214)
- one here: [`caspar::ffmpeg::frame_muxer::impl::push(...AVFrame...)`](https://github.com/CasparCG/Server/blob/2.1.0/modules/ffmpeg/producer/muxer/frame_muxer.cpp#L221)
- and here: [`caspar::ffmpeg::frame_muxer::impl::push(...core::mutable_audio_buffer...)`](https://github.com/CasparCG/Server/blob/2.1.0/modules/ffmpeg/producer/muxer/frame_muxer.cpp#L264)

And also commented out [the line that was throwing the exception.](https://github.com/CasparCG/Server/blob/2.1.0/modules/ffmpeg/producer/muxer/frame_muxer.cpp#L266)

If you take a look at the `original.txt` log file, you will notice that `av_read_frame()` function returns about 40 audio samples, following by 10 video samples and another 20 audio samples, before the audio/video samples start interleaving.

If you go to line 807 of the `original.txt` log file, you will see the `SEEK` command being issued (which used throw the exception). After that similar scenario ensues -- over 40 audio samples are returned by the `av_read_frame()` function before any video samples are returned.

As a result `audio_streams_.back().size()` grows up to 96988 samples (see line 1051), which is over maximum allowed 51200 and causes the exception to be thrown.

The remuxed.txt log is for the remuxed version of the same file. No re-encoding -- only remuxing was done with the following command:

    ffmpeg -i in.mov -codec copy out.mov

As you can see the samples are returned interleaved at all times.

The original file was produced at our studio on the west coast using Avid, so I assume it's not out of extraordinary to have ~60 audio samples precede video. And as I've mentioned earlier, Server 2.0.6 handles it just fine.

I am not sure how you've calculated the 32 multiplier on lines [224](https://github.com/CasparCG/Server/blob/2.1.0/modules/ffmpeg/producer/muxer/frame_muxer.cpp#L224) and [264](https://github.com/CasparCG/Server/blob/2.1.0/modules/ffmpeg/producer/muxer/frame_muxer.cpp#L266), but maybe it can be bumped up to something higher? Like 120?

@HellGore, your thoughts?

[original.txt](https://github.com/CasparCG/Server/files/596387/original.txt)
[remuxed.txt](https://github.com/CasparCG/Server/files/596392/remuxed.txt)

**Comment by HellGore** [comment]
> The original file was produced at our studio on the west coast using Avid, so I assume it's not out of extraordinary to have ~60 audio samples precede video. And as I've mentioned earlier, CasparCG Server 2.0.6 handles this file just fine.

Do you mean 60 video frames worth of audio samples instead of 60 audio samples? It is interesting though that it works differently in 2.0.6. I think it is fine to bump the limit to 120 anyway. It is actually a sanity checking limit for protecting against out of memory.

**Comment by dimitry-ishenko** [comment]
@HellGore I am not totally sure. The audio packets showed duration of 1024, whereas video packets were 1000 time base units. And haven't looked if the audio stream time base was the same as video. But in a ballpark, yeah, we are talking a second or so.

**Comment by dimitry-ishenko** [comment]
This was merged in #500
