### ISSUE TITLE
AMCP command for producer redirection

### ISSUE THREAD

**Issue by Canigou77** [CasparCG/Server#498]
With 2.0.7, I can redirect an input to an output with "PLAY 1-2 2-2" for example. With this, input of channel2 in playing in channel1.
With 2.1.0, I get an exception = FileNotFound in the frame_producer_registry::create_producer() function.
Is it normal ? Any idea of a solution ?

**Comment by HellGore** [comment]
PLAY 1-2 route://2-2

**Comment by Canigou77** [comment]
OK, I close it.
