### ISSUE TITLE
LENGTH command

### ISSUE THREAD

**Issue by dimitry-ishenko** [CasparCG/Server#499]
This is a continuation of my question regarding the `frame_number_` variable in PR #497. After some digging through the code, I think I understand now how it works.

This variable has to do with the `LENGTH` command (as in `PLAY ... LENGTH X` or `CALL ... LENGTH X`) and it counts how many frames have been played so far and indicates EOF after the count exceeds `X`. So, for example, if one were to issue this command:

    PLAY 1-10 sample/video SEEK 10 LENGTH 50

it will play 50 frames between 10 and 60 and then stop. This works out fine and aligns with the idea or marking IN and OUT points for a given clip, so that it plays between those 2 points.

The problem, however, arises if any sort of seeking is done during playback. For example, if after the above command another one is issued:

    CALL 1-10 SEEK 10

and executed after 40 frames have been played, it will seek back to frame 10, play 10 more frames and will stop at frame 20. While one may argue that this is by design, it is not very intuitive.

What I would like to propose is this:

1. In `PLAY ... SEEK X LENGTH Y` command rename `SEEK` to `IN`. `SEEK` will be retained until next major revision and these commands will be identical: `PLAY ... SEEK X` and `PLAY ... IN X`.

2. In `CALL ... START X` command rename `START` to `IN`. `START` will be retained until next major revision and these commands will be identical: `CALL ... START X` and `CALL ... IN X`.

3. Change meaning of the `LENGTH` command to represent time point (OUT) in the clip as a distance from the start point (IN). In other words, `PLAY ... SEEK 10 LENGTH 50` command will be guaranteed to play frames 10 to 60 regardless of any seeking.

4. Add `OUT` command to `PLAY` and `CALL` as an alternative to `LENGTH`. In other words, the following commands will be identical: `PLAY ... IN 10 LENGTH 50` and `PLAY ... IN 10 OUT 60`, as well as `CALL ... LENGTH 50` and `CALL ... OUT 60`.

**Comment by HellGore** [comment]
> While one may argue that this is by design, it is not very intuitive.

I view it as a bug and not by design.

The only change needed is really your proposal point 3. I see no need to introduce the parameters IN and OUT.

**Comment by mauricev78** [comment]
Well i find IN and OUT more practical then IN and LENGTH to be honest. 
This because it matches better with the production environment and the "terms" used there.
I think you normal want to play from a point to a point, not from a point for a certain time.
Next to that this saves a calculation steps / routine's on the client side

LS

**Comment by dimitry-ishenko** [comment]
@mauricev78 HellGore has been reviewing my PR #501 which allows you to do both.
