### ISSUE TITLE
Bug: Text producer for PSD in 2.1 BETA - Italic font rendering

### ISSUE THREAD

**Issue by hreinnbeck** [CasparCG/Server#503]
Was creating PSD templates using italic fonts and the rendering isn't correct.  I tried multiple fonts (Calibri, Myriad, Century schoolbook) and get the same results.

This show very well with text letter combinations "ál ýl íl úl ól öl áj ýj íj új ój öj" but it's not constrained to accented letters - that's just where it's most apparent.

Here are some screenshots:
![italicfontspsdproducer_myriad](https://cloud.githubusercontent.com/assets/1609119/20527388/23847156-b0c0-11e6-8725-c1774bff108b.png)
![italicfontspsdproducer_century](https://cloud.githubusercontent.com/assets/1609119/20527387/23835082-b0c0-11e6-8a51-e73a90f5f9e1.png)
![italicfontspsdproducer](https://cloud.githubusercontent.com/assets/1609119/20527389/23949540-b0c0-11e6-86d9-85621eeb1be9.png)

**Comment by HellGore** [comment]
It seems that this only happens when the mixer is set to have blending modes enabled.

**Comment by hreinnbeck** [comment]
Great catch HellGore.  Tested latest build and italics are rendering as expected.
