### ISSUE TITLE
Unused `flags` variable in `queued_seek`

### ISSUE THREAD

**Issue by dimitry-ishenko** [CasparCG/Server#504]
On line [#342](https://github.com/CasparCG/Server/blob/2.1.0/modules/ffmpeg/producer/input/input.cpp#L342) in `queued_seek()` the `flags` variable is initialized with `AVSEEK_FLAG_FRAME` and then set to `AVSEEK_FLAG_BYTE` for VP6 codec on line [#351](https://github.com/CasparCG/Server/blob/2.1.0/modules/ffmpeg/producer/input/input.cpp#L351).

However, the variable doesn't get used anywhere else. Was it meant to be used in the call to `avformat_seek_file`?

**Comment by HellGore** [comment]
After some investigation I can see that this is the commit where it stopped being used: https://github.com/CasparCG/Server/commit/7060484708769b2798ea0ac1ed20463eef3abc15

The commit message is "Fixed seeking for some files with invalid stream time_base meta-data"

**Comment by dimitry-ishenko** [comment]
@HellGore since nobody complained for the past several years, I am assuming it is safe to remove the flags variable

**Comment by HellGore** [comment]
I would say so

**Comment by dimitry-ishenko** [comment]
Thanks @HellGore
