### ISSUE TITLE
mipmapping_default_on config-parameter should be mipmapping-default-on

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#508]
`mipmapping_default_on` is the only config- parameter using `_`(underscore) and not `-`(dash) as separator in its name.

If we change this to `mipmapping-default-on` for 2.1, we will end up with inconsistency between 2.0 and 2.1, however, several other parameter have changed between anyways.

If you agree we should go with `mipmapping-default-on` I can submit a PR doing this. Otherwise, we'll just stick with this minor inconsistency and this issue can be closed.

**Comment by HellGore** [comment]
I agree
