### ISSUE TITLE
Clearify default SCREEN consumer device (screen_index)

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#511]
1) 2.1.0 doesn't seem to have implemented support for screen_index, always showing the Screen Consumer on device 0. I see a section of code in screen_consumer.cpp being commented out, this might be the missing piece? Why is this feature disabled in 2.1.0?
2) 2.1.0 seems to (should) have a default of `screen_index = 1`, meaning _"screen 2"_ on a multiscreen setup. I would like to se the default being `0` _("screen 1")_ once the feature gets re-enabled in 2.1.0. 
3) The config in 2.1.0 doesn't list any default value. It says `<device>[0...]</device>`, this should be `<device>0 [0...]</device>` once the feature gets re-enabled, and the default gets changed to `0`.

**Comment by parisjp** [comment]
Bump!

**Comment by Julusian** [comment]
This is fixed by https://github.com/CasparCG/Server/pull/620

In 2.0, the default is screen 1 which is the primary display. It is the same in this PR, so I have updated the example config to match. This is also consistent with the device number used for other consumers
