### ISSUE TITLE
INFO PATHS should return the resolve paths, not the raw values from CONFIG

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#512]
When I then run `INFO PATHS` I would expect to get the actual working directories, not the raw value from `INFO CONFIG`. 

- If you omit some `Paths` in the config, they fall back to their defaults. And `INFO PATH` doesn't take this into account (missing paths doesn't show up at all).
- If you specify invalid/unknown path(s) it seems to throw some exceptions and continue to work out of the assumption that these given paths are active. And `INFO PATH` still report the raw value from `INFO CONFIG`.

I would suggest the following:
- Validate given paths and fall back to the defaults the same way with invalid paths as not set paths.
- Report the resolved/working directories in `INFO PATH`

**Comment by jesperstarkar** [comment]
This is invalid. I was wrong on the fallback, it doesn't seem to choose the defaults if an invalid path is set.

**Comment by HellGore** [comment]
I must have misunderstood you somehow because I think this is what I did in https://github.com/CasparCG/Server/commit/a9062da7a9a6fa8933a27c8d9f3cb3c47529ec1f ?

**Comment by jesperstarkar** [comment]
Oooooh the shame! My apologies, I'll pull the latest build and test!

**Comment by HellGore** [comment]
You even commented on the commit :)

**Comment by jesperstarkar** [comment]
I knooooooooooow

**Comment by jesperstarkar** [comment]
It works just perfectly. Thank you.
