### ISSUE TITLE
With file recording options are ignored

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#513]
With the fix of the colorspace to HD bt709 the filerecorder options are ignored.
So you can't set YUV format or bitrate anymore.

ADD 1 FILE testH264.mp4 -preset ultrafast 
is not accepted anymore
With the recording of MXF files the option parameters are ignored too.
It defaults to YUV420 encoding

**Comment by TKooijmans** [comment]
I tested this one again with build 3439 but still no go with.
I tested with
ADD 1 FILE myfile.mp4 -vcodec libx264 -preset medium -tune film -crf 25
Result extreme high CPU load and PLANAR 4:4:4 YUV encoding
![image](https://cloud.githubusercontent.com/assets/4194609/25273132/c90577de-268a-11e7-8400-683a929a25bb.png)
Bitrate peaks to 20 mbit!
so all settings are ignored.

**Comment by TKooijmans** [comment]
With build 3439 I got file recording working, here are some examples
with HDMXF 30-40-50 422 420 with stereo audio
ADD 1 FILE myfile.mxf -pix_fmt  yuv422p -b 30000k		(30mbit 422)
ADD 1 FILE myfile.mxf -pix_fmt  yuv422p -b 50000k
ADD 1 FILE myfile.mxf -pix_fmt  yuv420p -b 30000k		(30 mbit 420)

HD mp4 with libx264 codec
options codec
-preset ultrafast,superfast,veryfast,faster,fast,medium,slow
-tune film,animation,grain,stillimage,psnr,ssim,fastdecode,zerolatency
-profile:v baseline,main,high,high10,high422,high444
crf range 0-51 (quality of the file)
ex.
ADD 1 FILE myfile.mp4 -vcodec libx264 -pix_fmt yuv420p -crf 32 -preset ultrafast -tune fastdecode
(about 4 mbit in HD)
ADD 1 FILE myfile.mp4 -vcodec libx264 -pix_fmt  yuv422p -crf 25 -preset veryfast -tune fastdecode -profile:v high422

or
ADD 1 FILE myfile.mp4 -vcodec libx264 -pix_fmt  yuv422p -crf 25 -preset veryfast -tune fastdecode

**Comment by HellGore** [comment]
Yes this is because of the commit i referenced this issue from, regarding `-pix_fmt` parsing being fixed. Without specifying an explicit pixel format the default will be for avfilter to decide among the pixel formats supported by the selected codec (an exception to this is in the case of the `dvvideo` codec where it is handled differently).

**Comment by ronag** [comment]
2.2
