### ISSUE TITLE
2.10 CINF broken

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#517]
The implementation of `CINF` seems to be nearly the same in 2.0.7 and 2.1.0, but 2.1.0 still produces another result than 2.0.7, and some cases aren't possible to sucessfully do with `CINF` in 2.1.0

- With `CINF` you pass a filename, and `CINF` then searches recursivly through all folders,  matching the file-name against all files, and reports the file attributes for all files with a matching file name.
- In 2.0.7, having two files with the same file name in different folders returns two lines of results.
- In 2.1.0, having the same two files with matching file names in the same sub folders, return only the first matching result.
- The only difference in logic bewtween 2.0.7 and 2.1.0 I can see is:
 
`auto file = path.replace_extension(L"").filename();` (2.0.7)

vs. 

`auto file = path.replace_extension(L"").filename().wstring();` (2.1.0)

This is a to be considered a breaking bug, as with the current 2.1.0 result you simply can't access `CINF`-info from sub folders.

I suggest that the new implementation should allow for passing in `subfolder/subsubfolder/filename` and match agains both `path` and `file`, allways producing a single line of result, never listing an array of multiple files with the same file-name in different sub folder.

**Comment by HellGore** [comment]
Fixed

**Comment by jesperstarkar** [comment]
Thank you, work well now! :)
