### ISSUE TITLE
LOAD doesn't work as expected

### ISSUE THREAD

**Issue by realies** [CasparCG/Server#518]
Trying this on an Ubuntu 14.04.5 with a DeckLink 4K Extreme as output:

LOAD 1-1 AMB

Does not show up the first frame on the output. DIAG shows that ffmpeg[AMB.mp4|1920x1080p25.00|1/268] exists.

**Comment by realies** [comment]
The same behaviour is present in the Windows version of the beta. Tested on Win10x64.



>[2016-12-16 10:57:40.812] [1564] [info]    Received message from 127.0.0.1: LOAD 1-1 "AMB"\r\n
[2016-12-16 10:57:40.836] [4844] [info]    ffmpeg[AMB.mp4|1920x1080p25.00|0/268] [video-decoder] H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[2016-12-16 10:57:40.839] [4844] [info]    Sent message to 127.0.0.1:202 LOAD OK\r\n
[2016-12-16 10:57:40.885] [1952] [info]    [frame_muxer] simple 1920x1080p25.00

**Comment by jesperstarkar** [comment]
This is not Linux-specific. Perhaps you could change the title to reflect this.

**Comment by HellGore** [comment]
Please give this a try in the latest build.

**Comment by realies** [comment]
Just tested CasparCG Server fab1f6b6fc8534cb16bd1f1675c96bf6b6a89379 on Windows 10 x64 with a screen consumer and it works as expected. Will have to confirm results with DeckLink cards and Linux.

**Comment by jesperstarkar** [comment]
Works perfectly! This is good.
