### ISSUE TITLE
absolute path support for CLS and CINF

### ISSUE THREAD

**Issue by realies** [CasparCG/server#524]
> zbang @ #casparcg: Curious... PLAY commands will accept an absolute filename ("e://video/Sign_Off_clean.mp4";) however CINF does not. Design or omission?

Perhaps having an optional [path:string] argument for CLS and support for absolute file location for CINF would allow for multiple file path locations. I see it playing nicely with DATA STORE/RETRIEVE.

**Comment by z-bang** [comment]
For consistency, any command that accepts a file identifier (which is then searched for) ought to also accept a full path (in the same vein as anything that accepts a hostname should also accept an IP address).

**Comment by HellGore** [comment]
I have now committed a change that adds path filtering on `CLS`, `TLS`, `DATA LIST` and `THUMBNAIL LIST`, but only for paths under the corresponding base directory, not anywhere on the hard drive.

Actually I think that `PLAY` accepting files outside of the media folder is wrong.

**Comment by ronag** [comment]
Moved to https://github.com/CasparCG/media-scanner
