### ISSUE TITLE
CasparCG on a virtual machine

### ISSUE THREAD

**Issue by realies** [CasparCG/server#527]
Is it possible to bring support for VMs supporting OpenGL 3.0+? Attempted using CasparCG under Ubuntu 14.04 and Windows 7/10 VMs on top of VMware Fusion 8 and VMware Workstation 12. Instances tested with either open-vm-ware-tools installed or the official drivers package.

Ubuntu tests (Beta 1) cause CasparCG to crash a few seconds after initialising, containing a warning message of "[image_mixer] TextureBarrierNV not supported. Post processing would no be available". If I attempt to play something before it quits it seems to start playing (according to DIAG), but as the warning suggest, the output is black.

Under Windows 7/10 it does not seem to crash (Stable and Beta 1), but the same [image_mixer] error is present with black output. Playback possible according to DIAG, generated thumbnails are also all black.

Any suggestions of methods for successful virtualisation of CasparCG?

**Comment by HellGore** [comment]
what graphics card do you have?

**Comment by c769214** [comment]
I have tried on Virtualbox and VMWare.... and got the similar issue

AFAIK,  OPENGL in VMWare is  not a 100% "clone" of OpenGL 3.0....is just like an "emulator"

Would like to hear if anyone can do this.....

**Comment by realies** [comment]
@HellGore, it seems it's not GPU dependent as @c769214 commented, although same results were observed on GT750M, K2100M and M2000 GPUs.

**Comment by ronag** [comment]
OpenGL 4.5 is a requirement.
