### ISSUE TITLE
Log flooded by 'Received message from Console: \r\n' messgage

### ISSUE THREAD

**Issue by toontoet** [CasparCG/Server#529]
I'm running build 'a8775b634ba22e0d2fa17cfc078a47a31ee77bcb' on Ubuntu 16.04.

I noticed our logfile got a lot (hundreds per second) lines reading: "Received message from Console: \r\n".

I run casparCG from a bash script like:
```
#!/bin/sh
while :
do
        cd /opt/casparcg/server
	./run.sh
	sleep 3
done
```

Running the script from a terminal works great, no messages like bellow. If we run the script using ALT-F2 (run command on Ubuntu) and without a terminal the the log starts going mad.

Probably something here: https://github.com/CasparCG/Server/blob/042abffe522430cd2f5cb411a39c657ed137d0b4/shell/main.cpp#L125
While the if shouldn't evaluate true, it does in this case.

```
...
2016-12-23 14:09:34.334] [7724]   [info]    Received message from Console: \r\n
[2016-12-23 14:09:34.334] [7724]   [info]    Received message from Console: \r\n
[2016-12-23 14:09:34.334] [7724]   [info]    Received message from Console: \r\n
...
```

**Comment by krzyc** [comment]
When log starts going mad? How do you close server when running without console?

From my test it looks that everything is ok until I try to kill run.sh - then "main thread" is still running and log gets mad (in console it behaves same - when I use kill instead of QUIT command log gets mad).

**Comment by HellGore** [comment]
Must have something to do with stdin not being available in a usual manner.

**Comment by HellGore** [comment]
I have now corrected the behaviour, but the result is not what I think @toontoet expects. It will now exit immediately because when you run your script via "ALT-F2" it will not attach keyboard input as stdin, thus immediately receiving EOF. I have now changed so that stdin EOF means EXIT, just as any other program does that uses stdin

**Comment by toontoet** [comment]
Nice. Exiting is way better than flooding the logfiles :-)

When CasparCG has to run in a headless environment you might want to reconsider.

**Comment by HellGore** [comment]
Use

```screen -d -m /path/to/your/script.sh```

It will run in a detached terminal, providing a valid stdin to CasparCG. You can also attach to the terminal at any time to manipulate stdin. `tmux` can also be used for the same purpose.

**Comment by silid** [comment]
In 2.0.7 you could send a set of AMCP commands on launch by redirecting the file to stdin:
```
casparcg.exe < startup.txt
```
This no longer works as when EOF is received casparcg.exe quits.

Work arounds are complicated and have their own issues.
