### ISSUE TITLE
SEEK desynchronises LOADBG AUTO

### ISSUE THREAD

**Issue by realies** [CasparCG/Server#530]
Whenever you `SEEK` forward, followed with `LOADBG` with an `AUTO` parameter, CasparCG waits for the amount of time that would have elapsed if there was no seek before it brings the background producer to the foreground. Similar issue might be present when seeking backward, but has not been tested.

Behaviour present in latest stable, beta and development builds.

**Comment by ronag** [comment]
Should be fixed in https://github.com/CasparCG/Server/issues/636#issuecomment-355753697
