### ISSUE TITLE
request: Scandinavian letters in PSD-template (PSD producer)

### ISSUE THREAD

**Issue by markusnygard** [CasparCG/server#531]
Tested with Tahoma and CasparCG server does not write out "scands" even if the server does it flash template. Tested with both copying Tahoma font to Servers "font"-folder and to change the path to font-folder to "c:\windows\fonts\", no effect.

**Comment by markusnygard** [comment]
Here is some more info
Hi
Has been sitting and testing the PS-template a bit.
It seems to be something real strange in the layers (f0 and f1) not being exactly the same but I cant find the difference.
if I have Tahoma Bold as font then the outcome of metadata ÅÄÖ åäö is f0 ÅÄ ä and f1 ÅÄÖ åäö
when I change the font to Arial Regular then its f0 ÅÄÖ and f1 ÅÄÖ åäö 
and if font is Old Bookman then its f0 ÅÄÖ ä and f1 ÅÄÖ åäö
and the only change here is that I have change fonts
it is also disscussed in 
http://casparcg.com/forum/viewtopic.php?f=3&t=3204&p=28330#p28330
br markus

**Comment by 5opr4ni** [comment]
Hi! There is still some issues with the PSD. I'll comeback with some info.

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
