### ISSUE TITLE
Bug: text layer in PSD-files moves position when run by PSD Producer 

### ISSUE THREAD

**Issue by markusnygard** [CasparCG/server#532]
When positining a text-layer in Photoshop with markers on positioning-track, the text moves up when you run it in CasparCG. For example opacity works correct so thats why I call this a bug, not a feature.

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
