### ISSUE TITLE
Include libgcrypt11 dependency on linux

### ISSUE THREAD

**Issue by baltedewit** [CasparCG/server#533]
On newer distro's this package is no longer available as a system wide dependency. This is a dependency that is relied on by cef, upgrading cef will remove the need for the dependency but then upgrading cef is a whole 'nother story.

Easy fix is to include libgcrypt.so.11.

PS: for anyone seeing this wanting to install: downloading libgcrypt.so.11 and placing it in the lib folder made casparcg work for me.

**Comment by walterav1984** [comment]
To run CasparCG 16.04 on ubuntu 16.04.1 linux install this system wide "sudo dpkg -i libgcrypt11_1.5.3-2ubuntu4.4_amd64.deb" or extract the lib and install as @baltedewit mentions.
http://security.ubuntu.com/ubuntu/pool/main/libg/libgcrypt11/libgcrypt11_1.5.3-2ubuntu4.4_amd64.deb
