### ISSUE TITLE
Template created in Windows and try to run in Linux version

### ISSUE THREAD

**Issue by c769214** [CasparCG/Server#538]
Hi, I found some very useful templates in Windows Version and  I would like them work in Linux too...

I just copied those file in "Template" Directory at Casparcg Windows server , into the Linux Server.

But it seems not working.... CasparCG client cannot load the library and displays "Template (0)"

What problems occurred?

**Comment by HellGore** [comment]
there is no flash support in linux

**Comment by c769214** [comment]
If Yes, CasparCG Server in Linux cannot run template files?

**Comment by HellGore** [comment]
All other kinds of templates: html, psd and scene but not flash
