### ISSUE TITLE
mixer grid and thumbnail grid KO on CPU

### ISSUE THREAD

**Issue by captnced** [CasparCG/Server#540]
when running casparcg server 2.1 on CPU only the mixer grid does not work (only displays the last layer in full frame, looks very similar to http://casparcg.com/forum/viewtopic.php?f=12&t=2724).
same problem with the thumbnails which do not show 4 quadrants.

**Comment by HellGore** [comment]
The CPU mixer does not support `MIXER FILL` and thus not `MIXER GRID`. No development efforts are going into the CPU mixer and it might be better to remove it completely.

**Comment by captnced** [comment]
ah; ok. thanks for the clarification.
