### ISSUE TITLE
AMCP is inconsistent in parsing paths

### ISSUE THREAD

**Issue by baltedewit** [CasparCG/Server#542]
Paths are returned and expected to be as per usual on the OS.

E.g. Windows will only accept "PLAY 1-10 FOLDER\FILE" and Linux will only accept "PLAY 1-10 FOLDER/FILE"

If this is intended: shouldn't the behaviour of AMCP be consistent across all platforms?

**Comment by HellGore** [comment]
> Windows will only accept "PLAY 1-10 FOLDER\FILE"

It accepts `PLAY 1-10 FOLDER/FILE`.

> Linux will only accept "PLAY 1-10 FOLDER/FILE"

Yes that's true.

> If this is intended: shouldn't the behaviour of AMCP be consistent across all platforms?

I agree that it should be the same for all platforms. The right thing to do is to remove the possibility of using backslash, but I don't know how that would hurt functionality of existing clients and automation systems.

**Comment by jesperstarkar** [comment]
If both platforms accept /, then all server responses from CasparCG should write out /, and \ should still be kept for Windows backwards compability, imo.

And documentation should of course tell to use /.

**Comment by HellGore** [comment]
`CLS`, `TLS`, `DATA LIST`, `THUMBNAIL LIST` and `CINF` all use `/`.

**Comment by jesperstarkar** [comment]
Cool, then everything is just great, @baltedewit ?

**Comment by baltedewit** [comment]
On 207 it returns \

this is, I guess, an issue that appeared out of my Dev machine being Linux
(thus 210) and my production machine being windows (thus stable 207)
