### ISSUE TITLE
Wrong return code for DATA REMOVE command

### ISSUE THREAD

**Issue by mcdikki** [CasparCG/Server#549]
The DATA REMOVE command returns a 201, but it does not contain an additional line of data, so it should be 202 instead. This behavior breaks AMCP parsing logic.

Tested on 2.0.7.

```
-->DATA STROE "test" "testdata"\n\r
<--202 DATA STORE OK\n\r
-->DATA REMOVE "test"\n\r
<--201 DATA REMOVE OK\n\r
```

**Comment by jesperstarkar** [comment]
Fixed in 2.1.0
