### ISSUE TITLE
Request: support PsF by optionally removing yadif filter

### ISSUE THREAD

**Issue by PimpShanti** [CasparCG/server#550]
In the same way that deinterlace and deinterlace_bob are short-cuts for yadif settings, I would like to see a short-hand to optionally remove yadif from the Producer altogether.

CasparCG doesn't support PsF. If you create a Progressive channel and ingest PsF content on a Decklink input, it appears as 1080i5000 and Caspar automatically applies a deinterlacing filter. If you provide your own yadif options you can override the hard-coded yadif filter but there appears to be no option to remove the filter altogether.

If the above short-hand was implemented, CasparCG would support PsF input on a Progressive channel.

Discussion/justification for this requirement can be viewed here: http://casparcg.com/forum/viewtopic.php?f=12&t=4377&p=28546#p28546

**Comment by PimpShanti** [comment]
After further research I have realised that Caspar _does_ support PsF but only if the SDI signal is correctly flagged. Unfortunately this is very rarely the case.

A true 1080PsF25 signal, flagged correctly, is detected by Decklink as PsF. This input _can_ be added to a Progressive channel in Caspar.

PsF which is carried in a 1080i50 signal is detected by Decklink as 1080i50 and, when added to a Progressive channel, get's automatically deinterlaced.

The whole point of PsF is that Progressive content be put into an _interleaved_ scan format and passed through (older) broadcast equipment which will handle it in the same way it would handle an interlaced signal. The resulting content though is still Progressive. In Europe, 1080i50 is still the broadcast standard and so there is a lot of 1080i50 kit out there. Unfortunately the large majority of this kit is reflagging the SDI signal as 1080i50. Even some modern, standard broadcast kit which is able to _generate_ a PsF signal (such as the AJA Ki Pro) is flagging the signal as 1080i50, not 1080PsF25. Caspar has no ability to correctly handle this.

My feature request is either:

1.   optionally remove the yadif filter when you know the input signal is not interlaced
2.  respect the user's choice of `FORMAT` when provisioning a Decklink input. i.e. even if Decklink is seeing the signal as 1080i50, `ADD 1 DECKLINK DEVICE 1 FORMAT 1080p2500` will instruct Caspar that the signal is not interlaced. Currently this scenario will result in no picture at all.

Thanks guys

**Comment by premultiply** [comment]
I think this can be closed as it is not needed anymore with new bwdif filter. Deinterlacing will be skipped by motion estimation if there is nothing to deinterlace.
