### ISSUE TITLE
Feature Request: XML writer for PSD / Scene Producer

### ISSUE THREAD

**Issue by didikunz** [CasparCG/server#551]
As I understand, the PSD producer uses the scene producer to do it's magic. As there seems to be a way to import XML-files into the scene producer it should be easy to build a AMCP command that outputs a XML of the current scene (read PSD) producer executing. That would make it easy to learn this XML, because that is not documented yet. And probably will not in the near future.

**Comment by HellGore** [comment]
Actually I'm currently documenting it. Have a look at the initial progress in https://github.com/CasparCG/Server/blob/2.1.0/core/producer/scene/scene.xsd but anyway I think your idea is a great compliment to the XML Schema.

**Comment by didikunz** [comment]
That's good news! Thank you. I look at it and it starting to make sense. However I would think it would make sense for users to get a fealing for the XML when we could get a PSD producers tree writen out. Could aslo be a way to not need to start from scratch and just further costomize what comes out of a PSD.

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
