### ISSUE TITLE
Update ffmpeg to 3.2 and enable NVIDIA GPU Encoding

### ISSUE THREAD

**Issue by davidweisgerber** [CasparCG/server#553]
In my production I produce 2 H264 videos at once (one for streaming, one for recording). It would be cool if the encoding process could be done on the GPU.
For this you need to upgrade ffmpeg to 3.2 and make a build with enabled NVIDIA support:
https://developer.nvidia.com/ffmpeg

**Comment by HellGore** [comment]
Cool but I'm pretty sure that `--enable-nonfree` breaks compatibility with GPLv3.

**Comment by davidweisgerber** [comment]
That's a good question (if it does), but I think that would be only true for the resulting binary and not for the source code itself.

Maybe it would be interesting to upgrade ffmpeg to latest and provide the normal gpl variant of it with the release version.
One could also provide replacement ffmpeg builds with enabled NVIDIA support so you could replace it on your own. (Like you always do on your Linux system ;-))

**Comment by baltedewit** [comment]
On linux it would be trivial to replace the shared libraries in the lib folder of casparcg.
