### ISSUE TITLE
Audio sync lost after SEEK

### ISSUE THREAD

**Issue by TondaKrist** [CasparCG/Server#556]
Audio sync is lost after SEEK command. We have tried MPEG2 with mpeg audio and PCM. Same results with another file format . I know that there is a problem with long-GOPs, but I can seek (even to GOP) but have not found frame where audio will be in sync after seek. Have tried many options, formats. Is there any format are you using for seeking?

**Comment by dimitry-ishenko** [comment]
DNxHD + PCM inside .mov

**Comment by TondaKrist** [comment]
Thanks! It works, but is there a way to seek in MPEG without loosing audio sync?

**Comment by TKooijmans** [comment]
I tested with Seek mp4 and MXF files both work fine in SD and HD.
(HD) mpeg files however go offsync with SEEK command.
This is the file info from a HD mpg file created with Premiere Pro (422) format
![image](https://cloud.githubusercontent.com/assets/4194609/24900630/c75531a6-1ea4-11e7-92f8-8f23e679f6fd.png)

This file works fine (MXF  mpeg encoding)
![image](https://cloud.githubusercontent.com/assets/4194609/24901271/d9b0c37c-1ea6-11e7-8720-146669932479.png)
 I also tested HD mpeg with dolby audio, this goes wrong too.
details of the file
![image](https://cloud.githubusercontent.com/assets/4194609/24902167/9d44b756-1ea9-11e7-84ca-fc8d07f6e60d.png)

**Comment by dimitry-ishenko** [comment]
If I understand it correctly -- and @HellGore can chime in if I am wrong -- but the server currently reads audio and video frames sequentially from a file without taking into consideration their timestamps and simply outputs them to the appropriate hardware. This works fine for playback.

Now, when you seek to a specific point in the file, if you seek into the middle of a GOP, the ffmpeg_producer will land you at the nearest I-frame instead, which can cause audio to go out of sync.

To work around this issue you can encode your files with I-frames only.

**Comment by TKooijmans** [comment]
Yes, I know that, but with HDcam mxf files, we also have long gop mpeg and these files work fine.
h264 mp4 is also long gop, they work fine too.
So only files with mpg extention seem to work wrong...

**Comment by dimitry-ishenko** [comment]
@TKooijmans oh I see. Well it could just be that the different ffmpeg demuxers behave differently. As I said the way the server reads a/v frames is pretty primitive. It disregards timestamps and relies on the demuxer to feed the frames in the right order.

If you take look over here https://github.com/CasparCG/Server/issues/492#issuecomment-261140947 for example, AVID is not very good at interleaving audio and video frames, which was causing problems for me earlier. IMHO, ultimately the server code would need to be re-written to take into account the timestamps.

But for now, maybe try "re-containering" your files and see if it handles the issue?

    ffmpeg -i infile.mpg -c copy outfile.mpg

**Comment by ronag** [comment]
Closing in favor of #636. Please create a new issue if it still remains after that one is resolved.
