### ISSUE TITLE
Memory leak playing streams in ffmpeg_producer

### ISSUE THREAD

**Issue by gartner-concepts** [CasparCG/Server#557]
What I have noticed is that when I play a transport stream in CasparCG that the working memory is rising and after a while this will result in a memory problem. For an example let's say you have 8GB memory and your normal usage is 2.5. When I start playing the stream in the consumer the memory rises immediately, after a couple hours the memory will be out of memory and crashes your system.

It looks like the consumer is keeping the old data from the transport stream so you can do the time shifting, how to disable this and let the system play it without caching? 

For me this is a serious problem as I really need it this way, I know a work around but that's not the solution I would like to use. Hope you guys can tell me how to fix this.

The work around is playing the same stream one layer behind it and just kill the original one once in a time.

**Comment by HellGore** [comment]
> The work around is playing the same stream one layer behind it and just kill the original one once in a time.

Do you mean producer and not consumer?

**Comment by gartner-concepts** [comment]
Good morning,

Thank you for your response!

That's exactly what I'm building now. Every 6 hours the system will create a swap layer on a non visible layer where I will start the same stream and when it's playing it will swap it with the old one and it will be killing the old one on the swap channel.

But is there not something that can just clear the old frames?

And yes I think it's consumer as I always swap those and never know which one it is haha.

Thank your for your reply and hopefully there will be something like a frame remover in the further.

Best Regards,

Kai Gartner


Op 9 mrt. 2017 om 11:22 heeft HellGore <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


The work around is playing the same stream one layer behind it and just kill the original one once in a time.

Do you mean producer and not consumer?

**Comment by HellGore** [comment]
It is producer

**Comment by pkeuter** [comment]
It appears that some function keeps owning the shared_ptr with AVPackets. I have a hard time figuring out where it is though. I reckon it is somewhere in video_decoder.cpp or audio_decoder.cpp

@HellGore do you have any idea what might cause this? Like I said, it's hard to find out the culprit with the shared_ptr. 

Additionally, but I am not sure if this has anything to do with this; when enabling trace logging, I'm seeing a lot of `[ffmpeg] [NULL @ xxxxxxxxxxxxxxxxxxxxxxxxx] Current profile doesn't provide more RBSP data in PPS, skipping`.

**Comment by ronag** [comment]
Closing in favor of #636. Please create a new issue if it still remains after that one is resolved.
