### ISSUE TITLE
Wrong alignment of text for psd templates

### ISSUE THREAD

**Issue by UndeadTrashman** [CasparCG/Server#561]
(Using current beta or development build of server)
When creating psd templates with text, only left-alignment seems to be supported. If I choose center- or right-alignment, the text doesn't crowd around the center or respectively builds to the left aligning to the right side, it just uses the middle or right edge of the text field as basis for a left-alignment. Proper positioning of dynamic text is very hard to do this way, so I would very much like it if this feature got corrected soon.

I've attached an image explaining what happens.
![alignment](https://cloud.githubusercontent.com/assets/21222516/23256530/29de440c-f9c0-11e6-8500-cbe02eec83ab.png)

**Comment by HellGore** [comment]
Could you provide a PSD I can test with?

**Comment by UndeadTrashman** [comment]
Here is my example - a scoreboard for a soccer game (don't mind the german names). f0 and f1 are the teams, respectively. f0 is right-aligned, so it fits to the score, and f1 is center-aligned, which would also be okay for both. f2 and f3 are the score. 
PSD is found here: https://filebin.net/5xqonlopb8c5qtcb/examplescore.psd
I've also attached what it looks like in Photoshop and Caspar Server.
![photoshop](https://cloud.githubusercontent.com/assets/21222516/23259905/b84d726c-f9cf-11e6-9422-39ed3630abfe.png)
![casparcg](https://cloud.githubusercontent.com/assets/21222516/23259908/ba735fe8-f9cf-11e6-8426-22009cc52f62.png)

**Comment by UndeadTrashman** [comment]
Fixed in the named build, works like a charm now. Thanks! 👍
