### ISSUE TITLE
String functions for scene producer

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#563]
I want to ask if there are string functions for the scene producer,  example , toUpper(), toLower(), etc. I could see some mathematical functions such as floor(), sin(), cos() etc in the sample scene templates but nothing to manipulate strings besides the addition.

**Comment by HellGore** [comment]
I will add it. It is super simple to add functionality like that to the scene producer.

**Comment by HellGore** [comment]
perhaps a `strlen()` or simpy `length()` should also be added regarding strings.

**Comment by PeterAkakpo** [comment]
That will be great

Peter Akakpo

Microtech Solutions Limited
peter.akakpo@gmail.com
0205389143

**Comment by PeterAkakpo** [comment]
Good to know that it has been implemented, good work

**Comment by PeterAkakpo** [comment]
to_upper() is not converting string to uppercase

**Comment by HellGore** [comment]
Yes it is when i test it. Every time you make a claim like that you need to give me the file so I can reproduce your problem or give you advice as to what you have done wrong, otherwise how do you expect me to help you?

**Comment by PeterAkakpo** [comment]
It's working now after restarting the server.

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
