### ISSUE TITLE
Child scene timelines

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/Server#564]
Child scene timelines do not work in parent scene. Is it by design or am I doing something wrong. If this is to work, it will save a lot of time . imagine I want a scene with three or two crawlers, I just have to design the base crawler once and then place three of it in my new scene and set parameters to change the content for each.

**Comment by HellGore** [comment]
Try
```
<tasks>
  <cg_play at="0" to_layer="crawler1" />
  <cg_play at="0" to_layer="crawler2" />
  <cg_play at="0" to_layer="crawler3" />
</tasks>
```

**Comment by PeterAkakpo** [comment]
Child scenes are still not playing after issuing those command in the
parent scene

Peter Akakpo

Microtech Solutions Limited
peter.akakpo@gmail.com
0205389143

**Comment by HellGore** [comment]
Well you aren't giving me much to go on here, could you give me the scenes involved?

**Comment by PeterAkakpo** [comment]
[Uploading template.zip…]() these are the two scene files

**Comment by PeterAkakpo** [comment]
[crawler.scene.txt](https://github.com/CasparCG/Server/files/805904/crawler.scene.txt)
[multi-crawler.sence.txt](https://github.com/CasparCG/Server/files/805905/multi-crawler.sence.txt)

i couldn't attach the scene files directly , so i had to add the txt extension

**Comment by HellGore** [comment]
> ```
> <producer>crawler</producer>
> ```

...should read:

```
<producer>[CG] crawler</producer>
```

It creates a CG aware proxy around the scene producer.

**Comment by PeterAkakpo** [comment]
its working now, thanks

**Comment by mauricev78** [comment]
Like the crawler. maybe we should add a version off this
in the deployment. there are a lot off people struggling with
smooth running crawlers/tickers including me ;)

**Comment by HellGore** [comment]
I have now committed an example of how a crawler could be done. It uses a different way of scrolling, by using the `frame` variable instead of timeline tweenings.

**Comment by PeterAkakpo** [comment]
thank you, great work

**Comment by dotarmin** [comment]
Could this issue be closed now?

**Comment by PeterAkakpo** [comment]
Yes.
