### ISSUE TITLE
Multiple active CG sub layer 

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#565]
I have a scene template that I want to play on the same layer but on two different sub layers. I issued the following command. CG 1-1 ADD 0 CRAWLER 1   and CG 1-1 ADD 1 CRAWLER 1. what happens is that the second command overrides the first. But this works CG 1-2 ADD 0 CRAWLER 1 , CG 1-1 ADD 0 CRAWLER 1. the observation is that multiple sub layers cannot be active at the same time.

**Comment by HellGore** [comment]
Yes the layer id after ADD is only used by the flash producer, it is ignored by all other CG producers. The sublayers of a scene can only be controlled by the scene itself, not from the outside without manually creating a scene with that possibility.

**Comment by PeterAkakpo** [comment]
Thanks for the clarity

Peter Akakpo

Microtech Solutions Limited
peter.akakpo@gmail.com
0205389143

**Comment by premultiply** [comment]
May the Sublayer parameter be removed at all?
Flash producers runs better when they are completly removed after STOP or before PLAY.

**Comment by Julusian** [comment]
#850

> Remove CG commands

Looks like ronag also wants to remove the sublayers

**Comment by dotarmin** [comment]
This discussion continues in #850! 😄
