### ISSUE TITLE
Wrong response on REQ command !

### ISSUE THREAD

**Issue by stile2017** [CasparCG/Server#568]
I start with testing some of the new features in casparcg server and i found that new REQ command not property response when i send wrong command.

example:
REQ unique PLAY 2-0 AMB (here we enter invalid channel)
401 PLAY ERROR (response is without unique id)

Need to be:
RES unique 401 PLAY ERROR

**Comment by jesperstarkar** [comment]
Good catch! Thank you.

**Comment by StilSoft** [comment]
Now is OK. The command returns the expected response.
