### ISSUE TITLE
system time as variable in sceneproducer

### ISSUE THREAD

**Issue by mauricev78** [CasparCG/server#569]
Hi

I don't know if this is hard to make but having the systemclock
as a var in the scene producer would be nice.

by the way love the concept off the scene producer good work all !!

**Comment by PeterAkakpo** [comment]
That will be  great

**Comment by HellGore** [comment]
I am guessing you want separate number variables for each component like

```
system_time_year
system_time_month
system_time_day
system_time_hour
system_time_minute
system_time_second
```

**Comment by mauricev78** [comment]
i was thinking in "ms since epoch".

but what you are suggesting is even better :) 

i say YES please

**Comment by PeterAkakpo** [comment]
That would not be bad, but in addition having a system time and date and
functions like hour(), seconds(), minutes(), milliseconds(), year() to
extract those variables. Variables will be hard to guess if there are not
proper documentation. But with functions like those stated above, they are
common function in most programming languages and would not to difficult to
guess

Peter Akakpo

Microtech Solutions Limited
peter.akakpo@gmail.com
0205389143

**Comment by PeterAkakpo** [comment]
Consider System_time_millisecond too, someone might ask, how do we format this variables to get their string representations like March 7, 2017 07:20 pm

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
