### ISSUE TITLE
Re-read config file via AMCP

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#57]
Converted from [SourceForge issue 3563177](http://sourceforge.net/support/tracker.php?aid=3563177), submitted by hummelstrand

Being able to change the config file remotely and then have the server re-read it would be handy.

**Comment by jesperstarkar** [comment]
Restart has been implemented. And consumers can be added/removed over AMCP. Event the channel format can be changed. The only thing that's not runtime configurable is the number of channels.

This issue can be closed, and I'll file a new one requesting manipulating the number of channels, if that's possible to implement.

**Comment by jesperstarkar** [comment]
@HellGore can be closed.

**Comment by HellGore** [comment]
But this could be good for another reason than changing the config at runtime -- that it remains changed every time you restart.

**Comment by HellGore** [comment]
> Being able to change the config file remotely

This is the part of the feature request I was referring to. Sort of like a `DATA STORE` like situation but for the configuration.

**Comment by jesperstarkar** [comment]
A config-save function you mean? So that config-changes (producers etc) added runtime can be stored persistently?

**Comment by HellGore** [comment]
Actually I didn't mean that the server should generate the XML based on the runtime configuration currently in effect, but that would be even more useful.

I meant simply instead of using ftp/samba to overwrite the file with the intended changes, AMCP could be used for that purpose.

**Comment by jesperstarkar** [comment]
Cool. Having sort of a local library of configs then loading at runtime (effectively restarting caspar with a new argument for config to choose)

**Comment by HellGore** [comment]
Do you mean selecting the filename as well? I was only thinking about a reverse `INFO CONFIG`, so it overwrites the config file **in use**, so that a `RESTART` causes it to be reread.

Selecting **which** config file to use would still be done via the initial command line parameter.

**Comment by jesperstarkar** [comment]
Hmm, that might be the easiest way to go. I actually don't know when to use it, so it is hard to say what's needed.

**Comment by jesperstarkar** [comment]
Being able to add channels is the primary objective here, and that's not solved until you can re-read a specific config at runtime or the combination of adding channels runtime and updating current config, as you say.

**Comment by HellGore** [comment]
Actually me neither. Only for programs similar to the Frontend, but with the difference that they would not have to run on the same computer.

**Comment by jesperstarkar** [comment]
Yeah, third party solutions could easily create configs and restart. So what's really needed is the runtime channel manipulation (#391)

**Comment by hummelstrand** [comment]
@jesperstarkar Keep or close this issue?

**Comment by ronag** [comment]
RESTART does this.

**Comment by TomKaltz** [comment]
I think that feature isn’t working. I’ll have to check again but I think I tried last week and did nothing.
