### ISSUE TITLE
Nesting or grouping layers in scene  producer

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#570]
What to find out if there are ways to group layers so that coordinates of the inner layers will be relative to the parent layer instead of the the scene itself. Example

```
<layer>
    <layer>
    </layer>
</layer>
```

**Comment by HellGore** [comment]
Not in that way, but via sub-scenes. Currently there is no way to defina a subscene inline within the same XML, but perhaps that would be good.

**Comment by TondaKrist** [comment]
That will be great since currently it is not possible to apply KEY (mask) to whole SUBSCENE. So each layer has to have own KEY.

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
