### ISSUE TITLE
high memory consumption - server 2.1

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#572]
I have been looping a 5mb mp4 file ( length is about 45seconds) with command "play 1-0 ad loop" for about 12 hours  and the memory consumption of the server within task manager was about 3gb, CPU about 10% , Is this normal?, I am using the march 7 build of the server. The server config is the default that came with the download.

**Comment by HellGore** [comment]
How was the memory consumption when you just started playing? Depending on what computer you have 10% cpu might be normal, or might not be.

**Comment by PeterAkakpo** [comment]
The memory increases by 1 mb every two seconds right from start

Peter Akakpo

Microtech Solutions Limited
peter.akakpo@gmail.com
0205389143

On 10 Mar 2017 09:01, "HellGore" <notifications@github.com> wrote:

How was the memory consumption when you just started playing? Depending on
what computer you have 10% cpu might be normal, or might not be.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CasparCG/Server/issues/572#issuecomment-285614831>, or mute
the thread

**Comment by HellGore** [comment]
I can't reproduce that with any file that I have. You will have to give me the file and the video mode you are running
