### ISSUE TITLE
COM SDK

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#573]
Beside the client server mode, is it possible to build the source as a com SDK to be used in a standalone application, just like medialooks mplatform sdk.

**Comment by HellGore** [comment]
The `shell` project uses the rest of CasparCG in that way.

**Comment by HellGore** [comment]
Not as a `COM SDK` though.

**Comment by PeterAkakpo** [comment]
I have noticed that casparcg served is down, is that delibrate or something
else is going on

Peter Akakpo

Microtech Solutions Limited
peter.akakpo@gmail.com
0205389143

**Comment by 5opr4ni** [comment]
Hi

No, we are having som issues with the hosting that probably will be resolved today. 

/Olle

**Comment by PeterAkakpo** [comment]
Thanks , that is a relief

Peter Akakpo

Microtech Solutions Limited
peter.akakpo@gmail.com
0205389143
