### ISSUE TITLE
MIX command causes audio sync to go badly off

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/Server#575]
Commands like this
PLAY 1-1 "XDCAM EX 35-COUNTER_H264" MIX 75
causes audio to go badly offsync.
Tested with HDcam MXF and HD h264 mp4 files.

steps to repro
test a file with
PLAY 1-1 "My testfile" to check audio sync
the test
PLAY 1-1 "My testfile" MIX 75

result
audio slows down and goes about 3 seconds offsync

VERSION SERVER
2.1.0.3394 5422850 Beta 1

**Comment by TKooijmans** [comment]
Just tested this and it works fine now but.......
If you use this combination with MIXER FILL and effect duration>0 the same problem occurs.

steps to repro with mixer fill and effect duration 50
MIXER 1-1 FILL 0.13 0 0.75 1 50
PLAY 1-1 "my video"

result in audio offsync of 50 frames

**Comment by HellGore** [comment]
The second problem should now be fixed as well.

**Comment by vimlesh1975** [comment]
Development and bug fixings are on fast Track.

**Comment by jesperstarkar** [comment]
I think we have encountered this bug as well. Will try to recreate with an old version, then check the referenced fix.

**Comment by TKooijmans** [comment]
Yep it's fixed!
Well done!
