### ISSUE TITLE
PURGELOGS

### ISSUE THREAD

**Issue by didikunz** [CasparCG/Server#576]
I would suggest adding a AMPC command to purge the logfile. Like PURGELOGS [numberOfFilesToKeep:int] that would delete older logfiles and keeps the most rescent ones defined by the number given. As on many systems (at least on all of mine) the CasprCG folder with all media, templates including the logs are stored on a SSD, that is not too big and the logfiles were eating space until nothing is available any more. As long as Caspar is run localy (localhost) I can add this functionality into the client. But for a remote server it will be not that easy.

**Comment by jesperstarkar** [comment]
It's not a bad idea, but it's not critical either, in my opinion. How about putting your log folder on another disk for a starter?

**Comment by premultiply** [comment]
Why don't you use logrotate or similar tool on the machine running the CasparCG server?

**Comment by HellGore** [comment]
Yes, I agree with @premultiply that this type of housekeeping task is usually done by another tool outside of the software doing the logging.

**Comment by didikunz** [comment]
Aha, I did not even know tools like logrotate existed. Good tipp, thanks.

**Comment by didikunz** [comment]
We could get rid of this request, because there seems to be tools to handle this nicely.

**Comment by HellGore** [comment]
ok, closing
