### ISSUE TITLE
CasparCG Multiple Instances

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#578]
Please find attached a snapshot of my task manager showing two instances of casparcg.exe running. Is that normal? i am running on the lastest download.
![untitled](https://cloud.githubusercontent.com/assets/7926382/24078909/7cf97778-0c72-11e7-82e8-e331817b3141.png)

**Comment by HellGore** [comment]
Yes, one is the CEF host process for the HTML producer.
