### ISSUE TITLE
Question about "CINF" command

### ISSUE THREAD

**Issue by sasestil** [CasparCG/server#580]
Hello.

I am curious why the command "CINF" returns information for all files with the same name. This seems somewhat inconsistent compared to other commands like "THUMBNAIL RETRIEVE" or "THUMBNAIL GENERATE", which return only information about the file you want.

Another problem with this way of implementation of this command is that as when you ask for information about a file that is located in the subdirectory (for example: CINF "folder/filename") command returns a 404 (media file not found) which is not true.

It would therefore be good this command returns information only for the requested file.
This suggestion is just to maintain consistency between similar commands.

Regards,
Aleksandar

**Comment by jesperstarkar** [comment]
Are you testing 2.0.7 or 2.1.0? The behaviour has changed in 2.1.0

**Comment by StilSoft** [comment]
I tested both versions of casparcg 2.0.7 and the latest 2.1.0.
The behavior is the same for both.

**Comment by ronag** [comment]
This functionality is moved to https://github.com/CasparCG/media-scanner
