### ISSUE TITLE
Animated Text producer

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#581]
Is there a were to produce an animated text with the text producer? Example like splashing of  text, which is common in most cg softwares

**Comment by 5opr4ni** [comment]
Hi

This is a question that belongs in the forum at casparcg.com. There are a bunch of people eager to help you. Please remove the issue. 

/olle

**Comment by PeterAkakpo** [comment]
Hi, you and I know there is nothing going on in the forum concerning version 2.1 and beside this is a question about functionality of the product and if it does exist the it become a good opportunity to add such functionality. Unless it already exist then you can direct me to the forum with a link pointing to such topic. Just instructing me to remove the ticket I think is so unfair on your part. We have asked similar question and helcore was considered then and give direction and even tries to implement them when he finds then necessary, all thanks to him.

**Comment by 5opr4ni** [comment]
Hi
Again, this is a question for the forum. if you search for Scene Producer and read a little about it and then download the server from builds and have a look in the Server/template/scene/crawler for example, you can se what you can do with the text producer. If no one starts the discussion in the forum nothing will happen there, and there is discussions about the scene producer which is a good way to ad functionality to the text producer. We do read the forums also, even Helgore, and thats the place for learning and sharing, and picking up ideas for us. Here at Github it is about development and testing. If we start having tutorials and help here it will end up very suboptimized and it will take time from the developers answering these questions. If you want to contribute to the project, we would be very glad if you initiated some threads regarding the text producer in the forums.

Regards
Olle Soprani
founder

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
