### ISSUE TITLE
Scene Producer - Dynamic Color layer

### ISSUE THREAD

**Issue by didikunz** [CasparCG/server#583]
I alreday posted this in the forum, but here is probably the better place. I played around with the new scene producer for a while. A little thing, that I noticed is missing (or I did not found it) is:

An easy way to set the color of a layer dynamicaly. There are functions to modify hue saturation and brightness, so it could be done somehow, but nice would be a way to set the color from a hex argb-value.

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
