### ISSUE TITLE
Scene Producer - Dynamic Image Producer

### ISSUE THREAD

**Issue by didikunz** [CasparCG/server#584]
I alreday posted this in the forum, but here is probably the better place. I played around with the new scene producer for a while. A little thing, that I noticed is missing (or I did not found it) is:

A dynamic image producer, or at least a way to send an image from the client, without putting it into the media folder. Can I host a Flash layer for this?

**Comment by didikunz** [comment]
Any news on this? For sports graphics, this is critical. So we need it asap, otherways the Scene producer is not of much value and that would be bad, as it's a very good idea.

**Comment by PeterAkakpo** [comment]
So how does the comited dynamic  image work. i have tried passing the image through a public variable, but it didnt work.

**Comment by Julusian** [comment]
Only available in my builds, this is a scene I have used showing it in action https://github.com/GuildTV/elections-gfx/blob/master/caspar/template/GE2018/winner-inner.scene

**Comment by PeterAkakpo** [comment]
@Julusian , i just downloaded your build and both [COLOR] and [PNG_BASE64] works fine. is there something similar for FFMPEG and ROUTE layers in your build, where the clip name can be passed through a variable.

**Comment by Julusian** [comment]
There is not. Ffmpeg and route producers do not support changing their source after creation, which is behaviour that scene producer variables relies on

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
