### ISSUE TITLE
Scene Producer - Blur Filter

### ISSUE THREAD

**Issue by didikunz** [CasparCG/server#585]
I alreday posted this in the forum, but here is probably the better place. I played around with the new scene producer for a while. A little thing, that I noticed is missing (or I did not found it) is:

A blur filter to cast a soft shadow or similar stuff.

**Comment by HellGore** [comment]
This would be implemented as a general image mixer feature, and also exposeable via a `MIXER BLUR` command.

**Comment by didikunz** [comment]
As long as it's accessable from the scene garph xml, that is ok with me.

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
