### ISSUE TITLE
HAP codec support by upgrading FFMPEG

### ISSUE THREAD

**Issue by mauricev78** [CasparCG/server#587]
Hi all

i see that FFMPEG is already supporting the HAP codec for a while
I have very good results with other commercial software and this codec.
as it is opensource i think it could be used within CCG

see 
https://github.com/vidvox/hap

and of coarse FFmpeg

**Comment by mauricev78** [comment]
ok i found out including "libsnappy" gives me support for decode and encoding HAP
while compiling FFMPEG from source. but i have no clue how to implement in CCG

**Comment by mauricev78** [comment]
bump

**Comment by ronag** [comment]
I've never seen the point of HAP. Feels more like an overly hyped technology which is "cool". Anyone care to enlighten my narrow opinion?

**Comment by MauriceVeraart** [comment]
you are right in saying that some people are seeing it as some sort of holy grail ,
which indeed it is not.

for "normal" playout like HD or UHD there is no point in using it.

on the other hand for higher/veryhigh or odd resolution systems this codec 
has a very nice balance in diskspeed/cpu/gpu load.

i already experienced that with Watchout / D3 / etc etc on several jobs

experimenting / doing jobs with casparCG on these resolutions shows me that
the bottleneck is quite often in CPU use for decoding.

for instance on a job where i use casparcg as a playout the resolution is
7680x2160 for one channel with casparcg i cannot get higher then 25P
while watchout on HAP can do it with ease on 50P

but i needed the wonderfull flexibility off casparCG
