### ISSUE TITLE
No sound when playing mp3 file with embedded artwork.

### ISSUE THREAD

**Issue by sasestil** [CasparCG/server#589]
casparcg not playing mp3 files with embedded artwork.
I tested with casparcg 2.0.7 and 2.1.0.
On older versions 2.0.6 and 2.0.4 mp3 file playing ok.

example files:
https://drop.me/BEPnqM (file without artwork)
https://drop.me/M7lRdB (same file with embedded artwork)

**Comment by TondaKrist** [comment]
Same Issue, is it possible to play MP3 with artworks?

**Comment by k4kfh** [comment]
I also have this issue.

**Comment by ronag** [comment]
Please test with 2.2 and reopen if still an issue.
