### ISSUE TITLE
adding a preview screen increases CPU load

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/Server#590]
It seems when adding a preview screen CPU load increases 10 to 20%

With this command I could add a screen without much load on the CPU
ADD 2 SCREEN 1 NO_AUTO_DEINTERLACE
PLAY 2-1 route://1

Using PAL settings for the preview channel should cause very low load.
With Win7 i7 cpu I see now a increase on load of about 15%.
This increased CPU load starts after I start the Route command.

**Comment by HellGore** [comment]
I have now added automatic deinterlacing to the channel route feature. So depending on what video format is in use on the routed-from channel yadif will be used.

**Comment by TKooijmans** [comment]
Quality of the preview screen is not important for me,  I just like to have a preview screen with nearly no CPU load.
With NO_AUTO_DEINTERLACE  CPU load was much less then with deinterlace active.

**Comment by TKooijmans** [comment]
![server v2 1 0 3394](https://cloud.githubusercontent.com/assets/4194609/24796032/b407a0e6-1b8b-11e7-9a4c-891faa9532fc.JPG)
![server v2 1 0 3422](https://cloud.githubusercontent.com/assets/4194609/24796039/b740c8fa-1b8b-11e7-9c14-a006971ba3c7.JPG)
Here is a comparison between Server V 3394 and Server V 3422, tested on a i5 Intel CPU and GTX570.
The preview screens take much more CPU load with the latest 3422 version.
Preview screens are set with deinterlace off.

**Comment by HellGore** [comment]
I have now added a `NO_AUTO_DEINTERLACE` flag to the `route://` producer as well. The default will still be to deinterlace interlaced content, but you can explicitly state that you don't want that with this parameter.

**Comment by TKooijmans** [comment]
This works great now!
I use these commands to startup of the screens in no_deinterlaced and de_interlaced route
ADD 3 SCREEN 1 NO_AUTO_DEINTERLACE
PLAY 3-1 route://1 NO_AUTO_DEINTERLACE
ADD 4 SCREEN 1 NO_AUTO_DEINTERLACE
PLAY 4-1 route://2 NO_AUTO_DEINTERLACE
Performance is great now! same system as above i5 , see picture
![grab systeem](https://cloud.githubusercontent.com/assets/4194609/24831020/e26caf10-1c91-11e7-9f3b-1f0716dcf78f.JPG)

**Comment by HellGore** [comment]
OK, good. Closing
