### ISSUE TITLE
Scene Producer - Mouse Click Task

### ISSUE THREAD

**Issue by didikunz** [CasparCG/server#592]
The Scene Producer supports mouse coordinates. It would therefore also make sense to support a mouse click as a "Task". That would allow some kind of button actions and the like to occure, because we could trigger something inside the template by clicking on something else.

The best would be to get back the name of the topmost layer in the scene where the mouse has been clicked, inside a global variable, That would be the luxury version. Simple trigger of a task would be enough for now.

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
