### ISSUE TITLE
AUDIO SYNC test server 2.1  build 3431

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#593]
I tested AV sync with build 3431 and I  found following
- HD mp4 file playback to Decklink output and recaptured                        Audio offset +1 frame (not sync)
- HD mp4 file playback to Casper File recorder  (mp4 format)                   Audio offset +1 frame (not sync)
- HDcam mxf playback to Decklink output and recaptured                       AV sync is ok
- HDcam mxf playback to Casper File recorder (mp4 format)                    AV sync is ok
- Black Magic Mjpeg HD avi playback to Decklink output and recaptured                       AV sync is ok
- Black Magic Mjpeg HD avi playback to Casper File recorder (mp4 format)                    AV sync is ok

So it seems we have 1 frame audio delay with playback of mp4 files.
steps to repro
render within Premiere Pro the Universal Counter leader with 1 sec beep to an h264 HD 1080i50 mp4 and
a HDcam50  MXF file.
playback both files with CasperCG server while capturing the output.
compare original with capture in Premiere Pro.
(Note Casper File recorder only captures in uncontrained 444 mp4 codec, all options are ignored.)
(this file let's Premiere crash, so you have to convert the file with AME)

**Comment by ronag** [comment]
@TKooijmans @5opr4ni please test and re-open if still an issue with 2.2.
