### ISSUE TITLE
After Effects render settings not opening on AECC2017

### ISSUE THREAD

**Issue by craftbyte** [CasparCG/Server#594]
I don't know where to file this, but it seems like when I try to open the After Effects Render Settings, it just adds weird characters on my Windows PC. I also tried on my Mac and it says it cannot read Unicode characters. Is there anyone who would be willing to export their render settings and update the download on Sourceforge?

**Comment by walterav1984** [comment]
Have you contacted Adobe about this?

**Comment by craftbyte** [comment]
No, I havent. I did some more debugging and it seems like it has something to do with wrong memory addresses. Not CasparCG related, so closing
