### ISSUE TITLE
Linux CasparCG server FILE consumer overwrites namedpipe instead of feeding it WORKAROUND

### ISSUE THREAD

**Issue by walterav1984** [CasparCG/server#596]
Update: Workaround
Thanks to @sesse and @baltedewit  the following ACMP command or .config file syntax is usable as a workaround with ffmpeg and melt, however I'm using rgba instead of bgra otherwise visual distortion occurs in melt and ffmpeg have to do pixel format conversion. This should be only used on a local machine not a LAN because of performance issues, maybe "Ultragid" @captnced will give a future opensource NDI alternative.

```
add 1 stream unix:///home/user/caspar.sock -c:v rawvideo -vf format=pix_fmts=rgba -f nut -listen 1
```

```
      <consumers>
       <!-- <screen>
          <device>1</device>
          <windowed>true</windowed>
        </screen> -->
        <ffmpeg>
          <device>1</device>
          <path>unix:///tmp/caspar.sock</path>
          <!-- <path>udp://localhost:5251/</path>  -->
          <args>-c:v rawvideo -vf format=pix_fmts=rgba -f nut -listen 1</args>
        </ffmpeg>
        <system-audio></system-audio>
      </consumers>
```

Original Issue:
This is probably intended behavior to overwrite already existing file(named pipe) `mkfifo /tmp/cgout.mov #creates the namedpipe`  when adding a FILE consumer to CasparCG Server using the following ACMP command from the server console  `add 1 file /tmp/cgout.mov `. The server is started using its default casparcg.config PAL settings.

However my expectation is that instead of replacing the namedpipe "cgout.mov" with a growing output file, CasparCG should feed the namedpipe realtime data like ffmpeg can when it adds a FILE consumer. I would expect that CasparCG shell may not do Bash Shell pipe|redirection> tricks but this is not even necessary  since ffmpeg avio understands and could accomplish this see example: 
 
```
mkfifo /tmp/cgout #creates the namedpipe 
melt -profile dv_pal_wide /tmp/cgout -consumer decklink #reads the pipe waits for feeding
ffmpeg -i test.mkv -vcodec copy -acodec copy -f matroska /tmp/cgout #feeds the pipe
```

Is there any other ACMP syntax / parameters like "STREAM" which sesse and balte use instead of "FILE" I can try since calling ffmpeg stream only wants to write to a netsocket and won't allow RAW video container as output?

Purpose is to pipe uncompressed RGBA  raw video container to "melt" composer and or "melted" server without the need of multiple Decklink SDI cards being connected with short loop cables with their selfs on the same system. Another tested workaround to full fill this purpose is using NDI, but that requires CasparCG Server on Windows with the tricaster plugin.

Version: CasparCG Server both linux beta's on ubuntu 16.04, ffmpeg version 2.5.10
Keywords: boost, nonblocking, asynchronous, avio

**Comment by baltedewit** [comment]
The file consumer is doing exactly what you're asking it to. In this case, the stream consumer would be more appropriate.

I did quite a bit of testing with casparcg and unix domain sockets for superflytv recently. I got it as far as receiving raw video over the socket, but I wasn't able to get playback working without artifacts. I think that' s more due to my knowledge than anything though. In the end I settled with using the libx264 codec with a matroska container.

You said calling "ffmpeg stream" (I assume you mean the stream consumer here?) won't allow RAW video container as output? What exactly makes you think that?

**Comment by walterav1984** [comment]
> The file consumer is doing exactly what you're asking it to.

We'll for what I read boost library even though (melt/melted) is not a child application initiated by casparcg might still detect the named_pipe and act like its writing to a file (if pipe is connected at other side at same time) without notice.

ffmpeg does it, casparcg with ffmpeg -- any ffmpeg_parameter should be able aswell but I haven't found a working syntax?

> You said calling "ffmpeg stream" (I assume you mean the stream consumer here?) won't allow RAW video container as output? What exactly makes you think that?

Found it somewhere in the ffmpeg mailing lists it was something related to timestamps with -f rawvideo go lost when streaming from ffmpeg instead of file/pipe redirect. If I'm not mistaking it will let you choose rawvideo but the player application at the end of the stream won't play a thing... in my case. Sorry I couldn't be more specific. Mpegts had other problems.

> ... the stream consumer would be more appropriate.
That would be an option because it will not care if the destination is actually been active, but 

The bigger purpose might be looking for an intra broadcast software universal consumer-producer linking system without the declink requirments for instance to feed OBS-studio or melt in my case with CG graphics. If it can be IP based which the streaming option of ffmpeg might assist in is great but not necessary.

**Comment by walterav1984** [comment]
Looks like @sesse  is going in the same direction (using software instead of hardware SDI) for feeding RGBA CasparCG Server output feed to its own software mixer/compositor called Nageru.

https://nageru.sesse.net/

https://git.sesse.net/?p=nageru;a=commit;h=bcdbb7bdfcfc45b34ccdf36d3950e7e0af6444bd

**Comment by sesse** [comment]
What @walterav1984 says is true, but it doesn't really work well unless CasparCG and Nageru are on the same machine. The longer-term plan for that is to also support NDI, but the current NDI licensing situation makes that impossible for me.

**Comment by walterav1984** [comment]
A use case on the same machine should already be great to have, since CasparCG may have its client on a different machine for interaction and the current machine will remain available for realtime interaction with the Nageru GUI control.

Will it require a "small" patch (libboost, nonblocking, asynchronous I'm just guessing) to CasparCG server its ffmpeg consumer implementation or do you have it running already with only patches on the Nageru side?

For remote IP based solution a problem besides sync will be uncompressed size of HD sources on 1Gbit LAN. Could this https://github.com/vidvox/hap assist in finding a NDI alternative, it uses S3TC to compress maybe it does it fast and small enough to get it over a lan with netcat?

I'll be willing to test any patched for CasparCG/Nagera or related broadcast apps melt/obs-studio, but first I should try to get Nageru to build and run on ubuntu 16.04 amd64 ;-)

**Comment by sesse** [comment]
Well, it seems to work already (no patches on either side). But I've done very little practical testing, so perhaps there's some snag I haven't thought of that will only show itself in real use.

S3TC has problems in itself, notably patents and IIRC pretty slow encoding.

**Comment by walterav1984** [comment]
Great to hear that it already seems to work for nageru :+1: .

Could you hint what kind of ACMP command  FILE / STREAM consumer and ffmpeg parameters (codec/container) you used to get the feed out of CasparCG Server this might work already with melt/obs-studio?

**Comment by sesse** [comment]
I never use melt or OBS, sorry.

**Comment by baltedewit** [comment]
Instantiate a listening unix socket, send the amcp command to stream to unix://pathtosock with parameters to send rawvideo out. I don't have my documentation on the commands for rawvideo but it would look something like `add 1 stream unix:///tmp/sock.sock -vcodec rawvideo -f rawvideo`

You should be receiving bgra rawvideo if all goes well. If caspar doesn't start the stream, set the debug mode to trace to get ffmpeg output.

**Comment by walterav1984** [comment]
Thanks got it working with similar looking syntax from @sesse his casparcg.config but still need to check if this can be used for 24/7 uptime:

https://git.sesse.net/?p=ultimatescore;a=blob_plain;f=casparcg.config;hb=HEAD

Still as a workaround I have to let ffmpeg do the reading of the unix socket and than pipe the output to melt. If I use bgra instead of rgba I also have to let ffmpeg change the pixformat otherwise black and white distorted frames will show up in melt composition.

**Comment by sesse** [comment]
I ran mine in a test over a few hours, which seemed to work well, but nothing like multiple days. There are a couple of issues:

* If the socket already exists, the listen fails, and there's no way of deleting it. (This is probably an FFmpeg issue.)
* The socket is one-shot; once Nageru (or melt, or whatever) has connected and then disconnects, the socket is dead and can't be reused. CasparCG should really restart it in this case, assuming the previous point gets fixed.
* As far as I can see, the duration of the frames is always 1, but the timebase is 1/60000. This isn't so critical, though, just a nit. And it might be my misinterpretation of the stream somehow.
* FFmpeg's muxers are not really optimized for transporting raw video. There's a lot of copying around that takes up CPU, and the trip through the kernel isn't so fast either. The transport is wasting almost a core for me (well, half a core). The ideal thing would be a transport through shared memory, or even better, sharing OpenGL surfaces through EGL (or equivalently for Windows, something like Spout).

**Comment by walterav1984** [comment]
Thanks for hinting possible show stoppers for the socket solution and mentioning Spout, I didn't knew of its existence :+1: . Spout brings me to Syphon for Mac Os.

Good to see multiple parties are trying to look for intra software realtime graphics sharing opengl/directx/video and others to port it over the network (ndi).

**Comment by captnced** [comment]
I know NDI is getting momentum in the industry but I shall mention an alternative option I've found interesting : UltraGrid (http://www.ultragrid.cz), which I understand looks GPLv2 compatible.
https://github.com/CESNET/UltraGrid/ 
Anyone here know about it ?

**Comment by 5opr4ni** [comment]
Nice!

**Comment by sesse** [comment]
I guess you didn't mean to close this? I don't see a workaround, and in any case, even if there is one, the bug is still a bug.

**Comment by walterav1984** [comment]
Maybe this issue can be addressed in restructuring the ffmpeg_consumer for the 2.2.0 target, like the ffmpeg_producer is undergoing right now?

As a little summary, the purpose of this fix/feature is to pipe the RGBA / BGRA video+audio output from casparcg server consumer to a other piece of video mixing software on the same machine which does composite it realtime as an extra layer. For instance mlt-framework melt & melted or nageru mixer or even obs-studio.

**Comment by ronag** [comment]
Is this a problem with 2.2? If so please re-open and give me a short summary of what this is?

**Comment by sesse** [comment]
Look at the first message in the issue (under “Original issue”) for a short summary of what it is? Or the issue title, for that matter.

**Comment by walterav1984** [comment]
Would like to test/confirm this issue is still there in 2.2.0, but don't know how to get 2.2.0 to run outside the docker build out so I can read/write media files/pipes  have Nvidia/Intel opengl 4.5. 

Like sesse mentions, the issue is really explained in the first post "Original issue" the title of the issue is really its subject: "Linux CasparCG server FILE consumer overwrites namedpipe instead of feeding it" cannot be more specific?

**Comment by ronag** [comment]
ah, yes, silly me... the feeding code is not in caspar but handled by ffmpeg. So it might just have been an issue of caspar using an old ffmpeg version.

Please try with 2.2. Unfortunately I can't help much with Linux & Caspar.
