### ISSUE TITLE
fast_memcpy is not very fast

### ISSUE THREAD

**Issue by sesse** [CasparCG/Server#598]
Hi,

When profiling CasparCG, I've noticed that it spends a lot of time in its own home-grown casparcg::fast_memcpy function. Writing such functions oneself instead of relying on the compiler-provided ones nearly always ends up making them slower, and indeed, so is the case here too; it seems the version used (memcpySSSE3) is a rather naïve, not-very-unrolled movaps loop. If I replace fast_memcpy with simply memcpy, the CPU usage on my machine (for the same simple HTML5 test scene, at 720p59.94) goes down from 80% to 55% and the memcpy routines fall almost entirely off the profile.

FWIW, this is on Linux; I don't know what the situation is like on Windows, but I have a hard time believing this won't be an equally big win there.

**Comment by HellGore** [comment]
Very interesting. I will check it out on Windows and see how it goes there.

**Comment by jesperstarkar** [comment]
By closing this, is the issue resolved? Any commits to this, if so?

**Comment by dimitry-ishenko** [comment]
@jesperstarkar #598 above is the commit

**Comment by dimitry-ishenko** [comment]
@ronag thanks for reviving 2.1! :smile:
