### ISSUE TITLE
Use Flash player 11.4 Worker API for TemplateHost

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/Server#60]
Converted from [SourceForge issue 3563668](http://sourceforge.net/support/tracker.php?aid=3563668), submitted by jesper-s

"Concurrency" (semi multithreading) can be achieved by using the new Worker API in Flash player 11.4. This means that every template can run independently in multiple players, and just sending their graphics to the main "thread" in TemplateHost.

We should evaluate and re-write the whole of TH to a new version, getting rid of legacy code and add new requested features for "smarter" templates.

**Comment by jesperstarkar** [comment]
This should be close.

Stupid idea (made by me).
