### ISSUE TITLE
CPU time is wasted on timing buffer mappings (and inefficient buffer management in general)

### ISSUE THREAD

**Issue by sesse** [CasparCG/Server#603]
A profile on CasparCG (HTML5 producer, Linux, FFmpeg raw output over socket) yields, among others:

```
-   22,44%     5,63%  OpenGL Renderin  [kernel.kallsyms]           [k] system_call_fast_compare_end
   - 18,43% system_call_fast_compare_end
      - 11,39% sys_clock_gettime
         - 5,41% posix_ktime_get_ts
            - ktime_get_ts64
                 3,42% read_tsc
           4,71% copy_user_enhanced_fast_string
      - 4,94% sys_sched_yield
         - 4,05% schedule
            - 3,38% ktime_get_ts64
               - 2,32% __schedule
                    0,68% pick_next_task_fair
                  + 0,61% update_rq_clock.part.82
               + 0,62% sys_futex
           0,54% _raw_spin_lock
   + 3,36% 0xbeef0100
```

So seemingly, something like 20% of all CPU time on just getting the clock. From what I can see, this is about the continuous measurement of every buffer mapping call, so that it can output a warning if it takes more than 20 ms.

This is symptomatic of a somewhat deeper problem in CasparCG's OpenGL handling; the flow is convoluted through futures and threads, so I might be missing something, but it is seemingly very fond of creating a buffer, mapping it, memcpy-ing into the mapping, unmap, using the buffer (for e.g. a texture upload) and then reusing it on the very next frame. This is not how you get high-performance OpenGL buffer management; by the time you're mapping the next frame, the GPU might still be working on the current one, and you'll get a CPU-GPU synchronization point, which is bad (the CPU has much more interesting things to do than to wait for the GPU to get ready, and then the GPU has to wait for the CPU to be able to generate more work for it afterwards, so it's really lose-lose).

There are two approaches, really: The classical one is calling glBufferSubData() instead of map + memcpy + unmap. If map + memcpy + unmap _is_ the fastest way, the driver will know and do that behind the scenes. If you're lucky, it could end up creating another buffer if the current one is busy, although you have no guarantees of that. In general, you want to have multiple buffers that you rotate through (occasionally known as ping-ponging, although that's inaccurate in this context), so that you minimize the risk of blocking, whether the driver is trying to save you or not.

Having multiple buffers also allows implementing more efficient schemes than glBufferSubData(), through persistent mappings. (This is part of a larger scheme known as AZDO, or “Approaching Zero Driver Overhead”.) Persistent mappings are ostensibly only available in OpenGL 4.5 or above, but nearly every card that supports OpenGL 3.0 supports them through the GL\_ARB\_buffer\_storage extension (since this is really about the driver, not the hardware), so it's pretty universal by now. In this scheme, for every buffer you create a persistent memory mapping, decode your data straight into that (or memcpy, if you can't easily do so) and then upload from that.

Using persistent mappings requires some care in that you need to make sure the GPU is done with the data before you can reuse the buffer, because you don't have a map call to block on. (Multiple strategies are possible, but in the end, it boils down to setting fences to know when the GPU has reached a certain point where you know it won't need your buffer anymore.) However, it largely eliminates any worries about the driver overhead of mapping and unmapping buffers, and it generally makes the handling of buffers much more explicit instead of the mysterious “well, uh, the map call blocked, I don't really know why”. Unfortunately, this strategy seems somewhat difficult to reconcile with CasparCG's current architecture.

But in any case, simply removing the map timers in production builds would probably speed up things a bit. :-) Or at the very least, doing some sort of random sampling so they're not measured as often.

**Comment by sesse** [comment]
Actually, even after removing CasparCG's timers, there are still thousands of clock\_gettime calls left every second (interspersed with sched\_yield); seemingly they are part of a busy-waiting scheme from NVIDIA's OpenGL driver. I guess this just reinforces my point about needing a conscious buffer management and CPU/GPU parallelism strategy (although the point might be more about readback than upload), but it removes the quick-fix of just killing the timers. :-)

**Comment by ronag** [comment]
I will look into this once I'm through some more high prio issues.

**Comment by ronag** [comment]
@sesse I have taken a look and although things could be done with lower overhead I don't see any major issues with the current implementation.

Sure, we can and should clean up a bit and remove the timers (https://github.com/CasparCG/Server/tree/opengl).

> but it is seemingly very fond of creating a buffer, mapping it, memcpy-ing into the mapping, unmap, using the buffer (for e.g. a texture upload) and then reusing it on the very next frame

map, memcpy, unmap, upload is the correct flow. It is not re-used on the next frame both through buffering in casparcg and the fact that we do `GL(glBufferData(target_, size_, nullptr, usage_))` to disassociate the underlying buffer storage from the buffer id so the driver can finish doing whatever it needs.

The biggest problem is that when doing readback `glReadPixels` and then calling `glMapBuffer` before the driver has downloaded the data can cause us to block everything. However, casparcg wait's ~2 frames before mapping after calling read... and if we can't read back a frame in the duration of 2 frames then we already have a problem.

**Comment by sesse** [comment]
> @sesse I have taken a look and although things could be done with lower overhead I don't see any major issues with the current implementation.

Well, perf does show there's a fair amount of CPU time spent in blocking. I don't know if this counts as issues for your use case or not. For my part, I had to eventually resort to running CasparCG at 4 (!) fps to have CPU left for the rest of the stuff on the system :-)

> map, memcpy, unmap, upload is the correct flow. 

It's semantically correct, but it's not performance-optimal by any means. There's absolutely no reason to use the mapping path if you're only memcpy-ing anyway (ie., not saving copies by rendering directly into it); at best, you're just increasing driver overhead by doing more calls.

> It is not re-used on the next frame both through buffering in casparcg and the fact that we do GL(glBufferData(target_, size_, nullptr, usage_)) to disassociate the underlying buffer storage from the buffer id so the driver can finish doing whatever it needs.

Why would you ever want to run glBufferData like this? It sounds like a path a driver would never optimize for, and worse, it requires that you create a new buffer the next time (on the same buffer name). Essentially, if you want to create new buffers for every frame, just do so, instead of going through this complicated dance of trying to associate new buffers with the same names. But better yet, actually reuse the buffers (not just the names), and reuse the mapping, too.

> The biggest problem is that when doing readback glReadPixels and then calling glMapBuffer before the driver has downloaded the data can cause us to block everything. However, casparcg wait's ~2 frames before mapping after calling read... and if we can't read back a frame in the duration of 2 frames then we already have a problem.

The CPU waiting for the GPU is pretty much a universal issue that is hard to get completely away from (they operate asynchronously, after all)—but you don't need to lock it to an integer frames if the producers and consumers are separate, and there's no real reason why a stalling consumer should also stall the producer (it will only compound the issue, as the next frame will get even later), at least as long as there's not a huge frame queue being built up.

Apart from that, there's of course the goal of keeping the GPU as busy as possible—any point where the GPU is waiting on the CPU for the rest of its work is going to mean more delayed frames.

**Comment by ronag** [comment]
> Well, perf does show there's a fair amount of CPU time spent in blocking. I don't know if this counts as issues for your use case or not. For my part, I had to eventually resort to running CasparCG at 4 (!) fps to have CPU left for the rest of the stuff on the system :-)

Sounds more like a driver issue on your system. I've run this code on 7 year old mainstream hardware with no issues even when running several full hd channels.

> It's semantically correct, but it's not performance-optimal by any means. There's absolutely no reason to use the mapping path if you're only memcpy-ing anyway (ie., not saving copies by rendering directly into it); at best, you're just increasing driver overhead by doing more calls.

The difference is minimal.

> Why would you ever want to run glBufferData like this? It sounds like a path a driver would never optimize for, and worse, it requires that you create a new buffer the next time (on the same buffer name). Essentially, if you want to create new buffers for every frame, just do so, instead of going through this complicated dance of trying to associate new buffers with the same names. But better yet, actually reuse the buffers (not just the names), and reuse the mapping, too.

Actually... this was the best practice during the OpenGL 3.0 era... the driver DOES optimize for this. Basically what you are telling the driver is that "I don't care about the previous data, if you can re-use the buffer do it, otherwise if it is still in use allocate a new one".

> The CPU waiting for the GPU is pretty much a universal issue that is hard to get completely away from (they operate asynchronously, after all)—but you don't need to lock it to an integer frames if the producers and consumers are separate, and there's no real reason why a stalling consumer should also stall the producer (it will only compound the issue, as the next frame will get even later), at least as long as there's not a huge frame queue being built up.

If a consumer is stalling there is no reason for the producer to run...

I see your points I just dont think they are relevant in practice...

**Comment by ronag** [comment]
http://www.seas.upenn.edu/~pcozzi/OpenGLInsights/OpenGLInsights-AsynchronousBufferTransfers.pdf

**Comment by ronag** [comment]
@sesse I've done some refactoring of the OpenGL code which incorporates some of your suggestions. See 2.2.0 master.
