### ISSUE TITLE
multi GPU & Nvidia SLI

### ISSUE THREAD

**Issue by captnced** [CasparCG/server#605]
is there any known nvidia configuration that enables the computation over mulitple GPUs ?

- webGl layers rendered on separate GPUs ?
- multiple channels rendered on separate GPUs ?
- one 4k channel split frame ?
- alternate frame rendering ?

for now I've been playing around with various attempts with `nvidia-xconfig --multigpu=<...> --sli=<...>`
but in all configurations I've found only one GPU to be loaded

`nvidia-smi 
Wed May 31 11:44:23 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           Off  | 06BD:00:00.0     Off |                  Off |
| N/A   41C    P8    16W / 150W |      0MiB /  8123MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M60           Off  | F164:00:00.0     Off |                  Off |
| N/A   48C    P0    60W / 150W |    263MiB /  8123MiB |     100%     Default |
+-------------------------------+----------------------+----------------------+
`

additionally SLI seems to be breaking WebGL...

Has anyone tried any multi GPU configuration with success ?
Witch of the strategies has more chances of succeeding ? (In my target configuration I need to render simultaneously 4 separate channels)

thanks !

**Comment by ronag** [comment]
@captnced I don't think CasparCG can take advantage of SLI.
