### ISSUE TITLE
issue with video files with 23.98 frame rate

### ISSUE THREAD

**Issue by skdhruv** [CasparCG/Server#607]
i am facing issue with video files with 23.98 frame rate, the files are not playing in caspagcg server beta 2.1 latest build, but it is showing blackout... files with 24 fps or 25 fps are playing fine

**Comment by skdhruv** [comment]
@didikunz

**Comment by ronag** [comment]
@skdhruv do you have a sample file?

**Comment by ronag** [comment]
Fixed with https://github.com/CasparCG/Server/issues/636#issuecomment-355753697
