### ISSUE TITLE
Thumbnail doesn't generate when media isn't placed on system drive

### ISSUE THREAD

**Issue by A-media** [CasparCG/Server#609]
Every file gets a thumbnail when placed on system root. But when movie files are placed in a folder on an external drive (tested on network and usb) CasparCG doesn't generate a thumbnail. It works on still images and movie files placed directly in directory root. The same goes for both 2.0.7 and 2.1 beta 2.

**Comment by dotarmin** [comment]
If I understand this right, if you have a folder under directory root it works but as soon as you put media files on directory root -> subfolder -> meda files it doesn't work?

Thanks!

**Comment by jesperstarkar** [comment]
This is fixed in one of 2.1 betas, I think. Please check again with the latest beta.

**Comment by dotarmin** [comment]
> This is fixed in one of 2.1 betas, I think. Please check again with the latest beta.

Thanks @jesperstarkar for your quick answer. @A-media is saying that it doesn't work on 2.1 beta 2. It may have worked on 2.1. BETA 1 but got broken in BETA 2...

**Comment by jesperstarkar** [comment]
I just did a clean install of a new system, with casparcg running from c:/ but all media/log/template/thumbnail/etc-paths on d:/

Thumbnails work.

**Comment by dotarmin** [comment]
I will close this issue because it seems to work according to you @jesperstarkar! Thanks for confirming this! :1st_place_medal:
