### ISSUE TITLE
Last video frame not played

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/Server#613]
Casparcg 2.1 beta 2 latest release does not play the last 27 video frames. i am using the default configuration in the download. attached is a simple video file

[COWBELL-017.zip](https://github.com/CasparCG/Server/files/1148238/COWBELL-017.zip)

**Comment by PeterAkakpo** [comment]
is casparcg 2.1 on recession?

**Comment by 5opr4ni** [comment]
nope!

**Comment by PeterAkakpo** [comment]
I asked that because its being a long while since the last update

**Comment by ronag** [comment]
@PeterAkakpo It's getting revived :). We will be working on it more regularly for a while at the least.
