### ISSUE TITLE
Text producer - when big font size is used, some characters are not rendered

### ISSUE THREAD

**Issue by TondaKrist** [CasparCG/server#615]
When font size exceeds 64 then some characters are not rendered.
Specialy when using special language characters as "ČŠŘŽ" etc... they are fine rendered when size of font is small. Font family does not matter, testable even with Arial font.

How to reproduce:
[TEXT] "ěščřžýáíé Vrba Kotrba" 0 0 size 64 color #000000 font Lato-Bold

and then same text with higher size:

[TEXT] "ěščřžýáíé Vrba Kotrba" 0 0 size 84 color #000000 font Lato-Bold

See pictures attached:

![20170718_111812](https://user-images.githubusercontent.com/17853744/28310122-abe2bf70-6bab-11e7-85ef-f6179c2709ce.jpg)
![20170718_111749](https://user-images.githubusercontent.com/17853744/28310123-abea582a-6bab-11e7-8685-03106756cb8d.jpg)

**Comment by Julusian** [comment]
Quite simply a 1024x512 texture cant hold many characters, so they just get thrown away. 
At an amcp font size of 100, that is ~72x72 pixels, so the atlas can only hold 98 characters, and the larger the characters get the fewer that can be stored. 
I'm taking a look at this currently.

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
