### ISSUE TITLE
Scene producer - values are not updated when variable name contains Uppercased letter

### ISSUE THREAD

**Issue by TondaKrist** [CasparCG/server#617]
When defining variable name (id) in scene file, it has to be lowercased, otherwise it is not updated by UPDATE command:

Works: 
`<variable type="string" id="crawltext" public="true">`

Does not work:
`<variable type="string" id="crawlTEXT" public="true">`

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
