### ISSUE TITLE
Recording only one layer

### ISSUE THREAD

**Issue by aleksandar29** [CasparCG/Server#618]
Would it be possible? For example, If I have more inputes which I want to record, I must have more channels. Is it possible to do something like: ADD 1-1 FILE "MY_FILE.mov" ?

**Comment by jesperstarkar** [comment]
It is not possible, you need channels. But you can route layers from one channel to different channels, to achieve something like you suggest.

This should either be marked as a feature request, or closed, as the githbs issues are not meant for general questions.

**Comment by dotarmin** [comment]
This issue will be closed because it's plain question rather than an issue. We can open the issue again if needed or requested as an feature request.

/Armin
