### ISSUE TITLE
JSON Data to HTML Template

### ISSUE THREAD

**Issue by jdzPtv** [CasparCG/Server#621]
As a follow up to https://github.com/CasparCG/Client/issues/138#issuecomment-326544259

It seems dat JSON data send by the Client is not being forwarded to the template. The server log says it's receiving the data, but somehow, it's not being received by the template. So that's why I think it's rather a server issue instead of a client issue.

**Copy/paste of previous post:**

Experiencing the same issue as 7omas. We're currently developing HTML templates and want to use JSON as our data format. 
We're using Client 2.0.8 to send data as JSON to Server 2.0.7 Stable, and the server log says it's receiving the data. However, The data is somehow not being forwarded to the template.

Even without parsing the JSON Data, the template isn't receiving anything, which is not the case when sending XML.

Log:
`Received message from 127.0.0.1: CG 1-20 ADD 1 "P/H0.0 - TestJSON/TEMPLATE" 1 "{\"f0\":\"some data\"}"\r\n`

Code:
```
function parseCasparJSON(str) {
    dataCaspar = JSON.parse(str);
}

function update(str) { 
	parseCasparJSON(str); 
	f0 = dataCaspar['f0'];
	$("#f0").text(f0);
}

```
`Uncaught ReferenceError: str is not defined`

**Comment by dotarmin** [comment]
Hello!

As I replied to your comment on [Client issue #138](https://github.com/CasparCG/Client/issues/138#issuecomment-326544259) this feature requires you to use CasparCG Server 2.1.x. I don't consider this as a bug but rather feature request for the 2.0.7 version of the Server.

Best regards,
Armin

**Comment by dotarmin** [comment]
I will close this issue because it's a feature request for 2.0.7 and something that works in 2.1.0 and that will be released. We can open the issue again if needed or requested as an feature request for 2.0.7.

/Armin

**Comment by jdzPtv** [comment]
Thanks, copy that.

As a follow up to this 'feature request'; with sending XML to flash templates, we're using CSV data regularly, which works well in the client. However, when I try to send the same data to an HTML template, JavaScript returns an error, concerning an illegal character, which is the **newline**. 
Is it possible for the server or client to escape the newline character automatically, because escaping an 30 line CSV sheet manually, is quite cumbersome.
