### ISSUE TITLE
1 frame is lost when playing the next file

### ISSUE THREAD

**Issue by yuriyOsinskiy** [CasparCG/server#624]
When i play several files using command "LOADBG" when previous file is playing (for example LOADBG 1-10 "FILE" AUTO).
I try record this in FCP and try insert on timeline FCP these several files directly.
Record on timeline have a difference between several files on timeline. In record transition between videos lost 1 frame, but not always. And when I play a lot of files i have a big time difference.
I use h264 5Mbps video and try IMX30, but i'm get same situation
PC HW:
Decklink Studio 2
NVidia Quadro K620
Intel Xeon E5 1650 v3
16GB RAM
HDD:
WDC WD5000AZRX-0 for system
TOSHIBA DT01ACA2 for media
System: CasparCG Server 2.0.7, Windows 7 x64
Config server:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<configuration>
  <paths>
    <media-path>D:\media\</media-path>
    <log-path>D:\log\</log-path>
    <data-path>data\</data-path>
    <template-path>D:\templates\</template-path>
    <thumbnails-path>thumbnails\</thumbnails-path>
  </paths>
  <channels>
    <channel>
      <video-mode>PAL</video-mode>
      <straight-alpha-output>true</straight-alpha-output>
      <auto-deinterlace>true</auto-deinterlace>
      <auto-transcode>false</auto-transcode>
      <pipeline-tokens>5</pipeline-tokens>
      <consumers>
        <screen>
          <device>1</device>
        </screen>
        <decklink>
          <device>1</device>
          <keyer>default</keyer>
          <key-only>false</key-only>
          <embedded-audio>true</embedded-audio>
          <latency>default</latency>
          <buffer-depth>3</buffer-depth>
          <custom-allocator>true [true|false]</custom-allocator>
        </decklink>
        <system-audio />
      </consumers>
    </channel>
  </channels>
  <controllers>
    <tcp>
      <port>5250</port>
      <protocol>AMCP</protocol>
    </tcp>
  </controllers>
</configuration>
```

**Comment by ronag** [comment]
Could anyone try to reproduce on 2.2?

**Comment by 5opr4ni** [comment]
Trying to test this but the AUTO plays the clip immediately.

`LOAD 1-10 MELLORECORDED`
`PLAY 1-10`
`LOADBG 1-10 ERIK_TONE_REP MIX 20 AUTO`

**Comment by ronag** [comment]
@5opr4ni you can test with latest gdrive version

**Comment by 5opr4ni** [comment]
Don't work. Now last frame from the clip before the LOADBG AUTO shows. the new clip don't start and no messages in the log.
`LOAD 1-10 MELLORECORDED`
`PLAY 1-10`
`LOADBG 1-10 ERIK_TONE_REP AUTO`
Shows the last frame of MELLORECORDED.

I will go and get a normal CasparCG Server, and try on that one.

**Comment by ronag** [comment]
@5opr4ni still an issue?

**Comment by ronag** [comment]
I believe this is sorted now.
