### ISSUE TITLE
BUG Videos play too fast in PSD producer

### ISSUE THREAD

**Issue by didikunz** [CasparCG/server#625]
It seems, that videoclips added using, for instance: [producer]CG1080i50 play too fast. With this video, the sound plays ok, but the picture is much faster, nearly twice the speed it should have. (2.1.0.3440 f15ba60 Beta 2 x64)

**Comment by dotarmin** [comment]
What Decklink card are you using and what version of driver are you using?

/Armin

**Comment by didikunz** [comment]
Decklink card: Extreme 4K, BMD driver: 10.3.7.0 as of 9.2.2015

**Comment by dotarmin** [comment]
> Decklink card: Extreme 4K, BMD driver: 10.3.7.0 as of 9.2.2015
We had similar issues if I remember correctly using for example Decklink Duo 2 or Quad 2 with a certain version of BMD drivers. But we didn't use the PSD producer on the other hand.

**Comment by didikunz** [comment]
I just found out, that it really must have to do with the Decklink driver, because on the Screen consumer it plays in the correct speed... funny.

**Comment by dotarmin** [comment]
> I just found out, that it really must have to do with the Decklink driver, because on the Screen consumer it plays in the correct speed... funny.

You could try version 10.1.4 of the driver altogether with your 4K Extreme.

**Comment by didikunz** [comment]
>  I just found out, that it really must have to do with the Decklink driver, because on the Screen consumer it plays in the correct speed... funny.
> 
> You could try version 10.1.4 of the driver altogether with your 4K Extreme.
It seems not to be the driver, because first it does it also with NDI and second it does it only in PAL and 1080i50 and not in 720p50 and 1080p50. So it has something to do with interlaceing. The video runs double speed in interlaced systems and normal speed in progressive modes.

**Comment by dotarmin** [comment]
> It seems not to be the driver, because first it does it also with NDI and second it does it only in PAL and 1080i50 and not in 720p50 and 1080p50. So it has something to do with interlaceing. The video runs double speed in interlaced systems and normal speed in progressive modes.

I just asked Helge and he says that BMD probably has fixed this issue related to the drivers and interlaced material. He also says that it *could* be the asset metadata in your file that is incorrect and that in turn could make the framerate_producer to play your file in another speed.

**Comment by didikunz** [comment]
> I just asked Helge and he says that BMD probably has fixed this issue related to the drivers and interlaced material. He also says that it could be the asset metadata in your file that is incorrect and that in turn could make the framerate_producer to play your file in another speed.

The thing is, Caspar plays the file ok, when played with the PLAY command and I tried also with "CG1080i50.mp4" that comes with Caspar. So you can try for yourself...

**Comment by dotarmin** [comment]
> The thing is, Caspar plays the file ok, when played with the PLAY command and I tried also with "CG1080i50.mp4" that comes with Caspar. So you can try for yourself...

Thanks for sending me test files. This bug is verified and another bug in the Scene producer was found thanks to this report. Thanks @didikunz!

/Armin

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
