### ISSUE TITLE
RUN command in AMCP

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#63]
Converted from [SourceForge issue 3567441](http://sourceforge.net/support/tracker.php?aid=3567441), submitted by hummelstrand

If the AMCP protocol could get a RUN command, it would open up for not only Python macros, but also for all types of automation such as BAT files, custom EXEs and more. The idea is that CCG Server would execute the file specified in the file name parameter in any subdirectory specified in the config file (think of it as a manual sandbox so you can't execute just anything.)

**Comment by ronag** [comment]
Not doing this.
