### ISSUE TITLE
Scene/PSD/HTML producer: INFO TEMPLATE does not return anything

### ISSUE THREAD

**Issue by didikunz** [CasparCG/server#630]
The INFO TEMPLATE command returns informations about fields in Flash templates. We should have a compatible functionality in HTML, PSD and Scene. It does not make sense to only support this in Flash, as it gives the posibility for automation systems or MOS enabled systems to inquire information about avaialable fields in themplates. In my opinion the returned XML should be as compatible as possible, so that a parsing of these informations does not need to know in what technology the template has been built. In HTML we could define a variable like the one in Flash: `private const customParameterDescription:XML` In Scene it could be similar and in PSD it could be parsed out of the layer names.

**Comment by premultiply** [comment]
+1
Very important feature for automated workflows and CG clients. No more guessing how the fields may be named. Just read them from the templates itself and show them to the user.

**Comment by dotarmin** [comment]
I agree @didikunz. It should work the same for the Scene/PSD/HTML when running the INFO TEMPLATE as it does with Flash.

**Comment by didikunz** [comment]
For HTML templates it could be a solution to have a XML file with the same name as the (main) HTML file. The XML would contain the same structure as the INFO TEMPLATE returns, Example:
```
<template version="2.0.0" authorName="Nebula Broadcast" authorEmail="info@nebulabroadcast.com" templateInfo="" originalWidth="1920" originalHeight="1080" originalFrameRate="50">
  <components/>
  <keyframes/>
  <instances/>
  <parameters>
    <parameter id="MainText" type="string" info="Main text line"/>
    <parameter id="HeaderText" type="string" info="Header text"/>
    <parameter id="LowerText" type="string" info="Bottom text line bellow the main text"/>
    <parameter id="Info" type="string" info="Info text"/>
    <parameter id="Label" type="string" info="Bottom small text"/>
  </parameters>
</template>
```
And INFO TEMPLATE would simply return that. The advantage to directly reading the contents of the XML File from the client program is, that it transparently works if the server is located on another machine in the net. That could also be the way to go for supporting Scene, PSD or even Flash templates (if we would not want to bring back the code from earlier versions).

**Comment by didikunz** [comment]
The new [GDD](https://github.com/json-schema-org/json-schema-spec/wiki) specification solves this issue.
