### ISSUE TITLE
Scene Producer: Dynamic generated XML

### ISSUE THREAD

**Issue by didikunz** [CasparCG/server#631]
As an alternative of using a XML file in the template-folder we could add a AMCP command, that sends the scene graph xml as a variable to Caspar. That would make it possible to send dynamically generated XML from the client.

**Comment by TondaKrist** [comment]
Our current walkaround is to dynamically create XML and save it to templates folder and then call AMCP command. Work only if you have access to template folder with write priviliges. I think that more powerfull can be some enhancement to dynamically set properties to text producers in scene.

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
