### ISSUE TITLE
Rewrite and update ffmpeg consumer

### ISSUE THREAD

**Issue by ronag** [CasparCG/Server#637]

**Comment by dimitry-ishenko** [comment]
Are you planning to make it respect the timestamps in the stream?

**Comment by ronag** [comment]
@dimitry-ishenko: yep

**Comment by premultiply** [comment]
Please use ffmpeg 3.4 (or higher) as it includes some important quality improvements for broadcast grade applications such as fixed scaling and the updated _bwdif_ deinterlacer as drop-in replacement for _yadif_.

**Comment by calumbrookes** [comment]
@ronag definitely a +1 from me to using FFmpeg 3.4 onwards - would be nice as  FFmpeg 3.4 onwards contains newtek NDI device input support libraries.

**Comment by sirfnomi** [comment]
will this add support for x265 ?

**Comment by dimitry-ishenko** [comment]
@ronag have you been able to make any progress on this? If you need any help with testing and whatever else please holler. :smiley:

**Comment by dotarmin** [comment]
@dimitry-ishenko We will need help with testing out stuff from the 2.1.0 Milestone. It would be really good if you have time to help out with this! 

/Armin

**Comment by ronag** [comment]
I'll keep everyone posted once there is something to start testing.
