### ISSUE TITLE
AMCP heartbeat

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#640]
provide a heartbeat against the AMCP processor without spamming the logs

**Comment by jesperstarkar** [comment]
Will this beat agains all connected clients, or is it a ping that clients can send to the server?

**Comment by ronag** [comment]
from client to server

**Comment by ronag** [comment]
the other way would also be useful both not very

**Comment by premultiply** [comment]
I suggest to introduce a PING command in AMCP which will only be logged in very high log level or never be logged at all:

`PING {[token:int]}`

Where token may be any (random) value choosen by the client. It will just be returned as sent.

Example:
```
>> PING 73487965
<< 201 PING OK
<< 73487965
```

or without token:

```
>> PING
<< 202 PING OK
```

**Comment by jesperstarkar** [comment]
Do we need the token? A client only gets its own responses back, doesn't it? And the REQ/RES protocol gives you the ability to track commands.

**Comment by premultiply** [comment]
Yes, you are right. REQ/RES provides the same function so the simple variant is enough.

**Comment by jesperstarkar** [comment]
I like the idea of the token, though. Don't mind it being added, however, just wanted to remind about REG/RES and the fact that only a single client receives responses.

**Comment by jesperstarkar** [comment]
@ronag I think this can be closed?
