### ISSUE TITLE
Thumbnails/Preview Images for Templates

### ISSUE THREAD

**Issue by premultiply** [CasparCG/server#641]
I am just thinking about a solution/improvement/feature request to provide a preview image for templates with or without field data for remote clients.

Please feel free to comment!

Just my thoughts:

At first a generic solution is required to get a meaningfull still frame from a dynamic template. It is not possible to just grab the first, mid or last frame (like on media files) as this is not adressable and may not contain any usefull content on screen (fade in/out, fields not visible etc.).
So it may be a good idea to define a special preview view while designing the template.
Let's call it "preview frame" for the moment which will never be played out on normal operation but may be called on request for rendering a still image with layout and field data. This needs a special jump-point, entry or function to be called inside a template. Let's call this function "preview".
On current CasparCG implementation it may be called like "CG ADD templatename fielddata", "CG INVOKE preview" followed by "PRINT" and "CLEAR CHANNEL" on an unused empty channel (with no consumer).
As there may be some problems in detail like getting a predictable filename from PRINT command and not writing to the captured image to the media directory it would be better to implement this functionality as a single command providing beautiful preview images from templates on request.

A syntax of such a command may look like this:
`CG PREVIEW STOR [template:string] {[data]}` (Saving the preview image with template filename in thumbnail folder on server)
and 
`CG PREVIEW RETRIEVE [template:string] {[data]}`  (Retrieves the image as a base64 encoded PNG-image over AMCP as temporary "realtime" preview to the client)

The internal tumbnail generator may even run automatically on templates without sending field data. The template then needs to provide some internal default example field data.

Again: Please feel free to comment!

**Comment by jesperstarkar** [comment]
Yes, a PREVIEW function (INVOKE 'preview()' for [html], INVOKE preview for CG-html and CG-flash) would be perfect. You would need a ≈100ms or so delay between the invoke and the capture, to calculate and populate the template.

Just as you know: you get predictable filenames if you use ADD 1 IMAGE 'filename'. ADD IMAGE is actually what happens as you do PRINT.

My opinion is that these commands should not lie under the CG namespace in the protocol, but should  extend the current THUMBNAIL commands with either a 'template/' prefix to the path, or with a template flag parameter.

**Comment by baltedewit** [comment]
There's reasons as to why you should not have default data in your templates. Default data is something we don't want to require from the server.

+1 for extending Thumbnail consumer and preview() functions inside templates.

**Comment by jesperstarkar** [comment]
If you implement a preview function, it would be "default data" that could mess up a normal CG ADD, as it's coded to only work within preview. So:

- preview can and should of course run automatically similar to media thumbnail generation.
- the developer can do whatever he/she wants within preview(), but needs to have a renderable graphic within the image capture delay.
- it will be considered bad practice to have default template data directly in the template, as this should be populated through the preview() command for this usage.

**Comment by premultiply** [comment]
> If you implement a preview function, it would be "default data" that could mess up a normal CG ADD, as it's coded to only work within preview.

Can you please explain that a bit more what you mean?


What I meant is:

For templates we have to distinguish two cases:
- Realtime preview which may never be stored to disk to check for example font rendering, linebreaks etc. from client (with user provided field data) on user request.
- "Normal" thumbnails like they are created for media files (without any field data).
What is meant here by "default data" are example text strings etc. that are defined only in preview() function inside the template which are rendered if nothing else is provided for any data field at all from CasparCG Server.  It would just help to get visual feedback how text is positioned and rendered in each template if browsing through the prerendered templates thumbnails. It is up to the template designer what to define here or even just blank out at this point. This is what is used in case of automatic thumbnail creation.

**Comment by jesperstarkar** [comment]
- Realtime preview doesn't need any protocol changes or nothing, just invoke a custom function or set a flag in your data to identify your desired preview mode. We do this allready. Sure, it would be convenient with a highlevel function, as clients could start to develop preview-compatible clients, and with that have preview as a normal feature of most templates in the future. I'm not against the idea, but it is not super simple to enforce, and we dont _need it_. It is a really good idea, though.

- Yes, fully with you. Brilliant.

**Comment by premultiply** [comment]
> Realtime preview doesn't need any protocol changes or nothing, just invoke a custom function or set a flag in your data to identify your desired preview mode. We do this allready.

Great. Can you provide an example of full AMCP commands to do this with current implementation, please?

Is it already possible to do it without creating a full channel (with all its overhead) and at least write a temporary image file to disk for each request?

The goal would be to implement it with smallest foodprint on system resources as possible.

**Comment by jesperstarkar** [comment]
I don't follow? Do you want to extract files as you run a show? Why not just render it at a separate preview channel with your consumer of choice?

**Comment by premultiply** [comment]
Think of providing a networked preview to many journalists and show operators for preparing and editing rundowns from any office desk or mobile devica via a webtool or MOS newsroom system.
They just browse the availible medias or CG templates and drop them to a shared rundown. A form will allow for editing the data fields provided by each template. To get an impression what the typed text will look like anybody can hit a button to get an updated preview image of the item currently in edit mode, rendered by the CasparCG system in studio which will be used for playout later during the show.
Of course this functionality may enhance the native CasparCG client too, but there could also be a pure web-based graphical rundown editor etc.

The template preview function is the last missing thing for me to start implementing and sharing a fully functional MOS gateway and MOS ActiveX Control for CasparCG.

Yes there may be workarounds with an extra CG channel or even an idependant CasparCG server instance just for preview and an extra custom software layer in between to queue the preview requests from different clients (they occur in parallel) and make the correspondig AMCP requests (with delays) to CasparCG for CLEAR CHANNEL, CG PLAY, CG INVOKE, (wait 100ms), ADD IMAGE, (read image from disk), (delete image from disk)... Yes, possible but not smart and not efficent.
At least an ACMP command to return a screenshot of a channel base64 encoded (like THUMBNAIL RETRIEVE) via AMCP would be really helpfull.

**Comment by jesperstarkar** [comment]
@premultiply Retrieving a PRINT/IMAGE over AMCP as Base64 is one of my biggest wishes. I have had several discussions with @HellGore about this, and he didn't support the idea. But I _really_ see the use and need for such a feature. And: you can allready today send an image _to_ CasparCG over AMCP, so why not retrieve as well?

@ronag @sopr What do you think about being able to take snapshots and getting the feedback back over AMCP as base64?

**Comment by jesperstarkar** [comment]
Ref: https://github.com/CasparCG/Server/issues/474

**Comment by ronag** [comment]
getting it back through AMCP sounds fine... not sure about the base64 part... why not just raw?

**Comment by baltedewit** [comment]
thumbnails are base64, makes sense to keep it consistent, right?

**Comment by jesperstarkar** [comment]
And the similar implementation to send images to an image producer over AMCP is Base64.

**Comment by silid** [comment]
@jesperstarkar I agree that retrieving an image over AMCP would be very useful. This is compounded by the fact that the THUMBNAIL GENERATE command doesn't immediately generate it and there is no way to register for thumbnail updates.

For example if I grab an image (by ADD IMAGE) it is likely I'd want a thumbnail of the grabbed image in my client tool.

@premultiply I've been thinking about how to generate previews lately. I think there are two workflows to consider. 

1. Template thumbnails with generic data.
2. Rendered previews with real data.

Can virtual channels be opened on the fly to render thumbnails correctly?
How can CasparCG know when to grab the preview without a return path?

**Comment by jesperstarkar** [comment]
@silid your 2. point, if I understand correctly, can be done quite easily today with existing AMCP commands. Your templates need an implementation of your wanted preview behaviour though. What else do you want for 2.? Any convenience function you have in mind?

**Comment by silid** [comment]
@jesperstarkar - I agree it can be accomplished, but I think if there was a new PREVIEW command added to the server it should also be considered as part of the workflow.

As far as convenience, it would be really helpful if a template could know what video channel and layer it is running on without being passed as a separate variable. For the purposes of generating previews, the template should be able to notify the server when it is rendered, and will need some way of identifying itself.

**Comment by jesperstarkar** [comment]
What implementation of `PREVIEW` do you see? The only thing I can think of from the top of my head, is a public update() function in the template (and legacy flash template host, probably) - which populates data and renders the preview frame (seeking/freezing).

I think the asynchrony nature of rendering a preview to a still image file can be solved by a stupid (configurable) timeout, no need for callback. Do you?

**Comment by Julusian** [comment]
@silid Making html templates be aware of the layer they are running on is fairly simple. I started playing around with that the other day but didnt finish.

My main concern with any of this would be making sure to not accidentally impact any external server the template may make an ajax request to. Having a preview function in js should be safe enough as long as template devs are aware that a preview render could occur, or #630/#340 could be done and have a meta tag to allow making a preview of the template.

Having a callback should be pretty easy to do, CEF allows for easily exposing native c++ methods to javascript, which we are already doing to allow templates to fully remove themselves, so adding another should be simple enough. of course a timeout would also be a good idea in case the template crashes or takes too long, but in most cases having a callback should be able to speed up generation and make it produce better/more reliable results
https://github.com/CasparCG/Server/blob/a209c3aabc6f0550c2dd2bd5c1321a4ad84debe1/modules/html/html.cpp#L123

Thinking to the scene producer, I think this could be done by a mark of type preview and running the sequence up until that frame, ignoring any stop marks.

**Comment by jesperstarkar** [comment]
> My main concern with any of this would be making sure to not accidentally impact any external server the template may make an ajax request to.

Can you please explain what kind of interference, I'm not getting this at the moment.

> Having a callback should be pretty easy to do, CEF allows for easily exposing native c++ methods to javascript.

Meaning we could have a native AMCP pipe back to the server, natively sending AMCP commands and receiving responses?

**Comment by Julusian** [comment]
> My main concern with any of this would be making sure to not accidentally impact any external server the template may make an ajax request to.
> 
> Can you please explain what kind of interference, I'm not getting this at the moment.

For example in one template I am making a crawler which loads it data over http from a controller. The controller will only serve each segment of text once to avoid the content being repeated between template runs. In this scenario, if caspar decided to render a new preview frame and the ajax request was made, then my controller would serve the preview some text and then not serve it to the real running template next time it requested data.
This is very dependent on the template and whether it is made 'correctly', and it would not affect most templates, but might affect a few. 
Does that help?

> Having a callback should be pretty easy to do, CEF allows for easily exposing native c++ methods to javascript.
> 
> Meaning we could have a native AMCP pipe back to the server, natively sending AMCP commands and receiving responses?

Yes, that will be possible to do. I did have a quick look at it, but didn't spend long as the AMCP command queues are nowhere near the html producer from what I could see.

**Comment by jesperstarkar** [comment]
I think that's up to the template to solve.

**Comment by Julusian** [comment]
I was thinking that at first, but that requires template devs to be aware of the preview function. If it gets well documented along with the rest of the html cg producer methods that need implementing then I guess that could be ok.

**Comment by jesperstarkar** [comment]
As I see it, preview() is just a dumb endpoint within the template, doing nothing by default, completely opt-in. Perhaps it should synchronously return `true` to indicate that it's implemented and supported by the template.

**Comment by Julusian** [comment]
Using the return type of preview wouldn't really help in the following code though, as the request be made before the preview function is run. If we want a supported check it needs to be pre-javascript, which is why I suggested the meta tags.
We cant even rely on preview existing as in order for CEF to know, it has to execute complete contents of the script tag, and so also make the request. This is especially true if the functions are defined inside some code run through webpack, as the webpacked file will need to be evaluated in order for the functions to exist. 
```
<script>

function preview(){
  ...
}

$.post("http://localhost/change-some-state");

</script>
```

**Comment by silid** [comment]
@Julusian It looks as though your update performs on a load prior to any play or preview or other invoke?

Would you not put your state change inside the play function?

Or if the template was aware of the channel it was running on, your template could avoid the state change unless on a primary channel.

**Comment by Julusian** [comment]
Yes, this is intended to run that call on load. The more I try to justify this, the more it feels like a very obscure edge case but it could still happen.
I could (and should) put it in play/update, but again this relies on template developer awareness that bad things may happen if they do not.

My concerns only apply if the template is made without thinking about previews, but that could be a good way to check how to behave.

@silid On a related note, do you think the host calling a javascript function layer(channel, layer) or setting window.CASPAR_CHANNEL and window.CASPAR_LAYER would be better? Consider that the layer and channel can change during the lifetime of the layer, and it may have already loaded before the data is available (I havent checked, but I suspect it could be the case)

**Comment by ronag** [comment]
not in server

**Comment by premultiply** [comment]
where else? needs direct access to the server renderer

**Comment by ronag** [comment]
@premultiply why? flash, html etc... can easily run outside of server...

**Comment by premultiply** [comment]
shure you can run flash and html outside of server in standalone applications but that does not give you the same result and the interfaces as requiered for integrated workflows. And what about psd and scene producer using them all with a common interface?
This topic is not of being able to run something outside of server but to get the same results as running in server.

**Comment by ronag** [comment]
> standalone applications but that does not give you the same result and the interfaces as requiered for integrated workflows.

This is solvable outside of the server. We do it at nxtedition.

> And what about psd and scene producer using them all with a common interface?

A very good point. It's not relevant until 3.0. But yes, that is a problem. I think we can resolve this once producers can run in their own processes. Which then can implement an interface for casparcg playout and one interface for thumbnails, preview etc...
