### ISSUE TITLE
[PSD Producer] Access violation when usage 2+ text layers with same names

### ISSUE THREAD

**Issue by drakmor** [CasparCG/server#642]
Access violation in psd_scene_producer.cpp [bind(var) command ](https://github.com/CasparCG/Server/blob/b2a17fcb83bb2aa5350f89d9d5e3803f6c7fd1a0/modules/psd/psd_scene_producer.cpp#L601)when PSD have 2+ text layers with same names.

**Comment by didikunz** [comment]
It cannot have multiple layers with the same name. So no wonder that there is a problem. But it should be handled gracefully than with an access violation. Is it that what you wanted to say?

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
