### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by leveex** [CasparCG/Server#643]
Sorry, I know that this is not the right place, but maybe someone can help me.
How do I register on casparcg forum?
I have tried from a few email addresses(business and private), but never got the activation email.
It says to contact board administrator, and when I try to do that... says The board administrator contact page has been disabled.
Am I missing something?
Thanks in advance

**Comment by dotarmin** [comment]
First of all I want to apologize that you experience this issue with the forum. 
That's not good at all.

I could help you with this right away, please contact me at armin@instaware.se

/Armin

**Comment by didikunz** [comment]
leveex: I just enabled one of your requests. Please appologize for the inconviniance. The probllem is, that we have masses of new user requests, that turn out to be spammers. So I try to find out, by checking the domain of the e-mail address, if possible, if this guy has something to do with TV or streaming etc. That works very poor for e-mail addresses with a gmail or yahoo domain (or the like), as it could be everything. I then try to figure out based on username maching e-mail address and so it seams that you always was falling trough the net. Sorry for that.

**Comment by dotarmin** [comment]
@didikunz Good work! :+1: 

/Armin

**Comment by didikunz** [comment]
Thanks
