### ISSUE TITLE
Image consumer wrongly calculated alpha values

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#648]
Semi transparent alpha values are wrongly produces in Image consumer. I think this is matter of calculating on premultiplied vs straight values.

**Example file: Text on transparent background. Notice the darkened outline effect in the anti-aliasing area around the text.**
![20171107t174539](https://user-images.githubusercontent.com/6236874/32507386-89a6c16a-c3e7-11e7-9c1f-5177106939cd.png)

**Demo: Compositing this on top of a white solid in Photoshop (or Nuke)**. Upper half of the stage is a PRINT from CasparCG where the same text layer is compsited by MIXER on top of a white solid (inside of CasparCG).
![screen shot 2017-11-07 at 14 44 33](https://user-images.githubusercontent.com/6236874/32507379-863194a6-c3e7-11e7-94d6-e1f8b053f1ab.png)

**Example file: 10% transparent white background (still HTML producer)**
![20171107t181850](https://user-images.githubusercontent.com/6236874/32507685-77d847f0-c3e8-11e7-954f-6afa6819b4f0.png)

**Demo: Same here. The 10% white on top of solid white should become 100% white.**
![screen shot 2017-11-07 at 18 21 15](https://user-images.githubusercontent.com/6236874/32507922-0fa22d26-c3e9-11e7-8b86-2bdfb8879312.png)

I have done the same examples as QTRLE movie clips and checked in similar comps inside of Nuke and After Effects, and the File consumer doesn't have the same problems. Which leads me to think that this is only related to Image consumer, or perhaps only the PNG handling, since @Julusian has noted similar problems in the Image producer as well: #614

**Comment by jesperstarkar** [comment]
I think it only needs to be un-premultiplied before saved.

**Comment by premultiply** [comment]
PNG does not allow premultilplied alpha. It is definded as linear in specification. So PNG decoder or mixer has to premultiply it first if requiered.

**Comment by jesperstarkar** [comment]
I think the problem here is that the MIXER-stage is premultiplied, so it then needs to be un-premultiplied before being saved as PNG.

**Comment by premultiply** [comment]
Yes, sorry, UN-premultiplied in this case.

**Comment by sesse** [comment]
I've had the same problem with the FFmpeg consumer. Premultiplied alpha is great during mixing, but not when storing on surfaces with non-linear gamma or reduced precision (so basically anything that's not 16-bit floating point or better should use postmultiplied). You can tell the mixer to convert back to postmultiplied through ACMP:

MIXER 1 STRAIGHT_ALPHA_OUTPUT 1

It's also possible to set this in casparcg.config.
