### ISSUE TITLE
Virus in dev. build of the newest client?

### ISSUE THREAD

**Issue by didikunz** [CasparCG/Server#651]
Hi
my Kaspersky deleted imediately caspar.dll after unzipping the newest dev. build of the Client.
CasparCG Client 012c50b49a48f4f2bc8dbbde1090ebe9436be814

Object name: HEUR:Trojan.Win32.Generic Object type: Trojan program

same experiences?

(posted by Peter Aellig in the forum)

**Comment by Julusian** [comment]
Forum link: https://casparcg.com/forum/viewtopic.php?f=12&t=4789

**Comment by dotarmin** [comment]
Thanks for reporting!

This is a client thing and should be reported in the CasparCG Client. I will close this and move it to the right one! 

/Armin

**Comment by dotarmin** [comment]
Please see https://github.com/CasparCG/Client/issues/239
