### ISSUE TITLE
OSC Messages

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/server#654]
Hi

In 2.1 the OSC messages for 
`/channel/[0-9]/stage/layer/[0-9]/file/frame`
always produces 0 0

Ref to earlier issues with OSC messages from CasparCG
#266 
#255 
#446 

/olle

**Comment by TKooijmans** [comment]
Hi,
I use this filter
/channel/1/stage/layer/1/file/frame
and this works fine but only with videofiles not with stills
(build V 2.1..0.3440)

**Comment by 5opr4ni** [comment]
Hmmm!

This is my exact filter:
`/channel/1/stage/layer/10/file/frame`
I have tried with different types of videofiles.

I run
2.1.0.3440f15ba60 Beta 2

/olle

**Comment by 5opr4ni** [comment]
Actually no OSC packages containing `/channel/1/stage/layer/10/file/frame` frame is issued from casparcg.

/olle

**Comment by TKooijmans** [comment]
I don't use layer 10 but I will check that....

**Comment by TKooijmans** [comment]
If I use this as filter It returns Cliptimecode when I start a mp4 clip on channel 1-10
"/channel/1/stage/layer/10/file/frame"

**Comment by 5opr4ni** [comment]
Hmm!

/channel/1/stage/layer/10/file/frame should produce frame number not a time. 
The time you get with this path /channel/1/stage/layer/10/file/time.

Strange!!!

/channel/1/stage/layer/10/file/frame
should give:
Seconds elapsed on file playback | Total Seconds

path /channel/1/stage/layer/10/file/time
should give:
Frames elapsed on file playback | Total frames

http://casparcg.com/wiki/CasparCG_OSC_Protocol

Solved it by calculating with the fps
path /channel/1/stage/layer/10/file/fps and the known time path.

/olle

**Comment by TKooijmans** [comment]
Yeah you are right, I use this to get the framecount.

**Comment by baltedewit** [comment]
Did a dump on 2.1 beta 2 osc values recently, this is all I'm getting for an ffmpeg producer:

```
{
       "paused":false,
       "loop":false,
       "type":"file",
       "path":"playback.avi",
       "fps":23.976041793823242,
       "time":20.68731689453125,
       "duration":2869.28076171875,
       "profilerTime":[
           0.0010000000474974513,
           0.019999999552965164
       ]
 }
```

**Comment by romanZay** [comment]
Guys! I have a problem. I'm parsing OSC bundles manually and only one problem is:
after address **/channel/1/stage/layer/5/file/time** I get some bytes: ,hh . According to description of OSC protocol "," is a signal for parser that next characters are data tags (describes the type of followed data). As long as packet size is multiply by 4, space after "hh" is necessary to reach correct packet size. After that goes TWO 4-byte values ("h" - is 4-byte and another "h" is 4-byte follewed). I transcode it to decimal and get some strange values. 1) "current time" don't start from zero. And generally - what means these values? Who can explain how to interpret them?
P.S. Once again - I'm parsing OSC bundles manually
