### ISSUE TITLE
Seek with MXF files shows sometime black and is very slow

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#655]
Hi,
I'm using following code to step through a MXF file
During PLAY mode I send
CALL 1-1 SEEK requestedframecount
During PAUSE Mode I send
LOAD 1-1 CLIPNAME SEEK requestedframecount

If I want to step through the MXF file in PAUSE mode CALL command does not update the output

LOAD with SEEK goes wrong with longer MXF files > 5 minutes if send you this a few times
LOAD 1-1 CLIPNAME SEEK (CurrentFrameCount+250)
results sometimes in a black output and CurrentFrameCount of 0 

I get the CurrentFrameCount with OSC or with INFO command

**Comment by TKooijmans** [comment]
extra info
same commands with a MP4 file works fine

**Comment by Julusian** [comment]
Sounds like an issue that will be fixed by updating ffmpeg https://github.com/CasparCG/Server/issues/636

**Comment by 5opr4ni** [comment]
It would be nice to get different views on this issue. 
How do you get around this when you look for new in-points in video before transmission. :)
Wold appreciate some input.
The most convenient way would off course be to get it to work with call x-x seek xxx in paused video allso. Or?

/olle

**Comment by TKooijmans** [comment]
Hi olle,
what seems to work is while in PAUSE mode is sending twice the command
LOAD 1-1 CLIPNAME SEEK requestedframecount
but sometimes recall of the requested frame takes more then a second.

We use SEEK in a studio player app to do last minute trims or for a quick check of the contents.
It works better in PLAY mode then in PAUSE mode with MXF

**Comment by TKooijmans** [comment]
I like to add, if you set log settings to warning or error only performance with long MXF files is much better.

**Comment by ronag** [comment]
Please test with 2.2 and reopen if still an issue.

**Comment by premultiply** [comment]
Is there a current development build availible for download?

**Comment by ronag** [comment]
@premultiply if you join us on slack yes :) @hummelstrand 

We have a beta candidate that should be made official soon.
