### ISSUE TITLE
Bluefish Supernova CG - Stream selection not working?

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Server#657]
I can't reconfigure the streams on the card. `A` is always paired with `B`, and I can't pair `C` with `D`.

cc @jamesdwise

**Comment by jamesdwise** [comment]
Hi Thanks for the feedback,
I can confirm your bug, and I am currently working on a fix.

If i guess correctly you are trying to do 2 stream of 4224 / Fill and key output?
Until i implement the fix, I suspect this might work for you if you reverse the order in which you initialize the channels. ie, if your doing "a then c" try "c then a", this *might provide a temporary fix until i can upload some code that fully solves the issue.

 - James

**Comment by jesperstarkar** [comment]
My test bench has two Bluefish SuperNova CG cards. Device 1 is 2i/2o, device 2 is QuadOut.

The major problems are 1) and 4).

Different CasparCG configs gives different results:

1. **Device 1, Stream a, Keyer disabled**
Plays FILL on both `#1 SDI a` and  `#1 SDI b`. I don't know why b is active here, I didn't expect that.
Should I be able to disable the b output through BluePropsLight, or is all configuration fed from CasparCG?
![screen shot 2017-11-29 at 11 04 33](https://user-images.githubusercontent.com/6236874/33369526-1d241352-d4f5-11e7-8c4d-8061a0de26e8.png)

2. **Device 1, Stream a, Keyer external**
Plays as expected: FILL on `#1 SDI a` and KEY on `#1 SDI b`
![screen shot 2017-11-29 at 11 03 49](https://user-images.githubusercontent.com/6236874/33369815-017140f2-d4f6-11e7-9491-7534b1f8bc2f.png)

3. **Device 2, Stream a, Keyer external**
Plays as expected: FILL on `#2 SDI a` and KEY on `#2 SDI b`
![screen shot 2017-11-29 at 10 55 13](https://user-images.githubusercontent.com/6236874/33369930-544f3e00-d4f6-11e7-9bb7-6d79a0f038b9.png)

4. **Device 2, Stream c, Keyer external**
Plays only FILL on `#2 SDI c`. Why didn't it activate KEY on `#2 SDI d`? And again, nothing I can do in BluePropsLight to enable this?
![screen shot 2017-11-29 at 10 53 59](https://user-images.githubusercontent.com/6236874/33369988-7866a170-d4f6-11e7-81e8-2384521b64a4.png)

5. **Device 1 or 2, Stream b or even d**
Plays as expected FILL on only the selected SDI.





Haven't tested onboard/internal keyer.

**Comment by jesperstarkar** [comment]
...neither have I tried two streams or two devices at the same time.

**Comment by jamesdwise** [comment]
Hi Jesper,

With regards to your findings..
1.  This is the expected result, the default mapping is for video channel A to go to SDI-A and SDI-B
as soon as you start doing something that requires SDI-B it will be configured accordingly.

2. Good.

3. Good.

4. I believe this is a genuine bug on our behalf. I have now implemented a fix for this specific configuration, and will be making a pull request soon.

5. Good.
