### ISSUE TITLE
INFO SYSTEM: Bluefish streams/decklink sub-devices

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/server#658]
My background for this topic comes from building a GUI configurator for CasparCG, exposing a server's capabilities and letting the user map channels to devices. 
![screen shot 2017-11-29 at 11 32 59](https://user-images.githubusercontent.com/6236874/33370854-15ec93d0-d4f9-11e7-858d-066a20fb3b63.png)
To do so, the client queries CasparCG Server with `INFO SYSTEM` to get a list of devices. We have mapped the name of different Decklink cards to a list of channels, to calculate the available inputs and outputs in the server.

**The problems come with newer cards like Decklink Duo/Quad2, and withBluefish cards that can be reconfigured in firmware and appear in different configurations.**

@jamesdwise from Bluefish proposed and implemented a "stream" entity in the CasparCG config file. A stream is a logical channel on the Bluefish card, which by firmware gets mapped to physical outputs. What we then need to client side parse and gain knowledge of the server's capabilities is knowledge about the streams, not only the devices. @jamesdwise proposed `<device>Blue SuperNova s+ [1] 4 Outputs 0 inputs </device>` or similar string to say something about the device's capabilities. The problem about this syntax is that you need deep knowledge about each device to know that the output streams have different capabilities (Bluefish only allows key/fill pairs on stream A and C, similarly to how Decklink Duo2 works). 

A better way would be to have a structure laying out the streams of a device. The main question is if adding a second level to the Device-tag in the response XML from `INFO SYSTEM` is considered backwards compatible. Clients paring devices and expecting a text node will probably have trouble getting child nodes returned in the XML, so probably breaking change?

I don't have a proposal right now on how we should mark up streams, as they can be di-directional i Decklinks, and they can ble split (a+b or a/b) in Bluefish. Open for discussion.

What we need to take into account:

1.  If the Decklink has paired 1 + 3, then 3 is never available by itself at runtime.
2. Bluefish however can at runtime either pair A + B, or use B standalone.
3. Decklinks with bi-directional SDI can at runtime be used as producers, if not occupied as consumers.
4. Bluefish in- and out-mapping is static and can never change at runtime.

**Comment by jesperstarkar** [comment]
How about just adding a new streams-section next to devices, to keep compability?

**Comment by jamesdwise** [comment]
Can you give an example of what that would look like?

**Comment by jesperstarkar** [comment]
```
<devices>
	 <decklink>
		 <device>DeckLink Duo 2 [1]</device>
		 <device>DeckLink Duo 2 [2]</device>
		 <device>DeckLink Duo 2 [3]</device>
		 <device>DeckLink Duo 2 [4]</device>
	</decklink>
	 <bluefish>
		 <device>Blue SuperNova s+ [5]</device>
		 <device>Blue SuperNova s+ [6]</device>
		 <device>Blue SuperNova s+ [7]</device>
		 <device>Blue SuperNova s+ [8]</device>
	</bluefish>
</devices>
<sub-devices>
	 <decklink>
		 <device id="DeckLink Duo 2 [1]">
            <sub-device index="0" mode="full" />
         </device>
		 <device id="DeckLink Duo 2 [2]">
            <sub-device index="1" mode="half" />
         </device>
		 <device id="DeckLink Duo 2 [3]">
            <!-- I'm unsure if this will be full or null here, being a paired sub-device to 0 -->
            <sub-device index="2" mode="full" />
         </device>
		 <device id="DeckLink Duo 2 [4]">
            <sub-device index="3" mode="half" />
         </device>
	</decklink>
	 <bluefish>
		 <device id="Blue SuperNova s+ [5]"</device>
            <sub-device index="a" mode="full" />
         </device>
		 <device id="Blue SuperNova s+ [6]"</device>
            <sub-device index="b" mode="half" />
         </device>
		 <device id="Blue SuperNova s+ [7]"</device>
            <!-- I'm unsure if this will be full or null here -->
            <sub-device index="c" mode="full" />
         </device>
		 <device id="Blue SuperNova s+ [8]"</device>
            <sub-device index="d" mode="half" />
         </device>
	</bluefish>
</sub-devices>
```

The decklink API doesn't give information about which sub-devices are paired together, this is static information you just need to know (0-3, 1-2). It doesn't mention the SDI connectors either, same story here.

If the Bluefish API has information about connectors and pairing, it would be nice to add.

**Comment by jamesdwise** [comment]
I'm a bit unsure on what you mean by "which sub-devices are paired together",
again i'm unsure on what you mean by mode="full"  or mode="half"?
Is that your way of saying a channel supports fill+key (ie. 4224), or just fill (ie. 422)? 

In terms of what options we can actually offer the best way to explain thing is...

Device ID = Bluefish444 physical card
SDI stream = index of Inputs / Outputs
Type = Input or output
Mode = 422 (fill) / 4224 (fill/key)

Would creating a sub-device category made up of these elements would be the best way to go?
The bluefish API has a default mapping between internal memory channels, and SDI connectors, but in reality this is (almost) entirely flexible. It is actually artificially limited within Caspar in order to minimize the setup complexity.

**Comment by jesperstarkar** [comment]
How about this one James? The only knowledge the programmer needs besides this is that stream 1 is fill and stream 3 is key from the same memory channel.

Do you agree?

```
<devices>
	 <decklink>
		 <device>DeckLink Duo 2 [1]</device>
		 <device>DeckLink Duo 2 [2]</device>
		 <device>DeckLink Duo 2 [3]</device>
		 <device>DeckLink Duo 2 [4]</device>
	</decklink>
	 <bluefish>
		 <device>Blue SuperNova s+ [5]</device>
		 <device>Blue SuperNova s+ [6]</device>
		 <device>Blue SuperNova s+ [7]</device>
		 <device>Blue SuperNova s+ [8]</device>
	</bluefish>
</devices>
<sub-devices>
	 <decklink>
		 <device id="1" name="DeckLink Duo 2 [1]">
            <sub-device index="0" mode="full" />
         </device>
		 <device id="2" name="DeckLink Duo 2 [2]">
            <sub-device index="1" mode="half" />
         </device>
		 <device id="3" name="DeckLink Duo 2 [3]">
            <!-- I'm unsure if this will be full or null here, being a paired sub-device to 0 -->
            <sub-device index="2" mode="full" />
         </device>
		 <device id="4" name="DeckLink Duo 2 [4]">
            <sub-device index="3" mode="half" />
         </device>
	</decklink>
	 <bluefish>
		 <device id="5" name="Blue SuperNova s+ [5]"</device>
            <sub-device index="1" type="output" mode="4224" />
         </device>
		 <device id="6" name="Blue SuperNova s+ [6]"</device>
            <sub-device index="2" type="output" mode="422" />
         </device>
		 <device id="7" name="Blue SuperNova s+ [7]"</device>
            <sub-device index="3" type="output" mode="4224" />
         </device>
	    <device id="8" name="Blue SuperNova s+ [8]"</device>
            <sub-device index="4" type="input" mode="422" />
         </device>
	</bluefish>
</sub-devices>
```

**Comment by jamesdwise** [comment]
Your example still uses a different device ID for each channel on a single bluefish device, this is not how it currently works, and there are no plans to change this.  So I think we need to find a solution that maintains the deviceID = bluefish card, but that also satisfies your needs.

I think it would probably be best to try and keep the values uniform between decklink and bluefish, and settle on either 4224/422 OR full/half, but not both.
Actually I think Fill/FIll+Key  would be the ideal term for this property.
Aslo, rather than use the term index, I would prefer to use the existing term we use for talking the different HW channels, ie. sdi-stream

How about this..?

```
<devices>
	 <decklink>
		 <device>DeckLink Duo 2 [1]</device>
	         <device>DeckLink Duo 2 [2]</device>
		 <device>DeckLink Duo 2 [3]</device>
		 <device>DeckLink Duo 2 [4]</device>
	</decklink>
	 <bluefish>
		 <device>Blue SuperNova s+ [5]</device>
		 <device>Blue SuperNova s+ [6]</device>
		 <device>Blue SuperNova s+ [7]</device>
		 <device>Blue SuperNova s+ [8]</device>
	</bluefish>
</devices>
<sub-devices>
	 <decklink>
		 <device id="1" name="DeckLink Duo 2 [1]">
                       <sub-device sdi-stream="0" mode="Fill+Key" />
         </device>
		 <device id="2" name="DeckLink Duo 2 [2]">
                      <sub-device sdi-stream="1" mode="Fill" />
         </device>
		 <device id="3" name="DeckLink Duo 2 [3]">
            <!-- I'm unsure if this will be full or null here, being a paired sub-device to 0 -->
                      <sub-device sdi-stream="2" mode="Fill+Key" />
         </device>
		 <device id="4" name="DeckLink Duo 2 [4]">
                       <sub-device sdi-stream="3" mode="Fill" />
         </device>
	</decklink>
	 <bluefish>
		 <device id="1" name="Blue SuperNova s+ [5]"</device>
                       <sub-device sdi-stream="1" type="output" mode="Fill+Key" />
         </device>
		 <device id="1" name="Blue SuperNova s+ [6]"</device>
                      <sub-device sdi-stream="2" type="output" mode="Fill" />
         </device>
		 <device id="1" name="Blue SuperNova s+ [7]"</device>
                      <sub-device sdi-stream="3" type="output" mode="Fill+Key" />
         </device>
	        <device id="1" name="Blue SuperNova s+ [8]"</device>
                   <sub-device sdi-stream="4" type="output" mode="Fill" />
         </device>
	</bluefish>
</sub-devices>

```

Alternatively a system with a single 2in 2out bluefish device would look like..
Ii'm not sure what the decklink would look like for 2in 2out though, perhaps they need a term to describe the bi-directional nature of their i/o's.

```
<devices>
	 <bluefish>
		 <device>Blue SuperNova s+ [1]</device>
		 <device>Blue SuperNova s+ [2]</device>
		 <device>Blue SuperNova s+ [3]</device>
		 <device>Blue SuperNova s+ [4]</device>
	</bluefish>
</devices>
<sub-devices>
	 <bluefish>
		 <device id="1" name="Blue SuperNova s+ [1]"</device>
                      <sub-device sdi-stream="1" type="output" mode="Fill+Key" />
         </device>
		 <device id="1" name="Blue SuperNova s+ [2]"</device>
                      <sub-device sdi-stream="2" type="output" mode="Fill" />
         </device>
		 <device id="1" name="Blue SuperNova s+ [3]"</device>
                      <sub-device sdi-stream="1" type="input" mode="Fill" />
         </device>
	        <device id="1" name="Blue SuperNova s+ [4]"</device>
                     <sub-device sdi-stream="2" type="input" mode="Fill" />
         </device>
	</bluefish>
</sub-devices>
```

How about that?

**Comment by jesperstarkar** [comment]
I just need to find out if the Decklink API gives information about the input/output/bi-directional capabilities of a card runtime. It will affect which terms to use for `mode` and also if we should add the type attribute to decklinks.

In my example with devices 1-4 being decklinks, will the first bluefish be device 1 or 5?

**Comment by jamesdwise** [comment]
I'm pretty sure that the first bluefish device would be 1, but i would need to test to be 100% sure.

**Comment by jesperstarkar** [comment]
Yeah, probably makes sense.

**Comment by ronag** [comment]
info deprecated
