### ISSUE TITLE
Add file type to TLS/CLS

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#66]
Converted from [SourceForge issue 3569408](http://sourceforge.net/support/tracker.php?aid=3569408), submitted by sovdjur1

Add the file type of the media-/template file in the returned list of available files. This could be appended to CLS/TLS in some way. Perhaps using a new parameter or similar? The file type is needed in order to be able to select a file in the list and access it directly on the caspar disk, or download it. (Both media and Flash templates need the file type in the returned list)

**Comment by ronag** [comment]
media-scanner
