### ISSUE TITLE
interlace information is not set in recorder files

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#660]
With CasperCG 2.07 I use this code to record an interlaced HD file (upper field HD1080i50 channel)

ADD 1 FILE "FILENAME.mp4" -b 12000k -preset ultrafast   
If you check this file with mediainfo, you can see the proper info and Premiere Pro imports this alright..
![image](https://user-images.githubusercontent.com/4194609/33618055-c839bb0c-d9e1-11e7-8a98-ef21c36e898e.png)

With CasperCG 2.1 v3440 I use this code

ADD 1 FILE "FILENAME.mp4" -pix_fmt yuv420p -vcodec libx264 -preset ultrafast -tune film -crf 20
it shows this with FileInfo, Premiere Pro does not see this as interlaced upper field, it imports as progressive.
How can I set this interlaced upper field option?

![image](https://user-images.githubusercontent.com/4194609/33618179-137605f8-d9e2-11e7-9970-8a52caaab399.png)

**Comment by dimitry-ishenko** [comment]
Shooting in the dark here, but maybe try adding `-flags +ildct` ffmpeg option

**Comment by TKooijmans** [comment]
This does not do the trick, for the record, the file are recorded as interlaced video.
If we manual overrule fieldsettings in Premiere Pro the file is ok.
Only the scan type info is not set correct

**Comment by TKooijmans** [comment]
just adding -x264opts tff=1 does the trick so
ADD 1 FILE "FILENAME.mp4" -pix_fmt yuv420p -vcodec libx264 -preset ultrafast -tune film -crf 20 -x264opts tff=1
Now this works fine for mp4 files but not for recording of MXF files.

**Comment by TKooijmans** [comment]
This is what I use to record 35mbit MXF files (HDcamEX35 PAL)
ADD 1 FILE "FILENAME.MXF" -target xdcamhd422 -vtag xd5c -pix_fmt yuv422p -b 35000k

**Comment by TKooijmans** [comment]
Ok usefull info for others!
ADD 1 FILE "FILENAME.MXF" -b 50000000 -acodec pcm_s24le -vcodec mpeg2video -pix_fmt yuv422p -alternate_scan 1  -g 12 -bf 2 -minrate 50000k -maxrate 50000k -color_primaries bt709 -color_trc 1  -colorspace 1 -f mxf_d10
This creates a 50 Mbit HDCam50 MXF with the right upper field settings

**Comment by TKooijmans** [comment]
I got above info from the CasperCG board, a small correction to this, you have to remove -f mxf_d10.
This belongs to IMX50 format which is SD.

So it should be
ADD 1 FILE "FILENAME.MXF" -b 50000000 -acodec pcm_s24le -vcodec mpeg2video -pix_fmt yuv422p -alternate_scan 1 -g 12 -bf 2 -minrate 50000k -maxrate 50000k -color_primaries bt709 -color_trc 1 -colorspace 1 

This result in this Premiere Pro info
![image](https://user-images.githubusercontent.com/4194609/33658165-063f06c4-da7c-11e7-9b6b-ee648e381413.png)

**Comment by ronag** [comment]
Note to self. Need to verify in 2.2

**Comment by premultiply** [comment]
Interlaced encoding in ffmpeg:
`-flags +ilme+ildct -field_order tt`

**Comment by ronag** [comment]
You need to manually send the flags in 2.2. `-flags:v +ilme+ildct -field_order:v tt`.
