### ISSUE TITLE
Unable to play audio stream when MP3 contains album art

### ISSUE THREAD

**Issue by TondaKrist** [CasparCG/server#663]
`PLAY 1-1 "Audio Mp3 With Album Art"`

Renders album art on output, but no audio is playing.

**Comment by ronag** [comment]
@TondaKrist please provide a sample file

**Comment by TondaKrist** [comment]
[05 Dear Boy.zip](https://github.com/CasparCG/server/files/1728179/05.Dear.Boy.zip)

**Comment by ronag** [comment]
Ok, there is a weird video stream in the file which I am unsure how to handle. It has a long duration but only a single packet.

**Comment by ronag** [comment]
The workaround for now is to do it like this "PLAY 1 "05 Dear Boy" VF NULLSRC

**Comment by TondaKrist** [comment]
[audio.zip](https://github.com/CasparCG/server/files/1728372/audio.zip)
Same things happen for any other MP3 with artworks

**Comment by TondaKrist** [comment]
workaround works only on 2.2, right?

**Comment by ronag** [comment]
@TondaKrist correct

**Comment by TondaKrist** [comment]
@ronag thanks. Are there any Win binaries already to download or do I have to build it by myself?

**Comment by ronag** [comment]
@TondaKrist there is a link on slack, and we should have official binaries soon

**Comment by ronag** [comment]
This is fixed in 2.2 master without the need for any workaround.

**Comment by ronag** [comment]
cd050f8cdd5c896af0c809253a1847fda9577105

**Comment by TondaKrist** [comment]
Great job!
