### ISSUE TITLE
CEF Remote Debugging from other machine

### ISSUE THREAD

**Issue by MauriceVeraart** [CasparCG/server#665]
Hi all
I use the remote debug option quite often. which is great !
On the moment you can only connect to this port from the same machine
how easy/difficult will it be to connect to this port from other machine's ???

**Comment by Julusian** [comment]
A quick google suggests that cef can only bind itself to localhost. It looks like you will need to use a seperate program to expose the port.

Running the following in an administrator command prompt or powershell should do it
```
netsh interface portproxy add v4tov4 listenport=9876 listenaddress=0.0.0.0 connectport=9876 connectaddress=127.0.0.1
netsh advfirewall firewall add rule name="ccg_cef_remote" protocol=TCP dir=in localport=9876 action=allow
```
I think the second line will persist after reboots, not sure about the first

**Comment by MauriceVeraart** [comment]
Thanks Julusian will try this out. 
I was already thinking about a workaround with a SSH portforward.
you are doing almost the same thing in windows ;) here.

**Comment by Julusian** [comment]
I don't think it is worth the effort/cost for us to try and implement something to make this possible.
If this isnt supported by CEF itself, then the solution is to use ssh or some other external tool to do a port forward.
