### ISSUE TITLE
Customizable resolutions and frame rates

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#67]
Converted from [SourceForge issue 3569456](http://sourceforge.net/support/tracker.php?aid=3569456), submitted by hummelstrand

As more and more users are not using CasparCG for broadcast, it would be good to be able to support non-broadcast resolutions and frame rates, such as portrait mode, and have those resolutions be changed via the config file.

**Comment by hummelstrand** [comment]
Cleaning out old issues. This issue is replace by #674.
