### ISSUE TITLE
Feature request: custom channel resolution

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/server#674]
The MIXER should be able to operate on arbitrary channel resolutions and framerates. It would need to be applied a aspect conversion + positioning step from producer to mixer, and similarly from mixer to consumer. 

Imagine running the mixer at natively 5760*1080 mapping 3 regions to 3 different producers for a tiled layout.

**Comment by jesperstarkar** [comment]
Related to #67

**Comment by MauriceVeraart** [comment]
Hi Jesper

I did this several times all ready with a custom build.
it's actually suprisingly simple to do. 

Having a way to do this with the config file or a AMCP command would 
seriously make casparCG a versatile tool for the AV market.

**Comment by jesperstarkar** [comment]
Yes, we have full multiscreen capabilities in our tool-suite already, but it would be good to have native support with convenience methods + bigger canvases

**Comment by Julusian** [comment]
One particular use case is for videowalls or projector blends. Being able
to output these with more predictable synchronisation and lower delay vs
channel routing would be really good.
Also having to composite in a  4k channel for a 2x1 grid of 1080 outputs
isn't great as every layer has to be transformed to fit the used  output
area.

**Comment by Julusian** [comment]
Additionally, at one event I worked, the projects were driven from a Barco E2, which could handle the blend itself. So VT and graphics was done from some macbook pros, with the output resolution set to match the projector size (the E2 can set the EDID on the hdmi to make this easy to do). Being able to match this odd resolution in the screen consumer would be a step towards making caspar a viable alternative for the playback software that was used.

**Comment by Julusian** [comment]
In the [NRK fork](https://github.com/nrkno/tv-automation-casparcg-server) we have prototyped this and shall be testing it out over the next couple of months. 
The intention is to look at merging any changes back here later.
If you are interested please give it a test and let us know of any problems in the nrk repository.

**Comment by MauriceVeraart** [comment]
Hi Julian

Tried this out really nice feature.
one thing though.

i know there is / was a way to position a borderless screen producer.
but i can not find the way off doing that in the config file ?

**Comment by Julusian** [comment]
Hi Maurice

Unfortunately I believe that was a change made for 2.2 so isn't available in the NRK fork (as it is based on 2.1)

**Comment by MauriceVeraart** [comment]
Ah ok

well lets make that a feature request then ;)

**Comment by MauriceVeraart** [comment]
![GRAb](https://user-images.githubusercontent.com/33925862/69233159-b64c4480-0b8c-11ea-8944-b7ff5a2de354.png)

Very nice results so far in combination with "cmdow.exe"

**Comment by Julusian** [comment]
https://github.com/CasparCG/server/pull/1433
The synced output needs some work, but the resolution portion works
