### ISSUE TITLE
Update CEF to 64.0.3282.71

### ISSUE THREAD

**Issue by BossOfGames** [CasparCG/Server#675]
Hey All,

Looking at the GitHub repo, I have found that the CEF plugin is a whopping 3 years old and is basically 30+ versions behind. I am attempting to use the plugin with NodeCG to drive the web based graphics, rather than use Flash since in all reality Flash graphics are on their way out. If and when could we expect an update to this? I might just push the update myself into this repo as a pull request.

**Comment by Julusian** [comment]
We are already working on getting this updated in #611
I am currently leaving it to settle with some community testing and plan to get the maintainer to look at it soon, so hopefully it wont be long before it gets merged
