### ISSUE TITLE
Merging replay producer into main repository

### ISSUE THREAD

**Issue by krzyc** [CasparCG/server#677]
What do you think about merging replay consumer/producer into main repository?
https://github.com/krzyc/CasparCG-Server

It compiles and works fine in Windows and Linux.
It is probably used in production: https://casparcg.com/forum/viewtopic.php?t=1310
Original code was written by Jan Starzak and I have adopted it to 2.1.0 branch adding some improvements. I have already used it on some events and it looks stable.

Of course I will be happy to modify the code according to your suggestions.

**Comment by dimitry-ishenko** [comment]
IMHO it would be awesome and allow some people (myself included) ditch EVS :grinning:

**Comment by drakmor** [comment]
Has anyone tested for compatibility with framerate_producer?

**Comment by vimlesh1975** [comment]
On Jan 17, 2018 9:20 PM, Roman <notifications@github.com> wrote:

Has anyone tested for compatibility with framerate_producer?

**Comment by hummelstrand** [comment]
Seems like framerate_producer is not available in th elatest builds. #676 https://github.com/CasparCG/Server/issues/676#issuecomment-358304514

**Comment by Julusian** [comment]
While it sounds like there is some interest, it doesnt look like much.
And there isnt enough maintainer time as is, so im not keen on merging new complex features that will rely on external maintenance.
