### ISSUE TITLE
TemplateHost: Byteload of ft

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/Server#68]
Converted from [SourceForge issue 3571120](http://sourceforge.net/support/tracker.php?aid=3571120), submitted by sovdjur1

Sandbox violation errors occurs when loading ft files outside of the (Felx/AIR) application folder. This is avoided by loading files the same way as when the TH loads ct-files (using byteArray/SWFLoader).

**Comment by dotarmin** [comment]
@jeansson @Sovdjur1 I will close this issue because it's should not reside in this repository. Please create you issue under the CasparCG/templatehost repository.

Best regards,
Armin
