### ISSUE TITLE
Incompatible boost version on Ubuntu 16.04/17.10

### ISSUE THREAD

**Issue by Julusian** [CasparCG/server#692]
I am attempting to build 2.2.0 on 16.04 using the docker images, but the build looks to have been broken by the change fdcf8c32898bc60524228c3492ef1a3c3a98c51f.

The cause looks to be because Ubuntu 16.04 uses boost 1.58, but the project is relying on a header added in 1.66. Ubuntu 17.10 has the same issue as it uses boost 1.62
```
[ 25%] Building CXX object accelerator/CMakeFiles/accelerator.dir/ogl/image/image_kernel.cpp.o
In file included from /source/accelerator/ogl/image/image_kernel.cpp:31:0:
/source/accelerator/ogl/image/../util/device.h:29:37: fatal error: boost/asio/io_context.hpp: No such file or directory
compilation terminated.
accelerator/CMakeFiles/accelerator.dir/build.make:73: recipe for target 'accelerator/CMakeFiles/accelerator.dir/ogl/image/image_kernel.cpp.o' failed
make[2]: *** [accelerator/CMakeFiles/accelerator.dir/ogl/image/image_kernel.cpp.o] Error 1
```

**Comment by ronag** [comment]
@k0d

**Comment by k0d** [comment]
I'll upgrade to Boost 1.66 for the linux builds. I have to compile it from source, but will link statically so runtime dependencies should all still be available in the distro repositories.

**Comment by ronag** [comment]
http://www.boost.org/doc/libs/1_66_0/more/getting_started/unix-variants.html

**Comment by k0d** [comment]
I've compiled it before inside the Docker image....so it's quite a simple task :)
