### ISSUE TITLE
Brew custom params bug

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/Server#7]
Converted from [SourceForge issue 3544560](http://sourceforge.net/support/tracker.php?aid=3544560), submitted by jesper-s

http://www.casparcg.com/forum/viewtopic.php?f=10&t=811&p=4293#p4293

Replace line 435 from

var documentClassArray = documentClass.split("\n");

to

var documentClassArray = documentClass.split(/\r\n|\r|\n/);

Otherwise custom params wouldn't be recognized.

**Comment by dotarmin** [comment]
@jesperstarkar Can this issue be closed?

**Comment by jesperstarkar** [comment]
I don't think it is resolved. Belongs to TemplateGenerator

**Comment by dotarmin** [comment]
I'm closing this issue and moving it to CasparCG/templategenerator.
Thanks!
