### ISSUE TITLE
Accelerator in 2.2.0 doesn't build 

### ISSUE THREAD

**Issue by pkeuter** [CasparCG/Server#703]
Looking at the other issues, I'm pretty sure @ronag is working hard on this already. But just in case:

The accelerator project in 2.2.0 doesn't seem to build with VS2015. One of the reasons is that `device.cpp` is referencing `asio.hpp` in common and there is only a `asio.h`-file. When I change it, the build still fails.  `dispatch_async` is not found, I think because the accelerator is in another namespace and it should be `caspar::dispatch_async`. And more of the like.

**Comment by krzyc** [comment]
Yes, there are more issues related to OpenGL refactoring and this affects GCC too. @ronag mentioned in another issue that something not ready was pushed - maybe this is related.

**Comment by ronag** [comment]
Sorry, I'm working on resolving this.

**Comment by ronag** [comment]
Should be esolved.
