### ISSUE TITLE
Linux problems on 2.2.0

### ISSUE THREAD

**Issue by krzyc** [CasparCG/Server#705]
1. When using GPU accelerator I get segmentation fault. 2.1.0 branch compiled from source works ok.

2. When using CPU accelerator after 52c7ee26e057c6486c69fafca762eef337d2db7c I get repeating exception message (Throw location unknown (consider using BOOST_THROW_EXCEPTION) Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::out_of_range> > std::exception::what: circular_buffer Caught at (video_channel 1): ./casparcg : caspar::core::video_channel::impl::tick() + 0x868). Before this commit it was working ok.

3. Playing color gives no effect (PLAY 1 "#FF0000").

Kubuntu 17.10. Intel HD Graphics 4000.

**Comment by ronag** [comment]
1. Very much work In progress. Can you do run it with gen?

2,3. Interesting. Will look into it.

**Comment by ronag** [comment]
1 GDB

**Comment by ronag** [comment]
@krzyc what opengl version do you have?

**Comment by krzyc** [comment]
@ronag 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 17.2.4
OpenGL core profile shading language version string: 4.20
OpenGL version string: 3.0 Mesa 17.2.4
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.2.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

**Comment by ronag** [comment]
@krzyc: yea, with the recent opengl update I think 4.5 is required (https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_direct_state_access.txt). I will update the opengl version check to check for 4.5 instead of 4.0.

**Comment by krzyc** [comment]
@ronag It looks that mentioned commands are supported on my driver.
Running in gdb prints:
"0x00007ffff0a7e478 in tcmalloc::CentralFreeList::Populate() () from ./libcef.so"
and backtraces to
"#4  0x00007ffff3832490 in tc_malloc () at ./libcef.so"
I will try to check it on machine supporting OGL 4.5.

CPU renderer now works, playing colors not.

**Comment by krzyc** [comment]
Finally I have compiled CCG in docker on my production machine.
GPU mixer works ok (Quadro 4000, nVidia proprietary driver, OpenGL 4.5)
After copying binaries to laptop (HD 4000) there is still segmentation fault.

Playing colors on GPU works ok, playing colors on CPU do not work - so it is CPU renderer related.

**Comment by ronag** [comment]
@krzyc Can i close this?
