### ISSUE TITLE
Text Producer

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#712]
Port from 2.1.0 to 2.2.0

**Comment by Julusian** [comment]
If you are to resurrect the text producer code from 2.1.0, then I have some useful fixes: https://github.com/Julusian/CasparCG-Server/commit/6e37dd4abe10090529df7dbd0cecd5bd4aff2a20
Fixes #615 #627 and an edge clipping issue

**Comment by 5opr4ni** [comment]
Nice!

**Comment by Julusian** [comment]
I am closing this to clean up the number of stale issues. If someone wants to revive the scene producer, all of the closed tasks can be found at https://github.com/orgs/CasparCG/projects/1/views/1
