### ISSUE TITLE
Decklink Producer only supports 1:1 format

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#714]
decklink producer currently needs to run in same format as channel

**Comment by ronag** [comment]
This should be really easy to fix. Just need to properly configure the FFMPEG filters in the decklink producer.

Someone up for the task?

**Comment by ronag** [comment]
Preferably we should use decklink auto format detection instead of having the input format as an argument.

**Comment by TomKaltz** [comment]
+1

**Comment by premultiply** [comment]
Yes and you have to keep in mind that input format may change during operation.

Older cards do not support auto detect and there are modes that are the same on SDI level like 1080i50 and 1080psf25.
