### ISSUE TITLE
Bluefish Consumer

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#716]
Port from 2.1.0 to 2.2.0

**Comment by ronag** [comment]
@jamesdwise if you make a PR I'm more than happy to re add this.

**Comment by jamesdwise** [comment]
What does the <buffer-depth> property of the decklink consumer do?
Is it just to set the buffer depth, or should it also effect the latency between the computer display and the SDI output?

I'm hoping to make the bluefish consumer as similar as possible.

**Comment by ronag** [comment]
Which property?

**Comment by jamesdwise** [comment]
Oh dear, what an idiot.  the <buffer-depth> property. sorry :(

**Comment by ronag** [comment]
It’s just pre-roll. Decklink is very sensitive to that depending on what settings and drivers you use.

I don’t think you need that option for bluefish.

**Comment by jamesdwise** [comment]
OK thanks, i will not add it to our consumer options.

Another thing I have noticed is that the key channel appears to always be a full white on output.
Eg. when i configure a 4224, fill and Key output, the Key channel is always all white?
Since i am getting a full RGBA buffer from caspar i'm pretty sure that it is actually not giving me the correct data for the key (ie. A part of the RGBA) can anyone confirm that this is working correctly on a decklink consumer?

**Comment by ronag** [comment]
Works for us. What card and config are you using?

**Comment by jamesdwise** [comment]
I've tried a number of different bluefish cards, but inspecting the memory indicates that the alpha channel is all FF.  I am using the CG1080i50.mp4 clip - which i'm pretty sure works with the key data correctly in 2.0.7 and 2.1.0.  

Could you expand on what is required to make ffmeg filter graph maintain the alpha?

**Comment by jamesdwise** [comment]
just to be clear i am doing
load 1-1 cg1080i50 loop
play 1-1

On the Fill output i see the clip playing, but just white on the Key Channel.
The Key output is black prior to loading the clip

**Comment by dotarmin** [comment]
> can anyone confirm that this is working correctly on a decklink consumer?

Hey @jamesdwise 
I have just tried this with same file, CG1080i50 and can confirm it works. I have correct alpha shown. But if you don't have the CG1080i50_A file, then you will see solid white alpha channel.

/Armin

**Comment by Julusian** [comment]
Can this be closed? #935
