### ISSUE TITLE
PSD files for simple templates

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#72]
Converted from [SourceForge issue 3576019](http://sourceforge.net/support/tracker.php?aid=3576019), submitted by hummelstrand

To make it easier to get started, it would be a great idea to be able to read a PSD file and separate the layers so that groups could be animated in the Mixer based on names, plus text layers could be updated.

**Comment by Julusian** [comment]
Duplicate of #707
@dotarmin
