### ISSUE TITLE
Slow Motion Playback

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#73]
Converted from [SourceForge issue 3576065](http://sourceforge.net/support/tracker.php?aid=3576065), submitted by aircooled76

Hi Guys, we are using Caspar as a live sport capture tool using the disk consumer... the ability to play back clips in slow motion would be a massive feature for us.  Replay machines cost $20-50k... Caspar could provide a far cheaper solution for all us Sport DIYers...

FFMPEG seems to support show motion playgack with -speed and setpts=2.0*PTS for example.

**Comment by Julusian** [comment]
duplicate #677
