### ISSUE TITLE
nugetify windows build

### ISSUE THREAD

**Issue by ronag** [CasparCG/Server#730]
Would allow us to remove a lot of dependencies.

**Comment by ronag** [comment]
@Julusian

**Comment by ronag** [comment]
boost, sfml and ffmpeg have up to date packages on nuget. Using those we'd go down to 300 MB instead of 2 GB dependencies.

**Comment by ronag** [comment]
Somebody that would like to have a go at this? @jesperstarkar @sesse @Julusian?

**Comment by ronag** [comment]
Seems to be rather annoying to get working with cmake

**Comment by ronag** [comment]
@k0d does the qt build system support nuget?

**Comment by k0d** [comment]
@ronag I kind of remember seeing something about it once. It most likely can...but really CMake can be made to use it also...it just requires some 'glue'.

My opinion about this whole dependencies thing is....we move everything out we can to package managers, etc etc...then we put what we can't into it's own git repo and use it as a gitsubmodule with the main repo....then we blizt the repo from all traces of those huge files....I'm sure there's some stuff I've missed in the plan though...

**Comment by ronag** [comment]
@Julusian @k0d Done! https://github.com/CasparCG/Server/pull/733

Might have broken Linux build :/. Please check and fix.

**Comment by ronag** [comment]
40 second clone :)

**Comment by Julusian** [comment]
the linux build was likely already broken. I still haven't gotten around to checking it built with my cef changes due to the existing boost version issue
