### ISSUE TITLE
Move the source to one folder...

### ISSUE THREAD

**Issue by k0d** [CasparCG/server#736]
I think it'd make sense to move the source (things that actually get compiled) into its own folder 'src'. This would help a lot with development inside docker by being able to mount the src folder directly.

I suggest these files/folders would move into the source folder.
```
accelerator
CMakeModules
common
core
modules
protocol
shell
CMakeLists.txt
version.h
version.tmpl
```
Any suggestions/comments?

**Comment by ronag** [comment]
I'm fine with it. I'll do it tomorrow.

**Comment by ronag** [comment]
@k0d Could you do it and PR?

**Comment by k0d** [comment]
sure...

**Comment by dotarmin** [comment]
@k0d Good initiative! :)

**Comment by ronag** [comment]
DOne
