### ISSUE TITLE
Client re fetches thumbnail after every Server restart?

### ISSUE THREAD

**Issue by ronag** [CasparCG/Server#737]
@dotarmin I need a client guy to help me here.

**Comment by dotarmin** [comment]
@ronag Yes it does, each time the connection state changes against a Caspar device it does this. Is this just a question or do you need some sort of action?

**Comment by ronag** [comment]
The thumbnail list contains thumbnail size + mtime which should be enough for the client to determine which thumbnails are updated and therefore skip fetching them.

Preferably the client should fetch thumbnails lazily on demand instead of fetching thousands of thumbnails... so I guess this is a client issue?

**Comment by dotarmin** [comment]
> The thumbnail list contains thumbnail size + mtime which should be enough for the client to determine which thumbnails are updated and therefore skip fetching them.

Indeed!

> Preferably the client should fetch thumbnails lazily on demand instead of fetching thousands of thumbnails... so I guess this is a client issue?

I will move create an issue for the client and reference this.
