### ISSUE TITLE
Audio Metering

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#74]
Converted from [SourceForge issue 3576072](http://sourceforge.net/support/tracker.php?aid=3576072), submitted by aircooled76

Am involved in live sports capture and using CasparCG as a capture tool using the disc capture device. It would be really useful if there was a way of monitoring audio levels in the active capture channels while we capture...

Would it be possible to add it into the CGDiag window as a graph line, or some other way of checking we are not peaking our levels?

**Comment by Julusian** [comment]
This can be done now with osc
@dotarmin

**Comment by ronag** [comment]
2.2
