### ISSUE TITLE
Move node service into separate project?

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#742]
@dotarmin What do you think? What should we call it?

**Comment by k0d** [comment]
In my project restructuring PR you can see I put it into it's own folder in the src folder...maybe that's a good solution? I called it media-library....but I'm sure there is a better name.

**Comment by baltedewit** [comment]
I think keeping this seperate from CasparCG is good. It would emphasize the flexibility of casparcg, but also: is it entirely related to the current codebase? It seems a reasonably independent program, so I think it deserves it's own repository.

Beyond that, is it really so great to have this implemented in node or should we aim for better integration? Looking at a future http / websocket protocol to replace AMCP?

**Comment by dotarmin** [comment]
> @baltedewit I think keeping this seperate from CasparCG is good.

I agree, I would be much better to have it separated from the server and let it live in a own repository. It could be included as a sub-module instead. The benefit of doing that would be that it would be simpler for community members to contribute to only the node-service only and would be much easier to review for others.

**Comment by dotarmin** [comment]
> @ronag  What do you think?

Please see my answer above.

> @ronag What should we call it?

Good question! I thought it was well known that naming stuff isn't my strong side! You should ask my wife! 😄

**Comment by dotarmin** [comment]
@ronag Name suggestions:

- CasparCG/content-scanner4server
- CasparCG/node-scanner4server
- CasparCG/media-scanner
- CasparCG/node-media-scanner

@k0d had a suggestion as well: CasparCG/media-library

**Comment by Julusian** [comment]
> The benefit of doing that would be that it would be simpler for community members to contribute

Or potentially fork and add their own custom behaviour. For example to add in a list of video streams or templates they load over http.

**Comment by ronag** [comment]
https://github.com/CasparCG/media-scanner/settings/collaboration

**Comment by ronag** [comment]
> Or potentially fork and add their own custom behaviour. For example to add in a list of video streams or templates they load over http.

Exactly! Though we need to make the url configurable in the server. Currently it's hardcoded to  127.0.0.1:8000
