### ISSUE TITLE
Packaging with node service

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#743]
For windows will need node, ffmpeg and ffprobe distributed with the package. For linux it will need them installed on host?

**Comment by baltedewit** [comment]
Note that Ubuntu 16.04's ffmpeg version is 2.8.11, I'm not sure if that could raise issues with supported codecs / libraries etc. Same story for node, the version from the repositories lags behind the released versions. (although not as majorly as ffmpeg, IIRC)

**Comment by k0d** [comment]
We compile ffmpeg for the linux version of the server, so I guess we can distribute the binaries we build as well. NodeJS, we can either do the same thing, or use the official nodejs apt repo?

**Comment by baltedewit** [comment]
For node, I think leaving the installation as a user responsibility is fine. We could provide links to information for Ubuntu too.

I feel like that would require a versioning of 3.0.0, major/breaking, and not 2.2.0, a feature update.
Or, will the old AMCP commands still be there? Then we could make this entirely optional as well.

**Comment by ronag** [comment]
@baltedewit the AMCP service uses the node service. No breaking change. We just want to move non critical things out of the CasparCG executable to improve stability and flexibility.

**Comment by dotarmin** [comment]
> @baltedewit For node, I think leaving the installation as a user responsibility is fine. We could provide links to information for Ubuntu too.

I think this as well, as long as we have an updated README with instructions on how to do this.

**Comment by Julusian** [comment]
> For node, I think leaving the installation as a user responsibility is fine. We could provide links to information for Ubuntu too.

I agree. I can think of a bunch of cases where I wouldn't bother running this service as I'm either not using local media and templates, or they are hardcoded into the control software
