### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#746]
I did some cleanup but it needs to be properly updated.

**Comment by MauriceVeraart** [comment]
As asked in #862 
how to make scanner.exe to get CLS TLS to work

**Comment by dotarmin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update README for CasparCG Server](https://trello.com/c/oP34t06g/30-update-readme-for-casparcg-server)

**Comment by dotarmin** [comment]
@MauriceVeraart Little late but does scanner.exe work for you?
