### ISSUE TITLE
Fix warnings for "pragma once"

### ISSUE THREAD

**Issue by k0d** [CasparCG/server#749]
"warning: #pragma once in main file"

**Comment by k0d** [comment]
@ronag please assign this to me, I know the fix...just making the issue so it's not lost.

**Comment by Julusian** [comment]
Yeah, the pragmas were all removed by a tidying PR

From what I can tell from some googling, the pragma would have no effect anyway when the precompiled headers are done correctly.

What was the fix you originally had in mind?

**Comment by k0d** [comment]
Great that this was cleaned up. Am a bit confused by this issue now, would need to check it out again but I think my original fix was to change pragma once to ifdef header duplicate protection instead of pragma once. But I can’t be sure.

In my opinion, I think and try to not close other people’s issues. If I think its fixed then I will write ‘Is this issue still relevant?, if not, or if its fixed then please close.’ Letting the original author be involved still. Maybe adding a tag ‘stale?’. Then if the author hasn’t replied within, say 7 days, its probably ok to close.

**Comment by Julusian** [comment]
OK, ifdef guards might be a good idea. Not sure how necessary they will be though

I have generally been adding a closing message, not sure why I didn't here though..
I don't generally like keeping issues open though as it adds a load of clutter but it varies depending on what it is and whether I feel it needs feedback
