### ISSUE TITLE
It would be nice if diagnostic peaks were recorded somehow

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/Server#75]
Converted from [SourceForge issue 3576698](http://sourceforge.net/support/tracker.php?aid=3576698), submitted by hellgore

The current diag window provides useful realtime performance diagnostics, but it would also be good if this information (or the most relevant events) was recorded for later inspection.

**Comment by HellGore** [comment]
Available in https://github.com/CasparCG/Server/commit/ce7d4df26ca9ee3bda33969597dee934867f1c74

**Comment by hummelstrand** [comment]
Excellent, thanks Helge!
