### ISSUE TITLE
version.h not properly generated on build

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#764]

**Comment by Julusian** [comment]
It is generating for me on windows. Both as part of cmake and whenever I build

**Comment by ronag** [comment]
Not for me...

**Comment by ronag** [comment]
How/What generates it?

**Comment by k0d** [comment]
It should generate ok on windows, it's part of the CMake script. It won't generate on Linux yet properly as it needs access to the .git folder to get the commit hash.

https://github.com/CasparCG/server/blob/2.2.0/src/CMakeModules/Bootstrap_Windows.cmake#L15 I guess the paths are wrong now?

**Comment by Julusian** [comment]
Im thinking this is related to #766. The build docs indicate to generate cmake to a different path outside of /src, but if you dont then there are some issues. This could be the opposite case

**Comment by ronag** [comment]
Ah, @k0d could you please fix?

**Comment by Julusian** [comment]
When I do a build all in vs, the output log starts with this if I have changed version.tmpl. I guess it may not do it if all that has changed is the git hash though
```
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
1>CMake is re-running because C:/Code/CasparCG22/src/CMakeFiles/generate.stamp is out-of-date.
1>  the file 'C:/Code/CasparCG22/src/version.tmpl'
1>  is newer than 'C:/Code/CasparCG22/src/CMakeFiles/generate.stamp.depend'
1>  result='-1'
```

**Comment by k0d** [comment]
There's some things I need to update for this (variables in version.tmpl) ...if I don't do it before, I'll fix it on Monday.

**Comment by k0d** [comment]
Writing this here for my reference...you can ignore.
```
#define CASPAR_GEN ${CONFIG_VERSION_MAJOR}
#define CASPAR_MAYOR ${CONFIG_VERSION_MINOR}
#define CASPAR_MINOR ${CONFIG_VERSION_BUG}
#define CASPAR_TAG "${CONFIG_VERSION_TAG}"
#define CASPAR_REV ${GIT_REV}
#define CASPAR_HASH "${GIT_HASH}"
```

**Comment by k0d** [comment]
Have made a fix and committed, should be tested on windows still.

When running inside of docker, it won't get the GIT hash...as that's not available.
We should add some code in the Dockerfile to do that I guess? any comments?
