### ISSUE TITLE
Fresh 2.2.0 build fails during "copy dependencies"

### ISSUE THREAD

**Issue by wlcx** [CasparCG/server#766]
I followed the instructions in building.md, and the build fails in "copy dependencies" due to not being able to find packages and boost headers. Apologies if I am doing something stupid!

Also, regarding the instruction
> Open ./src/CasparCG Server.sln
for me this file ends up in the project root, not `src`. 

OS: Windows 10 Ent
Git: 2.16.1
VS: Community 2017

Full build log:
https://gist.github.com/anonymous/13497e39b944601aa0a27c7419c0bd6d

**Comment by ronag** [comment]
did nuget properly restore packages? What do you have in "C:/Users/bob/server/src/packages/FFmpeg.Nightly.20180130.1.0/build/native/bin/x64"?

**Comment by wlcx** [comment]
I did try nuget but wasn't sure if I was doing it right.
`Right Click>Restore NuGet Packages` on the root solution in solutions explorer results in 
`All packages are already installed and there is nothing to restore.` I note that nuget doesn't seem to actually see any dependencies via `Manage Dependencies`...

Here is the contents of my packages folder
![image](https://user-images.githubusercontent.com/3065381/35988311-0012b42e-0cf6-11e8-9885-54966ea3cef1.png)


I am not familiar with VS and NuGet, is there an additional step I need to take first?

**Comment by ronag** [comment]
That should have worked. I will look into it when I get the time.

**Comment by wlcx** [comment]
Thanks, glad it's not just me! Is it worth having the nuget step in `building.md` too?

**Comment by ronag** [comment]
visual studio should do it automatically when building the solution.

**Comment by ronag** [comment]
@wlcx if you want alpha builds join us in the slack channel. We're testing and discussing there.

**Comment by wlcx** [comment]
Would love to - though can't find any links to join?

On 8 Feb 2018 18:03, "Robert Nagy" <notifications@github.com> wrote:

@wlcx <https://github.com/wlcx> if you want alpha builds join us in the
slack channel. We're testing and discussing there.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/CasparCG/server/issues/766#issuecomment-364197132>, or mute
the thread

**Comment by ronag** [comment]
@hummelstrand

**Comment by dotarmin** [comment]
@wlcx Have you access by now? If not, let me know and I can help you.

**Comment by wlcx** [comment]
@dotarmin I don't yet no! Email's on my profile if that helps :)

**Comment by dotarmin** [comment]
@wlcx You should received an invitation in your inbox :)

/Armin

**Comment by Julusian** [comment]
@ronag Im currently playing around with this. Seems to be that packages.config needs to sit next to the vs project files, which it doesnt currently. 
Im guessing you are generating cmake into the src folder? That would explain why it works for you

**Comment by ronag** [comment]
> Im guessing you are generating cmake into the src folder? 

Yes, I think that is also how it's documented in BUILDING.md?

**Comment by Julusian** [comment]
Following BUILDING.md causes the solution files to be put in the root of the repo not in /src

Which is what has happened to @wlcx:
> Open ./src/CasparCG Server.sln
> for me this file ends up in the project root, not src.

**Comment by Julusian** [comment]
Do we want to do it this way? I am getting git tell me about a lot of untracked files now. I can add them to gitignore and raise a PR if we do, or we could generate cmake into a /build dir but that will add some complexity to the cmake files to handle the packages.config files and resulting path differences

**Comment by ronag** [comment]
@Julusian I don't have much of an opinion other than it should be as clean as possible. What do you think?

**Comment by ronag** [comment]
Visual Studio has direct support for cmake, i.e. you can open a CMakeLists instead of a solution file. However, I haven't gotten that to work properly... but that would be the cleanest.

**Comment by Julusian** [comment]
I think it would be nicer into a seperate directory. It does make the script a bit more fiddly, but it shouldnt be too bad, and might make packages.config more error prone to update, but it makes it less likely that some stray binary/cmake result will be committed. Ill give it a try and we can see how it looks

> Visual Studio has direct support for cmake

That would be nice to use, I tried it and got an error with accelerator not finding Stdafx.h and havent looked further yet

**Comment by k0d** [comment]
As I don't do much with the Windows build at the moment, I'm not really sure what this issue is. Is there something that doesn't work correctly now...could someone explain it a bit more please?

**Comment by ronag** [comment]
@Julusian so the real fix here is to update the README.md correct? Your PR is a separate thing I believe.

**Comment by Julusian** [comment]
Yes, changing the instructions to run cmake from inside /src would solve it

**Comment by wlcx** [comment]
Ah, I hadn't appreciated it was that simple a fix. Sorry!
