### ISSUE TITLE
STREAM command from client not working

### ISSUE THREAD

**Issue by malmgrenola** [CasparCG/server#768]
"Connect to" in client is not working.
ADD 1 STREAM seems broken.

**Comment by ronag** [comment]
Pending client update.

**Comment by TKooijmans** [comment]
I checked this with the latest build and it is still broken.
The stream starts and can be monitored but it only shows black.
Also tested ADD 1-1 STREAM

**Comment by dotarmin** [comment]
> @ronag Pending client update.

This works in CasparCG Client 2.0.9 with CasparCG Server 2.2.0.

**Comment by dotarmin** [comment]
> @TKooijmans (It runs with black input)

Server or Client?

**Comment by TKooijmans** [comment]
The server can start a RTMP stream, but that results in a black stream.
This happens also when you give the add stream command (custom) from 2.09 client.
Above command works fine with Server 2.1 but not with Server 2.2,
So to test this please add a rtmp stream...
