### ISSUE TITLE
LEVELS should not affect alpha channel

### ISSUE THREAD

**Issue by hummelstrand** [CasparCG/server#771]
Make LEVELS only affect RGB but not A. Currently the LEVELS command is useless. #82

**Comment by 5opr4ni** [comment]
I actually can't se that it does. Have tried both 2.1 and 2.2. The Levels has no effect on the alpha neither in a composition on the channel or out from Decklink.

Can someone else verify this, or Hummlan, kan du testa igen.

**Comment by hummelstrand** [comment]
Ah, this may be a bug that has been fixed and I've missed that in the
commits. I'll actually test this time! :)
-- 
     Jonas Hummelstrand
     <http://SuperFly.tv>
     +46-733-970000
