### ISSUE TITLE
What is the master clock on channel?

### ISSUE THREAD

**Issue by premultiply** [CasparCG/server#772]
I was not able to find any documentation how timing and genlock is implemented in CasparCG server.
So I think some clarification about the implemented concept is needed. At the end I could try to create a documentation part on this topic.

What is the master clock source on each channel?
How is the gelock input on decklink output boards handled by CasparCG?
What happens if multiple non-synchronized live outputs are fed from a channel?
What happens if using channel/layer rerouting to other (asynchronous) channels?
Is any live input (Decklink input, FFMPEG live input) frame synchronized / resampled to channel clock?

Who could help me with this questions?

**Comment by ronag** [comment]
This needs additional work and is not implemented very well at the moment. But it is good enough for most use cases:

> What is the master clock source on each channel?

Slowest consumer which is considered synchronized (bluefish, decklink) or a high precision system clock.

> How is the gelock input on decklink output boards handled by CasparCG?

It's synced against it.

> What happens if multiple non-synchronized live outputs are fed from a channel?

Uses system clock. Oal consumer automatically compensates audio drift. Screen consumer drops/dups frames.

> What happens if using channel/layer rerouting to other (asynchronous) channels?

Drop/Dup :(. We might have time to add audio drift compensation to 2.2.0.

> Is any live input (Decklink input, FFMPEG live input) frame synchronized / resampled to channel clock?

Nope.
