### ISSUE TITLE
Strange behaviour when using BlendModes

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/server#781]
Strange behaviour when using BlendModes

PLAY 1-10 "ERIK_TONE_REP" CUT 0 Linear RIGHT
PLAY 1-14 [HTML] "http://svt.se" CUT 0 Linear RIGHT
MIXER 1-14 FILL 0.655208 0.551852 0.241146 0.344444 0 Linear
MIXER 1-14 BLEND Lighten

This makes the composition to fail and go bananas. No errors in the console, just crazy picture.
Even after:
MIXER 1-14 BLEND Lighten

Restart of Caspar required after this.

**Comment by ronag** [comment]
What gpu?

**Comment by ronag** [comment]
Did blend modes work in 2.0 on the same setup?

**Comment by 5opr4ni** [comment]
![screen shot 2018-02-09 at 22 11 24](https://user-images.githubusercontent.com/20354852/36050294-40de67fa-0de6-11e8-95eb-b4d7ced89fe5.png)

**Comment by ronag** [comment]
I'm suspecting a missing opengl extension and since we removed the opengl check it segfaults. I will try it on an nvidia card on monday.

**Comment by 5opr4ni** [comment]
No you are right Robert, it actually don't. Know that there was an issue with that when you mention it.
We had to use an earlier version of 2.1, before the beta 1.

Hmmmm!

**Comment by ronag** [comment]
Closing in favor of #782
