### ISSUE TITLE
Mix transition blend issue

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/server#783]
When performing an regular mix transition it seams as the first/s and last frames of the mix, in this case, ore omitted.
This differs from 2.1 where they have a predicted behaviour.

Have also seen, a couple of times, frames from another transition in the current one. As if there was a buffer that was not clean. Cant reproduce it, but it was after testing LOADBG and AUTO.

`PLAY 1-10 MELLORECORDED MIX 20`

**Comment by ronag** [comment]
Could I ask for a deeper investigation of what exactly is going on here? i.e. interlaced videos with field counters?

**Comment by 5opr4ni** [comment]
Actually, iv'e done that today. You will have it in a couple of minutes.

**Comment by ronag** [comment]
Please verify if this is an issue on nvidia as well.
