### ISSUE TITLE
SEEK and LENGTH

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/server#785]
Issue with SEEK and LENGTH for LOADBG, LOAD and PLAY

`PLAY 1-10 ERIK_TONE_REP`
`LOADBG 1-10 "ERIK_TONE_REP" SEEK 200 LENGTH 400`
_In 2.1:_
![screen shot 2018-02-10 at 13 56 48](https://user-images.githubusercontent.com/20354852/36062319-7e0394a0-0e6a-11e8-8744-d28d9340dd22.png)
`PLAY 1-10` And the video respects the seek and the length.

**And the same thing in 2.2:**
`PLAY 1-10 ERIK_TONE_REP`
`LOADBG 1-10 "ERIK_TONE_REP" SEEK 200 LENGTH 400`
![screen shot 2018-02-10 at 14 00 06](https://user-images.githubusercontent.com/20354852/36062337-bf5fe2fa-0e6a-11e8-8e0a-07dbf45504d2.png)
`PLAY 1-10` Nothing happens, and the diag is trying something. Se the bottom of the Diagwindow.

**Comment by ronag** [comment]
Fixed in https://github.com/CasparCG/server/pull/787
