### ISSUE TITLE
Trace stack trace for TH errors

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/Server#8]
Converted from [SourceForge issue 3544562](http://sourceforge.net/support/tracker.php?aid=3544562), submitted by ronag

Trace to stack trace for template host errors out to CasparCG. This helps debugging errors such as #1009.

**Comment by jesperstarkar** [comment]
This should be close.

Developers can override TemplateHost or use Scout during development. No need for stack traces in production.
