### ISSUE TITLE
FFmpeg consumer fails

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/server#801]
Trying to record with ffmpeg consumer, but fails.

`ADD 1 FILE -codec:v libx264 asd.mp4`

![screen shot 2018-02-13 at 17 26 58](https://user-images.githubusercontent.com/20354852/36161127-3109a614-10e3-11e8-8b82-182c18862e62.png)

**Comment by ronag** [comment]
```ADD 1 FILE asd.mp4 -codec:v libx264```

output first

**Comment by ronag** [comment]
should handle failure better though

**Comment by 5opr4ni** [comment]
Hm! This makes the server to choke.
`ADD 1 FILE asd.mp4 -codec:v libx264`

![screen shot 2018-02-13 at 17 34 12](https://user-images.githubusercontent.com/20354852/36161569-5094b41e-10e4-11e8-99c1-9215d1073ee9.png)

**Comment by ronag** [comment]
@5opr4ni too heavy for you computer :) try -profile:v veryfast

**Comment by 5opr4ni** [comment]
tried several but all fails in one or other way.
latest one
`ADD 1 FILE "asd.mp4" codec:v libx264 -profile:v ultrafast`
do I need the audio codecs after the ffmpeg refactoring?

**Comment by ronag** [comment]
I'll have to teamviewer into your computer. Doing just "ADD 1 FILE asd.mp4" works fine on my computer.

**Comment by ronag** [comment]
ah sorry! it should be `preset:v veryfast`

**Comment by 5opr4ni** [comment]
OK! It's me not Caspar.
This works:
`ADD 1 FILE olle.mp4 -preset:v veryfast`
`REMOVE 1 FILE olle.mp4`
