### ISSUE TITLE
Unable to play twitch.tv stream

### ISSUE THREAD

**Issue by KeloCube** [CasparCG/server#820]
As discussed in #622, streams from twitch.tv don't work, even though they play fine with ffplay.

One frame might be loaded but the stream doesn't play.

URL for testing from https://www.twitch.tv/cosmos:
https://video-weaver.arn03.hls.ttvnw.net/v1/playlist/CvUCecZW-b2fnk-ww7BqvO3ac7tcwCOzIv83GoTHcACgYAz-DP8_qwZAvGV_MOmnCp7VpIoXByhlT3OAwrYVjteV1G4oWsyeLjblTZgQSqlpv-lnIPGehORKTAOsm_lzManczinGBHfaHtRbAWbHejkptQnz1DsBmdwYl-pbB661Cuxx2fkqpMT-Mb2SV7WR1TPppnQGxCctpmfBZR_mjYw9PAMitEfG-52sW3UMsN2r_-VFGmQpheO19H61jDzPeBDTPEwjXf_IH3tG_35lgLT-bc3NT7mGaStg7cgD3Fq0QJo-8cswMcsi1vzHhOfE_kkGAkx-xpiaIa-qTMMlp63fVNOWLKshlY-ABxT2rjSyDd4xv_EVk2MEZaqNPlW-aH4QO0ZwTmWnj8dzVsGpJOa_N9OAnuoB9yxKyu7xQekmclggQnusBWT7CqplEW73IiIQSOQsdQEsv7a7q0Pa2LUH269AhW9HXhhJ0OXklfhqZgCccGBzRxIQMcVD8Smq_oiPQDdcVHQ8BRoMEkWRpNTdurxU-njm.m3u8

Make sure that the stream is still live and the url works by playing the stream in ffplay before testing in CasparCG. If not, you can get another url by opening up the developer tools in Chrome on a page with a twitch stream, and looking for documents of type `vnd.apple.mpegurl` on the network panel. Any such url should be able to initiate stream playback even if it's not the latest one.

**Comment by ronag** [comment]
CasparCG automatically adds a async filter to all audio streams to sync up the audio. I believe this stream doesn't have timestamps on audio which is why it fails. ffplay has custom handling for this scenario.

Might be worth looking into.

**Comment by premultiply** [comment]
From https://ffmpeg.org/ffmpeg.html:

-async samples_per_second
[...]

**This option has been deprecated. Use the _aresample_ audio filter instead.**

**Comment by ronag** [comment]
@premultiply yep, that's what we do, but we add it automatically

**Comment by premultiply** [comment]
My hint was just that the async option is labeled as deprecated in favor of aresample filter in ffmpeg documentation.

**Comment by ronag** [comment]
This is fixed in master. Thanks @premultiply !
