### ISSUE TITLE
Windows Build - Shell.rc error from zip

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#828]
Building on windows with the current 2.2.0 source gives an error because "shell.rc" includes "version.h" which is always not in the right place. "version.h" is suppose to be in the shell folder but its not there. copying the "version.h" into the shell folder gives a successful build

**Comment by ronag** [comment]
Did you follow the instruction in BUILDING.md exactly? Because depending on where and how you run cmake you can get this issue. @Julusian

**Comment by PeterAkakpo** [comment]
I have realize that anytime i clone the repo (which is larger), build is successful. This issue occurs anytime i download the ZIP file (which is about 6MB). Is there any difference (in terms of code)  between cloning the repo and downloading the ZIP file?

**Comment by ronag** [comment]
@PeterAkakpo I don't know. How exactly do you download?

**Comment by PeterAkakpo** [comment]
![cg](https://user-images.githubusercontent.com/7926382/36265655-98441a14-1267-11e8-9c60-ab52a20f5229.png)

**Comment by Julusian** [comment]
When you download the zip file, you won't be getting any of the files which are stored in LFS. So it looks as though cmake failed to run fully because those files were still the LFS pointers instead of full files.

I expect that downloading as a zip should be fine after #734, or when building for linux

**Comment by PeterAkakpo** [comment]
Just "version.h"

**Comment by ronag** [comment]
@PeterAkakpo "version.h" should be auto generated from "version.tmpl".

**Comment by Julusian** [comment]
> We could remove LFS at this point I believe.

Everything still in /src/packages is still in LFS. <25mb according to the tree I am currently in.

**Comment by ronag** [comment]
@Julusian I'm fine with converting to regular git. What do you think?

**Comment by PeterAkakpo** [comment]
yes version.h is generated into a folder called "generated" instead of the "shell" folder.

**Comment by ronag** [comment]
that doesn't sound LFS related

**Comment by ronag** [comment]
@PeterAkakpo could you try with the zip again?

**Comment by PeterAkakpo** [comment]
Ok, let me do that now

**Comment by ronag** [comment]
ah! the problem is that version.h cannot be generated since the version is read from git.

**Comment by ronag** [comment]
@PeterAkakpo I don't know how to fix this properly. I think we're leaving it as is for now. Until someone finds a solution...

**Comment by PeterAkakpo** [comment]
ok this is my result. i just downloaded the zip and noticed that the size has increased by about 3M. 
verson.h is still being generated into the "generated" folder. this is the content of the version.h generated.

#define CASPAR_GEN 2
#define CASPAR_MAYOR 2
#define CASPAR_MINOR 0
#define CASPAR_TAG "Beta 1"
#define CASPAR_REV fatal: Not a git repository (or any of the parent directories): .git
#define CASPAR_HASH "fatal: Not a git repository (or any of the parent directories): .git"

when i copy this version.h into the shell folder and i try to build , i get  "unknown key fatal". i guess this error came about because the content of the version.h is not right. 

so i replaced the version.h in the shell folder with the one from the cloned repo source generated. this is the content

#define CASPAR_GEN 2
#define CASPAR_MAYOR 2
#define CASPAR_MINOR 0
#define CASPAR_TAG "Beta 1"
#define CASPAR_REV 3143
#define CASPAR_HASH "3ed9f8b2c"

and the build was successful.

**Comment by PeterAkakpo** [comment]
i think one solution is to just add the version.h file into the shell folder as part of the download, so that its not generated by cmake. 

it is in the shell folder because shell.rc references it from there.

**Comment by Julusian** [comment]
@PeterAkakpo I have just had a chance to properly play with this, and have solved the issue with the contents of version.h, but the location of the file is not an issue. It is being placed into the folder "generated" and shell.rc is correctly fidning it in there. cmake is setting that folder as a include directory, so if cmake ran correctly it will be found.
