### ISSUE TITLE
Make a Beta Release

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#834]

**Comment by dotarmin** [comment]
@ronag An announcement at CasparCG forum has been done and I think we now have a CasparCG 2.2.0 Beta released for the community. 

Should we do a release here at GitHub as well?

**Comment by ronag** [comment]
please make a github release as well, I personally see the forum as more of community thing

**Comment by dotarmin** [comment]
I'll do that! Is it enough for you just to tag current rev. or should I make a branch? What do you prefer?

**Comment by dotarmin** [comment]
Done.
