### ISSUE TITLE
Color producer output not always correct when passing alpha value

### ISSUE THREAD

**Issue by pkeuter** [CasparCG/server#837]
`PLAY 1-1 #00000000` -> full transparancy -> good
`PLAY 1-1 #000000` -> full black -> good
`PLAY 1-1 #000000FF` -> blue -> incorrect (should be black)
`PLAY 1-1 #FFFFFFFF` -> yellow -> incorrect (should be white)

**Comment by pkeuter** [comment]
After studying the code, I see this is my fault, the order is ARGB. Seems strange to me, but ok.

**Comment by ronag** [comment]
Yea, that is weird. Not sure why it was done like that.
