### ISSUE TITLE
Fix separated alpha sample files and document limitations

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#845]
The current implementation is broken in many scenarios, e.g. looping etc.... Is it still worth to keep it?

**Comment by 5opr4ni** [comment]
?

**Comment by 5opr4ni** [comment]
Sorry! Ment to ?

**Comment by ronag** [comment]
We have the "_A" playback functionality. It will currently only work if the video files are exactly right, e.g. the CG1080i50 files included in the caspar packaging will not work with loop since the alpha has a shorter duration.

**Comment by 5opr4ni** [comment]
Then we have to change, so that those files are correct.

**Comment by 5opr4ni** [comment]
Say when you want me to take it for a test spin
