### ISSUE TITLE
HTML CG INVOKE ERROR

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#848]
running this command works
CG 1-1 INVOKE 0 showCaption('BREAKINGNEWS', 'WHATADAY')

the following command throws an error (**uncaught syntax error: missing ) after argument list**)

CG 1-1 INVOKE 0 showCaption('BREAKING NEWS', 'WHAT A DAY')
the error occurs when there is/are white spaces in the arguments.

**Comment by ronag** [comment]
I think you need to wrap the argument in quotes:

CG 1-1 INVOKE 0 "showCaption('BREAKING NEWS', 'WHAT A DAY')"

**Comment by PeterAkakpo** [comment]
thanks Rob, that worked
