### ISSUE TITLE
Parse colon in filenames to enable protocols to be used

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/server#85]
Converted from [SourceForge issue 3608385](http://sourceforge.net/support/tracker.php?aid=3608385), submitted by paulgregoryuk

This is a shortened solution to a problem, omitting a DATA idea, in the hope that it can be implemented sooner. 

The longer version is here:
https://github.com/CasparCG/CasparCG.Server/issues/77

Currently, if a command is sent like:
ADD 1 FILE rtmp://LOCALHOST/LIVE/

the filename will be end up being treated as "C:/CASPARCG/MEDIAFOLDER/RTMP://LOCALHOST/LIVE"
because it is always prefixed with the media folder, and treated as uppercase.

This requires workarounds in order to stream out, which in turn make it difficult to load anything from the media folder.

My shortened proposal basically is:
If a filename contains a colon, do not prefix it with the media folder. Instead, lowercase anything before the colon.

This should only require fairly simple string manipulation and a conditional. (Sadly I'm not the right kind of programmer to just do this myself.)

This should make it simple to pass through a streaming target such as rtmp://LOCALHOST/LIVE/

This does not help streaming targets that are case-sensitive in the URL portion, but is still useful in a lot of cases. Thanks for considering this.

**Comment by ronag** [comment]
2.2
