### ISSUE TITLE
Seeking files without header/index table/"duration" crashes FFMPEG producer

### ISSUE THREAD

**Issue by premultiply** [CasparCG/server#852]
MPEG2-PS/TS, some MXF, ...

**Comment by ronag** [comment]
@premultiply please provide a sample file

**Comment by premultiply** [comment]
Please take the second file I sent you the link via email some time ago.

**Comment by ronag** [comment]
@premultiply Thanks!

P.S. Next time please upload to e.g. dropbox and link here in the issue... I get lots of mail and it's hard to keep track of.

**Comment by premultiply** [comment]
I am not shure on rights to share some files to the public.

**Comment by ronag** [comment]
@premultiply I think I fixed this in https://github.com/CasparCG/server/commit/3b0052d20bda07c2f1e5f0844c29af12346e08e7

Could you try with latest build?

**Comment by premultiply** [comment]
If its on gdrive I can try tomorow
