### ISSUE TITLE
Decklink consumer causes channel performance issues

### ISSUE THREAD

**Issue by Julusian** [CasparCG/server#855]
There are performance issues with both the html and flash producers when the decklink consumer is enabled. The screenshots below show both of the producers perform better after the decklink consumer is removed.
The templates also appears a lot smoother in the screen consumer once the decklink consumer has been removed.

HTML [smooth_scroll_html.zip](https://github.com/CasparCG/server/files/1738157/smooth_scroll_html.zip) runs significantly better with decklink removed

![image](https://user-images.githubusercontent.com/1327476/36396881-18c49328-15b8-11e8-9cf8-10cd38ebff54.png)

Flash NTSC-TEST-30 buffer is consistent with decklink removed
![image](https://user-images.githubusercontent.com/1327476/36396994-9a36b88c-15b8-11e8-835b-eed44031d187.png)

Screen consumer gets better after removing decklink
![image](https://user-images.githubusercontent.com/1327476/36397118-2cf6781a-15b9-11e8-9ef6-95a116936478.png)

**Comment by ronag** [comment]
Do you have the same behaviour in progressive mode?

**Comment by Julusian** [comment]
No, I was just about to edit to say that it happens in 1080i5000 but is fine in 1080p5000

**Comment by ronag** [comment]
@Julusian I think I know what's causing it. Will look into it tomorrow.

**Comment by ronag** [comment]
Fixed

**Comment by premultiply** [comment]
Works fine now.

![diag](https://user-images.githubusercontent.com/4681172/36429355-67f4dd26-164a-11e8-9f4c-e59d4c09d19f.png)
