### ISSUE TITLE
Decklink producer, audio out of sync.

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/server#861]
After having the server running for 14 hours the server was out of sync for the audio on the deckling producer.

`PLAY 1-10 DECKLINK DEVICE 4 FORMAT 1080i5000`

I have no idea of when it was noticeable but will run the test again.

**Comment by 5opr4ni** [comment]
I have tested this more during the day and it all comes down to that it has to be the Decklink producer.
It some times flashes the video in black without affecting the audio. After a couple of hours there is loss of audio/video sync.

**Comment by ronag** [comment]
Please try with latest gdrive. Note, you need to download all the dlls as well, not just .exe.

**Comment by 5opr4ni** [comment]
Thnx, in test now.

**Comment by 5opr4ni** [comment]
OK!

I have run this on two different systems.

**Decklink Quad 2 with reference locked.**
During 13 hours and 44 minutes the delay on the audio was 27 frames (> 1 second)

**Decklink 4k Pro no reference.**
During 12 hours still in sync.

????

**Comment by 5opr4ni** [comment]
Can be a faulty Decklink Quad 2 Card, we have apparently seen this before here at work.
Can the glitch cause the shifting in audio?

**Comment by ronag** [comment]
Depends on what "glitch". If the frames come out of sync from the card there is not much to do in caspar. I can add some sync graphs that might be helpful.

**Comment by 5opr4ni** [comment]
Could help! Maybe also in the log.

**Comment by 5opr4ni** [comment]
With the sync status in the log I have found that the source was the issue not the server it self. So I am doing a new test. Stay tuned for more info.

**Comment by 5opr4ni** [comment]
This morning the Decklink Producer was frozen.
<img width="1372" alt="screen shot 2018-02-23 at 08 12 29" src="https://user-images.githubusercontent.com/20354852/36582768-15704c5e-1873-11e8-8aad-9509644f93fb.png">

**Comment by ronag** [comment]
@5opr4ni what's the status here? something we need to look into or are u still testing?

**Comment by 5opr4ni** [comment]
I will do one last test tomorrow and come back on this. Did you look at the files I sent late Saturday evening? :) You can hear a sever audio shift in the files. There is sync, but there is also some kind of ghost echo sound around one second later. it takes around 10 hours to reproduce. :(

**Comment by premultiply** [comment]
I had it running for two days now with Vistek Valid Generator and Reader and it looked ok BUT audio was always LATE by 40ms.

1080i5000. Decklink 4K Pro. Source and Decklink reference locked.

**Comment by ronag** [comment]
@premultiply was it late from the beginning or after a while?

**Comment by premultiply** [comment]
From the beginning.

**Comment by vimlesh1975** [comment]
On Mar 1, 2018 10:49 AM, premultiply <notifications@github.com> wrote:

From the beginning.

**Comment by 5opr4ni** [comment]
It seems as @premultiply is right. Watch this image, it seems as the Decklink Consumer has the problem with a late audio..
![2018-03-01 at 08 43](https://user-images.githubusercontent.com/20354852/36833009-4a92db44-1d2e-11e8-8583-88492623f360.png)

**Comment by 5opr4ni** [comment]
This is out of issue, should we move it to a new issue. @ronag

**Comment by premultiply** [comment]
=> #891

**Comment by ronag** [comment]
Is this an issue with the producer or consumer or unknown?

**Comment by 5opr4ni** [comment]
Working!
