### ISSUE TITLE
FFmpeg OSC /file/time value inconsistent

### ISSUE THREAD

**Issue by Julusian** [CasparCG/server#866]
Whilst looking through the ffmpeg producer code to document the osc data in the wiki, I noticed that one of the times the file/time value is set, it is being done differently to the rest.

The first field is the one I am concerned with. The second field I can understand being different depending on where the frame is from.

I don't have a build of caspar on me to verify this, or check which is wrong.

https://github.com/CasparCG/server/blob/416ffad3d0a31ab512e00a6c73fa2bc97e4862a5/src/modules/ffmpeg/producer/av_producer.cpp#L469
vs
https://github.com/CasparCG/server/blob/416ffad3d0a31ab512e00a6c73fa2bc97e4862a5/src/modules/ffmpeg/producer/av_producer.cpp#L772
https://github.com/CasparCG/server/blob/416ffad3d0a31ab512e00a6c73fa2bc97e4862a5/src/modules/ffmpeg/producer/av_producer.cpp#L793

**Comment by ronag** [comment]
Thanks! Fixed.
