### ISSUE TITLE
2.1.x large files were removed

### ISSUE THREAD

**Issue by krzyc** [CasparCG/server#869]
I can not compile CasparCG Server after fresh clone of 2.1.x - large files from dependencies64 were removed and renamed to .REMOVED.git-id.

After copying dependencies64 from previous checkout, everything worked as expected.

**Comment by ronag** [comment]
@krzyc that shouldn't have happened. One moment and I'll try to resolve that.

**Comment by ronag** [comment]
@krzyc please try now (you need LFS).

**Comment by gizahNL** [comment]
The correct way to do it when working from an already initialized repo:
-install git-lfs (follow instructions for your OS)
-move to root of project and issue 'git lfs fetch' command, this should download all files.
-issue 'git lfs checkout .'  command (not really sure if needed)

**Comment by krzyc** [comment]
Fixed
