### ISSUE TITLE
STOP ON LAST FRAME

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#874]
I have two video files, one file (ANDREWS_012.mp4) play and returns to the first frame when done playing, the other (FREEFON_003.mp4) stays on the last frame when done playing. is there way to always stay on the last frame when play is done? the above mentioned files are in the attached file.
[fillers.zip](https://github.com/CasparCG/server/files/1750745/fillers.zip)

**Comment by ronag** [comment]
ANDREWS_012.mp4 is a weird file... it loops the video twice... so it actually doesn't go to the first frame it just goes to the next frame which contains an identical frame to the first

**Comment by ronag** [comment]
@PeterAkakpo: the workaround for now is to properly encode that file

**Comment by dotarmin** [comment]
This is fixed in branch `v2.2.x` as far as I know.

ping @Julusian

**Comment by Julusian** [comment]
This is still a problem in both 2.2.x and master branches
