### ISSUE TITLE
Mixer tweens don't work on empty layer

### ISSUE THREAD

**Issue by TomKaltz** [CasparCG/server#879]
Not sure if it's a bug or feature but a mixer fill tween doesn't start until there is a producer on the layer.  Steps to reproduce...

MIXER 1 FILL .25 .25 .5 .5 60 easeinoutquad
PLAY 1 AMB

The tween will not start until the second command is sent.

**Comment by jesperstarkar** [comment]
This is a bug

**Comment by pkeuter** [comment]
Same goes for KEYER. This only works when there's a producer on the layer.
