### ISSUE TITLE
ffmpeg consumer does not honor -vcodec option

### ISSUE THREAD

**Issue by TomKaltz** [CasparCG/server#881]
libx264 encoder is always what gets used.  Steps to reproduce...

ADD 1-5 FILE record.mov -vcodec prores
or
ADD 1-5 FILE record.mov -vcodec dnxhd

**Comment by 5opr4ni** [comment]
Try it like this!

`ADD 1 FILE dnx.mxf -codec:v dnxhd -b:v 220M -flags:v +ilme+ildct -threads:v 4 -filter:v format=yuv422p,interlace`
**220 should be some other BR for NTSC**

`ADD 1 FILE "asd.mp4" codec:v libx264 -flags:v +ilme+ildct -threads:v 4 -filter:v interlace -preset:v veryfast`

**Comment by TomKaltz** [comment]
Ah yes I need to put all options explicitly.  Your command worked.  Thanks!
