### ISSUE TITLE
ffmpeg consumer cannot be properly stopped after dropped frames

### ISSUE THREAD

**Issue by TomKaltz** [CasparCG/server#883]
No warnings are displayed in log.  Shows constant dropped frames in diag.  REMOVE command will not work after that.  Commands gets OK response but the consumer is still left on DIAG.

![capture10](https://user-images.githubusercontent.com/2965281/36693569-a54a90e4-1b09-11e8-9e20-1793af8c5648.PNG)

**Comment by TomKaltz** [comment]
@ronag I'm able to reproduce this pretty consistently.  I have found that the consumer will destroy if I stop it very soon after I start getting dropped frames.  If I let it repeat dropping frames for a couple seconds longer the producer will not destroy.

**Comment by TomKaltz** [comment]
ADD 1-700 FILE record8.mxf -codec:v dnxhd -b:v 120M -codec:a pcm_s16le -flags:v +ilme+ildct -filter:v scale=out_color_matrix=bt709:out_range=tv,format=yuv422p,interlace

This is a 1080i5994 channel

is the command I'm using per discussion in #884

**Comment by ronag** [comment]
Fixed
