### ISSUE TITLE
Decklink producer wrong colorspace

### ISSUE THREAD

**Issue by premultiply** [CasparCG/server#885]
When passing live video through the server it looks like the colorspace conversion from Decklink HD-SDI Input to internal RGB processing is not BT.709 but BT.601 so color levels and values are shifted.

Tested by passing a simple 1080i5000 color bar from generator through the server to a waveform monitor.

**Comment by TomKaltz** [comment]
d99ad73af7c03ff584f80d08d366bab0b675357b

**Comment by premultiply** [comment]
What should this change?

**Comment by ronag** [comment]
I think @TomKaltz wanted to refer to https://github.com/CasparCG/server/commit/88740587f6d0eb2adc1158f35e483c805dfcea07

But as you indicated on Slack that didn't seem to help,,,

**Comment by premultiply** [comment]
Yes. It does not help.
But I think it may be used by using `colorspace` filter and `iall` option to overwrite the wrong assumed input propertys

or

if possible do the correction/conversion and scaling in one step using `scale` at the output step of the ffmpeg chain.

**Comment by premultiply** [comment]
Using ffmpeg to scale the video to the channel resolution (and convert to RGBA) has the benefit that any input size would be possible which seems to be limited to 1:1 right now.

**Comment by premultiply** [comment]
My theory is validated by running colorspace filter:
`PLAY 1 DECKLINK 1 VF colorspace=iall=bt709:all=bt709`
gives correct results for HD-SDI input but should be replaced by scaler solution.

**Comment by ronag** [comment]
Pushed to master. If someone can build it for you please test it. @dotarmin is autobuild up and running?

**Comment by dotarmin** [comment]
Yes it is but I haven't enabled upload to builds.casparcg.com just yet. I plan to do it after lunch today and announce at forum as well.

**Comment by premultiply** [comment]
https://github.com/CasparCG/server/commit/1aa8a8fa4bfa42e18cfe0641660705931b7313a4
Should work for HD input now but is far away from a final and clean solution.

**Comment by ronag** [comment]
@premultiply yep, there is a nice TODO waiting for a PR ;)

**Comment by ronag** [comment]
Since it is possible to workaround I think for now we can add an entry to the wiki.

**Comment by ronag** [comment]
I wish the decklink api could tell us what is the correct color space.

**Comment by ronag** [comment]
@premultiply slightly better implementation pushed. Though the SDK does not have any flags for bt2020.

**Comment by premultiply** [comment]
Better but the main problem is the colorspace filter itself. Now the colorspace may be converted two times
First time from YUV to YUV and second time from YUV to RGB(A). It should be done in single step during the YUV to RGB(A) conversion.

And I am still not shure how this is done in current implementation.

I am familiar with all those broadcast standards, workflows, measurements and I can read most of the C++ code but I am not able to high perfomance coding in C++.

**Comment by ronag** [comment]
@premultiply the colorspace filter in this case does no conversion, it only sets the proper metadata fields on the frames
