### ISSUE TITLE
Decklink consumer, audio out of sync

### ISSUE THREAD

**Issue by premultiply** [CasparCG/server#891]
Audio is delayed by ~40ms (1080i5000).

**Comment by 5opr4ni** [comment]
![2018-03-01 at 08 43](https://user-images.githubusercontent.com/20354852/36833261-21bbca18-1d2f-11e8-860d-0dd23fdbd9c5.png)

**Comment by premultiply** [comment]
Playing the same Vistek Valid MXF file (1080i5000) created and validated on external equipment through FFMPEG producer to Decklink consumer with different channel configurations:

Channel set to 1080i5000 Audio Delay 26ms
![img_2962](https://user-images.githubusercontent.com/4681172/36836000-4a5e79e4-1d38-11e8-8e62-06632ebb0f54.JPG)

Channel set to 720p5000 Audio Delay 14ms
![img_2960](https://user-images.githubusercontent.com/4681172/36836021-610a0e9c-1d38-11e8-8821-0801cb493cb8.JPG)

Channel set to PAL Audio Delay 4ms
![img_2961](https://user-images.githubusercontent.com/4681172/36836037-6d1eb9bc-1d38-11e8-8517-5b8ac8d25823.JPG)

**Comment by ronag** [comment]
Is ffmpeg_consumer out of sync as well?

**Comment by premultiply** [comment]
Let me check... May take a while. I am quiet busy at the moment.

**Comment by ronag** [comment]
@premultiply nvm, @5opr4ni's check answers my question

**Comment by premultiply** [comment]
@ronag Not for shure. Exactly one frame may be another reason than the different offsets seen on my measurements on decklink output.

**Comment by ronag** [comment]
can you provide your test file?

**Comment by premultiply** [comment]
Yep. But it's quite huge and you may need a valid reader device for it.

**Comment by 5opr4ni** [comment]
96 hours later. ;)
<img width="805" alt="screen shot 2018-03-06 at 12 35 03" src="https://user-images.githubusercontent.com/20354852/37030406-1a784668-213b-11e8-8352-863bbb38cb17.png">

**Comment by ronag** [comment]
So it's roughly 60 ms off.

**Comment by premultiply** [comment]
So I did some tests again. The audio offset is not fix (file to decklink). It changes in range from 0 to 40 ms when restarting the server and/or changing the output mode but it seems to be constant over time.

**Comment by 5opr4ni** [comment]
40ms, se my image earlier in the thread so you can compare with the original file.

**Comment by premultiply** [comment]
Recording file by ffmpeg_consumer and playing again through server to decklink_consumer adds no additional delay so ffmpeg_consumer seems to be fine.

**Comment by ronag** [comment]
ok, so it's a decklink frame scheduling issue. Could be either Caspar or Decklink drivers or both.

**Comment by 5opr4ni** [comment]
Strange! I am testing the latest build for the deckling producer and did an external SDI recording and got this. Now I will leave it running until tomorrow. I think we are accurate enough?
<img width="805" alt="screen shot 2018-03-06 at 12 58 00" src="https://user-images.githubusercontent.com/20354852/37031354-c2d8878e-213e-11e8-9c1e-0ad4c4509abd.png">

**Comment by premultiply** [comment]
I am wondering why there is no "connection" to the hardware reference clock of the decklink board visible to me from code. For me it looks like server feeds frames by "system time" (or HPET etc.) to decklink board. So decklink boards will drop or duplicate frames as needed to match their own free running or genlocked clock. Decklink is not the clock master for channel. This would explain why there is random timing. Or am I wrong?

**Comment by TomKaltz** [comment]
I'm curious about this too.  Decklink genlock clock should drive channel ticking.  Is this not the case @ronag?

**Comment by ronag** [comment]
> Or am I wrong?

You are wrong. The decklink api has a callback it calls based on it's internal clock.

**Comment by premultiply** [comment]
https://github.com/CasparCG/server/blob/8dcbc80c617211eda521a80ec38d3215eb7d2dd7/src/modules/decklink/consumer/decklink_consumer.cpp#L726
Maybe this is the reason for the main 1 Frame Audio Offset.

Has anybody checked if this is really true?:
Buffering 3 Frames of Video and 4 Frames auf Audio??? Sounds really strange to me.
What happens if they are set equal? Can someone build it with equal buffersizes for me?

**Comment by ronag** [comment]
yes... that has occurred to me as well... I think helge wanted to lower the latency by doing that... but yea that means the audio is off sync.

**Comment by ronag** [comment]
@premultiply could you try with master now?

**Comment by premultiply** [comment]
The 1 frame offset ist fixed for normal and low delay mode now.

![img_2967](https://user-images.githubusercontent.com/4681172/37198588-18aeb042-237f-11e8-8201-61e68b447bb1.jpg)

**Comment by jesperstarkar** [comment]
Good job guys. Brilliant.

**Comment by premultiply** [comment]
System delay (decklink_producer to decklink_consumer, genlocked) is 8 frames in low delay mode now and 9 frames in normal mode now.

**Comment by premultiply** [comment]
Genlocked yes. Haven't measured it without genlocking the decklink card... Let me check...

**Comment by ronag** [comment]
@premultiply thanks for the help!
