### ISSUE TITLE
Server (hardware) stalls when using flash producer

### ISSUE THREAD

**Issue by dotarmin** [CasparCG/server#893]
When flash producer is used for playing a template we have noticed that the whole server (hardware) stalls. It feels like a threading issue because it stalls for some ticks and then releases and stalls for some ticks and does so until the template has played. We get a frame rate of 2-3 frames per second.

We have also tested on various servers with various templates and have the same issue on all. Templates used for testing contains animations.

Best regards,
Armin

**Comment by dotarmin** [comment]
I will dig into this issue because I have successful tests on a completely different machine compared to those used before. I will write an update on this when I have more information.

**Comment by niklaspandersson** [comment]
Problem solved with latest graphic drivers.

**Comment by dotarmin** [comment]
> Problem solved with latest graphic drivers.

👍

**Comment by jesperstarkar** [comment]
Which drivers/GPU?

**Comment by dotarmin** [comment]
> Which drivers/GPU?

ping @niklaspandersson

**Comment by ronag** [comment]
Nvidia Graphics Drivers

**Comment by niklaspandersson** [comment]
Mmm. I have a Quadro K2200, and with the latest drivers (390.77) everything seems fine.
