### ISSUE TITLE
Last frame is not removed when stopping flash-producer

### ISSUE THREAD

**Issue by niklaspandersson** [CasparCG/server#894]
If a flash-template ends with a frame with some content, that frame is still visible after a STOP command

**Comment by ronag** [comment]
STOP or CG STOP?

**Comment by ronag** [comment]
This might be fixed in https://github.com/CasparCG/server/commit/a7856fd638ff37bcc1e881c95cc2d84c1474f8a2

Please verify

**Comment by dotarmin** [comment]
I'm on it!

**Comment by dotarmin** [comment]
I can confirm that it works as expected now. Both STOP and CG STOP works.
