### ISSUE TITLE
osc messages for consumer and producer destruction

### ISSUE THREAD

**Issue by TomKaltz** [CasparCG/server#900]
Would be nice to get an osc message when a producer or consumer is destroyed so our clients can be smarter.

**Comment by ronag** [comment]
osc is not for messaging, it's a realtime state transfer protocol, in this case the client should notice when the consumer is removed from the osc state.

**Comment by TomKaltz** [comment]
we definitely need more info but I remember in my 2.0.7 fork I added osc messages when file was eof and it was extremely helpful for the client I was building.  I’ll see if I can find what else I added and explain why it was so helpful

**Comment by TomKaltz** [comment]
Also I don’t think detecting when state isn’t updated anymore is difficult. Getting a distinct message for certain events is way more useful.

**Comment by ronag** [comment]
> Getting a distinct message for certain events is way more useful.

It's easier. But it's not possible with OSC.

**Comment by baltedewit** [comment]
> Though I'm unsure we are sending enough state information over OSC currently.

I think we could do better. I'd love to see diagnostics info added back so we can start exploring visualization in a webpage rather than through opengl.

The HTML producer doesn't output anything yet and the decklink outputs as if it is a file. The image producer outputs a path, but without any differentation of whether it is a movie or an image.

As a personal request, I'd love to see volume per layer in addition to the channel volume.

Perhaps their could be a general issue created to discuss how the osc output should evolve?

**Comment by Julusian** [comment]
> Getting a distinct message for certain events is way more useful.
> osc is not for messaging (since it's UDP + lossy)

Perhaps there could be an TCP based event socket that clients can connect to for infrequent one off messages such as this? There could be better ways though.

> Perhaps their could be a general issue created to discuss how the osc output should evolve?

That would be a good idea. 
Also, adding the missing osc data to the other producers is usually pretty simple to do, so if there can be an issue listing the endpoints what you want to see added for those than that can be discussed and quickly tackled (hopefully into 2.2)

**Comment by TomKaltz** [comment]
I’ve used one-off messaging via osc with very good results. It’s very rare you have UDP packet loss these days.  I understand it’s considered not safe but perhaps we can add these osc messages with the explicit documentation that they can be unreliable?

Of course if we figure a better way to get pertinent info to client apps then we should definitely not do this.
