### ISSUE TITLE
Windows: CMake copies both debug and release dlls to output

### ISSUE THREAD

**Issue by Julusian** [CasparCG/server#908]
### Current Behaviour
When building a release build, then the debug dlls are copied to the output directory. The same is true with release dlls when doing a debug build.

These is present in each of 2.2, 2.1 and 2.0 builds.

### Expected Behaviour
It would be better to not include the unused dlls. This reduces the clutter in the build folder and will reduce the resulting size of the folder/zip

**Comment by dotarmin** [comment]
Good timing @ronag ;)

**Comment by ronag** [comment]
I win!

**Comment by dotarmin** [comment]
Only by 2 seconds! But I guess a win is a win! :bowing_man:

**Comment by Julusian** [comment]
This was done when writing new build scripts in the repository https://github.com/CasparCG/server/commit/abc35821b797bbcc9cfedabf396fd2e2ef5c9b8c
