### ISSUE TITLE
Audio distortion at NTSC framerates

### ISSUE THREAD

**Issue by TomKaltz** [CasparCG/server#915]
When running in NTSC framerates I get distorted audio in the system audio consumer and the ffmpeg consumer.

Audio sounds better from a recorded (ffmpeg consumer) file but still distorts.

Seems like something with our old friend the NTSC audio cadence run.

**Comment by TomKaltz** [comment]
This is related to #838. @ronag feel free to close this if you think the other issue fully covers this.

**Comment by ronag** [comment]
I think so.
