### ISSUE TITLE
Console logging is strange on Windows 10

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#916]
Sometimes it just stops printing...

**Comment by TomKaltz** [comment]
I noticed this too at one point then couldn’t reproduce after restart.  I have a suspicion it has to do with new line characters. There may have been a preceding new line in the commands I was pasting into console.

**Comment by Julusian** [comment]
Seems to occur either when scrolling up to the very top, or stopping it from outputting (eg marking text) which it then never recovers from

**Comment by baltedewit** [comment]
> Seems to occur either when scrolling up to the very top, or stopping it from outputting (eg marking text) which it then never recovers from

> There may have been a preceding new line in the commands

Just FYI: can't reproduce this on linux/debian 9.3.

**Comment by Jeff-Clark-MST** [comment]
I've had this in several CasparCG builds and other console based app's on Windows 10. This solved it for me:

1. Right Click the CasparCG Console window.
2. Untick 'Quick Edit Mode'
3. Untick 'Insert Mode'

Windows 10 behaviour for console windows is pretty poor, it also sometimes sleeps the window unless you do something to hit (like press enter on it)

**Comment by ronag** [comment]
Would be nice if we could set these programmatically.

**Comment by Jeff-Clark-MST** [comment]
C++ isn't my thing at all. But the below unticks them both for me:

In  ..\src\shell\main.cpp

Calling after print_info(); in run()

```
    HANDLE hConsole = GetStdHandle(STD_INPUT_HANDLE);
    SetConsoleMode(hConsole, ENABLE_EXTENDED_FLAGS);
```

source: https://docs.microsoft.com/en-us/windows/console/setconsolemode 

At present this does prevent you typing in the console window however. Which is strange since manually disabling QuickEdit mode still allows you to type.

**Comment by dotarmin** [comment]
@Jeff-Clark-MST, thanks for helping out. @niklaspandersson will look at this issue this week and I'm sure this is helpful information!

**Comment by dotarmin** [comment]
Does this issue apply only on Windows 10 or Windows 7 as well?

**Comment by Jeff-Clark-MST** [comment]
I personally have only had the issue on windows 10.

I've had a number of console based apps (CasparCG server included) that have been used on both Windows 10 and Windows 7 machines and the console hanging until you give it focus or press a button on it has only occurred on Windows 10.

**Comment by dotarmin** [comment]
Thanks @Jeff-Clark-MST

**Comment by ronag** [comment]
Fixed. 87791e16fbe1430f50811cfcd85c0abfcabee5d6
