### ISSUE TITLE
Improve output on linux when config file is missing

### ISSUE THREAD

**Issue by Julusian** [CasparCG/server#917]
### Expected Behaviour
The user should be informed that the specified file could not be found.
Potentially a default file should be generated to the specified filename.

### Current Behaviour
```
julus@julus-archimedes:/opt/casparcg-2.2$ ./run.sh test.config
Type "q" to close application.
julus@julus-archimedes:/opt/casparcg-2.2$ 
```

Windows gives better output:
```
PS C:\casparcg\ccg22> .\casparcg.exe test.config
Type "q" to close application.
[2018-03-09 01:15:44.630882] [0x00002ffc] [error]    ### Invalid configuration file. ###
[2018-03-09 01:15:44.631382] [0x00002ffc] [fatal]   At test.config:0: read error. Please check the configuration file (test.config) for errors.
```

### Environment
* CasparCG Server version: 7c0ffc4c
* Operating system: Ubuntu 18.04

**Comment by gizahNL** [comment]
gijs@testlab-707:~/casparcg_server$ ./run.sh 
Type "q" to close application.


CasparCG will automatically shutdown. See the log file located at the configured log-file folder for more information.

/any/ error output would be helpful. Caspar is also refusing to log anything to files, perhaps also the possibility to start with debug (i.e.: extra verbose messages) would be nice.
