### ISSUE TITLE
LAST FRAMES NOT PLAYED (ver 2.1 beta 2)

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#925]
### Expected Behaviour
Video should play to the end of file

### Current Behaviour
Video plays, but does not play the last frames. VLc player and windows media player are able to play the files right to the end with no problem.

### Steps to Reproduce 
play any video file and run then DIAG. You will observe that when the file ends , the frames played is always less then the total frames and you don't get to hear the last audio.

### Environment
* CasparCG Server version:  2.1 BETA 2
* Operating system: WINDOWS 7, WINDOWS 8, WINDOWS 10

### Attachments

**Comment by ronag** [comment]
Please provide sample file

**Comment by PeterAkakpo** [comment]
Is there a way to send a file that is more than 10MB. My sample file is about 60MB.

**Comment by ronag** [comment]
Ah sorry, I didn't see this is for 2.1. We are not doing any more work on that. PS. Use dropbox, gdrive or some other cloud storage service for providing files.
