### ISSUE TITLE
newtek-ivga consumer is always interlaced?

### ISSUE THREAD

**Issue by waitforit** [CasparCG/server#927]
It appears that no matter which video-mode is set for a channel, the ndi output is always being sent as interlaced.  Is there a configuration option to override this?

**Comment by Julusian** [comment]
It appears to be hardcoded to always interlaced, no matter the channel format.
Simply requires changing this line to check if format_desc is progressive:

https://github.com/CasparCG/server/blob/97cbe67806b867cef564c625a55be983b7f813e0/src/modules/newtek/consumer/newtek_ivga_consumer.cpp#L82

**Comment by ronag** [comment]
It should be always progressive. Fixed in master.

**Comment by TomKaltz** [comment]
shouldn't we be able to choose the format of this output?  I think some switchers can take interlaced over NDI.

**Comment by ronag** [comment]
Make a new issue
