### ISSUE TITLE
How to look at producetime in graph

### ISSUE THREAD

**Issue by MauriceVeraart** [CasparCG/server#931]
hi all

I am benchmarking a custom build off 2.2.0
to see how it performs on the moment for my application

please have a look at the picture

I was wondering are the route producers now working on the edge
as the producetime is ticking the ceiling or is this spikey behavior normal ??

### Attachments
[img]https://preview.ibb.co/koV0ec/Untitled.png[/img][/url]

**Comment by ronag** [comment]
That doesn't look too good. Basically the produce time is how quick the route is getting frames from the source channel and the consume time is how faster the destination channel is consuming the frames.

However, as long as you don't get any vertical lines (dropped or late frame) you should be fine.
