### ISSUE TITLE
Move CII and CLK protocols to external services

### ISSUE THREAD

**Issue by Julusian** [CasparCG/server#934]
These both look like things that could easily be implemented as standalone services that convert to AMCP

**Comment by ronag** [comment]
They will be moved. We're looking into moving SVT stuff into their own fork. However, until that is ready they will unfortunately stay.

**Comment by Julusian** [comment]
https://github.com/CasparCG/server/commit/103038c8b8a6cef3227a7124d0e58714cdcce6d8
