### ISSUE TITLE
UNABLE to get BACKGROUND media via OSC or AMCP INFO

### ISSUE THREAD

**Issue by TondaKrist** [CasparCG/server#941]
Expected Behaviour
Return snapshot state of specified layer, either via AMCP INFO or OSC

Current Behaviour
Unable to get info about background media in specified layer
and other details which were able to get via AMCP in <= 2.1

**Comment by Julusian** [comment]
Related #923 #924

**Comment by Punkley** [comment]
Background media information is a must to be able to get.

**Comment by TomKaltz** [comment]
Regarding my previous comment https://github.com/CasparCG/server/issues/857#issuecomment-372438022
> I was tinkering and it seems that OSC will not get updated with the info from the background since it's not currently receiving frames since it's in the background. My work-around was to send the background producers print() information on every foreground frame receive but obviously this is a HUGE hack and delivers the background producer data in a weird string format.

@ronag do you think there is an easy solution to this problem or is my hack something that can be released as stop-gap measure until a proper fix is implemented?

**Comment by ronag** [comment]
It's easy to just add another osc path.

**Comment by Julusian** [comment]
#1063 #1080
