### ISSUE TITLE
osc info "/channel/1/stage/layer/1/file/frame" not comming

### ISSUE THREAD

**Issue by vimlesh1975** [CasparCG/server#943]
Many osc  information which were coming in servrer 2.1 are missing in server 2.2.
Most important is /channel/1/stage/layer/1/file/frame

![osc](https://user-images.githubusercontent.com/4338487/37697020-6df70f9c-2d00-11e8-91e1-a7ef790e7ee1.png)

**Comment by ronag** [comment]
You can calculate /frame from /time.

**Comment by vimlesh1975** [comment]
That will ok.
But what about dBFS vaules for audio?

**Comment by ronag** [comment]
Those can also be calculated from the values you get.

**Comment by dotarmin** [comment]
> You can calculate /frame from /time.

@vimlesh1975 This will be done in the CasparCG Client.

**Comment by vimlesh1975** [comment]
Total time is wrong in pause mode.

**Comment by ronag** [comment]
@vimlesh1975 can you raise that as a separate issue?
