### ISSUE TITLE
Memory leak on win 7 x64 with default config

### ISSUE THREAD

**Issue by saltomodules** [CasparCG/server#946]
### Expected Behaviour

Memory usage remains more or less stable all other factors staying the same.

### Current Behaviour

Memory usage keeps going up with about 100 - 300 kb per second even when casparcg isn't really doing anything. 

This begins immediately after starting casparcg with the default configuration.

Behavior is present in latest build 88171e16  but is als observable in earlier builds the earliest  tested being 7ba5e475 

### Steps to Reproduce 
Start casparcg with default config and monitor memory usage

### Environment
* CasparCG Server version: 
2.2.0.4 88171e16 Beta 1  (2018-03-20)
is also observed in 2.2.0.3 7ba5e475 Beta 1 (2018-02-28)
* Operating system:
Win 7 x64
* Graphics driver:
Nvidia 391.01 (for GTX660)
* Decklink drivers:
none

**Comment by baltedewit** [comment]
Judging from the task menu I can reproduce this on Windows 10.

This appears to be coming from the system-audio consumer, removing it stopped the excessive growth of memory. Although it appears there is still some minor growth with just the screen consumer. I don't notice any growth without consumers.

**Comment by dotarmin** [comment]
I can confirm this.

**Comment by ronag** [comment]
I can only reproduce it with system audio.

**Comment by Jeff-Clark-MST** [comment]
Can confirm reproducing this on Window 10.

Removing `<system-audio />` from my config for each channel solves.

E.g. 
Causes Mem Leak:
```
  <channels>
    <channel>
      <video-mode>1080i5000</video-mode>
      <consumers>      
         <decklink>
          <device>1</device>
          <embedded-audio>true</embedded-audio>
	  <keyer>external</keyer>
        </decklink>
        <system-audio />  <!-- causes mem leak -->
      </consumers>
    </channel>
  </channels>
```

No Mem Leak:

```
  <channels>
    <channel>
      <video-mode>1080i5000</video-mode>
      <consumers>      
         <decklink>
          <device>1</device>
          <embedded-audio>true</embedded-audio>
          <keyer>external</keyer>
        </decklink>
      </consumers>
    </channel>
  </channels>
```

**Comment by Punkley** [comment]
confirmed..

**Comment by Xeing** [comment]
confirmed:

Server version:
2.2.0 66a9e3e2 Stable
Operating system:
Win 10 x64
Graphics driver:
Nvidia 417.35 (for GTX1050)
Decklink drivers:
none
