### ISSUE TITLE
correct build-instructions

### ISSUE THREAD

**Issue by bastolino** [CasparCG/server#948]
### Expected Behaviour
On a complete vanilla system one would expect the build-instructions to simply work. All dependencies should be installed.

### Current Behaviour
- dependencies missing: git, docker.io (just add these packages to ./BUILDING.md, section Development, point 1)
- typo in section Development, point 6 "`" missing at the end of the line

**Comment by dotarmin** [comment]
> @bastolino On a complete vanilla system one would expect the build-instructions to simply work. All dependencies should be installed.

Git will be added.
Docker should be installed by following the instructions from Docker manual it-self, @k0d, please correct me if I'm wrong.

> typo in section Development, point 6 "`" missing at the end of the line

Fixed already!

**Comment by Julusian** [comment]
> Docker should be installed by following the instructions from Docker manual it-self

Yes, I had to install from the docker instructions rather than ubuntu repos in order to build successfully.

**Comment by bastolino** [comment]
Thanks for that info - then it would be worth mentioning the Docker manual as dependency also, right?

**Comment by dotarmin** [comment]
> @Julusian Yes, I had to install from the docker instructions rather than ubuntu repos in order to build successfully.

Thanks for confirming! :)

> Thanks for that info - then it would be worth mentioning the Docker manual as dependency also, right?

Yes, I will add it as step 2.

Thanks!

/Armin

**Comment by dotarmin** [comment]
Fixed!
