### ISSUE TITLE
How to do playback of youtube clips?

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#958]
When I test this command
https://www.youtube.com/embed/OUH3fio-fwE?autoplay=true&showinfo=0&autohide=1

A youtube clip should play

### Expected Behaviour
should play a youtube clip

### Current Behaviour
shows title but doesnot play.

### Environment
latest Casper 2.2 beta

### Attachments

**Comment by ronag** [comment]
If it doesn't work in ffplay it won't work in caspar, i.e. this doens't work either:

```bash
ffplay "https://www.youtube.com/embed/OUH3fio-fwE?autoplay=true&showinfo=0&autohide=1"
```

**Comment by pkeuter** [comment]
You can try using youtube-dl (https://github.com/rg3/youtube-dl) with the -g flag to extract the video URL of the link. This video will be playable by ffplay (and thus CasparCG)

**Comment by TKooijmans** [comment]
What about youtube live streams?

**Comment by pkeuter** [comment]
Same. youtube-dl will provide you with an HLS stream.
