### ISSUE TITLE
FFMPEG Consumer - Unused Options

### ISSUE THREAD

**Issue by PeterAkakpo** [CasparCG/server#959]
### Expected Behaviour

All options accepted by ffmpeg should also work
### Current Behaviour

running this in casparcg 
**add 1-89 file test.mp4 -c:a copy -c:v libx265 -vf scale=720:576** does not use 
the **-c:a copy and -vf scale=720:576**

also after recording, the format is **h264-mpeg4 avc (part 10) (avc1)** instead of **h.265 hevc**
does this means that casparcg does not support **h.265**?

but running this from the windows command prompt
**ffmpeg -i POIS01E03.mp4 -c:a copy -c:v libx265 -vf scale=720:576 video.mp4**
works as expected

also after converting, the format is **h.265 hevc** as expected.

### Steps to Reproduce 
Run the following command and see the response in the console
add 1-89 file test.mp4 -c:a copy -c:v libx265 -vf scale=720:576
the -c:a copy and -vf scale=720:576 were unused

### Environment
* CasparCG Server version: 2.2.0.4
* Operating system: Windows 10
![recording](https://user-images.githubusercontent.com/7926382/38452063-6f86e82c-3a2b-11e8-9a7a-dde07c3c6466.png)

### Attachments

**Comment by ronag** [comment]
You need to use the long form ffmpeg options:

```
add 1-89 file test.mp4 -codec:a copy -codec:v libx265 -filter:v scale=720:576
```

**Comment by ronag** [comment]
codec `copy` is not implemented and doesn't make much sense. If you just want to copy then this is basically it:

```
add 1-89 file test.mp4 -codec:a pcm_s32le -codec:v libx265 -filter:v scale=720:576
```
