### ISSUE TITLE
new command "INFO MOVIE" like "INFO TEMPLATE"

### ISSUE THREAD

**Issue by mcdikki** [CasparCG/server#96]
REQUEST:
It would be pretty nice to be able to get more information about movie files than given by CINF command for non playing or loaded movies.
Like duration, orig fps/height/width etc.
I think of a command equal to INFO TEMPLATE for movies/audios and stills.

The response should be a xml string like:
<movie modified="DATE" originalWidth="768" originalHeight="576" originalFrameRate="50" originalAspect="16/9" originalColorspace="RGB" hasAlpha="false" numberOfFrames="15896"/>
<still modified="DATE" originalWidth="768" originalHeight="576" originalColorspace="RGB" hasAlpha="false"/>
<audio modified="DATE" originalSamplingRate="48000" originalChannels="2" numberOfFrames="158"/>

**Comment by ronag** [comment]
info is deprecated
