### ISSUE TITLE
Strange alpha blending behavior

### ISSUE THREAD

**Issue by dimitry-ishenko** [CasparCG/server#964]
I've created two .mov files with Fill&Key -- red circle and blue square.

The red circle was created from:
FILL:
![red_f](https://user-images.githubusercontent.com/2858291/38697571-6b6be6a0-3e60-11e8-9f9d-df65419bf9c0.png)
KEY:
![red_k](https://user-images.githubusercontent.com/2858291/38697572-6b80695e-3e60-11e8-9b3b-3024acbbfd00.png)

The blue square was created from:
FILL:
![blue_f](https://user-images.githubusercontent.com/2858291/38697569-6b3e6518-3e60-11e8-916e-75a30f3755cf.png)
KEY:
![blue_k](https://user-images.githubusercontent.com/2858291/38697570-6b534294-3e60-11e8-9164-1cd719ff1559.png)

Here are the final .mov files (using qtrle codec):
[red.zip](https://github.com/CasparCG/server/files/1904569/red.zip)
[blue.zip](https://github.com/CasparCG/server/files/1904570/blue.zip)

When I overlay these files individually over a live feed (using linear key on GV Korona), they work fine eg:
```
play 1-10 blue loop
play 1-10 empty
play 1-11 red loop
play 1-11 empty
```
However, as soon as I try to play the red circle on top of the blue square, the square turns purple!
```
play 1-10 blue loop
play 1-11 red loop
```
Once I remove the circle, the square turns blue again:
```
play 1-11 empty
```
You can see the whole process here: [record](https://streamable.com/gsby2)

### Expected Behaviour
Red circle on top of blue square.

### Current Behaviour
The blue square turns purple!

### Steps to Reproduce 
```
play 1-10 blue loop
play 1-11 red loop
```

### Environment
* Operating system: Ubuntu 16.04 LTS
* CasparCG Server version: 2.1.0.472 dc2e94b Beta 2
* Graphics card: Quadro K2200
* Graphics driver: 387.34
* Decklink card: DeckLink 4K Extreme
* Decklink drivers: 10.9.7

**Comment by 5opr4ni** [comment]
Hi

CasparCG normally works in premultiplied, so creating the files as you do is not correct, they are straight as you do them. Caspar internali work in premultiplied mode, so you actually get the correct result based on your source files. 
Historically, straight was the preferred but now a days premultiplied is the one to go with. It is actually called producers choice. Today most Dsk’s has support for this.

**Comment by hummelstrand** [comment]
It's easy to make the assumption that alpha channels are "cut-out masks", but every couple of years I have to refresh my memory by reading https://www.schoolofmotion.com/blog/premultiplication/ and reminding myself that the alpha channel is multiplied with the fill.  :)

**Comment by dimitry-ishenko** [comment]
OK I feel stupid... I was trying to solve another problem and in the process completely forgot that Caspar needs premult alpha. Sorry and thank you pointing it out.
