### ISSUE TITLE
log console.log to log file

### ISSUE THREAD

**Issue by ronag** [CasparCG/server#975]
We need to be able to log from templates to caspar log.

**Comment by ronag** [comment]
What could be better? Can we merge it as a step 1?

**Comment by Julusian** [comment]
It doesn't distinguish any of the console log levels (eg console.warn) and parameters are not logged in the same way as they are to the console within chrome. I believe this is a limitation in the chromium api, which is what I was wanting to look into again to confirm.

```
console.log("Test line")

[2018-07-18 00:02:19.806] [info]    html[http://google.com] Log: Test line
```

```
console.log("Multi params", "p2", "p3")

[2018-07-18 00:02:34.240] [info]    html[http://google.com] Log: Multi params
```

**Comment by ronag** [comment]
Thanks! Feel free to improve.

**Comment by drakmor** [comment]
Print only first argument - is bug of CEF https://bugs.chromium.org/p/chromium/issues/detail?id=365427
