### ISSUE TITLE
Make build-scripts checkout themselves when a build is triggered

### ISSUE THREAD

**Issue by dotarmin** [CasparCG/server#978]
### Expected Behaviour
When a build is triggered automatically, the build-server should checkout the build-scripts itself from a repository. By going this approach, it would be enough with a pull request against the build-scripts repository to update the scripts when needed.

### Current Behaviour
When changes are made to CasparCG/server that affect files, folders, and versions of media-scanner that needs to be packaged to the final build (for example), it requires changes to the build-scripts located on the build-server. Those changes are dependent ob those who have access to the actual building server, which is bad.

**Comment by Julusian** [comment]
we have github actions now, witht the needed scripts in this repositoru
