### ISSUE TITLE
CLS extended version

### ISSUE THREAD

**Issue by MauriceVeraart** [CasparCG/server#982]
feature request

CLS

now gives minor information of assets
while FFPROBE gives us a lot more usefull  information about it.

to stay backward compatible 
maybe making a CLSE (extended) 
command  that outputs more detailed information is nice to have.

played around with this my self, CLS gives me now info like FPS/CODEC/RESOLUTION/AR
which makes making clients a lot easier for me.

**Comment by Julusian** [comment]
the scanner has some http endpoints that allow for this
