### ISSUE TITLE
INFO commands not working with latest build

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#983]
THE AMCP commands like INFO PATHS, INFO SYSTEM
don't return information with latest 2.2 build of 23-04-2018

### Current Behaviour
commands like
PLAY 1-1 clipname   work but
INFO 1-1 or INFO PATHS or INFO SYSTEM  return all the same info

### Steps to Reproduce 

Send command like
INFO PATHS,
check return info

### Environment
* CasparCG Server version: 2.2.04  (23 april build)
* Operating system: Win7-64

**Comment by Julusian** [comment]
This is expected behaviour. The info command has been removed in favour of OSC
#923 #924 #941

**Comment by dotarmin** [comment]
@ronag has added #923 to milestone 2.2.0. Info will be put pack to v2.2 with reservation that XML-structure could possibly change.
