### ISSUE TITLE
How to get output stream working again?

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#984]
With the latest builds I can't get output stream working.
When I try 
ADD 1 STREAM 1 rtmp://yourWowzaserver/live/zwaluw
with FF mpeg settings
-pix_fmts yuv420p -format flv -vcodec libx264 -crf 28 -vf scale=1280:720 -c:a libvo_aacenc -b:a 96k -tune film -preset veryfast

So total command would be
ADD 1 STREAM 1 rtmp://yourWowzaserver/live/zwaluw -pix_fmts yuv420p -format flv -vcodec libx264 -crf 28 -vf scale=1280:720 -c:a libvo_aacenc -b:a 96k -tune film -preset veryfast

Casper Connects to Wowza server but does not stream any video and audio.

### Expected Behaviour
This works with CasperCG 2.1

### Current Behaviour
I Get connection but no video or audio

This is the log, It seems that the FFmpeg settings are changed?

[2018-04-30 12:51:04.604] [info]    Received message from 127.0.0.1: ADD 1 STREAM rtmp://media.omroepgelderland.nl/live/zwaluw -pix_fmts yuv420p -format flv -vcodec libx264 -crf 28 -vf scale=1280:720 -c:a libvo_aacenc -b:a 96k -tune film -preset veryfast\r\n
[2018-04-30 12:51:04.604] [info]    ffmpeg[rtmp://media.omroepgelderland.nl/live/zwaluw] Initialized.
[2018-04-30 12:51:04.604] [info]    Sent message to 127.0.0.1:202 ADD OK\r\n
[2018-04-30 12:51:04.729] [warning] ffmpeg[rtmp://media.omroepgelderland.nl/live/zwaluw] Unused option c=libvo_aacenc:a
[2018-04-30 12:51:04.729] [warning] ffmpeg[rtmp://media.omroepgelderland.nl/live/zwaluw] Unused option crf=28
[2018-04-30 12:51:04.729] [warning] ffmpeg[rtmp://media.omroepgelderland.nl/live/zwaluw] Unused option pix_fmts=yuv420p
[2018-04-30 12:51:04.729] [warning] ffmpeg[rtmp://media.omroepgelderland.nl/live/zwaluw] Unused option preset=veryfast
[2018-04-30 12:51:04.729] [warning] ffmpeg[rtmp://media.omroepgelderland.nl/live/zwaluw] Unused option tune=film
[2018-04-30 12:51:04.729] [warning] ffmpeg[rtmp://media.omroepgelderland.nl/live/zwaluw] Unused option vcodec=libx264
[2018-04-30 12:51:04.729] [warning] ffmpeg[rtmp://media.omroepgelderland.nl/live/zwaluw] Unused option vf=scale=1280:720

**Comment by baltedewit** [comment]
short hand parameters are no longer accepted by the ffmpeg consumer.

**Comment by sirfnomi** [comment]
with ADD 1 STREAM udp://192.168.10.17:5001 -vcodec libx264 -f mpegts -tune zerolatency -preset medium -crf 18 getting error

> [error]   [ffmpeg] [NULL @ 00000000209B0A80] Unable to find a suitable output format for 'udp://192.168.10.17:5001'


Log:

> [2018-05-01 21:32:24.441] [info]    Received message from Console: ADD 1 STREAM udp://192.168.10.17:5001 -vcodec libx264 -f mpegts -tune zerolatency -preset medium -crf 18\r\n
> [2018-05-01 21:32:24.442] [info]    ffmpeg[udp://192.168.10.17:5001] Initialized.
> [2018-05-01 21:32:24.442] [error]   [ffmpeg] [NULL @ 00000000209B0A80] Unable to find a suitable output format for 'udp://192.168.10.17:5001'
> [2018-05-01 21:32:24.442] [error]   
> [2018-05-01 21:32:24.442] [error]   [ffmpeg] [NULL @ 00000000209B0A80] Unable to find a suitable output format for 'udp://192.168.10.17:5001'
> [2018-05-01 21:32:24.442] [error]   
> [2018-05-01 21:32:24.453] [error]   Exception: C:\Program Files (x86)\Jenkins\workspace\casparcg-server-dep\master\src\modules\ffmpeg\consumer\ffmpeg_consumer.cpp(572): Throw in function auto __cdecl caspar::ffmpeg::ffmpeg_consumer::initialize::<lambda_1c3c76a4aed4389bbadcffe3259fc23f>::operator ()(void) const
> [2018-05-01 21:32:24.453] [error]   Dynamic exception type: class boost::exception_detail::clone_impl<struct caspar::ffmpeg::ffmpeg_error_t>
> [2018-05-01 21:32:24.453] [error]   [struct boost::errinfo_api_function_ * __ptr64] = avformat_alloc_output_context2( &oc, nullptr, !format.empty() ? format.c_str() : nullptr, path_.c_str())
> [2018-05-01 21:32:24.453] [error]   [struct boost::errinfo_errno_ * __ptr64] = 22, "Invalid argument"
> [2018-05-01 21:32:24.453] [error]   [struct caspar::tag_stacktrace_info * __ptr64] =  0# 0x000000013FF292CE in casparcg
> [2018-05-01 21:32:24.453] [error]    1# 0x000000013FF57B00 in casparcg
> [2018-05-01 21:32:24.453] [error]    2# 0x00000001400F538F in casparcg
> [2018-05-01 21:32:24.453] [error]    3# 0x00000001400F7C70 in casparcg
> [2018-05-01 21:32:24.453] [error]    4# 0x000000013FF23FE9 in casparcg
> [2018-05-01 21:32:24.453] [error]    5# crt_at_quick_exit in ucrtbase
> [2018-05-01 21:32:24.453] [error]    6# BaseThreadInitThunk in kernel32
> [2018-05-01 21:32:24.453] [error]    7# RtlUserThreadStart in ntdll
> [2018-05-01 21:32:24.453] [error]   
> [2018-05-01 21:32:24.453] [error]   
> 
> [2018-05-01 21:32:24.453] [error]    0# 0x000000013FF292CE in casparcg
> [2018-05-01 21:32:24.453] [error]    1# 0x000000013FF28BFF in casparcg
> [2018-05-01 21:32:24.453] [error]    2# 0x00000001403ED257 in casparcg
> [2018-05-01 21:32:24.453] [error]    3# _C_specific_handler in VCRUNTIME140
> [2018-05-01 21:32:24.453] [error]    4# _FrameUnwindFilter in VCRUNTIME140
> [2018-05-01 21:32:24.453] [error]    5# RtlRestoreContext in ntdll
> [2018-05-01 21:32:24.453] [error]    6# 0x00000001400121DA in casparcg
> [2018-05-01 21:32:24.453] [error]    7# 0x0000000140012D55 in casparcg
> [2018-05-01 21:32:24.453] [error]    8# 0x0000000140009C8D in casparcg
> [2018-05-01 21:32:24.453] [error]    9# 0x000000014000CB00 in casparcg
> [2018-05-01 21:32:24.453] [error]   10# 0x000000013FF23FE9 in casparcg
> [2018-05-01 21:32:24.453] [error]   11# crt_at_quick_exit in ucrtbase
> [2018-05-01 21:32:24.453] [error]   12# BaseThreadInitThunk in kernel32
> [2018-05-01 21:32:24.453] [error]   13# RtlUserThreadStart in ntdll
> [2018-05-01 21:32:24.453] [error]   
> [2018-05-01 21:32:24.486] [warning] Assertion Failed: counter < 8 file:C:\Program Files (x86)\Jenkins\workspace\casparcg-server-dep\master\src\core\consumer\frame_consumer.cpp line:96 
> [2018-05-01 21:32:24.487] [info]    ffmpeg[udp://192.168.10.17:5001] Uninitialized.

**Comment by Julusian** [comment]
fixed by https://github.com/CasparCG/server/commit/670bec33e704d7951192dfe8a63787bf38c6a49c
