### ISSUE TITLE
fill works as crop

### ISSUE THREAD

**Issue by TKooijmans** [CasparCG/server#989]
With latest build using
MIXER 1-1 FILL 0.12 0 0.75 1 25 easeinsine
causes picture to crop instead of squeeze

### Expected Behaviour
picture should squeeze

### Current Behaviour
picture cropping occurs

load a picture on layer 1-1
send command
MIXER 1-1 FILL 0.12 0 0.75 1 25 easeinsine

### Environment
* CasparCG Server version: build 4 may 2018
* Operating system: Win7 -64

### Attachments

**Comment by Julusian** [comment]
Possibly caused by #966

**Comment by dotarmin** [comment]
@TKooijmans Could you test with a build from 3 May or earlier and check if the issue still exists?

**Comment by grahamspr86** [comment]
Build 72943c537c9829c10c9491c929ae2b811e857f26 works okay which is from the 2nd May.

Issue also affects Distort.

**Comment by ronag** [comment]
@Julusian can you take a look? Otherwise we might have to revert your PR.

**Comment by Julusian** [comment]
I had a quick look the other day. 
The distort looks pretty obvious, the calculations werent updated to handle that geometry is now triangles rather than quads.
I didn't have enough time to get anywhere on the fill/rotate issue. I can take another look this week and try to get to the bottom of it

**Comment by TKooijmans** [comment]
It seems that this problem is back with 5 june version.

**Comment by Julusian** [comment]
> It seems that this problem is back with 5 june version.

Can you double check you are using the right version and commands?
There have only been a couple of changes since this was fixed, and none of them have gone anywhere near any relevant code...

**Comment by TKooijmans** [comment]
You are right!
the build of 5 june is ok!
only the FFmpeg stream encoder settings are still ignored
![afbeelding](https://user-images.githubusercontent.com/4194609/41283179-37799c92-6e36-11e8-9cc1-3b0d8e975fcd.png)

see another thread..
