### ISSUE TITLE
unable to clone 2.1.x branch, github over quota.

### ISSUE THREAD

**Issue by gizahNL** [CasparCG/server#990]
Checking out files: 100% (14322/14322), done.
Downloading dependencies64/boost/stage/lib/win32/libboost_atomic-vc140-mt-1_59.lib (6.8 KB)
Error downloading object: dependencies64/boost/stage/lib/win32/libboost_atomic-vc140-mt-1_59.lib (a333606): Smudge error: Error downloading dependencies64/boost/stage/lib/win32/libboost_atomic-vc140-mt-1_59.lib (a3336066f76f75ca6f59efdd7dd88ef0de8fa4decce021ae0f4a861e802632cb): batch response: This repository is over its data quota. Purchase more data packs to restore access.

**Comment by ronag** [comment]
@dotarmin ping

**Comment by dotarmin** [comment]
Fixed!

@ronag we should remove Git LFS references for 2.1 branch, even if the repo gets large. What do you think?

/Armin

**Comment by ronag** [comment]
@dotarmin No opinion on 2.1. Sorry :).
