### ISSUE TITLE
Screen consumer Stay on top

### ISSUE THREAD

**Issue by MauriceVeraart** [CasparCG/server#995]
feature request

### Expected Behaviour
window should stay on top (maybe as a option in config file)
### Current Behaviour
Other windows can now overlap the screen consumer

**Comment by dotarmin** [comment]
I'm not sure about this actually even if I like the idea. It could become strange if 1080 video-mode is used on a full-hd screen. You would have to move the window out of the screen (or something) to be able to interact with other windows such as the CasparCG Console window itself, right?

**Comment by MauriceVeraart** [comment]
Jep that's true

it should indeed be an option in the config and certainly not default behaviour. ;)
I guess when somebody uses (borderless / interactive=false / stay ontop) 
know what the consequence will be.

ls

**Comment by dotarmin** [comment]
> @MauriceVeraart: I guess when somebody uses (borderless / interactive=false / stay ontop) know what the consequence will be.

But if this is the case, it wouldn't even be possible to move the window, or would it? Personally I am having really hard to see what value this feature brings to the server but I'm sure it's because I cannot see a scenario when to use it.

**Comment by jesperstarkar** [comment]
I makes perfect sense to have this as an option. The most obvious use case is in headless server/client configurations.

**Comment by dotarmin** [comment]
> @jesperstarkar: I makes perfect sense to have this as an option.

I have no opinion about that.

> @jesperstarkar: The most obvious use case is in headless server/client configurations.

Why would you have a screen consumer running on the server speaking in terms of a headless server?

**Comment by jesperstarkar** [comment]
By headless I here mean to not interact with the server. Just boot it and have instant output on the attached screen (rack/workstation) or the built in screen (laptops) – the point is that you have a client/server setup and never want to interact with the server, just have a feed coming out.

Another case is for multi-screen workstations where you run the client on one screen and want an output on the other. Stay-on-top would prevent notifications and other popups to ruin the playback. Kinda like how you run Qlab and similar on Macs.

**Comment by Julusian** [comment]
I too would like this behaviour. This would be especially useful for low budget stations (hdmi + bmd micro converter is a lot cheaper than a decklink) or for stage video work, where it is unlikely that sdi will be used from a pc as their mixers commonly accept formats such as dvi or displayport. Especially so when combined with #674

Also when running multi-screen it is very easy to accidentally leave the control window sticking a little over the output and not notice. Some programs in windows 10 also cast a shadow which will draw on the second screen even when maximised, or they will overflow the screen by 1px

**Comment by MauriceVeraart** [comment]
I am working on 2 projects at the moment were this becomes handy.

one is a signage style solution were NUC's are driving lower res LED screens on HDMI/DVI level
they are normally unattended  / self restarting on powerfailure or crash. 

on a other project output is on output 2 and 3 from the server and the GUI is  on output 1 
dragging windows around could easily result in having the wrong things on the outputs ;)

**Comment by ronag** [comment]
https://github.com/CasparCG/server/pull/1022

**Comment by MauriceVeraart** [comment]
#1022 
works like a charm nice one

**Comment by Julusian** [comment]
> It works fine when specified in config file. But when we close screen consumer and reopen it with add 1 screen always_on_top screen consumer is added but now it is not always_on_top.
> Is it implemented or command syntax is wrong? I have tried
> always-on-top
> always-on-top=true
> ALWAYS_ON_TOP
> ...

From the code it looks like defining that property over amcp was not implemented

**Comment by vimlesh1975** [comment]
I request a feature to access following screen property from AMCP command.
X
Y
width
height
always on top
